### ISSUE TITLE
bump-version feature for Gradle projects

### ISSUE THREAD

**Issue by beleagaalexandra** [renovatebot/renovate#21308] opened 2023-04-03 20:19 UTC
### What would you like Renovate to be able to do?

Hello,
I am currently using Renovate to update dependencies in a Gradle custom catalog library which we then share across all our microservices. The thing is that we want to dynamically update de version of the catalog library after renovating dependencies. Looking at the documentation, the property to be used for this scenario is **"bumpVersion"**, but I can see that is ony supported for: **helmv3, npm, nuget, maven, sbt**. Do you think it's possible to implement this feature also for Gradle projects? (I've tried using it, but it had no effect on the opened PRs).
* config from output log file: 
`{
  "name": "renovate",
  "hostname": "***",
  "pid": 17,
  "level": 20,
  "logContext": "KwCe6OHRXfpz8wt-nrZjN",
  "config": {
    "configMigration": true,
    "onboarding": false,
    "requireConfig": "ignored",
    "autodiscover": true,
    "autodiscoverFilter": [
      "***"
    ],
    "bumpVersion": "minor",
    "automerge": false,
    "automergeType": "pr",
    "platformAutomerge": false
  },
  "msg": "CLI config",
  "time": "2023-04-03T13:06:50.214Z",
  "v": 0
}`

### If you have any ideas on how this should be implemented, please tell us here.

-

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment] 2023-04-03 20:30
Duplicate of #7214

**Closed by HonkingGoose** 2023-04-03 20:30 UTC
Labels: type:feature, status:requirements, duplicate, priority-5-triage
