### ISSUE TITLE
Bot marks checkbox as incomplete when ticked during run

### ISSUE THREAD

**Issue by Preisschild** [renovatebot/renovate#7071] opened 2020-08-24 07:09 UTC
**What Renovate type are you using?**

Selfhosted Renovate (running on k8s)
Platform: Gitlab

**Describe the bug**
When I press the checkbox to force a Rate Limited update in the Dependency Dashboard while Renovate is running, renovate marks the checkbox as "incomplete" while finishing the run. 

**To Reproduce**

- Start renovate
- While renovate is running, mark a force rate limited update checkbox as "complete" in the Dependency Dashboard
- Notice that Renovate marks the task as "incomplete" after all the other MRs are updated.

**Additional context**

**Comment by rarkins** [comment] 2020-08-24 09:15
Duplicate of #4355 - please subscribe to that issue

**Closed by rarkins** 2020-08-24 09:15 UTC

**Comment by Preisschild** [comment] 2020-08-24 12:29
Thanks! didn't find it at first.

**Comment by rarkins** [comment] 2020-08-24 12:35
No problem, we used to call it "master issue" so you wouldn't have found it if searching for dependency dashboard.
