### ISSUE TITLE
Support finding latest packages from a remote repo

### ISSUE THREAD

**Issue by ocofaigh** [renovatebot/renovate#8616] opened 2021-02-09 23:27 UTC
**What would you like Renovate to be able to do?**

Problem: An artifactory remote repository acts a proxy for a repository located on a remote server. Packages only get cached to the artifactory remote repository after you actually attempt to pull a version of a package. So that means renovate does not work when set up to check for newer versions of packages on a remote repository since no new versions will exist on the artifactory remote repository.

Solution: Can renovate support actually checking the back end source remote server for newer packages?

**Did you already have any implementation ideas?**

Renovate won't know what the remote server is behind the artifactory remote repository, so I was thinking maybe it can initiate a pull of the dependency package it finds in the git repo scan via the artifactory remote repository - and hence forcing them to be cached to the remote repository? I guess it should be able to find the latest major, minor and patch versions for the package.

**Comment by rarkins** [comment] 2021-02-10 08:06
Please create a simple repo (e.g. `package.json` with one package, which is outdated, plus a lock file) and then use this config:

```
"packageRules": [{
  "matchDatasources": ["npm"],
  "npmrc": "registry=https://registry.npmjs.org"
}, {
  "matchDatasources": ["npm"],
  "matchUpdateTypes": ["pin", "patch", "minor", "major"],
  "npmrc": null
}]
```

The idea of the above - I am yet to test it - is that it will override your existing `.npmrc` settings during the npm lookup phase (internal to Renovate) but then reset the override before calling to `npm install` to update the lockfile. It assumes that Renovate isn't blocked from accessing registry.npmjs.org

**Comment by rarkins** [comment] 2021-02-26 06:43
Closing due to lack of reproduction or feedback so nothing further can be done

**Closed by rarkins** 2021-02-26 06:43 UTC
Labels: priority-4-low, reproduction:needed, status:requirements, type:feature
