### ISSUE TITLE
Java8 is used in docker image

### ISSUE THREAD

**Issue by eloo** [renovatebot/renovate#6178] opened 2020-05-08 14:19 UTC
**Describe the bug**
I've read often here that the default jre used in the docker images is the default of ubuntu 18.04 which should be java 11.

But it looks like java8 is used instead of java11.

**To Reproduce**
```
docker run --rm -i -t renovate/renovate bash -c "java -version" 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

Is this on purpose? 
And how can i get java 11 runing in renovate?

Thanks

**Comment by viceice** [comment] 2020-05-08 14:29
Currently you only way is to build your own renovate based on this image: https://github.com/renovatebot/docker-renovate-full and change java to 11

**Comment by eloo** [comment] 2020-05-08 16:04
i'm not sure why this is closed.. 
my idea is not to build my own renovate image..
i'm trying to use your helm chart which is referring the mentioned image and this is java 8 based and not java11 as expected

**Comment by viceice** [comment] 2020-05-08 16:11
We hat installed java11 for a short period and rolled it back to java 8, because we got a lot issues for older gradle users.

@JamieMagee Is it possible to override the renovate image in your helm chart? So users can use a custom renovate build?

**Comment by JamieMagee** [comment] 2020-05-08 16:13
Yes, you can override the `image.repository` setting. The default is `renovate/renovate`.

**Comment by rarkins** [comment] 2020-05-08 17:10
> please reopen this bug

It's not a bug. If the versions of tools we build with do not satisfy you, you need to build your own image. We will switch to Java 11 once we think  that will satisfy more users than Java 8 does.

**Comment by eloo** [comment] 2020-05-09 20:11
i like the irony that a dependency update tool is using EOL dependencies :D

**Comment by rarkins** [comment] 2020-05-10 05:28
I was under the impression that Java 8 was still supported, but according to Wikipedia at least:

> Oracle released for the "legacy" Java 8 LTS the last free "public update" in January 2019 for commercial use, while it will otherwise still support Java 8 with public updates for personal use up to at least December 2020

Does that mean it's still supported if you're a personal user, or if you're a paying commercial user, but it's not supported if you're a non-paying commercial user?

@viceice I do agree that we should generally try to be on the latest. Should we switch?

**Comment by viceice** [comment] 2020-05-10 07:07
I think we can switch to java 11 with renovate v20 because we know it's a breaking change for some users

**Comment by eloo** [comment] 2020-05-10 10:44
or maybe it would be possible to have image with java 11 and one with java 8 so it would be easier for your customers to test it and plan a migration on their own?

**Comment by viceice** [comment] 2020-05-10 11:04
No, we won't do this, there are to many possible tool combinations we would have to builld too.

If we start to do this for java, other users would like to have that for other tools too. The current full image is as example. We will deprecate the usage and prefer to use the slim image or a custom image build by users. We will soon provide a git template for users with a full build pipeline to build a customised renovate image with user required tools preinstalled.

**Comment by eloo** [comment] 2020-05-10 12:24
okay.. sounds good to me

**Comment by JamieMagee** [comment] 2020-05-10 16:47
Oracle JDK != JDK.

Oracle are major contributors to the JDK, and previously they were giving away support for _their_ build of the JDK for free. They changed their license as of January 2019, which meant that they no longer provided it for free.

Thankfully a lot of organisations stepped in to fill the gap and provide support. Relevant to us, Ubuntu has committed to providing support, for free, until **April 2021** ([Source](https://lists.ubuntu.com/archives/ubuntu-release/2018-February/004275.html)).

If we wanted to continue using OpenJDK, we could switch to AdoptOpenJDK, which has committed to supporting JDK 8 until **May 2026** ([Source](https://adoptopenjdk.net/support.html)). Though I think that's a bit extreme.

I think doing this in v20 is a good compromise (Though that release is getting bigger by the day!)

**Comment by viceice** [comment] 2020-05-20 11:07
renovatebot/docker-renovate-full#33

**Closed by viceice** 2020-05-20 11:07 UTC

**Comment by viceice** [comment] 2020-05-20 11:16
renovatebot/docker-gradle#36
