### ISSUE TITLE
Renovate does not update gradle wrapper`s execution files

### ISSUE THREAD

**Issue by driver733** [renovatebot/renovate#5837] opened 2020-03-30 19:12 UTC
**What Renovate type are you using?**

Self-hosted

**Describe the bug**

Renovate should (but does not as of v.19.189.1) update the gradle wrapper version this way:
```
./gradlew wrapper --gradle-version {e.g. 6.3}
```
instead of simply changing the version in the `distributionUrl`.

The `version` param should be extracted from the original distributionUrl.
The optional`distribution-type` param should not be specified since, as per the Gradle [docs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html#org.gradle.api.tasks.wrapper.Wrapper:distributionType) and Gradle repo [discussion](https://github.com/gradle/gradle/issues/3470#issuecomment-344320332), this setting is managed by the aformentioned gradle wrapper update command using the information from the project's `build.gradle`.

No further actions should be taken by Renovate after running the aforementioned command as it does everything necessary to update the Gradle wrapper:

1. Update `distributionUrl`
2. Update `./gradlew`
3. Update `./gradlew.bat`

**Did you see anything helpful in debug logs?**

No

**To Reproduce**

Given:

```
./gradle/wrapper/gradle-wrapper.properties
distributionUrl=http\://.../gradle-6.2.1-bin.zip

./gradlew
./gradlew.bat
```

When:

`Run renovate`

Then:

Expected result:

```
./gradle/wrapper/gradle-wrapper.properties
distributionUrl=http\://.../gradle-6.3-bin.zip

./gradlew (updated)
./gradlew.bat (updated)
```

Actual result:
```
./gradle/wrapper/gradle-wrapper.properties
distributionUrl=http\://.../gradle-6.3-bin.zip

./gradlew (NOT updated)
./gradlew.bat (NOT updated)
```

**Comment by driver733** [comment] 2020-03-30 19:34
@rarkins I can try to fix this issue. Can you assign it to me?

**Comment by ikesyo** [comment] 2020-03-30 19:39
This is a duplicate of #3565.

**Comment by rarkins** [comment] 2020-03-30 19:39
@driver733 thank you very much for trying. I actually wasn't sure though how it should be implemented though, so it may not be an easy one. The [updateDependency](https://github.com/renovatebot/renovate/blob/ed5792ad5d028688a90cad31070816e76e2e524f/lib/manager/gradle-wrapper/update.ts#L29) function is not meant to return multiple files, so it might be necessary to implement it using the "artifacts" concept, where multiple files can be returned.

**Comment by rarkins** [comment] 2020-03-30 19:39
Thanks @ikesyo. @driver733 can you comment in #3565 and I'll assign it there?

**Closed by rarkins** 2020-03-30 19:39 UTC
Labels: #gradle, feat, pri3-normal, ready
