### ISSUE TITLE
"Action Required: Fix Renovate Configuration"

### ISSUE THREAD

**Issue by janpio** [renovatebot/renovate#8375] opened 2021-01-21 14:34 UTC
All our repositories got opened an issue similar to https://github.com/renovatebot/renovate/issues/2008 - which also was reopened by the bot.

Some of them were already closed again by the bot. Will this happen to all of them and we should just ignore these? Or is there something we should do?

**Comment by rarkins** [comment] 2021-01-21 14:46
See https://github.com/renovatebot/renovate/issues/8371#issuecomment-764637869

Duplicate of #8371

**Closed by rarkins** 2021-01-21 14:46 UTC
