### ISSUE TITLE
pipes are not correctly escaped in github PR description

### ISSUE THREAD

**Issue by danez** [renovatebot/renovate#5735] opened 2020-03-17 12:00 UTC
**What Renovate type are you using?**

Github

**Describe the bug**

When renovate bot widens the  range of a dependency the description in the PR is broken, because the pipes (||) are somewhow clashing with the table which also uses pipes.

**To Reproduce**

https://github.com/researchgate/tooling/pull/23

Relevant raw source
```
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [eslint-plugin-node](https://togithub.com/mysticatea/eslint-plugin-node) | dependencies | major | [`^10.0.0` -> `^11.0.0`](https://renovatebot.com/diffs/npm/eslint-plugin-node/10.0.0/11.0.0) |
| [eslint-plugin-node](https://togithub.com/mysticatea/eslint-plugin-node) | peerDependencies | major | [`^10.0.0` -> `^10.0.0 || ^11.0.0`](https://renovatebot.com/diffs/npm/eslint-plugin-node/10.0.0/11.0.0) |

---
```

**Additional context**

https://stackoverflow.com/a/17320389/3739237

**Comment by rarkins** [comment] 2020-03-17 12:09
Can you past the source markdown here too, in raw form?

**Comment by viceice** [comment] 2020-03-17 12:19
duplicate of #5397

**Closed** 2020-03-17 12:51 UTC
Labels: fix, pri3-normal, ready
