### ISSUE TITLE
Go Modules: update import paths after major upgrades

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3627] opened 2019-05-03 06:51 UTC
Suggestion:

@rarkins But there is a section about updating dependencies; see https://github.com/marwan-at-work/mod#upgrading-a-dependency . Also according to official go mod docs you are supposed to update your import paths when increasing major version (from v2 and onward, see https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) and renovate doesn't cover this currently. Renovate fails to upgrade for example caarlos0/env because of missing major version in imports, see https://github.com/caarlos0/env/issues/86.  marwan-at-work/mod seems to be a nice fit to automatically fix the import paths for major versions updates. Not sure whether it fixes also this issue but given it is a recommended tool by official documentation I would expect it to work correctly.

_Originally posted by @rkuska in https://github.com/renovatebot/renovate/issues/3557#issuecomment-488127692_

**Comment by Hexcles** [comment] 2019-10-22 22:10
IIUC, without this, major upgrades to v2+ are completely broken for Golang in Renovate if the code has explicitly included version numbers in import paths.

e.g. our codebase has

https://github.com/web-platform-tests/wpt.fyi/blob/446d5d8e21905a1c66b0468bc7780ad79eb15873/api/taskcluster/webhook.go#L20

Renovate creates this PR for us: https://github.com/web-platform-tests/wpt.fyi/pull/1550

which does not work at all.

Running `go build` will add v20 back to `go.mod` and v21 isn't imported at all. In fact, running `go mod tidy` will remove v21 altogether as it's not used. (There might be another bug here: I enabled `gomodTidy` but it doesn't seem to take effect.)

**Comment by rarkins** [comment] 2019-10-23 05:22
@Hexcles are you aware of any existing tools/commands that could achieve this today as a post install step? Or fool-proof logic for updating .go files that Renovate could implement natively?

Of course the next challenge is that even with updated import paths, you’re probably still “broken” due to breaking change itself.

**Comment by Hexcles** [comment] 2019-10-23 15:52
I tried `marwan-at-work/mod` to no avail. `psampaz/go-mod-outdated` also doesn't list available major upgrades. I can't find an automated solution so far and am quite surprised by that...

I think the right thing to do here is to accept the fact that we can't automatically upgrade major versions for Go modules yet and stop creating those no-op PRs that only touch `go.mod`.

**Comment by Hexcles** [comment] 2019-10-23 15:54
FWIW, Dependabot has the same limitation: https://dependabot.com/blog/go-modules-alpha/

**Comment by rarkins** [comment] 2019-10-23 17:46
@Hexcles you can disable major updates for go modules this way in config:

```json
  "gomod": {
    "major": {
      "enabled": false
    }
  }
```

Although I suggest instead putting them behind an approval step so they're not completely "out of sight out of mind".

```json
  "masterIssue": true,
  "gomod": {
    "major": {
      "masterIssueApproval": true
    }
  }
```

The PRs currently aren't "no-op" in the sense that they do update the `go.mod` file, and for many projects it's important to *be aware* that a major update is available, even if the PR itself isn't mergeable. In pretty much every language that uses semver, it's often the case that the PR that Renovate raises is "broken" and requires human updates on top, but that's no reason to disable them by default - people should be aware when there's a major update available.

And it goes without saying that the second there's a third party tool that can update the imports, or a foolproof way we can do it ourselves, then we can add it. Unlike Dependabot, we operate on a shallow clone of repos so we already can do things like `go get`, `go mod vendor` and `go mod tidy`.

**Comment by Clivern** [comment] 2020-07-21 19:05
I have seen that case when renovate did upgrade from `github.com/logrusorgru/aurora` to `github.com/logrusorgru/aurora/v3`. there is a tool in go that can update the import path for all go files. it is pretty much like `sed` but only to update go source code. 

Something like this will update all import paths to `/v3`

```
$  gofmt -w -r '"github.com/logrusorgru/aurora" -> "github.com/logrusorgru/aurora/v3"' ./
```

https://golang.org/cmd/gofmt/

**Comment by viceice** [comment] 2021-03-09 17:26
Duplicate of #3348

**Closed by viceice** 2021-03-09 17:26 UTC
Labels: manager:gomod, priority-3-normal, status:ready, type:feature
