### ISSUE TITLE
Does not detect release notes from CHANGELOG.md

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#5378] opened 2020-02-05 11:55 UTC
**What Renovate type are you using?**

GitHub

**Describe the bug**

See https://github.com/sourcegraph/sourcegraph/pull/8283

No release notes, but the diff includes an addition to the CHANGELOG.md

**Did you see anything helpful in debug logs?**

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment] 2020-02-05 18:21
Don't blame you for not realizing it, but this is a duplicate of #5181. IMO standard-version has a really unfortunate convention for markdown headings, although naturally we will try to support it.

**Closed by rarkins** 2020-02-05 18:21 UTC
