### ISSUE TITLE
Go modules inside a Gitlab subgroup are not detected

### ISSUE THREAD

**Issue by lucasfernand-es** [renovatebot/renovate#10336] opened 2021-06-07 12:06 UTC
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [X] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [X] GitLab self-hosted

Renovate version: 25.36.0

**Describe the bug**

I currently have several go packages hosted in a self-hosted gitlab. Some have this path `privatehost.com/group/goModuleB` and other this `privatehost.com/group/subgroup/goModuleA`. 

For those located in a subgroup, I have the following error:

`Failed to look up dependency privatehost.com/group/subgroup/goModuleB`

It seems not to be an authentication issue because another private module not in a subgroup can be found `(privatehost.com/group/goModuleA)`.

According to logs, it's not properly recognizing `group/subgroup` as a valid path.

I might be related to this other issue [10218](https://github.com/renovatebot/renovate/issues/10218).

...

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: GitLab API 404 (repository=group/subgroup/project)
       "url": "https://self-hosted/api/v4/projects/group%2Fsubgroup/repository/tags?per_page=100"
DEBUG: Datasource 404 (repository=group/subgroup/project)
       "datasource": "go",
       "lookupName": "self-hosted/group/subgroup/project",
       "url": "https://self-hosted/api/v4/projects/group%2Fsubgroup/repository/tags?per_page=100"

```

</details>

I changed the actual names to `group` and `subgroup`.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [X] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

As referenced in [10218](https://github.com/renovatebot/renovate/issues/10218), the source of the problem seems to be:

https://github.com/renovatebot/renovate/blob/83ab94eba680f6705dbbdbb60207620eeec06a76/lib/datasource/go/index.ts#L193-L212

**Comment by rarkins** [comment] 2021-06-07 12:11
Without a reproduction repo, and without description of why this is different to #10218, I would prefer to keep discussion there.

**Comment by rarkins** [comment] 2021-06-07 12:11
Duplicate of #10218

**Closed by rarkins** 2021-06-07 12:11 UTC
Labels: priority-5-triage, status:requirements, type:bug
