### ISSUE TITLE
Composer update does not commit changes to vendor folder

### ISSUE THREAD

**Issue by esetnik** [renovatebot/renovate#7661] opened 2020-11-05 20:00 UTC
**What Renovate type, platform and version are you using?**
Github app

**Describe the bug**
Our project commits the `vendor` folder (generated by composer) into the repository. When renovate creates a PR only the `composer.json` and `composer.lock` are committed and not the changes to the vendor folder, leaving the committed vendor source code out of sync with the versions found in `composer.json` and `composer.lock`

**Relevant debug logs**

**To Reproduce**
Create any php repository which manages its dependencies with `composer` and don't put `vendor` in the `.gitignore` (e.g. commit the vendor folder).

Updated: Reproducing repository https://github.com/esetnik/composer-test

**Additional context**
I tried to use `ignorePaths` to override the default behavior of ignoring the `vendor` folder, but then renovated created a large number of PRs for dependency updates of `**/vendor/**/composer.json`. I didn't find any other configuration that would allow me to tell renovate to stop ignoring file changes in the `vendor` folder when committing dependency updates to the repository.

**Comment by viceice** [comment] 2020-11-05 20:09
I think this is currently not supported.

**Comment by rarkins** [comment] 2020-11-05 20:11
Needs a reproduction repo that can be tested against. Eg has vendored modules and creates a PR

**Comment by esetnik** [comment] 2020-11-05 20:25
Note that I did see `excludeCommitPaths` and am currently using the default value of `[]` so I would expect that all changes in my entire repository would be committed.

**Comment by esetnik** [comment] 2020-11-05 20:38
@rarkins I updated the bug report with a minimal public repo that reproduces the issue. Specifically, you can take a look at https://github.com/esetnik/composer-test/pull/2. In this case, renovated did the right thing in creating a PR to update this dependency, but it did not commit the changes to `vendor` folder which leaves the repository in an inconsistent state as the `composer.lock` and `vendor` no longer contain a consistent set of dependencies.

**Comment by rarkins** [comment] 2020-11-05 20:39
> Note that I did see `excludeCommitPaths` and am currently using the default value of `[]` so I would expect that all changes in my entire repository would be committed.

That works to exclude files which were already included. If vendor wasn't included, the `[]` is meaningless.

**Comment by esetnik** [comment] 2020-11-05 20:40
> > Note that I did see `excludeCommitPaths` and am currently using the default value of `[]` so I would expect that all changes in my entire repository would be committed.
> 
> That works to exclude files which were already included. If vendor wasn't included, the `[]` is meaningless.

Is there a configuration I should be using to include `vendor` for this scenario?

**Comment by rarkins** [comment] 2020-11-05 20:44
No, this requires a feature addition, not configuration. Logic similar to https://github.com/renovatebot/renovate/blob/master/lib/manager/gomod/artifacts.ts needs to be added to https://github.com/renovatebot/renovate/blob/master/lib/manager/composer/artifacts.ts. 

The first step is to decide *whether* to check for vendored files, and then run logic like https://github.com/renovatebot/renovate/blob/4c68175f81b45dd50b5c6a380153b493f29b38af/lib/manager/gomod/artifacts.ts#L122-L141

But is such a first step necessary here? If they are git ignored then they won't show up in a git modified check, so if they *do* show up then should we add them to the PR automatically?

**Comment by esetnik** [comment] 2020-11-05 20:48
> But is such a first step necessary here? If they are git ignored then they won't show up in a git modified check, so if they _do_ show up then should we add them to the PR automatically?

From my perspective this is the ideal behavior as it mirrors what would happen if the user ran `composer update` manually and committed the changes. If they wanted `vendor` ignored they could add it to their `.gitignore` and if they wanted it included, they just omit it.

**Comment by esetnik** [comment] 2020-11-06 16:35
@rarkins I implemented this feature in https://github.com/renovatebot/renovate/pull/7672. Let me know if it looks like a reasonable solution.

**Comment by xknown** [comment] 2020-11-17 21:26
One of the problems with the change added in #7672 is that it also updates development dependencies which might not be desirable in some use cases. For example, if one decides to have a versioned vendor dir (i.e. there's no composer installer on production servers for security reasons), the proposed PRs now have dev changes too.

**Comment by rarkins** [comment] 2020-11-17 21:31
@xknown is there a way to control that programmatically?

**Comment by xknown** [comment] 2020-11-18 21:44
As far as I know, there's only the `--no-dev` flag that can be passed when executing `composer update` to avoid adding dev dependencies to the `vendor` directory. I wonder if this can be somehow controlled in a renovate config setting, so most use cases could be covered -- some people might want dev dependencies changes included, others might not.

**Comment by rarkins** [comment] 2020-11-19 05:57
And there's no feasible way to automatically detect that it was run previously with --no-dev ?

**Comment by mjrider** [comment] 2020-12-10 06:56
i assume this issue is the reason why renovate started to commit the vendor directory  out of the blue, while there was no vendor folder there to begin with.

it would be nice if it didn't do that when there was no vendor folder before the upgrade, and committing the vendor folder is considered bad practise so a feature toggle to enable would be the expected way to go for this

**Comment by rarkins** [comment] 2020-12-10 08:31
@mjrider it definitely shouldn't add the vendor folder if it didn't exist before. I'm going to close this one as implemented but can you create a new bug report with a simple reproduction and we'll treat it as high priority?

**Closed by rarkins** 2020-12-10 08:31 UTC
Labels: manager:composer, priority-3-normal, reproduced :heavy_check_mark:, type:feature

**Comment by rarkins** [comment] 2020-12-10 08:39
Actually I can reproduce with an old repo I have, so no need for that.
