### ISSUE TITLE
Error while updating GitLab include

### ISSUE THREAD

**Issue by anro87** [renovatebot/renovate#19867] opened 2023-01-16 14:09 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest Docker Image

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab CE

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

While running renovate on a .gitlab-ci.yml, to update the gitlab include, I'm receiving the following error:

<details><summary>Select me to see logs</summary>

```
WARN: Error updating branch: update failure (repository=anro87/include-target-example, branch=renovate/pin-dependencies)

WARN: Error updating branch: update failure (repository=anro87/include-target-example, branch=renovate/non-major.versions)
```

</details>

No merge request created at the target repo as the renovate-bot cannot determine the right branch.

The following examples have been created to help you reproduce the issue:
- Source Project: https://gitlab.com/anro87/include-source-example
- Target Project: https://gitlab.com/anro87/include-target-example
- Renovate Project:  https://gitlab.com/anro87/renovate-example

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by anro87** [comment] 2023-01-24 08:45
Adjusted issue documentation. Please review

**Comment by rarkins** [comment] 2023-01-24 08:47
Can you get debug logs during a run where updates fail? Set `LOG_LEVEL=debug` in env before running

**Comment by anro87** [comment] 2023-01-24 09:36
Done, please check latest pipeline run: https://gitlab.com/anro87/renovate-example/-/jobs/3649914235

**Comment by rarkins** [comment] 2023-01-24 10:46
```
DEBUG: Branch needs creating (repository=anro87/include-target-example, branch=renovate/non-major.versions)
DEBUG: Using reuseExistingBranch: false (repository=anro87/include-target-example, branch=renovate/non-major.versions)
DEBUG: Setting current branch to main (repository=anro87/include-target-example, branch=renovate/non-major.versions)
DEBUG: latest commit (repository=anro87/include-target-example, branch=renovate/non-major.versions)
       "branchName": "main",
       "latestCommitDate": "2023-01-16T13:51:16+00:00"
DEBUG: manager.getUpdatedPackageFiles() reuseExistingBranch=false (repository=anro87/include-target-example, branch=renovate/non-major.versions)
DEBUG: Starting search at index 67 (repository=anro87/include-target-example, packageFile=.gitlab-ci.yml, branch=renovate/non-major.versions)
       "depName": "anro87/include-source-example"
DEBUG: Found match at index 67 (repository=anro87/include-target-example, packageFile=.gitlab-ci.yml, branch=renovate/non-major.versions)
       "depName": "anro87/include-source-example"
 WARN: Error updating branch: update failure (repository=anro87/include-target-example, branch=renovate/non-major.versions)
```

**Comment by rarkins** [comment] 2023-01-24 10:48
```
DEBUG: packageFiles with updates (repository=anro87/include-target-example, baseBranch=main)
       "config": {
         "gitlabci-include": [
           {
             "packageFile": ".gitlab-ci.yml",
             "deps": [
               {
                 "datasource": "gitlab-tags",
                 "depName": "anro87/include-source-example",
                 "depType": "repository",
                 "currentValue": "1.0.0",
                 "registryUrls": ["https://gitlab.com/"],
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "1.0.1",
                     "newValue": "1.0.1",
                     "releaseTimestamp": "2023-01-16T13:17:17.000Z",
                     "newMajor": 1,
                     "newMinor": 0,
                     "updateType": "patch",
                     "newDigest": "ce03f9f51480f560c7149ed33ede8eb89a761f11",
                     "branchName": "renovate/non-major.versions"
                   },
                   {
                     "isPinDigest": true,
                     "updateType": "pinDigest",
                     "newValue": "1.0.0",
                     "newDigest": "ce03f9f51480f560c7149ed33ede8eb89a761f11",
                     "branchName": "renovate/pin-dependencies"
                   }
                 ],
                 "warnings": [],
                 "versioning": "semver",
                 "sourceUrl": "https://gitlab.com/anro87/include-source-example",
                 "registryUrl": "https://gitlab.com/",
                 "currentVersion": "1.0.0",
                 "isSingleVersion": true,
                 "fixedVersion": "1.0.0"
               }
             ]
           }
         ]
       }
```

Does the problem go away if you remove `pinDigests=true` from your config?

**Comment by anro87** [comment] 2023-01-26 15:00
Yes that solves the problem, but I need this to be enabled as I'm using pinDigest to update my Docker-Images via the bot. From my point of view the bot should only use the non-major for GitLab-Includes and ignore pinDigest.

**Comment by rarkins** [comment] 2023-01-26 17:19
It's a bug somehow, and PRs are welcome if you'd like to fix it

**Comment by anro87** [comment] 2023-01-27 09:53
Apologize I cannot. Anyone out there that can help?

**Comment by viceice** [comment] 2023-04-12 12:54
Duplicate of #14177

**Closed by viceice** 2023-04-12 12:54 UTC
Labels: type:bug, help wanted, priority-3-medium, manager:gitlabci, status:ready, reproduction:provided, logs:problem
