### ISSUE TITLE
PRs not automatically merging (Bitbucket)

### ISSUE THREAD

**Issue by carlosfunk** [renovatebot/renovate#2860] opened 2018-11-21 21:07 UTC
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
With automerge enabled no PRs are being automatically merged, last log line is always `INFO: PR is not ready for merge`

My renovate.json looks like this and I want all patch releases automerge plus minor devDependencies automerged.  (The project is Django with a React frontend hence the monorepo:react and the pip_requirements)

```
{
  "extends": ["config:js-app", "monorepo:react"],
  "pip_requirements": {
    "fileMatch": ["(^|\/)requirements\/.+.txt$"]
  },
  "separateMinorPatch": true,
  "patch": {
    "automerge": true
  },
  "devDependencies": {
    "automerge": true,
    "major": {
      "automerge": false
    }
  }
}
```

**Did you see anything helpful in debug logs?**
Logs for patch release of wheel 0.32.2 -> 0.32.3

```
DEBUG: processBranch with 1 upgrades (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branchExists(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getBranchPr(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: findPr(renovate/wheel-0.32.x, null, open) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getPrList() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branchExists=false (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Branch has 1 upgrade(s) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: recreateClosed is false (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: findPr(renovate/wheel-0.32.x, Update dependency wheel to v0.32.3, MERGED,DECLINED,SUPERSEDED) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getPrList() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: prAlreadyExisted=false (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Checking schedule(at any time, null) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: No schedule defined (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branchExists(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
 INFO: Branch needs creating (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Using parentBranch: undefined (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: manager.getUpdatedPackageFiles() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getFile(filePath=requirements/base.txt, branchName=undefined) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: pip_requirements.updateDependency(): ==0.32.3 (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Updating packageFile content (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Updated 1 package files (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Getting updated lock files (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: lock file dirs (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "dirs": {
         "yarnLockDirs": [],
         "npmLockDirs": [],
         "pnpmShrinkwrapDirs": [],
         "lernaDirs": []
       }
DEBUG: getFile(filePath=lerna.json, branchName=undefined) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Writing package.json files (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "packageFiles": ["package.json"]
DEBUG: getFile(filePath=package.json, branchName=undefined) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Writing yarn.lock (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getFile(filePath=yarn.lock, branchName=undefined) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Writing any updated package files (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: No updated lock files in branch (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: 1 file(s) to commit (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: commitFilesToBranch('renovate/wheel-0.32.x', files, message, 'master)' (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branchExists(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Checking if we can automerge branch (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: mergeStatus=no automerge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Ensuring PR (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: There are 0 errors and 0 warnings (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getBranchPr(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: findPr(renovate/wheel-0.32.x, null, open) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getPrList() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getChangeLogJSON(args) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "args": {
         "manager": "pip_requirements",
         "versionScheme": "pep440",
         "depName": "wheel",
         "fromVersion": "0.32.2",
         "toVersion": "0.32.3",
         "repositoryUrl": "https://github.com/pypa/wheel"
       }
DEBUG: getBranchStatus(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branch status check result (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "sha": "3eb51d6bf29f1a98818018582f2b46eb944dd598",
       "statuses": []
DEBUG: Creating PR (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "prTitle": "Update dependency wheel to v0.32.3"
DEBUG: Creating PR (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "title": "Update dependency wheel to v0.32.3",
       "base": "master"
 INFO: PR created (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "pr": undefined
DEBUG: getBranchStatus(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branch status check result (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "sha": "3eb51d6bf29f1a98818018582f2b46eb944dd598",
       "statuses": []
DEBUG: Skipping assignees and reviewers as automerge=true (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
 INFO: Created Pull Request #114 (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Checking #undefined for automerge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
 INFO: PR is not ready for merge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
```

**Comment by rarkins** [comment] 2018-11-21 21:59
First of all, I'm not sure if support for automerging in Bitbucket was included in this initial release. However in the log above it shows a PR being created and then denied automerge in the same run, and that is expected for all platforms - we don't automerge instantly after creating the PR unless you've disabled all status checks.

1. Do you have any tests?
2. Do you have any example log where tests have passed but the automerging is skipped?

**Comment by carlosfunk** [comment] 2018-11-21 22:42
I wasn't sure if automerging was supported so thought I'd raise it anyway.
Yes I have tests and they're passing, I've run renovate again on this repo here are the logs just for the same package above.

```
DEBUG: processBranch with 1 upgrades (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branchExists(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getBranchPr(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: findPr(renovate/wheel-0.32.x, null, open) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getPrList() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Found PR #114 (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: isBranchStale(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branchExists=true (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Branch has 1 upgrade(s) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Checking if PR has been edited (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Found existing branch PR (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Checking schedule(at any time, null) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: No schedule defined (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branchExists(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Branch already exists (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getBranchPr(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: findPr(renovate/wheel-0.32.x, null, open) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getPrList() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Found PR #114 (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: isBranchStale(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Branch does not need rebasing (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Using parentBranch: renovate/wheel-0.32.x (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: manager.getUpdatedPackageFiles() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getFile(filePath=requirements/base.txt, branchName=renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: pip_requirements.updateDependency(): ==0.32.3 (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: No package files need updating (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Getting updated lock files (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: lock file dirs (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "dirs": {
         "yarnLockDirs": [],
         "npmLockDirs": [],
         "pnpmShrinkwrapDirs": [],
         "lernaDirs": []
       }
DEBUG: getFile(filePath=lerna.json, branchName=undefined) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Writing package.json files (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "packageFiles": ["package.json"]
DEBUG: getFile(filePath=package.json, branchName=undefined) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Writing yarn.lock (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getFile(filePath=yarn.lock, branchName=undefined) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Writing any updated package files (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: No updated lock files in branch (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: No files to commit (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Checking if we can automerge branch (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: mergeStatus=no automerge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Ensuring PR (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: There are 0 errors and 0 warnings (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getBranchPr(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: findPr(renovate/wheel-0.32.x, null, open) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getPrList() (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Found PR #114 (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: isBranchStale(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Found existing PR (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getChangeLogJSON(args) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "args": {
         "manager": "pip_requirements",
         "versionScheme": "pep440",
         "depName": "wheel",
         "fromVersion": "0.32.2",
         "toVersion": "0.32.3",
         "repositoryUrl": "https://github.com/pypa/wheel"
       }
DEBUG: getBranchStatus(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branch status check result (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "sha": "3eb51d6bf29f1a98818018582f2b46eb944dd598",
       "statuses": [
         {
           "key": "4becbd474f48d92e5c9ecd60a0d57c95",
           "description": "This commit looks good.",
           "repository": {
             "links": {
               "self": {
                 "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm"
               },
               "html": {"href": "https://bitbucket.org/completecc/madc-crm"},
               "avatar": {
                 "href": "https://bytebucket.org/ravatar/%7Bda9969ab-f8ff-412a-ab50-938181006d2c%7D?ts=default"
               }
             },
             "type": "repository",
             "name": "madc-crm",
             "full_name": "completecc/madc-crm",
             "uuid": "{da9969ab-f8ff-412a-ab50-938181006d2c}"
           },
           "url": "https://jenkins.tools.madtech.nz/job/madc-crm-pipeline/job/PR-114/1/display/redirect",
           "links": {
             "commit": {
               "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm/commit/3eb51d6bf29f1a98818018582f2b46eb944dd598"
             },
             "self": {
               "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm/commit/3eb51d6bf29f1a98818018582f2b46eb944dd598/statuses/build/4becbd474f48d92e5c9ecd60a0d57c95"
             }
           },
           "refname": null,
           "state": "SUCCESSFUL",
           "created_on": "2018-11-21T20:56:35.514464+00:00",
           "commit": {
             "hash": "3eb51d6bf29f1a98818018582f2b46eb944dd598",
             "type": "commit",
             "links": {
               "self": {
                 "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm/commit/3eb51d6bf29f1a98818018582f2b46eb944dd598"
               },
               "html": {
                 "href": "https://bitbucket.org/completecc/madc-crm/commits/3eb51d6bf29f1a98818018582f2b46eb944dd598"
               }
             }
           },
           "updated_on": "2018-11-21T20:58:23.226770+00:00",
           "type": "build",
           "name": "madc-crm » PR-114 #1"
         }
       ]
DEBUG: Processing existing PR (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: getBranchStatus(renovate/wheel-0.32.x) (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: branch status check result (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "sha": "3eb51d6bf29f1a98818018582f2b46eb944dd598",
       "statuses": [
         {
           "key": "4becbd474f48d92e5c9ecd60a0d57c95",
           "description": "This commit looks good.",
           "repository": {
             "links": {
               "self": {
                 "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm"
               },
               "html": {"href": "https://bitbucket.org/completecc/madc-crm"},
               "avatar": {
                 "href": "https://bytebucket.org/ravatar/%7Bda9969ab-f8ff-412a-ab50-938181006d2c%7D?ts=default"
               }
             },
             "type": "repository",
             "name": "madc-crm",
             "full_name": "completecc/madc-crm",
             "uuid": "{da9969ab-f8ff-412a-ab50-938181006d2c}"
           },
           "url": "https://jenkins.tools.madtech.nz/job/madc-crm-pipeline/job/PR-114/1/display/redirect",
           "links": {
             "commit": {
               "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm/commit/3eb51d6bf29f1a98818018582f2b46eb944dd598"
             },
             "self": {
               "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm/commit/3eb51d6bf29f1a98818018582f2b46eb944dd598/statuses/build/4becbd474f48d92e5c9ecd60a0d57c95"
             }
           },
           "refname": null,
           "state": "SUCCESSFUL",
           "created_on": "2018-11-21T20:56:35.514464+00:00",
           "commit": {
             "hash": "3eb51d6bf29f1a98818018582f2b46eb944dd598",
             "type": "commit",
             "links": {
               "self": {
                 "href": "https://api.bitbucket.org/2.0/repositories/completecc/madc-crm/commit/3eb51d6bf29f1a98818018582f2b46eb944dd598"
               },
               "html": {
                 "href": "https://bitbucket.org/completecc/madc-crm/commits/3eb51d6bf29f1a98818018582f2b46eb944dd598"
               }
             }
           },
           "updated_on": "2018-11-21T20:58:23.226770+00:00",
           "type": "build",
           "name": "madc-crm » PR-114 #1"
         }
       ]
DEBUG: Pull Request #114 does not need updating (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
DEBUG: Checking #114 for automerge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
 INFO: PR is not ready for merge (repository=completecc/madc-crm, dependencies=wheel, branch=renovate/wheel-0.32.x)
```

**Comment by ddehghan** [comment] 2018-12-22 14:34
This is a bug. automergeType is not defaulted to to pr.

I had the same problem but with GitLab. 

Noted this in the logs. even through it should have ben defaulted to "pr": 
>      "automergeComment": "automergeComment"

so I explicitly set "pr"
>      "automergeType": "pr",

and it started to work again.

**Comment by rarkins** [comment] 2018-12-22 14:49
automergeComment is a separate setting to automergeType though. That comment log is really just overeager logging and doesn’t indicate that automergeType=comment. AutomergeType defaults to pr. I suggest raising in renovatebot/config-help first in case it’s a config misunderstanding or ambiguity.

**Comment by TrejGun** [comment] 2019-11-03 16:12
I have the same problem with Github, checking @ddehghan 's solution

**Comment by rarkins** [comment] 2020-05-10 06:12
Closing due to inability to reproduce

**Closed by rarkins** 2020-05-10 06:12 UTC
Labels: #bitbucket, needs-requirements, pri3-normal
