### ISSUE TITLE
Fetch rubygems metadata

### ISSUE THREAD

**Issue by CPatchane** [renovatebot/renovate#8273] opened 2021-01-13 09:55 UTC
**What Renovate type, platform and version are you using?**

App for Github

**Describe the bug**

When getting a PR for a ruby gem, I don't have any changelog (compared to NPM renovate PRs).

**Relevant debug logs**

Here is a package infos found in the log (I got `DEBUG: There are 0 errors and 0 warnings` for this gem in the logs):
```
{
            "depName": "aws-sdk-s3",
            "managerData": {
              "lineNumber": 76
            },
            "currentValue": "~> 1.86",
            "datasource": "rubygems",
            "lockedVersion": "1.86.2",
            "depIndex": 52,
            "updates": [
              {
                "fromVersion": "1.86.0",
                "toVersion": "1.87.0",
                "newValue": "~> 1.87.0",
                "newMajor": 1,
                "newMinor": 87,
                "updateType": "minor",
                "isSingleVersion": false,
                "isRange": true,
                "isBump": true
              }
            ],
            "warnings": [],
            "fixedVersion": "1.86.2"
          }
```

I notice that I can't find any sourceUrl like we have for a node package:

```
{
            "depType": "dependencies",
            "depName": "@babel/core",
            "currentValue": "7.12.10",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "lockedVersion": "7.12.10",
            "depIndex": 2,
            "updates": [],
            "warnings": [],
            "fixedVersion": "7.12.10",
            "sourceUrl": "https://github.com/babel/babel",
            "sourceDirectory": "packages/babel-core",
            "homepage": "https://babeljs.io/"
          },
```

But maybe I am wrong and it's not related.

**Additional context**

I can find some changelog lines `DEBUG: Fetching changelog: https://github.com/eslint/eslint (7.16.0 -> 7.17.0)
` for NPM but nothing for ruby gems.
If we used to have the changelog before, maybe this is a change in the rubygems API or something similar?

**Comment by rarkins** [comment] 2021-01-13 10:14
We needed to stop querying the Rubygems API because of rate limiting and instead fetch the same file Bundler uses, but which does not contain metadata.

However we now support [concurrentRequestLimit](https://docs.renovatebot.com/configuration-options/#concurrentrequestlimit) in `hostRules` so could maybe try querying the API just to get metadata and caching it for a *long* time (e.g. a week) to reduce API stress. Even though, we may trip their rate limits again quickly.

**Comment by rarkins** [comment] 2021-01-13 10:19
Proposal:

Specifically for Rubygems.org, we should:
- Query the API for metadata only (e.g. `sourceUrl`)
- Try to comply with [rate limits](https://guides.rubygems.org/rubygems-org-rate-limits/)
- Cache for a long time (proposed: one week)

BTW I'm wondering if we should randomize the cache time a little so that we don't end up with waves of requests. e.g. if we turned this feature on we'd expect to hit Rubygems.org a lot in the first hour or so, but then have nearly everything cached for exactly one week before we have another large hour, etc. If we randomized our cache between 6-7 days with small granularity then that would help a lot).

**Comment by godric** [comment] 2021-01-13 10:25
👋 My two cents:
It's worth noting that since Changelog only changes when a new version is released. 
And even then, the Changelog for one specific version should not change. So if you could tie the cache to the Gem version you could theoretically keep it forever.

I realise that's it's a big assumption, but maybe good enough ?

**Comment by rarkins** [comment] 2021-01-13 10:29
The Changelog itself would usually fetched from GitHub and never from Rubygems.org directly, so not directly relevant to this problem. We do have a backoff algorithm that decides how long to cache those for, but we have nothing to cache if we never fetch the source URL from rubygems.org in the first place. In our experience, changelogs get changed sometimes, and also may be added well after the release itself - keeping forever would result in bad data.

**Comment by godric** [comment] 2021-01-13 14:10
@rarkins Makes sense! 
I wasn't actually suggesting to keep them forever, merely stating that longer that a week could work if necessary.

Thanks for the answer anyway, looking forward to this 🙇

**Comment by rarkins** [comment] 2021-08-18 11:19
Duplicate of #3670

**Closed by rarkins** 2021-08-18 11:19 UTC
Labels: type:feature, priority-3-normal, datasource:rubygems, status:ready
