### ISSUE TITLE
rollback PR created while using 'followTag' option and existing value is a range

### ISSUE THREAD

**Issue by ajafff** [renovatebot/renovate#2864] opened 2018-11-23 21:57 UTC
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
https://github.com/fimbullinter/wotan/pull/465 was created to "roll back" `typescript@^3.2.0-dev.20181114` -> `typescript@^3.3.0-dev`
I'm using the `"followTag": "next"` option.

This PR was created right after TypeScript started to publish prereleases of the new minor version.

**Did you see anything helpful in debug logs?**
Dashboard is currently not loading, sorry.

**To Reproduce**

**Expected behavior**
No rollback. Instead I want the usual update PR.

**Comment by rarkins** [comment] 2018-11-23 22:09
It looks like it's moving forward not backward. Was the 3.3.0-dev version wrong, or was it just the "roll back" that's wrong?

**Comment by rarkins** [comment] 2018-11-23 22:09
BTW try logging out then back in again in the dashboard if necessary

**Comment by ajafff** [comment] 2018-11-23 22:11
The relevant job log is at https://renovatebot.com/dashboard#github/fimbullinter/wotan/29632698. It doesn't find a version matching the current range (of course) and therefore creates the rollback PR.

It's not just the wording that's wrong. I'd like the update to contain the exact version like `^3.3.0-dev.20181122` instead of just `^3.3.0-dev`

**Comment by rarkins** [comment] 2018-11-24 07:44
I'm not sure I really considered the concept of followTag *and* ranges. Is it really necessary for your workflow to have the caret range, or can it be pinned to the exact version?

**Comment by ajafff** [comment] 2018-11-24 11:31
That caret range was actually a mistake I made when I manually updated the dependency once. For my workflow I prefer the exact pinned version.

**Comment by rarkins** [comment] 2018-11-24 13:54
Confirmed that if you have the existing versions as a non-range then it works as expected.

**Comment by ajafff** [comment] 2018-11-24 14:08
Awesome. Should this issue be closed then? Or do you want to keep it open to track `followTag` used with a version range?

**Comment by rarkins** [comment] 2018-11-24 14:10
I guess let’s close it, thanks

**Closed by rarkins** 2018-11-24 14:10 UTC
Labels: fix, pri4-low, ready
