### ISSUE TITLE
dependency not updated

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3254] opened 2019-02-22 01:21 UTC
**What Renovate type are you using?**
Renovate Pro?

**Describe the bug**
in `dmx-io/dmx-vehicle-info` repo, `joi-us-zipcode` library is still in `^1.0.4` version in `package.json` though `2.0.0` is available

`renovate.json`:
```
{
  "commitMessage": "[renovate] update all dependencies",
  "groupName": "All",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "rangeStrategy": "bump",
  "schedule": "before 5am on the 22nd day of the month",
  "packageRules": [
    {
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    }
  ]
}
```
I have a schedule for packages not matching `^@dmx/` but the last PR (https://github.com/dmx-io/dmx-vehicle-info/pull/414) except of `@dmx` packages updated `mocha` as well so I don't understand why it didn't update `joi-us-zipcode`.

**Did you see anything helpful in debug logs?**
I the logs I see:
```
DEBUG: 1 result(s): 1.10.122 (dmx_base)(dependency="dmx_base")
DEBUG: 1 result(s): ^2.0.0 (joi-us-zipcode)(dependency="joi-us-zipcode")
DEBUG: 1 result(s): >=v11.10.0 (node)(dependency="node")

...

DEBUG: Found PR #410(dependencies=["joi-us-zipcode"], branch="renovate/major-all")
DEBUG: Found closed PR with current title(dependencies=["joi-us-zipcode"], branch="renovate/major-all")
DEBUG: Returning from graphql closed PR list(dependencies=["joi-us-zipcode"], branch="renovate/major-all")
DEBUG: Closed PR already exists. Skipping branch.(dependencies=["joi-us-zipcode"], branch="renovate/major-all")
{
  "prTitle": "[renovate] update all dependencies"
}
INFO: Merged PR is blocking this branch(dependencies=["joi-us-zipcode"], branch="renovate/major-all")
{
  "pr": 410
}
DEBUG: branchPrefix: renovate/
DEBUG: Found 0 Renovate PRs
{
  "renovatePrs": []
}
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: No renovate branches found
```

I don't understand why a merged PR blocks updating `joi-us-zipcode`.
btw. the merged PR (https://github.com/dmx-io/dmx-vehicle-info/pull/410) updated only this:
```
mocha	devDependencies	major	`^5.2.0` -> `^6.0.0`
```
and the `renovate/major-all` branch has been deleted.

**Comment by rarkins** [comment] 2019-02-22 04:29
Please change your config to be like this (note the top two lines only):

```
{
  "commitMessagePrefix": "[renovate] ",
  "groupName": "all dependencies",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "rangeStrategy": "bump",
  "schedule": "before 5am on the 22nd day of the month",
  "packageRules": [
    {
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    }
  ]
}
```

**Comment by piotr-s-brainhub** [comment] 2019-02-22 05:07
thanks @rarkins 

I just updated all the repos with these `commitMessagePrefix` and `groupName`

**Comment by rarkins** [comment] 2019-02-22 09:41
Thanks for the feedback. The `commitMessage` override was causing problems with our "are there any existing PRs that should block this one?" logic. This should be the root cause of any merged PRs blocking updates logs that you've seen previously too.

I recommend enabling "masterIssue" for better visibility, and you might also want to have your own config preset hosted on github or npmjs so that you don't have to change config in more than one location each time.

**Closed by rarkins** 2019-02-22 09:41 UTC
