### ISSUE TITLE
Allow to pair dependencies based on an overlapping pattern

### ISSUE THREAD

**Issue by gajus** [renovatebot/renovate#14748] opened 2022-03-21 18:58 UTC
### What would you like Renovate to be able to do?

I want to pair all dependencies that match a pattern `@types/*` and `*`, e.g. `@types/react` and `react` both should be upgraded only if there is a version that is satisfied by both packages.

Some considerations: There should be an option to match up to a degree of accuracy. I would imagine that the most common use case would be to match based on the semver minor version and ignore patch differences, i.e. `@types/react` `v2.9.1` and `react` `v2.9.0` should be a valid pair (configurable).

### If you have any ideas on how this should be implemented, please tell us here.

N/A

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment] 2022-03-22 04:44
Let's combine this together with https://github.com/renovatebot/renovate/issues/519. It happens to be this project's second-oldest open issue. It's been a while since I thought about that, so some fresh eyes could help.

**Comment by rarkins** [comment] 2022-03-22 04:44
Duplicate of #519

**Closed by rarkins** 2022-03-22 04:44 UTC
Labels: type:feature, status:requirements, priority-5-triage
