### ISSUE TITLE
Support upgrading shared config version

### ISSUE THREAD

**Issue by fclairamb** [renovatebot/renovate#15807] opened 2022-05-31 12:33 UTC
### What would you like Renovate to be able to do?

We use renovate intensively at [habx](https://www.habx.com) through [shared renovate config](https://github.com/habx/devops-repo-shared-configs).

Renovate supports versioned config which is great but it doesn't support upgrading the config which is quite unfortunate.

So for example [here](https://github.com/habx/devops-repo-shared-configs/blob/0b9507479e26dc4cedc2a17b2e55d49396969ef1/.github/renovate.json#L4), I have a `v0.1.0` version of the config but the latest tag of the repo is `v0.11.0`, it would be nice to have a PR to upgrade it to v0.11.0.

This is useful because if I make major changes to my config I would prefer that it's not instantly applied to all our 400 repositories at once, let the `stabilityDays` delay this and force this for a few core repositories.

### If you have any ideas on how this should be implemented, please tell us here.

I guess it would be implemented by looking at the tags of the target config repos.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment] 2022-05-31 13:49
you can easily workaround with regex manager

**Comment by rarkins** [comment] 2022-06-02 14:55
Duplicate of #13308

**Closed by rarkins** 2022-06-02 14:55 UTC
Labels: type:feature, status:requirements, priority-5-triage
