### ISSUE TITLE
PIP requirements are case sensitive

### ISSUE THREAD

**Issue by josebama** [renovatebot/renovate#11139] opened 2021-08-06 16:23 UTC
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [X] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [X] GitLab self-hosted

Renovate version: 25.69.0

**Describe the bug**
When specifying `django` in my `requirements.txt`, Renovate fails to lookup the dependency. If I change it to `Django`, then it works. PIP requierements are meant to be case-insentive. From [PEP426](https://www.python.org/dev/peps/pep-0426/#name):

> All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.

both `pip install django` and `pip install Django` work exactly the same, and `https://pypi.org/simple/Django/` redirects to `https://pypi.org/simple/django/`.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
...
DEBUG: Failed to look up dependency django (repository=iwoca/renovate-testground, packageFile=requirements.txt, dependency=django)
DEBUG: Package releases lookups complete (repository=iwoca/renovate-testground)
       "baseBranch": "master"
DEBUG: branchifyUpgrades (repository=iwoca/renovate-testground)
DEBUG: 2 flattened updates found: django-model-utils, django-model-utils (repository=iwoca/renovate-testground)
DEBUG: Returning 2 branch(es) (repository=iwoca/renovate-testground)
DEBUG: config.repoIsOnboarded=true (repository=iwoca/renovate-testground)
DEBUG: packageFiles with updates (repository=iwoca/renovate-testground)
       "config": {
         "pip_requirements": [
           {
             "packageFile": "requirements.txt",
             "deps": [
               {
                 "depName": "django",
                 "currentValue": "==2.2.19",
                 "datasource": "pypi",
                 "currentVersion": "2.2.19",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "django",
                     "message": "Failed to look up dependency django"
                   }
                 ],
                 "versioning": "pep440"
               },
...
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [X] I have provided a minimal reproduction repository: https://github.com/josebama/renovate-issue-11139-reproduction
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Because `https://pypi.org/simple/django/` resolves, and the fact that there's no log `pip package not found` tells me that Renovate is actually finding the package, but failing to parse the response from pypi.

I believe the problem is in the function `extractVersionFromLinkText`, which compares strings that it got from the `GET https://pypi.org/simple/django/` response, where all lines start with `Django`, with the package name `django` that it read from the `requirements.txt`.

So probably making everything lower case before comparing the strings would be enough?

**Comment by josebama** [comment] 2021-08-09 16:44
Hi,

I have just created a minimal reproduction repository: https://github.com/josebama/renovate-issue-11139-reproduction

While reproducing it, I found out that it only happens when I set a registry URL in the config. From my readme:

It fails to lookup the `django` dependency.

<details><summary>Failing logs</summary>

```
DEBUG: Failed to look up dependency django (repository=josebama/renovate-issue-11139-reproduction, packageFile=requirements.txt, dependency=django)
DEBUG: Package releases lookups complete (repository=josebama/renovate-issue-11139-reproduction)
       "baseBranch": "main"
DEBUG: branchifyUpgrades (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: 0 flattened updates found:  (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: Returning 0 branch(es) (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: config.repoIsOnboarded=true (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: packageFiles with updates (repository=josebama/renovate-issue-11139-reproduction)
       "config": {
         "pip_requirements": [
           {
             "packageFile": "requirements.txt",
             "deps": [
               {
                 "depName": "django",
                 "currentValue": "==3.2.5",
                 "datasource": "pypi",
                 "currentVersion": "3.2.5",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "django",
                     "message": "Failed to look up dependency django"
                   }
                 ],
                 "versioning": "pep440"
               }
             ],
             "registryUrls": ["https://pypi.org/simple/"]
           }
         ]
       }
```

</details>

If I were to rename the dependency to `Django` instead, it would find it:

<details><summary>Logs with requirement set to Django instead of django</summary>

```
DEBUG: Package releases lookups complete (repository=josebama/renovate-issue-11139-reproduction)
       "baseBranch": "main"
DEBUG: branchifyUpgrades (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: 1 flattened updates found: Django (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: Returning 1 branch(es) (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: Fetching changelog: https://github.com/django/django (3.2.5 -> 3.2.6) (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: config.repoIsOnboarded=true (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: packageFiles with updates (repository=josebama/renovate-issue-11139-reproduction)
       "config": {
         "pip_requirements": [
           {
             "packageFile": "requirements.txt",
             "deps": [
               {
                 "depName": "Django",
                 "currentValue": "==3.2.5",
                 "datasource": "pypi",
                 "currentVersion": "3.2.5",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "3.2.6",
                     "newValue": "==3.2.6",
                     "newMajor": 3,
                     "newMinor": 2,
                     "updateType": "patch",
                     "isRange": true,
                     "branchName": "renovate/django-3.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "pep440",
                 "sourceUrl": "https://github.com/django/django",
                 "changelogUrl": "https://github.com/django/django/tree/master/docs/releases",
                 "isSingleVersion": true,
                 "fixedVersion": "3.2.5"
               }
             ],
             "registryUrls": ["https://pypi.org/simple/"]
           }
         ]
       }
```

</details>

This seems to only happen when setting a specific `registryUrls` in the config, even if it is the 
official registry. If I remove it, it also works fine with the `django` dependency:



<details><summary>Logs</summary>

```
DEBUG: Package releases lookups complete (repository=josebama/renovate-issue-11139-reproduction)
       "baseBranch": "main"
DEBUG: branchifyUpgrades (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: 1 flattened updates found: django (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: Returning 1 branch(es) (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: Fetching changelog: https://github.com/django/django (3.2.5 -> 3.2.6) (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: config.repoIsOnboarded=true (repository=josebama/renovate-issue-11139-reproduction)
DEBUG: packageFiles with updates (repository=josebama/renovate-issue-11139-reproduction)
       "config": {
         "pip_requirements": [
           {
             "packageFile": "requirements.txt",
             "deps": [
               {
                 "depName": "django",
                 "currentValue": "==3.2.5",
                 "datasource": "pypi",
                 "currentVersion": "3.2.5",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "3.2.6",
                     "newValue": "==3.2.6",
                     "releaseTimestamp": "2021-08-02T06:28:33.000Z",
                     "newMajor": 3,
                     "newMinor": 2,
                     "updateType": "patch",
                     "isRange": true,
                     "branchName": "renovate/django-3.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "pep440",
                 "sourceUrl": "https://github.com/django/django",
                 "homepage": "https://www.djangoproject.com/",
                 "changelogUrl": "https://github.com/django/django/tree/master/docs/releases",
                 "isSingleVersion": true,
                 "fixedVersion": "3.2.5"
               }
             ]
           }
         ]
       }
```

</details>

**Comment by viceice** [comment] 2021-08-09 18:13
It's because you've set registry url to the simple url

https://github.com/renovatebot/renovate/blob/f2b6af88da4f1784f65a33febc7704250b64c72e/lib/datasource/pypi/index.ts#L39-L63

Renovate default registry is this:
https://github.com/renovatebot/renovate/blob/f2b6af88da4f1784f65a33febc7704250b64c72e/lib/datasource/pypi/index.ts#L24-L26

**Comment by viceice** [comment] 2021-08-09 18:14
@josebama What's the intension with overriding the `registryUrls` ?

**Comment by viceice** [comment] 2021-08-09 18:17
Here is the code which is higly case sensitive:
https://github.com/renovatebot/renovate/blob/f2b6af88da4f1784f65a33febc7704250b64c72e/lib/datasource/pypi/index.ts#L168-L196

So best is to not use simple pypi registry at all and always use the newer JSON API.

**Comment by josebama** [comment] 2021-08-10 10:41
> What's the intension with overriding the registryUrls ?

In my original case, I'm using a private registry.

> It's because you've set registry url to the simple url

Thanks, I assumed I had to use simple, [like in PIP](https://pip.pypa.io/en/stable/cli/pip_install/#install-index-url), where it says the following:

> should point to a repository compliant with PEP 503 (the simple repository API)

I believe that the documentation should mention somewhere that the expected URL is not the one that points to simple, unlike with PIP. Another problem with this is that since the index-url set in the requirements file takes precedence over the one in `renovate.json` and that one should point to the simple API to play nice with PIP, now I am forced to put a package rule to avoid using simple as it is declared in the requirements file.

Also, why not make `extractVersionFromLinkText` case insensitive? That way simple will also behave as expected. I believe the fact that the function is not PEP 426 compliant makes this a bug.

**Comment by josebama** [comment] 2021-08-25 07:23
Hi,

why is this still marked as reproduction needed? I did provide a minimal reproduction repo: https://github.com/renovatebot/renovate/issues/11139#issuecomment-895375470 Is there anything else I should do?

**Comment by Bruceforce** [comment] 2021-09-21 10:04
I just wanted to add that when using Pipenv by default the following sections are added to the Pipfile
```
[[source]]
url = 'https://pypi.python.org/simple'
verify_ssl = true
name = 'pypi'
```
see <https://github.com/pypa/pipfile#pipfile>.

This seems to also persuade renovate bot to use the simple registry. At least I'm assuming this because I nowhere configured renovate to use any registry.

If I set url in the Pipfile manually to `url = https://pypi.python.org/pypi` it works as expected. But this bug caused all of my "Pipenv-Repositories" to fail the lookup because of wrong case in the package name and I had to spend a few hours in debugging.

**Comment by rarkins** [comment] 2021-09-22 05:56
@Bruceforce sounds like a separate (although related) problem you have regarding registry urls. Please start a discussion with some more info about it if you'd like us to look at it and decide if it's a bug or needs better docs

**Comment by Bruceforce** [comment] 2021-09-23 17:19
@rarkins I opened a separate issue which was closed in favor of this one here ;).

As requested in the other ticket I'll quickly copy-paste the content in here

### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:27.18.0-slim@sha256:f98bd8eccde499daaeb1b6ae47dabe778c10f2ad83e5e9d7f6c2f3707de5ac30

### Describe the bug

Renovate bot fails to lookup dependencies defined in Pipenv if the case in the Pipfile does not match the case in pypi. This can be fixed by either:
* changing the source.url to `https://pypi.org/pypi/` in the Pipfile or
* Change the case from flask to Flask in the Pipfile

However since the Pipfile in the reproduction repo was created by just issuing the command `pipenv install flask==2.0.0` this issue should be resolved since `https://pypi.org/simple` is the default registry for Pipenv.

Here is a minimal reproduction repo: <https://gitlab.com/1O/pipenv-case-issue>

This bug is most likely related to #11139.  

### Relevant debug logs

<details><summary>Logs</summary>

```
{
    "name": "renovate",
    "hostname": "runner-z3wu8uu--project-29850052-concurrent-0",
    "pid": 11,
    "level": 20,
    "logContext": "k6lMZ4C2G",
    "repository": "1O/pipenv-case-issue",
    "config": {
        "gitlabci-include": [
            {
                "packageFile": ".gitlab-ci.yml",
                "deps": [
                    {
                        "datasource": "gitlab-tags",
                        "depName": "renovate-bot/renovate-runner",
                        "depType": "repository",
                        "skipReason": "unknown-version",
                        "registryUrls": [
                            "https://gitlab.com"
                        ],
                        "depIndex": 0,
                        "updates": []
                    }
                ]
            }
        ],
        "pipenv": [
            {
                "packageFile": "Pipfile",
                "deps": [
                    {
                        "depType": "packages",
                        "depName": "flask",
                        "managerData": {},
                        "currentValue": "==2.0.0",
                        "datasource": "pypi",
                        "depIndex": 0,
                        "updates": [],
                        "warnings": [
                            {
                                "topic": "flask",
                                "message": "Failed to look up dependency flask"
                            }
                        ],
                        "versioning": "pep440"
                    }
                ],
                "registryUrls": [
                    "https://pypi.org/simple"
                ],
                "lockFiles": [
                    "Pipfile.lock"
                ],
                "constraints": {
                    "python": "== 3.8.*"
                }
            }
        ]
    },
    "msg": "packageFiles with updates",
    "time": "2021-09-23T16:31:41.269Z",
    "v": 0
}
```

</details>


### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by wwuck** [comment] 2021-09-27 02:14
This is affecting me as well.  I have a private Nexus pypi repository and it appears to only support the PEP-503 simple repository API.  [Artifactory](https://www.jfrog.com/confluence/display/JFROG/PyPI+Repositories), [GitLab package registry](https://docs.gitlab.com/ee/user/packages/pypi_repository/#package-names), and [Google Artifact Registry](https://cloud.google.com/artifact-registry/docs/python) also only support PEP-503 package names.

Also, as mentioned by @josebama, the [`--index-url`](https://pip.pypa.io/en/stable/cli/pip_install/#install-index-url) argument to `pip install` says it only supports PEP-503 urls.

[PEP-503](https://www.python.org/dev/peps/pep-0503/#normalized-names) (Simple Repository API) says that all package names should be "normalized" to lowercase.

When I have a requirement of `sqlalchemy==1.4.23` listed in `setup.cfg`, it is not currently detected by renovate.  Renovate will only detect it when I change the requirement to `SQLAlchemy==1.4.23`.

**Comment by rarkins** [comment] 2021-09-27 04:57
Should pypi lookups always be case insensitive or do we need to determine which are and which aren't?

**Comment by Bruceforce** [comment] 2021-09-27 05:38
What would be arguments against a general case insensitivity? 

If I read <https://www.python.org/dev/peps/pep-0426/#name> correctly it says that package comparison MUST be case insensitive.

> All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.

**Closed** 2021-12-10 18:44 UTC
Labels: type:bug, priority-2-important, datasource:pypi, status:requirements, reproduction:provided
