### ISSUE TITLE
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. on creating of onboarding branches/PRs

### ISSUE THREAD

**Issue by Johannes1509** [renovatebot/renovate#18581] opened 2022-10-26 13:39 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Docker image renovate:32.236.3

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab Community Edition 15.4.1

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I am running renovate on multiple repositories with Dockerfiles. For about 95% the onboarding branch was created correctly, but for three repositories renovate exits with this error. No onboarding branch is created and no onboarding PR is created.
The repository is not empty.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for **MASKEDHOST** to hostRules
 INFO: Repository started (repository=**MASKEDPATH**/nginx)
       "renovateVersion": "32.236.3"
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/**MASKEDPATH**/nginx (repository=**MASKEDPATH**/nginx)
DEBUG: PackageFiles.clear() - Package files deleted (repository=**MASKEDPATH**/nginx)
       "baseBranches": []
DEBUG: No concurrency limits (repository=**MASKEDPATH**/nginx)
       "host": "**MASKEDHOST**"
DEBUG: **MASKEDPATH**/nginx default branch = v1.12 (repository=**MASKEDPATH**/nginx)
DEBUG: Enabling Git FS (repository=**MASKEDPATH**/nginx)
DEBUG: using http URL (repository=**MASKEDPATH**/nginx)
       "url": "https://**MASKEDHOST**/**MASKEDPATH**/nginx.git"
DEBUG: Resetting npmrc (repository=**MASKEDPATH**/nginx)
DEBUG: detectSemanticCommits() (repository=**MASKEDPATH**/nginx)
DEBUG: Initializing git repository into /tmp/renovate/repos/gitlab/**MASKEDPATH**/nginx (repository=**MASKEDPATH**/nginx)
DEBUG: Performing blobless clone (repository=**MASKEDPATH**/nginx)
DEBUG: git clone completed (repository=**MASKEDPATH**/nginx)
       "durationMs": 270
ERROR: Repository has unknown error (repository=**MASKEDPATH**/nginx)
       "err": {
         "task": {
           "commands": ["rev-parse", "HEAD"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)"
       }
DEBUG: Unknown res (repository=**MASKEDPATH**/nginx)
       "res": "unknown-error"
DEBUG: Repository result: unknown-error, status: unknown, enabled: undefined, onboarded: undefined (repository=**MASKEDPATH**/nginx)
DEBUG: Repository timing splits (milliseconds) (repository=**MASKEDPATH**/nginx)
       "splits": {},
       "total": 601
DEBUG: Package cache statistics (repository=**MASKEDPATH**/nginx)
       "get": {"count": 0},
       "set": {"count": 0}
DEBUG: dns cache (repository=**MASKEDPATH**/nginx)
       "hosts": []
 INFO: Repository finished (repository=**MASKEDPATH**/nginx)
       "cloned": true,
       "durationMs": 601
DEBUG: Reinitializing hostRules for repo
DEBUG: Clearing hostRules
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by PhilipAbed** [comment] 2022-10-27 12:39
it fails on running a git command `git rev-parse HEAD`, and it's failing with this exception.

reasons vary, but usually it happens on an empty repository where HEAD is not pointing to anything

what happens if you run 
`git show HEAD`?

does it work??

**Comment by rarkins** [comment] 2022-10-27 12:54
Let's continue the discussion in #16070, if anyone can shed new light on it.

**Comment by rarkins** [comment] 2022-10-27 12:54
Duplicate of #16070

**Closed by rarkins** 2022-10-27 12:54 UTC
Labels: type:bug, status:requirements, priority-5-triage
