### ISSUE TITLE
Renovate don't listen to PHP version constraints [Symfony] [Bitbucket]

### ISSUE THREAD

**Issue by dutchdevx** [renovatebot/renovate#19349] opened 2022-12-12 10:11 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest (34.55.0)

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

Bitbucket Cloud

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate don't listen to the requirements of PHP version.
It will open pull requests for PHP 8.1 on my Symfony Repo.

`{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "baseBranches": [
    "staging"
  ],
  "force": {
    "constraints": {
      "php": "< 8.0.25"
    }
  },
  "enabledManagers": [
    "npm",
    "composer"
  ],
  "packageRules": [
    {
      "matchUpdateTypes": [
        "major"
      ],
      "enabled": false
    },
    {
      "matchPackageNames": [
        "datatables.net",
        "datatables.net-bs4",
        "datatables.net-buttons",
        "datatables.net-buttons-bs4",
        "datatables.net-dt",
        "datatables.net-responsive",
        "datatables.net-responsive-bs4",
        "datatables.net-scroller",
        "datatables.net-scroller-bs4",
        "datatables.net-select",
        "datatables.net-select-bs4",
        "summernote",
        "typescript"
      ]
    }
  ]
}
`

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment] 2022-12-12 10:18
Duplicate of #18715

**Closed by viceice** 2022-12-12 10:18 UTC
Labels: status:requirements, priority-5-triage
