### ISSUE TITLE
Report / summary of all dependencies (across the whole codebase/org/etc)

### ISSUE THREAD

**Issue by dominykas** [renovatebot/renovate#8229] opened 2021-01-09 10:21 UTC
**What would you like Renovate to be able to do?**

Renovate already scans the list of _all_ available dependencies to get the latest versions for them. It would be nice to generate a summary of that (incl. all the regex based ones, etc).

This would be useful for generic audit purposes, esp. if there's a need to check whether some dependencies became deprecated or have not had any updates in a long time and need a replacement altogether.

**Did you already have any implementation ideas?**

I guess renovate already logs all of that information (I've seen a lot of it in debug logs), so it's a matter of collecting that into some object and dumping that into a `report.json` or `report.csv` at the end (if configured)?

I have not explored further just yet.

**Comment by viceice** [comment] 2021-01-09 10:28
Duplicate of #7372

**Closed by viceice** 2021-01-09 10:28 UTC
