### ISSUE TITLE
gitea parsing /user/login as json fails

### ISSUE THREAD

**Issue by tombueng** [renovatebot/renovate#15325] opened 2022-04-27 08:44 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.32.0

### Please select which platform you are using if self-hosting.

Gitea

### If you're self-hosting Renovate, tell us what version of the platform you run.

1.16.5

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

For gitea renovabot seems to try to retrieve /user/login an parse it as json which fails.
For gitea 1.16.5 the response seems to be html instead of json.
"Accept; application/json" seem to be sent to gitea correctly according to the logs.

### Relevant debug logs

<details><summary>Logs</summary>

```
docker run --rm --env-file env -v ".../config.js:/usr/src/app/config.js" renovate/renovate 
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /usr/src/app/config.js
 WARN: Config needs migrating
       "originalConfig": {
         "endpoint": "https://git.xxxx.com/",
         "token": "***********",
         "platform": "gitea",
         "dryRun": "true",
         "logLevel": "debug",
         "onboardingConfig": {"extends": ["config:base"]},
         "repositories": ["company/application"],
         "renovateFork": true,
         "gitAuthor": "Bot <bot@xxxx.com>",
         "username": "user.name",
         "onboarding": false,
         "printConfig": true,
         "requireConfig": true
       },
       "migratedConfig": {
         "endpoint": "https://git.xxxx.com/",
         "token": "***********",
         "platform": "gitea",
         "dryRun": "true",
         "logLevel": "debug",
         "onboardingConfig": {"extends": ["config:base"]},
         "repositories": ["company/application"],
         "includeForks": true,
         "gitAuthor": "Bot <bot@xxxx.com>",
         "username": "user.name",
         "onboarding": false,
         "printConfig": true,
         "requireConfig": true
       }
DEBUG: File config
       "config": {
         "endpoint": "https://git.xxxx.com/",
         "token": "***********",
         "platform": "gitea",
         "dryRun": "true",
         "logLevel": "debug",
         "onboardingConfig": {"extends": ["config:base"]},
         "repositories": ["company/application"],
         "includeForks": true,
         "gitAuthor": "Bot <bot@xxxx.com>",
         "username": "user.name",
         "onboarding": false,
         "printConfig": true,
         "requireConfig": true
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [],
         "dockerUser": "root",
         "platform": "gitea",
         "token": "***********"
       }
DEBUG: Combined config
       "config": {
         "endpoint": "https://git.xxxx.com/",
         "token": "***********",
         "platform": "gitea",
         "dryRun": "true",
         "logLevel": "debug",
         "onboardingConfig": {"extends": ["config:base"]},
         "repositories": ["company/application"],
         "includeForks": true,
         "gitAuthor": "Bot <bot@xxxx.com>",
         "username": "user.name",
         "onboarding": false,
         "printConfig": true,
         "requireConfig": true,
         "hostRules": [],
         "dockerUser": "root"
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Found valid git version: 2.36.0
DEBUG: Error authenticating with Gitea. Check your token
       "err": {
         "name": "ParseError",
         "code": "ERR_BODY_PARSE_FAILURE",
         "timings": {
           "start": 1650981233045,
           "socket": 1650981233045,
           "lookup": 1650981233048,
           "connect": 1650981233085,
           "secureConnect": 1650981233209,
           "upload": 1650981233209,
           "response": 1650981233238,
           "end": 1650981233241,
           "phases": {
             "wait": 0,
             "dns": 3,
             "tcp": 37,
             "tls": 124,
             "request": 0,
             "firstByte": 29,
             "download": 3,
             "total": 196
           }
         },
         "message": "Unexpected token < in JSON at position 0 in \"https://git.xxxx.com/user/login\"",
         "stack": "RequestError: Unexpected token < in JSON at position 0 in \"https://git.xxxx.com/user/login\"\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:22:15)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at JSON.parse (<anonymous>)\n    at parseJson (/usr/src/app/node_modules/got/dist/source/index.js:118:35)\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:11:48)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.32.0 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://git.xxxx.com/user/login",
           "hostType": "gitea",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 200,
           "statusMessage": "OK",
           "body": "<!DOCTYPE html>\n<html lang=\"en-US\" class=\"theme-\">\n<head>\n\t.......</body>\n</html>\n\n",
           "headers": {
             "date": "Tue, 26 Apr 2022 13:53:53 GMT",
             "server": "Apache",
             "content-type": "text/html; charset=UTF-8",
             "vary": "Accept-Encoding",
             "x-frame-options": "SAMEORIGIN",
             "set-cookie": [
               "i_like_gitea=07a66fe9508f1db0; Path=/; HttpOnly; SameSite=Lax",
               "_csrf=GdrzoiAoGpey_-xrJcpum8eEz-xxxxxxx; Path=/; Expires=Wed, 27 Apr 2022 13:53:53 GMT; HttpOnly; SameSite=Lax",
               "macaron_flash=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax"
             ],
             "content-encoding": "gzip",
             "connection": "close",
             "transfer-encoding": "chunked"
           },
           "httpVersion": "1.1"
         }
       }
FATAL: Authentication failure
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "xxxxxxxxxxxx",
           "msg": "Authentication failure"
         }
       ]

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment] 2022-04-27 09:34
Duplicate of https://github.com/renovatebot/renovate/discussions/15316

**Closed by viceice** 2022-04-27 09:34 UTC
Labels: type:bug, status:requirements, priority-5-triage
