### ISSUE TITLE
Regex manager: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by danports** [renovatebot/renovate#15914] opened 2022-06-06 16:13 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest (from GitLab template project)

### Please select which platform you are using if self-hosting.

gitlab.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate started throwing the following exception a couple of hours ago with no configuration changes on my side - seems like a regression:

```
TypeError: Cannot read properties of undefined (reading 'map')
    at handleAny (/usr/src/app/node_modules/renovate/lib/modules/manager/regex/strategies.ts:17:6)
    at Object.extractPackageFile (/usr/src/app/node_modules/renovate/lib/modules/manager/regex/index.ts:27:23)
    at extractPackageFile (/usr/src/app/node_modules/renovate/lib/modules/manager/index.ts:70:9)
    at getManagerPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:66:43)
    at /usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:50:28
    at async Promise.all (index 6)
    at extractAllDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:48:26)
    at extract (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:82:20)
    at extractDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/process/index.ts:105:26)
    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:42:52)
    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:152:7)
    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22
```

### Relevant debug logs

Doesn't look like there's anything else interesting here.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by AKorezin** [comment] 2022-06-06 16:33
I have the same issue.

## If you're self-hosting Renovate, tell us what version of Renovate you run.

`32.75.0` and `32.76.0`

## Describe the bug

Introduced in version `32.75.0`
Caused by `regexManagers` in `Dockerfile`. 

## Minimal repo
https://gitlab.com/AKorezin/renovate-issue-15914

**Comment by rarkins** [comment] 2022-06-06 16:53
Will be fixed in https://github.com/renovatebot/renovate/pull/15915 once merged

**Closed** 2022-06-06 17:07 UTC
Labels: type:bug, priority-1-critical, status:in-progress

**Comment by AKorezin** [comment] 2022-06-06 18:47
Waiting for https://gitlab.com/renovate-bot/renovate-runner

**Comment by danports** [comment] 2022-06-06 21:30
GitLab pipeline looks good now, thanks @rarkins @viceice!
