### ISSUE TITLE
CircleCI manager uses wrong branchPrefix for orbs

### ISSUE THREAD

**Issue by cfra** [renovatebot/renovate#3615] opened 2019-04-30 12:18 UTC
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**

We are using Renovate to perform upgrades of our CircleCI configuration.

We use CircleCI orbs.

Updates to the CircleCI orb-tools orb get put into a branch called `renovate/docker-orb-tools-8.x`. 

**To Reproduce**

1. Create a repo containing a `.circleci/config.yml` with the contents:
```yaml
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.5.0
```

**Expected behavior**

The branch should be called `renovate/circleci-orb-tools-8.x` or `renovate/orb-orb-tools-8.x`, or something else, but it should not contain `docker-`.

**Additional context**

**Comment by rarkins** [comment] 2019-04-30 12:46
This is because we started out with CircleCI considered part of the "docker" language and Docker defaults to using manager prefixes. Because managers can contain different datasource types, any prefixes should really be part of the datasource, not manager.

You could override this by config for now like this:

```json
{
  "packageRules: [{
	"datasources": ["orb"],
    "managerBranchPrefix": ""
  }]
}
```

**Comment by MaronHatoum** [comment] 2022-08-08 13:42
reproduction repository: https://github.com/MaronHatoum/bug-3615

**Comment by MaronHatoum** [comment] 2022-08-08 14:03
After running the latest release of Renovate on the reproduction repository,
Renovate created a new branch called:  `renovate/orb-tools-11.x`

- Logs from the last run: 
```
DEBUG: packageFiles with updates (repository=MaronHatoum/bug-3615)
       "config": {
         "circleci": [
           {
             "packageFile": ".circleci/config.yml",
             "deps": [
               {
                 "depType": "orb",
                 "depName": "orb-tools",
                 "currentValue": "8.5.0",
                 "datasource": "orb",
                 "packageName": "circleci/orb-tools",
                 "commitMessageTopic": "{{{depName}}} orb",
                 "versioning": "npm",
                 "rangeStrategy": "pin",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "major",
                     "newVersion": "11.2.0",
                     "newValue": "11.2.0",
                     "releaseTimestamp": "2022-06-01T17:13:57.771Z",
                     "newMajor": 11,
                     "newMinor": 2,
                     "updateType": "major",
                     "branchName": "renovate/orb-tools-11.x"
                   }
                 ],
                 "warnings": [],
                 "homepage": "https://circleci.com/developer/orbs/orb/circleci/orb-tools",
                 "currentVersion": "8.5.0",
                 "isSingleVersion": true,
                 "fixedVersion": "8.5.0"
               }
             ]
           }
         ]
       }
DEBUG: processRepo() (repository=MaronHatoum/bug-3615)
DEBUG: Processing 1 branch: renovate/orb-tools-11.x (repository=MaronHatoum/bug-3615)
```

- new branch in `github`:
![image](https://user-images.githubusercontent.com/98313426/183435695-2d54ccc5-e743-4097-84cc-25b3b2a675ec.png)

- new PR has been created also: 
![image](https://user-images.githubusercontent.com/98313426/183435826-b509064b-a977-4d46-a270-7537fadd645f.png)

As you see the new branch called: `renovate/orb-tools-11.x` does not contain 'docker`.

- I think we can close this issue.

**Closed** 2022-08-08 15:21 UTC
Labels: type:bug, priority-4-low, manager:circleci, status:ready, reproduction:provided
