### ISSUE TITLE
Allow renovation on mirrored GitLab projects

### ISSUE THREAD

**Issue by astellingwerf** [renovatebot/renovate#16864] opened 2022-07-29 21:41 UTC
### What would you like Renovate to be able to do?

For a GitLab project that originates from a forked GitHub project, and for which we've set up mirroring (pulling), Renovate refuses to work on it.  Unlike for forking, there appears to be no way to allow/force Renovate to work on it despite the mirroring configuration.  I don't see why the fact that a project also pulls from other servers is any different from users pushing to it.  I'd like to be able to, either by default or after adding an extra property in `renovate.json`, Renovate GitLab projects that do mirror.

### If you have any ideas on how this should be implemented, please tell us here.

I guess, either effectively revert df0d79f, or add a condition that checks that a property a la `includeForks` allows the Renovation.
```
    if (res.body.mirror) {
      logger.debug(
        'Repository is a mirror - throwing error to abort renovation'
      );
      throw new Error(REPOSITORY_MIRRORED);
    }
```

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment] 2022-07-30 03:48
I'm not sure this makes sense, as the next pull from upstream will revert any changes and the existing closed PR's will block new updates.

**Comment by astellingwerf** [comment] 2022-07-30 09:16
I don't believe that that's true. There are branches in the GitLab project that don't exist in the mirrored repo. Those are the branches that need the renovation.

**Comment by viceice** [comment] 2022-07-30 09:19
you know that renovate only reads the config from default branch where `baseBranches` option needs to be configured?

**Comment by astellingwerf** [comment] 2022-07-30 09:22
Yes, I know, and that's how the GitLab project is setup.

**Comment by PhilipAbed** [comment] 2022-07-31 11:15
@astellingwerf  there's another task for this https://github.com/renovatebot/renovate/issues/16436

**Comment by viceice** [comment] 2022-07-31 12:28
Duplicate of #16436

**Closed** 2022-07-31 12:28 UTC
Labels: type:feature, platform:gitlab, status:requirements, duplicate, priority-5-triage
