### ISSUE TITLE
Weird bug with emoji/icons and Bitbucket Server PRs

### ISSUE THREAD

**Issue by gjoseph** [renovatebot/renovate#4953] opened 2019-12-10 00:22 UTC
**What Renovate type are you using?**

self-hosted

**Describe the bug**

See 2 screenshots below - it looks like, depending on the number of updated libraries that start with a `@` (@types, @atlaskit, ...), the emoji-icons used at the bottom of the description, are not properly substituted.

<img width="705" alt="Screen Shot 2019-12-10 at 11 20 08" src="https://user-images.githubusercontent.com/74627/70484175-296b2a00-1b3f-11ea-8a1b-589ac9a6b3dd.png">

(the `@types/` deps are listed at the top of this PR, could not screenshot the whole thing)

<img width="626" alt="Screen Shot 2019-12-10 at 11 20 24" src="https://user-images.githubusercontent.com/74627/70484178-2cfeb100-1b3f-11ea-8a03-8e45cf7d7cca.png">

**Did you see anything helpful in debug logs?**

Nope

**To Reproduce**

Create a PR that updates libraries starting with `@`. Not sure if this is Bitbucket Server specific.

**Additional context**

**Comment by rarkins** [comment] 2019-12-10 05:32
Can you provide an exact repo that reproduces this on BB Server? Please validate it against your server instance then copy the files to a public location like a GitHub repo

**Comment by gjoseph** [comment] 2019-12-10 06:57
@rarkins good idea, will do.

**Comment by gjoseph** [comment] 2019-12-10 23:38
@rarkins here you go: https://github.com/gjoseph/renovate-bugs
 - shows both #4953 and #4952 
Here's a screenshot for one of the PRs

<img width="665" alt="Screen Shot 2019-12-11 at 10 30 43" src="https://user-images.githubusercontent.com/74627/70578606-57fe0900-1c02-11ea-8796-860dfb87e741.png">


(I expected jest and @types/jest would be bumped in the same PR, btw, i might have a look at contributing a group or two if that made sense ?)

**Comment by rarkins** [comment] 2019-12-11 07:03
Are you able to also "view source" on that PR and paste the raw contents in here?

@ViceIce any chance you can reproduce this with your BBS?

**Comment by rarkins** [comment] 2019-12-11 07:06
FYI I just fixed #4952 in master. I don't think it's related to this, but you never know.

**Comment by ViceIce** [comment] 2019-12-11 10:24
@gjoseph Are you using `unicodeEmoji=true` ?

**Comment by ViceIce** [comment] 2019-12-11 10:35
![image](https://user-images.githubusercontent.com/1798109/70614082-2b4def80-1c0a-11ea-8443-4872763310ea.png)

only happens with `unicodeEmoji=false`.

```md
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped) | devDependencies | patch | [`24.0.22` -> `24.0.23`](https://renovatebot.com/diffs/npm/@types%2fjest/24.0.22/24.0.23) |

---

### Renovate configuration

:date: **Schedule**: At any time (no schedule defined).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Whenever PR becomes conflicted.

:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.

---

This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).
```

**Comment by ViceIce** [comment] 2019-12-11 10:38
`unicodeEmoji=true`

```md
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped) | devDependencies | patch | [`24.0.22` -> `24.0.23`](https://renovatebot.com/diffs/npm/@types%2fjest/24.0.22/24.0.23) |

---

### Renovate configuration

📅 **Schedule**: At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻️ **Rebasing**: Whenever PR becomes conflicted.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).
```

**Comment by ViceIce** [comment] 2019-12-11 10:40
@gjoseph Please add `unicodeEmoji=true` to your `config.js` as a workaround.

@rarkins I think we can't do anything, looks like a bitbucket server markdown issue.

**Comment by rarkins** [comment] 2019-12-11 11:56
@gjoseph please confirm if the workaround succeeds. @ViceIce would that mean we should default to unicodeEmoji=true?

**Comment by ViceIce** [comment] 2019-12-11 12:06
@rarkins yes, planned for [v20](renovatebot/renovate#4426)

**Comment by gjoseph** [comment] 2019-12-12 10:33
Can that option be set at the repo level? Because if it can, I'm not sure what I'm doing wrong but I still see the bug: https://github.com/gjoseph/renovate-bugs/blob/master/renovate.json5
(and if it can't, perhaps invalid repo-configuration could/should be flagged in logs)

Meanwhile, I'm talking to BB developers to see about a fix to their markdown rendering.

**Comment by viceice** [comment] 2020-11-02 14:14
@rarkins I'll close this, as I've never seen this since `unicodeEmoji` becomes enabled by default. Also we don't have any new feedback.

**Closed by viceice** 2020-11-02 14:14 UTC
Labels: bug, platform:bitbucket
