### ISSUE TITLE
renovate/sidecar image is missing libraries to run pip-compile

### ISSUE THREAD

**Issue by ns-ggeorgiev** [renovatebot/renovate#20606] opened 2023-02-24 07:40 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

not sure

### Describe the bug

Some python libraries depend on dev package and other libraries. It is not exactly clear why but pip-compile tried to compile some libraries while determining the versions and as result fails for certain libraries if certain libraries are missing on the image. I have found for the set of libraries I use these are needed:
    "libffi-dev",
    "libgirepository-1.0-1",
    "libglib2.0-dev",
    "libmysqlclient-dev",
    "libssl-dev",

### Relevant debug logs

Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v "/tmp/renovate/repos/github/netskope/service":"/tmp/renovate/repos/github/netskope/service" -v "/tmp/renovate/cache":"/tmp/renovate/cache" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w "/tmp/renovate/repos/github/netskope/service/components/malinfo" docker.io/renovate/sidecar bash -l -c "install-tool python 3.8.16 && pip install --user pip-tools && pip-compile --allow-unsafe --generate-hashes requirements.in"
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [13 lines of output]
        /bin/sh: 1: mysql_config: not found
        /bin/sh: 1: mariadb_config: not found
        /bin/sh: 1: mysql_config: not found
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/tmp/pip-resolver-3v08s_06/mysqlclient/setup.py", line 15, in <module>
            metadata, options = get_config()
          File "/tmp/pip-resolver-3v08s_06/mysqlclient/setup_posix.py", line 65, in get_config
            libs = mysql_config("libs")
          File "/tmp/pip-resolver-3v08s_06/mysqlclient/setup_posix.py", line 31, in mysql_config
            raise OSError("{} not found".format(_mysql_config_path))
        OSError: mysql_config not found
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 64, in generate_metadata
    call_subprocess(
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: python setup.py egg_info exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/piptools/scripts/compile.py", line 589, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/piptools/resolver.py", line 253, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/piptools/resolver.py", line 343, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/piptools/resolver.py", line 456, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/piptools/repositories/local.py", line 87, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 238, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 201, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 509, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 462, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 545, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
  File "/opt/buildpack/tools/python/3.8.16/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 71, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by ns-ggeorgiev** [comment] 2023-02-24 07:46
I need to solve this sooner than later. Do you think that PR for the renovate/sidecar that adds to the image those libraries will be accepted, or I should consider of building my own image?

If I need to go on the path of building my own image, what is the easiest way that I can substitute only the sidecar image?

**Comment by viceice** [comment] 2023-02-24 08:01
Duplicate of https://github.com/containerbase/base/issues/98

**Closed** 2023-02-24 08:08 UTC
Labels: type:bug, status:requirements, priority-5-triage
