### ISSUE TITLE
Group PRs get version of one package to the PR title

### ISSUE THREAD

**Issue by back-2-95** [renovatebot/renovate#17092] opened 2022-08-10 05:22 UTC
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When having group PR made by Renovate, now the PR gets version of the last item updated in the PR.

See our group configuration:

```
{
      "matchPackagePrefixes": [
        "drupal/"
      ],
      "excludePackageNames": [
        "drupal/drupal",
        "drupal/core-dev",
        "drupal/core-dev-pinned",
        "drupal/core-recommended",
        "drupal/core-composer-scaffold"
      ],
      "updateTypes": ["patch", "minor"],
      "groupName": "Drupal modules",
      "addLabels": [
        "drupal",
        "drupal-module"
      ]
    },
```

Here the tile used to be either `Drupal modules (patch)` or `Drupal modules (minor)`.

Now for ~1 week these PRs get updated title to `Drupal modules to v3.1.1 (patch)` in case of one of the packages got updated and the new version was e.g. 3.1.1.

Here is one PR:

![CleanShot 2022-08-10 at 08 21 59@2x](https://user-images.githubusercontent.com/1140272/183821993-bda637bd-6fd2-488b-98fb-457033dec1d4.png)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment] 2022-08-10 05:58
seen this too for docker digest updates

**Comment by PhilipAbed** [comment] 2022-08-10 06:49
could be a duplicate of https://github.com/renovatebot/renovate/issues/16925

**Comment by viceice** [comment] 2022-08-10 07:05
Duplicate of #16925

**Closed** 2022-08-10 07:05 UTC
Labels: type:bug, priority-2-high, reproduction:needed, status:ready, core:config

**Comment by back-2-95** [comment] 2022-08-10 07:21
Thank you, seems to be same issue

**Comment by viceice** [comment] 2022-08-10 10:04
v32.152.0 brokes the version updates

- #16831
