### ISSUE TITLE
Permission problem running on openshift

### ISSUE THREAD

**Issue by alclonky** [renovatebot/renovate#4810] opened 2019-11-14 16:36 UTC
**What Renovate type are you using?**

on-premise renovate pro (0.17) running in openshift (4.2) againt gitlab

**Describe the bug**

By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID.
Tools like gradle are creating folders and files in userhome which isn't assigned or writable for that user.
see [https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines](url) -> Support Arbitrary User IDs

`
WARN: Gradle command sh gradlew --init-script renovate-plugin.gradle renovate failed. Exit code: 1. (repository=cd/infrastructure-test)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "sh gradlew --init-script renovate-plugin.gradle renovate",
         "stdout": "",
         "stderr": "Exception in thread \"main\" java.lang.RuntimeException: Could not create parent directory for lock file /.gradle/wrapper/dists/gradle-3.3-bin/198d7xr26wl2adv8ldd17x5v/gradle-3.3-bin.zip.lck\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)\n",
         "message": "Command failed: sh gradlew --init-script renovate-plugin.gradle renovate\nException in thread \"main\" java.lang.RuntimeException: Could not create parent directory for lock file /.gradle/wrapper/dists/gradle-3.3-bin/198d7xr26wl2adv8ldd17x5v/gradle-3.3-bin.zip.lck\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)\n",
         "stack": "Error: Command failed: sh gradlew --init-script renovate-plugin.gradle renovate\nException in thread \"main\" java.lang.RuntimeException: Could not create parent directory for lock file /.gradle/wrapper/dists/gradle-3.3-bin/198d7xr26wl2adv8ldd17x5v/gradle-3.3-bin.zip.lck\n\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)\n\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)\n\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       }
`

**To Reproduce**

run renovate on openshift

**Additional context**

**Comment by ikesyo** [comment] 2019-11-14 17:06
It seems that this is a duplicate of #4764.

**Comment by alclonky** [comment] 2019-11-14 18:22
Sorry did not see the other issue,
is there a Pro build with this fix we could try?

**Comment by JamieMagee** [comment] 2019-11-14 22:05
@alclonky There isn't a fix for this bug available yet. I'm going close this issue as a duplicate of #4764

**Closed by JamieMagee** 2019-11-14 22:05 UTC

**Comment by ikesyo** [comment] 2019-11-15 00:13
FYI there is a ongoing pull request #4785.
