### ISSUE TITLE
Truncate branch name to defined length

### ISSUE THREAD

**Issue by dbendaou** [renovatebot/renovate#8191] opened 2021-01-05 13:59 UTC
**What would you like Renovate to be able to do?**
Add an option to being able to specify the max length of the created branch. 

Because today our CI auto-deploy merge request to a dedicated staging environnement, branch name cannot exceed a hard length (32). I would like to being able to specify this in order to avoid created branch to not be staged because of this limitation. 

**Did you already have any implementation ideas?**
Roughly something like 
```javascript
const maxLength = 32
if (branchName.length < maxLength) {
   branchName = branchName.substring(0, maxLength);
}
```
I guess it should be added around there https://github.com/renovatebot/renovate/blob/5fdac61665345f71dd2a5662418d3892487c7ee0/lib/workers/repository/updates/branch-name.ts#L53

I would be happy to help adding this to the configurationOptions :)

**Comment by rarkins** [comment] 2021-01-05 15:44
Duplicate of #5390 - please see the discussions and concern there. Typically the last characters in a branch are what distinguishes major from minor

**Closed by rarkins** 2021-01-05 15:44 UTC

**Comment by dbendaou** [comment] 2021-01-06 09:21
Looking into it, thanks!
