### ISSUE TITLE
Updating terraform provider creates invalid lock file: "The recorded version constraints for provider ... must be written in normalized form"

### ISSUE THREAD

**Issue by DavidS-om** [renovatebot/renovate#21062] opened 2023-03-21 07:52 UTC
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Any update from Renovate to our terraform repository creates an invalid configuration that terraform complains about:

```
Initializing the backend...
╷
│ Error: Invalid provider version constraints
│ 
│   on .terraform.lock.hcl line 6:
│   (source code not available)
│ 
│ The recorded version constraints for provider
│ registry.terraform.io/hashicorp/aws must be written in normalized form: ">=
│ 4.56.0".
╵
```

Minimal reproduction:
* [repo](https://github.com/DavidS-om/renovate-tf-repro)
* working state pre-update: [commit](https://github.com/DavidS-om/renovate-tf-repro/commit/ab9c9ce6a973fced47443124e5428b72aa6f07ce) ([check](https://github.com/DavidS-om/renovate-tf-repro/actions/runs/4476644832/jobs/7867217353))
* onboarding PR: https://github.com/DavidS-om/renovate-tf-repro/pull/1
* failing PR: https://github.com/DavidS-om/renovate-tf-repro/pull/2

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

**Comment by DavidS-om** [comment] 2023-03-21 08:06
While removing renovate from our internal terraform repository, I did find one update that did produce a non-failing config:

![2023-03-21_09MS+0100_932x375](https://user-images.githubusercontent.com/118179693/226547773-d51afbbb-5ca7-45b2-afb1-f1b78d9ba74e.png)

Even this change is still affected by https://github.com/renovatebot/renovate/issues/13692 , so I'm gonna stay with dependabot for that repo for now.

**Comment by HonkingGoose** [comment] 2023-03-21 10:33
Thank you for the minimal reproduction! ❤️ 

I've forked the reproduction into our organization: https://github.com/renovate-reproductions/21062

**Comment by pascal-hofmann** [comment] 2023-07-28 09:00
I think this issue is a duplicate of https://github.com/renovatebot/renovate/issues/21062.

**Comment by viceice** [comment] 2023-07-28 15:58
Duplicate of #15580

**Closed** 2023-07-28 15:58 UTC
Labels: duplicate
