### ISSUE TITLE
"Renovate Ignore Notification" comment on merged PR

### ISSUE THREAD

**Issue by abraham** [renovatebot/renovate#3103] opened 2019-01-23 16:44 UTC
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**

I merged abraham/nutmeg#717 and got a comment posted that mistakenly thinks the PR was not merged. It's a minor issue but still unexpected.

> As this PR has been closed unmerged, Renovate will now ignore this update (4.4.24).

**Did you see anything helpful in debug logs?**

This looks like the job that added the comment. I don't see anything weird in it. https://renovatebot.com/dashboard#github/abraham/nutmeg/40955507

**To Reproduce**

¯\\\_(ツ)_/¯

**Expected behavior**

Not to get a comment saying a merged PR was closed unmerged.

**Comment by rarkins** [comment] 2019-03-08 11:30
Unfortunately I forgot to save this job's log before it was purged on the backend, so we'll need to solve this via code inspection for now. It looks like the merging and comment were done in the same minute according to GitHub, so I'm guessing it was partially a race condition where the merging was done during Renovate's job - but it can't be known for sure. We need to double check what logic Renovate uses to decide to raise this notification and think if it needs to be changed to avoid this situation. Somehow Renovate thought it was Closed and not Merged.

**Comment by wagnerand** [comment] 2019-09-14 11:00
Same here: https://github.com/mozilla/dispensary/pull/625#issuecomment-531470470

**Comment by rarkins** [comment] 2022-01-13 10:09
Haven't been able to reproduce this, so closing this issue

**Closed by rarkins** 2022-01-13 10:09 UTC
Labels: type:bug, priority-4-low, status:ready
