### ISSUE TITLE
Version detection for Go modules hosted in Gitlab subgroups broken for versions >v24.114.0

### ISSUE THREAD

**Issue by adamsteinbok** [renovatebot/renovate#10218] opened 2021-05-28 20:15 UTC
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 25.32.0

**Describe the bug**

Go modules hosted in a nested Gitlab group (such as seflhosted-gitlab.com/group/nested-group/module-name) are detected as submodules due to them having more than 3 "parts". This causes tag-based version detection to not work unless the tag is prefixed like: `module-name/v1.0.0`.

In this case, the module being referenced is not a submodule and it seems inappropriate to treat it as such.

**Relevant debug logs**

**Useful (redacted) trace logs from self-hosted**

<details><summary>Click me to see logs</summary>

```
TRACE: go.getReleases (repository=REDACTED/REDACTED/REDACTED)
       "nameParts": ["gitlab.redacted.com", "REDACTED", "REDACTED", "REDACTED"],
       "releases": [
         {
           "version": "v1.1.11",
           "gitRef": "v1.1.11",
           "releaseTimestamp": "2021-05-27T15:07:18.000-04:00"
         },
         {
           "version": "v1.1.10",
           "gitRef": "v1.1.10",
           "releaseTimestamp": "2021-04-22T12:21:16.000-04:00"
         },
       ]
TRACE: go.getReleases.prefix:REDACTED (repository=REDACTED/REDACTED/REDACTED)
TRACE: go.getReleases (repository=REDACTED/REDACTED/REDACTED)
       "submodReleases": []
DEBUG: Found no results from datasource that look like a version (repository=REDACTED/REDACTED/REDACTED, dependency=gitlab.redacted.com/REDACTED/REDACTED/REDACTED)
       "result": {
         "sourceUrl": "https://gitlab.redacted.com/REDACTED/REDACTED/REDACTED",
         "releases": []
       }
```

</details>

**Less useful logs from public reproduction repo**

<details><summary>Click me to see logs</summary>

```
DEBUG: Found 1 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "master",
  "stats": {
    "managers": {
      "gomod": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}
DEBUG: Go lookup source url
{
  "goModule": "gitlab.com/adamsteinbok1/renovate/go-demo-module",
  "goSourceUrl": "https://gitlab.com/adamsteinbok1/renovate/go-demo-module"
}
DEBUG: Found no results from datasource that look like a version (gitlab.com/adamsteinbok1/renovate/go-demo-module)(dependency="gitlab.com/adamsteinbok1/renovate/go-demo-module")
{
  "result": {
    "sourceUrl": "https://gitlab.com/adamsteinbok1/renovate/go-demo-module",
    "releases": []
  }
}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

Reproduction: https://github.com/adamsteinbok/renovate-go-gitlab-repro
Relevant demo go module:  https://gitlab.com/adamsteinbok1/renovate/go-demo-module

**Additional context**

Source of this issue seems to be:
https://github.com/renovatebot/renovate/blob/83ab94eba680f6705dbbdbb60207620eeec06a76/lib/datasource/go/index.ts#L193-L212

**Comment by adamsteinbok** [comment] 2021-05-31 14:17
Had some time this morning to create a reproduction repo. Updated decription.

**Comment by lucasfernand-es** [comment] 2021-05-31 21:21
I'm facing this same issue currently.

I've tried using v24.114.0 instead of the latest version but I ended up with the same problem.

**Comment by rarkins** [comment] 2021-06-01 10:16
We need to think of the most elegant way to fix this. e.g.

- If more than two segments, don't immediately assume that the first two are the repo and the remaining are module paths
- Try assuming the whole path is a repo first, and detect if that results in a 404
- If 404, try stripping the last segment off the path and retrying

Could be useful if anyone can study the Go source code to work out how they do it.

We could also "shortcut" this logic a little, e.g. by checking if the host is a known github host and if so then we know that it just be org/repo/module and not group/subgroup/project.

**Comment by adamsteinbok** [comment] 2021-06-01 13:51
> We could also "shortcut" this logic a little, e.g. by checking if the host is a known github host and if so then we know that it just be org/repo/module and not group/subgroup/project.

It might also be worthwhile to provide a more generic means of shortcutting. Maybe something like a `skipGoSubmoduleCheck` (TBD: find a better name) option that can be used with package rules to manually identify packages/sets of packages that are known to be problematic. In my use case almost all of my problematic packages come from a few subgroups, something like:

```
{
  "packageRules": [
    {
      "matchManagers": ["gomod"],
      "matchPackagePrefixes": ["gitlab-private.example.com/group/subgroup/"],
      "skipGoSubmoduleCheck": true
    }
  ]
}
```

would greatly reduce the number of 404 checks that would be needed.

**Comment by adamsteinbok** [comment] 2021-06-01 16:14
> Could be useful if anyone can study the Go source code to work out how they do it.

I'm not 100% sure I'm interpreting the source right, but it looks to me like they determine the repo root via [regex for known hosts](https://github.com/golang/go/blob/2e59cc5fb4e81fbd2ee9f662caa707c1138bf5ae/src/cmd/go/internal/vcs/vcs.go#L829)  or via [HTTP metadata for dynamic hosts](https://github.com/golang/go/blob/2e59cc5fb4e81fbd2ee9f662caa707c1138bf5ae/src/cmd/go/internal/vcs/vcs.go#L944). 

The (metadata parsing)[https://github.com/golang/go/blob/2e59cc5fb4e81fbd2ee9f662caa707c1138bf5ae/src/cmd/go/internal/vcs/discovery.go#L31] identifies the root from a single HTTP request, which is a bit cleaner than the suggested strip+retry approach if it can be made to work here.

**Comment by adamsteinbok** [comment] 2021-06-01 16:52
@lucasfernand-es 
> I'm facing this same issue currently.
> 
> I've tried using v24.114.0 instead of the latest version but I ended up with the same problem.

Odd. I've just re-confirmed that tags of the form `vX.Y.Z` are detected for modules in subgroups on v24.114.0 for me.

Maybe provide a relevant section of trace logs (I didn't find debug level logging very useful in this case)?

**Comment by lucasfernand-es** [comment] 2021-06-02 20:37
@adamsteinbok 

I'm still getting the same error for my private Go modules hosted in Gitlab

This is the relevant information I have:
> `Failed to look up dependency private.com/group/subgroup/repoA`

I think it's not an authentication issue because another private module not in a subgroup can be found (`
private.com/group/repoB`)

**Comment by adamsteinbok** [comment] 2021-06-02 21:11
@lucasfernand-es 

That looks like a different issue, but not one I've seen.

**Comment by rarkins** [comment] 2021-06-03 06:45
It could be the same issue if Renovate is assuming `repoA` is in fact a sub-module of `group/subgroup`.

Currently I'm thinking about using `registryUrls` as a "hint" to Renovate you can use to fix this up, because right now we don't have or need that concept in go so it could be repurposed.

**Comment by 56KBs** [comment] 2021-06-04 15:23
We too have just hit this issue this week - However I think there is a simple solution using data already available to the `getReleases()` function for the go datasource.

When completing a `getDatasource()`, a lookup occurs on `?go-get=1` which returns an item showing the URL of the root repository, e.g:

| Go Module                          | Sub-Module | go-import  URL                        |
|------------------------------------|------------|------------------------------------|
| gitlab.com/56kbs/project           | No         | gitlab.com/56kbs/project           |
| gitlab.com/56kbs/project/tools     | Yes        | gitlab.com/56kbs/project           |
| gitlab.com/56kbs/sub-group/project | No         | gitlab.com/56kbs/sub-group/project |

In the scenario of `getDatasource(lookupName: gitlab.com/56kbs/project/tools)` the following is returned

```json
{
    "datasource": "github-tags",
    "registryUrl": "https://gitlab.com",
    "lookupName": "56kbs/project"
}
```

At this point, we can identify whether this is a sub-module or not by using the `lookupName` returned. This would be a case of removing everything in the original `lookupName` by everything up to and including the `source.lookupName` value (along with trimming a slash too).

I'm happy to work on raising an MR for this behaviour.

**Comment by malmor** [comment] 2022-04-12 12:09
Hey, any updates on this? ✌

We are facing this issue aswell - Renovate fetches tags from subgroups instead of the projects located inside them.

**Comment by viceice** [comment] 2022-06-23 07:01
this is partially fixed by 
- #13352

**Comment by malmor** [comment] 2022-06-23 14:29
Yes, this MR should help with this 👍 

But in our case that part of the code is never reached. `getDatasource` uses [this regex](https://github.com/renovatebot/renovate/blob/84228b1b12a9926e1019b6030519c02665c09b61/lib/modules/datasource/go/base.ts#L15) to check if a source is a GitLab instance:  
`/^(?<httpsRegExpUrl>https:\/\/[^/]*gitlab\.[^/]*)\/(?<httpsRegExpName>.+?)(?:\/v\d+)?[/]?$/`

Our self-hosted GitLab instance is running at `https://git.company.local` - so there is no `gitlab` in the URL.

I am not sure how this could be solved. Maybe using a configuration option where one can define the hostType (e.g. `github` or `gitlab`) for a given URL? Or is there a way to "discover" the target with a little HTTP request?

Sadly I don't have a solution for this at the moment - just wanted to provide some more details/insights to this 😃

**Comment by viceice** [comment] 2022-06-23 16:10
i recently changed that detection for changelog retrieval. maybe we can move and reuse that code.

**Comment by 56KBs** [comment] 2022-10-10 16:46
> Yes, this MR should help with this 👍
> 
> But in our case that part of the code is never reached. `getDatasource` uses [this regex](https://github.com/renovatebot/renovate/blob/84228b1b12a9926e1019b6030519c02665c09b61/lib/modules/datasource/go/base.ts#L15) to check if a source is a GitLab instance: `/^(?<httpsRegExpUrl>https:\/\/[^/]*gitlab\.[^/]*)\/(?<httpsRegExpName>.+?)(?:\/v\d+)?[/]?$/`
> 
> Our self-hosted GitLab instance is running at `https://git.company.local` - so there is no `gitlab` in the URL.
> 
> I am not sure how this could be solved. Maybe using a configuration option where one can define the hostType (e.g. `github` or `gitlab`) for a given URL? Or is there a way to "discover" the target with a little HTTP request?
> 
> Sadly I don't have a solution for this at the moment - just wanted to provide some more details/insights to this 😃

Having come back to this issue I'm in the same situation, the code is never triggered because of our URL not matching exactly - You can fix this by configuring `hostRules` for your URL.

I'm configuring ours via environment variables (Requires https://docs.renovatebot.com/self-hosted-configuration/#detecthostrulesfromenv to be enabled) to avoid putting secrets in our configuration (And I'm not sure if `hostRules` expand environment variables themselves), using your example URL you can set `GO_GIT_COMPANY_LOCAL_USERNAME=<username>` and `GO_GIT_COMPANY_LOCAL_PASSWORD=<password>`.

You need to configure username & password because GitHub does not support bearer token authentication and only allows basic auth to function with `?go-get=1` from my testing.

**Comment by aarongoldenthal** [comment] 2022-10-24 01:25
The original issue and partial fix above appear to be scoped specifically to Go modules, but is this also applicable to others, like npm? Today I moved a gitlab.com hosted npm module into a subgroup and Renovate (v33.1.0, self-hosted on gitlab.com) now to longer retrieves release note data. Looking at the debug log, it doesn't even try (i.e. there are no errors, and the GitLab API for the project isn't in the log as accessed, although other projects in the original parent group are).

I wanted to check if this was an issue known to be common to the other package managers before opening a new issue or creating a minimal reproduction.

**Comment by viceice** [comment] 2022-10-24 05:51
@aarongoldenthal please open a discussion. it's probably because renovate can no longer detect the source url of the npm package.

**Comment by doriandekoning** [comment] 2023-02-24 13:50
Unfortunately, this still is an issue for us, I've tried the approach described by @56KBs but that does not resolve the issue on our side.

The easiest fix to me seems to update the regex to not only include gitlab.com but also different hostnames for gitlab (maybe make this configurable?). I'm not familiar with the codebase but if it would be appreciated (and maybe if you can give me some pointers) I'd like to propose a merge request with a fix.

**Comment by LorisFriedel** [comment] 2023-03-28 14:01
Hello!

I am facing the same issue:

I'm using Bitbucket server, with an URL like: `https://my.awesome.company.com/git`
We have some (private) Go modules in dedicated repositories, at URLs like: `https://my.awesome.company.com/git/TEAM-PROJECT/MODULE-REPOSITORY`

However, the following code is executed with no clear way for us to avoid having to create new tags like **MODULE-REPOSITORY/x.y.z** whereas the repository only host one module, it's just that the URL happens to have a third element (**/git**)

https://github.com/renovatebot/renovate/blob/39493b715ba06881111fb6df65766905a51f78a1/lib/modules/datasource/go/releases-direct.ts#L95-L112

Is there anything planned to add an option or similar to prevent this issue?

Thanks for you help 😃

**Comment by rarkins** [comment] 2023-04-22 08:55
This original issue is resolved, for example this PR works: https://github.com/renovate-reproductions/10218/pull/1

Anyone else should start a new Discussion with reproduction

**Closed by rarkins** 2023-04-22 08:55 UTC
Labels: type:bug, priority-3-medium, manager:gomod, status:ready, reproduction:provided
