### ISSUE TITLE
Trigger renovate-bot to check the syntax of renovate configuration on PRs

### ISSUE THREAD

**Issue by Goooler** [renovatebot/renovate#13948] opened 2022-02-01 16:33 UTC
### What would you like Renovate to be able to do?

- After I start a new PR to modify the renovate configuration, I want to trigger renovate-bot to check if there is any syntax error in the configuration.
- After the last step, I may need to check which dependencies can be updated after this PR, how can I do it?

### If you have any ideas on how this should be implemented, please tell us here.

Nope.

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment] 2022-02-01 18:03
> After I start a new PR to modify the renovate configuration, I want to trigger renovate-bot to check if there is any syntax error in the configuration.

You can use the `renovate-config-validator` program to check for syntax errors. [^reconfigure-via-pr]

> After the last step, I may need to check which dependencies can be updated after this PR, how can I do it?

I recommend you enable the Dependency Dashboard [^dashboard], that will give you an overview of all dependencies that you can update.

[^reconfigure-via-pr]: https://docs.renovatebot.com/getting-started/installing-onboarding/#reconfigure-via-pr

[^dashboard]: https://docs.renovatebot.com/key-concepts/dashboard/

**Comment by HonkingGoose** [comment] 2022-02-01 18:08
Your issue seems related to this older issue:

- #547

@rarkins do you want to keep this issue, or close it as a duplicate of the earlier issue?

**Comment by rarkins** [comment] 2022-02-01 18:10
They're a bit different

**Comment by Goooler** [comment] 2022-02-02 03:19
> I recommend you enable the Dependency Dashboard 2, that will give you an overview of all dependencies that you can update.

I mean I want to check dependencies in current PR instead of Dependency Dashboard.

**Comment by viceice** [comment] 2022-02-02 06:45
You need to create a workflow yourself to run renovate in dry run.

Your can checkout https://github.com/renovatebot/.github/blob/main/.github/workflows/test.yml on how to validate config on PR.

**Comment by rarkins** [comment] 2022-11-25 14:41
I think we could simplify this a lot if we establish a convention that the PR must be named e.g. `renovate/reconfigure` (`branchPrefix` + `"reconfigure"`). First step could be this issue (validation) and later step could be interactive as described in #547

**Comment by rarkins** [comment] 2023-05-09 05:42
Here's what we should do:
- Look for any `{{branchPrefix}}reconfigure` (e.g. `renovate/reconfigure`) branch
- If it exists, look for a config file in it (same way we would usually). Do not assume it's the same file name as in the default branch
- If found, perform validation
- Provide a passing or failing check run based on result

This should utilize repository cache so that we don't unnecessarily clone the repo each run if the branch is found but unchanged.

**Comment by HonkingGoose** [comment] 2023-08-14 09:59
### Add docs for the new feature

We should also add new docs for the feature, where we explain that you need to:

1. Create a branch named `renovate/reconfigure`
2. Create a commit with your changes, push it to the branch
3. Let Renovate run the config validation
4. Fix errors
5. When Renovate config validation passes, merge PR

We should also explain where the feature will work, and won't work... See the next heading. 😉 

### What about `renovate/reconfigure` PRs from forks?

I often make PRs from my _fork_ to another project. It would be _very handy_ to have Renovate check my config changes in the PR on the upstream project. To clarify, here's what I would like to have:

1. I create a new fork
2. I create a new branch `renovate/reconfigure` on my fork, and create new commits there
3. Once I think I'm good to go, I open a PR on the _upstream_ project
4. Renovate runs the config check, and tells me I messed up
5. I fix the bad stuff on my fork, Renovate runs again, and things are good
7. Upstream project merges my changes and enjoys a better Renovate config

**Comment by RahulGautamSingh** [comment] 2023-09-24 16:40
I assume we will handle this during the update part since we handle branches there?

https://github.com/renovatebot/renovate/blob/c767e742d3e033b93ac0139fdf86eb42b8efc7f2/lib/workers/repository/process/extract-update.ts#L207-L218

We can add the `renovate/reconfigure` to the branches array and then add an if-check in the `write` function after we have synced branch state..to handle the logic

ie.

```js
write(){
   // sync branch state
   
   
   // if branch is updated
   handleReconfigureBranch()
   // if branch is same skip processing
}
```

In the `handleReconfigureBranch` we can add the logic as you have mentioned above from step 2-4 and also + code to update the repo-cache

**Comment by lmilbaum** [comment] 2023-09-24 16:56
If it is still not to late to join the party, I'd say rephrase the ask as to have an effective CI framework which can provide the ability to functionally test the configuration.

**Comment by karfau** [comment] 2023-09-24 17:28
FYI: I have recently spotted that Dependabot always validates it's config file whenever it is changed and I replicated that behavior in a very simple [GitHub action workflow](https://github.com/bettermarks/renovate-config/blob/main/.github/workflows/renovate-config-validator.yml) and [action](https://github.com/bettermarks/renovate-config/blob/main/validator/action.yml) (both living in the same shared config repository, but can be used independently), but of course the workflow has to be copied into each repo, which I'm trying to automate away in our organization.

Of course it would be really useful if such a github action would be provided/maintained by renovate, or the GitHub app would just take care of it.

Hope this is helping some

**Comment by lmilbaum** [comment] 2023-09-24 17:48
> FYI: I have recently spotted that Dependabot always validates it's config file whenever it is changed and I replicated that behavior in a very simple [GitHub action workflow](https://github.com/bettermarks/renovate-config/blob/main/.github/workflows/renovate-config-validator.yml) and [action](https://github.com/bettermarks/renovate-config/blob/main/validator/action.yml) (both living in the same shared config repository, but can be used independently), but of course the workflow has to be copied into each repo, which I'm trying to automate away in our organization.
> 
> Of course it would be really useful if such a github action would be provided/maintained by renovate, or the GitHub app would just take care of it.
> 
> Hope this is helping some

Thanks for sharing @karfau. Another option which I'm using is the pre-commit [hook](renovate-config-validator). It works for me because I already use pre-commit for liniting other files.

**Comment by karfau** [comment] 2023-09-24 18:32
> Another option which I'm using is the pre-commit [hook](renovate-config-validator). It works for me because I already use pre-commit for liniting other files.

@lmilbaum 

That means you have to have the renovate package as a global or devDependency? It is quiye a heavy package, regarding transitive deps and running it using npx often takes seconds. And it is a dep that has a lot of updates so I prefer to not have it in my package.json.

If the validator would be an extra package with less deps I would assume it would also have less frequent updates, it would help a lot.

**Comment by lmilbaum** [comment] 2023-09-24 20:35
@karfau I don't think the renovate package is required as a global or devDependency. The only dependency I'm aware of is on the following [repo](https://github.com/renovatebot/pre-commit-hooks).

**Comment by karfau** [comment] 2023-09-25 04:05
Ah, I was not aware of that repo

**Comment by viceice** [comment] 2023-09-25 04:50
that will still use the renovate npm package under the hood. I'm not sure how pre commit runs nom packages

**Comment by rarkins** [comment] 2023-09-25 05:38
I think this would likely be better as a standalone function and not trying to embed it into our existing branch workflow logic

**Comment by RahulGautamSingh** [comment] 2023-09-25 10:20
Okay. So will need to create a folder like onboarding (or maybe just a file) with the logic. And then place the function in the `renovateRepository` function, where it gets called after we have confirmed that repo is onboarded.

**Comment by rarkins** [comment] 2023-09-25 10:45
I think I would do this last, once all branches have been processed. e.g. sometime around when we do pruneStaleBranches

**Comment by viceice** [comment] 2023-09-25 10:52
> I think I would do this last, once all branches have been processed. e.g. sometime around when we do pruneStaleBranches

sounds good to me

**Closed** 2023-11-03 13:39 UTC
Labels: type:feature, priority-2-high, status:in-progress, core:config

**Comment by sblask** [comment] 2023-11-13 05:23
I just tried this in a PR: https://github.com/sblask/dotfiles/pull/618 but only got `Validation Failed` without any message what exactly went wrong. I am using:

```
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.37.2
    hooks:
      - id: renovate-config-validator
```

Which didn't report any error. So I am not sure whether I am missing something or what to expect from this feature.

**Comment by rarkins** [comment] 2023-11-13 06:16
Please create a discussion and include logs
