### ISSUE TITLE
Support git dependencies in Poetry manager

### ISSUE THREAD

**Issue by yetanotherion** [renovatebot/renovate#21848] opened 2023-04-27 15:04 UTC
### What would you like Renovate to be able to do?

Support [git-dependencies](https://python-poetry.org/docs/dependency-specification#git-dependencies) in poetry manager.

### If you have any ideas on how this should be implemented, please tell us here.

As said by @rarkins in the related [discussion](https://github.com/renovatebot/renovate/discussions/21846#discussioncomment-5743936)  it seems that the feature is intentionally not supported for now.
I created https://github.com/yetanotherion/poetry-git-dependency-repro to reproduce the issue.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment] 2023-04-27 15:06
There is no version in https://github.com/yetanotherion/poetry-git-dependency-repro/blob/14c1ea02b866415bfb116081f8b0da501bdbb0fe/pyproject.toml#L11 so I'm not sure if this is a valid reproduction? There's nothing to update/do

**Comment by yetanotherion** [comment] 2023-04-27 15:10
> There is no version in https://github.com/yetanotherion/poetry-git-dependency-repro/blob/14c1ea02b866415bfb116081f8b0da501bdbb0fe/pyproject.toml#L11 so I'm not sure if this is a valid reproduction? There's nothing to update/do

Thanks @rarkins! if you have access to the log of the run, you'll most probably see skipReason: "git-dependency". (I don't have access to the logs of the app).

Without version, poetry takes the latest version when running.

```
poetry update
```
See 
```
...
[[package]]
name = "fastapi"
version = "0.95.1"
...
```
in the related [poetry.lock](https://github.com/yetanotherion/poetry-git-dependency-repro/blob/master/poetry.lock#L26
) file.

**Comment by rarkins** [comment] 2023-04-27 15:13
Please provide much more information in the reproduction repository about expected behavior. We can mark the reproduction as provided once it is complete

**Comment by rarkins** [comment] 2023-04-27 15:15
Best if you also include a hand-crafted update PR and the steps/commands you used to generate it.

In case it wasn't obvious, supporting "git dependencies" in poetry manager isn't one thing. The page you link to include multiple ways to specify git dependencies, some of which reference a commit or tag. In your case there is no commit or tag, even though it seems like you could reference a tag.

**Comment by yetanotherion** [comment] 2023-04-27 15:25
Hi @rarkins, you have the PR available at https://github.com/yetanotherion/poetry-git-dependency-repro/pull/3
I updated the [readme](https://github.com/yetanotherion/poetry-git-dependency-repro) accordingly:

The current head has fastapi on 0.95.0 when the version 0.95.1 is [available](https://github.com/tiangolo/fastapi/releases)

poetry update
generates the PR https://github.com/yetanotherion/poetry-git-dependency-repro/pull/3

Instead of running that manually, it would be great if renovate would generate such a PR automatically.
```

**Comment by rarkins** [comment] 2023-04-27 15:38
Any reason why you leave the version out of pyproject.toml?

**Comment by rarkins** [comment] 2023-04-27 15:39
"Poetry update" is not suitable for single dependency updates as it would update every dependency at once

**Comment by jonadaly** [comment] 2023-04-27 16:17
With `poetry` you can restrict updates only as they relate to a particular dependency in the tree, e.g. `poetry update fastapi`

**Comment by yetanotherion** [comment] 2023-04-27 16:40
Hi @rarkins, my bad the use case: only edit poetry.lock, does not seem to be easier to implement for renovate.

For this reason, I updated the README and the PR to describe a use case, @JohnDaly correct me if I'm wrong, that is much more adapted to our needs:
- detect a new version,
- bump it in pyproject.toml,
- run poetry update dependency --lock and commit diff in poetry.lock.


https://github.com/yetanotherion/poetry-git-dependency-repro/blob/master/README.md

**Comment by rarkins** [comment] 2023-04-27 16:45
@yetanotherion thanks, I was also testing that approach out just now and was about to recommend it.

`tag=` also works as an alternative to `ref=`.

e.g.
```
fastapi = {git = "ssh://git@github.com/tiangolo/fastapi.git", tag = "0.95.1" }
```

So I suggest we define that as our supported use case, because then Renovate can keep it updated deterministically.

**Comment by yetanotherion** [comment] 2023-04-27 16:52
@jonadaly would you be ok with it? This solution will not block the bump of major dependencies, still we could disable automerge on major bumps with https://docs.renovatebot.com/configuration-options/#matchupdatetypes.

**Comment by jonadaly** [comment] 2023-04-28 07:22
It's not ideal. Updating the lock file already makes it deterministic, there's no real value in keeping the tag pinned to a specific version in `pyproject.toml` as well - and it prevents us from avoiding unintentional major updates.

**Comment by rarkins** [comment] 2023-04-28 07:26
Please elaborate

**Comment by yetanotherion** [comment] 2023-04-28 07:27
> Updating the lock file already makes it deterministic

I agree

> there's no real value in keeping the tag pinned to a specific version in pyproject.toml

For the sake of readibility, I personally find the pyproject.toml to be easier to read than poetry.lock.

Another argument is that based on my current understanding of the renovate source code, the implementation
with a specified version in pyproject.toml will be much easier.

**Comment by rarkins** [comment] 2023-04-28 07:27
I see no advantage to lock file only updates because it makes it harder for users to instantly see which version is in use

**Comment by rarkins** [comment] 2023-04-28 07:30
Also, using the HEAD commit instead of tag commit looks like a design mistake. Two projects could think they're on 0.95.1 but neither actually is - they're both on a master branch commit which happened after 0.95.1. This is the opposite of what you should want

**Comment by yetanotherion** [comment] 2023-04-28 07:36
Hi @rarkins! To give you more context on why it could make sense to avoid tag in our very specific use case:
- we use renovate, among others, to do trunk based development on our internal source code, hosted in multiple git repositories.
Using HEAD would reflect this intent of emulating trunk based development in multiple git repositories.

Still, in practice this has another downside as we will not be able to prevent updates that break post merge tests to be propagated. This could be avoided with tags (by publishing the tag after successful post merge tests).

@jonadaly IMO, despite HEAD being closer to what we try to do, IMO the practical scenario above suggests that we'd rather use the proposal of @rarkins. WDYT?

**Comment by rarkins** [comment] 2023-04-28 07:42
If you want to use HEAD, then I'd recommend using the ref= syntax in Poetry so that it's clear. But in this example you're using, I really don't like it because:
- The "package file" just says the repo. In other words "we use some code from this repo, you'll need to dig into the lock file to know exactly which"
- The lock file - like most lock files - is far less readable than a package file, for any typical developer
- So you look in the lock file, and you see "Oh great, looks like we're using 0.95.1" and you look up the release notes to see what's the latest in that
- Actually, you have been befuddled. You're _actually_ using a head commit! There's new code you're using that is not described in 0.95.1

I'm not a Poetry user, but I see a lot of different approaches of package managers, and I think the above is a bad idea. It's essentially misleading that Poetry in one place says you're using 0.95.1 but in reality you are using a newer commit.

Meanwhile all this is solved if you use either a ref= or tag=  in the package file, to clearly indicate intent that you're either using versioned tags (ignore new commits until they're tagged into a release) or you are wanting to do "trunk based development" and use the latest commit whenever possible

**Comment by yetanotherion** [comment] 2023-04-28 07:47
@rarkins, AFAIU, your strong conviction is that a dev **should not have to read poetry.lock** 
to know which version is currently used in a project.
Did I understand correctly?

**Comment by rarkins** [comment] 2023-04-28 07:52
Yes, that's a concept I apply across all package managers. Clarifying it a little: you should avoid the need for developers to read through lock files in order to know which version of a direct dependency you're using. 

- For transitive dependencies, it's unavoidable. But on the other hand it's rare that a developer needs to dig that deep
- When publishing a library, it is often desirable to use constraints/ranges rather than pinned versions, and that's ok too

BTW one final point: despite my conviction on this, I'm happy for Renovate to support all approaches. My opinion on what is best or recommended only influences the order in which I would support them if I were implementing. If you were to add support for tag and ref, I suspect it would be very minimal code compared to the "lockfile only" approach

**Comment by yetanotherion** [comment] 2023-04-28 07:55
>If you were to add support for tag and ref, I suspect it would be very minimal code
I very much agree. From what I see in the PR that implemented [poetry support](https://github.com/renovatebot/renovate/pull/3440) we should just modify the part that extract and the part that updates.

Waiting for @jonadaly's take on this, @rarkins assuming we get a consensus, would you be ok if I try to implement a first version of that feature?

**Comment by rarkins** [comment] 2023-04-28 07:57
Of course, please go ahead. I have marked this as `status:ready` to indicate that support for tag= and ref= if using _versions_ is definitely ready to implement

**Comment by yetanotherion** [comment] 2023-05-02 15:30
FYI I have something working
https://github.com/yetanotherion/poetry-git-dependency-repro/pull/6/ [1]
One minor issue is that I need to use as depName, the name referencing the github project (**org/project**, here **tiangolo/fastapi**, instead of the name used in poetry (**fastapi**).
The PR generated is ok though.
IMO this is fine for our use case, WDYT @rarkins?

[1]: the content is exactly the same as https://github.com/yetanotherion/poetry-git-dependency-repro/pull/4/files

**Comment by yetanotherion** [comment] 2023-05-02 17:42
Thank you so much @rarkins!
https://github.com/yetanotherion/poetry-git-dependency-repro/pull/7
I'll polish the code and submit a PR in the next days, thanks!

**Comment by omercnet** [comment] 2023-12-10 15:33
any plans to support branches (I wanna just get from main) or should I open a different FR for that?

**Closed** 2024-01-04 08:55 UTC
Labels: type:feature, priority-3-medium, manager:poetry
