### ISSUE TITLE
Renovate creates PR with invalid pom.xml

### ISSUE THREAD

**Issue by thiagofabre** [renovatebot/renovate#18520] opened 2022-10-24 16:53 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

33.2.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.4.2-ee

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate opens a PR with a invalid `pom.xml`.

git diff:
![Screenshot from 2022-10-24 16-29-41](https://user-images.githubusercontent.com/116581167/197581956-f85c231e-602c-4a42-b1b4-ac35c6a36bf7.png)

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment] 2022-10-24 17:22
Duplicate of #18515

checkout the converted discussion

**Closed** 2022-10-24 17:22 UTC
