### ISSUE TITLE
Renovate breaks over pin GitHub action update

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7509] opened 2020-10-20 12:35 UTC
**What Renovate type, platform and version are you using?**

GitHub app, Renovate version `23.55.0`.

**Describe the bug**

The Renovate bot errors out over the pinning of GitHub Actions.

**Relevant debug logs**

```
INFO: Repository started
{
  "renovateVersion": "23.55.0"
}
INFO: Dependency extraction complete
{
  "baseBranch": "main",
  "stats": {
    "managers": {
      "github-actions": {
        "fileCount": 2,
        "depCount": 4
      },
      "npm": {
        "fileCount": 1,
        "depCount": 7
      }
    },
    "total": {
      "fileCount": 3,
      "depCount": 11
    }
  }
}
WARN: Error updating branch: update failure(branch="renovate/pin-dependencies")
INFO: Repository finished
{
  "durationMs": 6860
}
```

**To Reproduce**

Take a look at my repository's dashboard: https://github.com/RoostingGeese/git-gosling/issues/48

> Errored
> 
> These updates encountered an error and will be retried. Click a checkbox below to force a retry now.

> Pin dependencies (actions/checkout, actions/setup-node)

**Additional context**

Does this https://github.com/renovatebot/renovate/commit/845c7bd63650ce88cce15e2d7316fde72914efbd commit fix the problem?

**Comment by viceice** [comment] 2020-10-20 12:43
should already be fixed with 23.55.1

**Comment by HonkingGoose** [comment] 2020-10-20 12:44
Do you want me to force a rerun via the Dashboard, or do you want me to freeze the situation?

**Comment by viceice** [comment] 2020-10-20 12:47
I think you need to wait one or two hours, until the fixed renovate bot is fully deployed. @rarkins can give an update when it's done.

**Comment by viceice** [comment] 2020-10-20 12:49
But I'm not sure, what renovate tries to pin in your repo. 🤔

**Comment by HonkingGoose** [comment] 2020-10-20 12:49
I'll wait for instructions before changing the situation then. :+1:

**Comment by HonkingGoose** [comment] 2020-10-20 12:53
> But I'm not sure, what renovate tries to pin in your repo. :thinking:

Wild guess incoming: maybe Renovate doesn't like that I'm using a pre-release of `actions/setup-node@v2.1.2` instead of the "stable" `1.4.4` version? And it gets confused on how to pin the action?

https://github.com/RoostingGeese/git-gosling/blob/a3f838188210598246a31346764c8251d01ba32f/.github/workflows/prettier.yml#L29

https://github.com/RoostingGeese/git-gosling/blob/a3f838188210598246a31346764c8251d01ba32f/.github/workflows/node.js.yml#L22

**Comment by rarkins** [comment] 2020-10-20 13:04
I wasn't aware that we were attempting to pin actions already actually. @viceice do we have a working example of that and was it intentional? I was expecting upgrading only to begin with

**Comment by rarkins** [comment] 2020-10-20 13:04
FYI 23.55.1 is now deployed

**Comment by HonkingGoose** [comment] 2020-10-20 13:06
> FYI 23.55.1 is now deployed

My Renovate dependency dashboard is normal now without me touching it, so it's probably due to Renovate `23.55.1` coming online.

**Comment by viceice** [comment] 2020-10-20 13:07
![image](https://user-images.githubusercontent.com/1798109/96590047-d2e58500-12e5-11eb-9eb9-6e96a5db87d6.png)

That wouldn't work? 

caused by:

**Comment by rarkins** [comment] 2020-10-20 13:08
Let's remove it. I thought this branch had been more tested :-/

**Closed** 2020-10-20 15:02 UTC
Labels: bug, manager:github-actions
