### ISSUE TITLE
Onboarding PR has an incorrect link to the job log

### ISSUE THREAD

**Issue by ylemkimon** [renovatebot/renovate#11691] opened 2021-09-12 03:56 UTC
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

```
This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#{{platform}}/{{repository}}).
```

The link to the log doesn't have `{{platform}}` and `{{repository}}` replaced: https://github.com/ylemkimon/renovate-yarn-private/pull/1

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Filling in onboarding PR template
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by HonkingGoose** [comment] 2021-09-12 10:19
Duplicate of #7526

**Closed by HonkingGoose** 2021-09-12 10:19 UTC
Labels: type:bug, status:requirements, priority-5-triage

**Comment by HonkingGoose** [comment] 2021-09-12 10:21
Thank you for reporting this problem! ❤️ 

I managed to find a earlier issue (#7526) that explains _why_ the link is not working properly:

>Onboarding PRs are not compiled with handlebars

We only keep one issue per bug, so I've closed this issue as a duplicate of the earlier issue.
