### ISSUE TITLE
Dependency updates strip quotes from YML files

### ISSUE THREAD

**Issue by kezz** [renovatebot/renovate#14460] opened 2022-02-28 21:18 UTC
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

See <https://github.com/KyoriPowered/adventure/pull/706>. This PR erroneously strips the quotation marks from the GitHub actions file.

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by kezz** [comment] 2022-03-02 10:33
Possibly related, after manually updating the dependency Renovate can't seem to figure out that it's been updated? It closed the PR originally, but since then it reopened it and an update is still sitting in the Dependency Dashboard for the repo.

See https://github.com/KyoriPowered/adventure-webui/pull/82.

**Comment by rarkins** [comment] 2022-03-02 12:06
Regarding the initial topic of this bug report: if it's valid to have no quotation marks for that field's value then it's not *erroneous*, it's *undesirable*. We do aim to preserve formatting like this where we can though, which is why I accepted it as a bug.

Regarding the second point, you've closed the PR and the branch is deleted, so I can't tell anymore what happened. Needs a reproduction to see if it happens again.

**Comment by kezz** [comment] 2022-03-02 14:28
Alright, in that case I'll see if I can reproduce this and if so I'll open a new issue - will keep this one for quotation marks.

**Comment by zml2008** [comment] 2022-03-04 03:59
There's a reproduction repository for this issue, also covering its interaction with end-of-line comments in #14508

**Comment by rarkins** [comment] 2022-03-04 05:22
Duplicate of #14508

**Closed by rarkins** 2022-03-04 05:22 UTC
Labels: type:bug, priority-4-low, manager:github-actions, reproduction:needed, status:requirements
