### ISSUE TITLE
registry-failure causing no PRs to be opened, even when some upgrades have been discovered

### ISSUE THREAD

**Issue by bjeanes** [renovatebot/renovate#3372] opened 2019-03-13 01:07 UTC
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

No upgrades have been happening for days

**Did you see anything helpful in debug logs?**

Everything failing with `registry-failure`

<img width="928" alt="2019-03-13 at 12 02 pm" src="https://user-images.githubusercontent.com/2560/54246247-4959c700-4588-11e9-9bec-a013f96d0ba2.png">

**To Reproduce**

I'm not sure but I think Rubygems is causing rate limit errors and this tanks the entire job

**Expected behavior**

An error in one source/repository (e.g. Bundler/rubygems) should not tank upgrades from other sources (Docker, NPM)

**Screenshots**
inline above

**Additional context**
n/a

**Comment by rarkins** [comment] 2019-03-13 06:04
We do need to throw when there's registry failures, otherwise you can end up with a lot of open/closed/open/closed PRs. In this case though it seems the Rubygems doesn't have the capacity of other services we've seen so we need to reduce our concurrent queries. I got some ideas from this: https://meta.discourse.org/t/rubygems-too-many-requests-problem-returns/102499/16

In the meantime, you can disable Bundler again and I'll let you know when it's fixed. Sorry for the inconvenience!

**Comment by bjeanes** [comment] 2019-03-13 07:14
> In the meantime, you can disable Bundler again and I'll let you know when it's fixed. Sorry for the inconvenience!

No worries. Will do! Bundler hasn't been opening any PRs anyway, so I've only been keeping it enabled for our collective benefit of getting the integration working well!

**Comment by rarkins** [comment] 2019-03-13 07:24
Thanks. I would like to solve the marshalling error with your help some time but will fix the 429 first

**Comment by rarkins** [comment] 2019-03-15 05:41
I'll close this issue because specifically on the topic of "should the failure of a default registry cause the entire run to be aborted?" then the answer is Yes. We've seen way too much "flapping" of PRs caused by the npm registry going up and down in the past for example. Even just yesterday it was returning 502 errors for a period. Users hate the noise of PRs opened and closed, and it makes them have to debug it to make sure it's "expected". The current approach of cautiously aborting still seems the right approach to me. 

OTOH, our Rubygems logic needs fixing to avoid 429's! But I'm working on that elsewhere.

**Closed by rarkins** 2019-03-15 05:41 UTC
