### ISSUE TITLE
Datasource gitlab-releases

### ISSUE THREAD

**Issue by andreabettich** [renovatebot/renovate#10645] opened 2021-06-29 08:49 UTC
**What would you like Renovate to be able to do?**

Currently there is only the datasource gitlab-tags, which checks for new tags. But maybe not every tag should be a release which should get upped in other repositories.

**Did you already have any implementation ideas?**

It looks like that we can copy `github-releases` datasource and do a gitlab flavor of it.

I will try to do a PR myself.

**Comment by secustor** [comment] 2021-06-29 08:57
Duplicate of https://github.com/renovatebot/renovate/issues/7534

**Closed** 2021-06-29 09:22 UTC
Labels: priority-5-triage, status:requirements, type:feature

**Comment by andreabettich** [comment] 2021-06-29 09:52
Thanks and sorry. I searched but didn't see this issue.

**Comment by rarkins** [comment] 2021-06-29 09:57
@andreabettich no problem at all! Hope you're not deterred from submitting a PR.. and yes I think it can be modelled on the GitHub releases datasource.

**Comment by HonkingGoose** [comment] 2021-06-29 14:22
Duplicate of #7534
