### ISSUE TITLE
[Feature Request] Updating Git submodules

### ISSUE THREAD

**Issue by sr229** [renovatebot/renovate#3051] opened 2019-01-09 01:23 UTC
**What would you like Renovate to be able to do?**
Currently, Renovate can update dependencies from a package manifest. However I would like Renovate to perform git submodule updates on submoduled dependencies.

**Describe the solution you'd like**
To do this, Renovate has to compare the referenced git commit tag vs the origin's latest commit. If it matches, its a latest release. If not, the submodule is update via `git submodule update --remote`, and returns a PR

**Describe alternatives you've considered**
An alternative would be running a automated cron job in a VM in GCP to automatically update the git remotes, or use a Webhook to perform commits.

**Additional context**
This is heavily inspired of #2502 and #1356.

**Comment by rarkins** [comment] 2019-03-08 09:18
I think I will treat this as a duplicate of #2502 because I think they need the same solution. @sr229 please let me know if there's a difference I'm missing or if the final solution doesn't satisfy. It would help if you have a public repo that can be used to test against, too.

**Closed by rarkins** 2019-03-08 09:18 UTC
Labels: feat, pri3-normal, ready
