### ISSUE TITLE
Renovate adding duplicate widened version in peer dependencies

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/renovate#8659] opened 2021-02-11 23:46 UTC
**What Renovate type, platform and version are you using?**

Self hosted running via node as a chron job. From my current package.json file:
```
"renovate": "24.49.2",
```
Before this we were running v24.44.0 which seems like it would also likely have the same issue.

**Describe the bug**

Unsure what caused this but I just caught a renovate PR opened with the following contents:
```
  "peerDependencies": {
-    "@some-company/internal-package": "^4.0.0-rc.5 || ^4.0.0-rc || ^4.0.0-rc || ^4.0.0-rc || ^4.0.0-rc",
+    "@some-company/internal-package": "^4.0.0-rc.5 || ^4.0.0-rc || ^4.0.0-rc || ^4.0.0-rc || ^4.0.0-rc || ^4.0.0-rc",
    "react": "^16.13.1 || ^17.0.0"
  },
  ```

I got lucky someone actually checked or else this would have kept on going

**Relevant debug logs**

I can provide relevant logs upon request however this is running on an internal system so I'd have to scrub them before posting anything.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I tracked down the first time this iterative loop started recently. Seems to have started when the package was updated to 4.0.0-rc.6 however the peer-dependencies didn't update correctly:
```
  "devDependencies": {
-    "@some-company/internal-package": "4.0.0-rc.5",
+    "@some-company/internal-package": "4.0.0-rc.6",
  },
  "peerDependencies": {
-    "@some-company/internal-package": "^4.0.0-rc.5",
+    "@some-company/internal-package": "^4.0.0-rc.5 || ^4.0.0-rc",
  },
  ```

**Comment by rarkins** [comment] 2021-02-12 04:57
Needs a reproduction otherwise there's no way to look into it

**Comment by k2snowman69** [comment] 2021-02-12 05:00
Let me see if I can come up with something in the public npm repository this weekend.

**Comment by k2snowman69** [comment] 2021-02-16 06:56
Add the following expect in `bumps complex ranges` in the file `lib\versioning\npm\index.spec.ts`

```
    expect(
      semver.getNewValue({
        currentValue: '^4.0.0-rc.5 || ^4.0.0-rc',
        rangeStrategy: 'widen',
        fromVersion: '4.0.0-rc.6',
        toVersion: '4.0.0-rc.6',
      })
    ).toEqual('^4.0.0-rc.5 || ^4.0.0-rc');
```

This should fail because the actual value is `^4.0.0-rc.5 || ^4.0.0-rc || ^4.0.0-rc`

**Comment by rarkins** [comment] 2021-02-16 07:04
This doesn't seem like a valid example. It shouldn't be attempting to widen if the existing constraint already satisfies the new version.

**Comment by k2snowman69** [comment] 2021-02-16 07:13
I don't disagree which is why I was curious why renovate widened it in the first place. Digging into this a bit more and figuring out how I ended up with my bug:

```
console.log(semver.getNewValue({
  currentValue: '^4.0.0-rc.5',
  rangeStrategy: 'widen',
  fromVersion: '4.0.0-rc.5',
  toVersion: '4.0.0-rc.6',
}))
// ^4.0.0-rc.5 || ^4.0.0-rc

console.log(semver.getNewValue({
  currentValue: '^4.0.0-rc.5 || ^4.0.0-rc',
  rangeStrategy: 'widen',
  fromVersion: '4.0.0-rc.5',
  toVersion: '4.0.0-rc.6',
}))
// ^4.0.0-rc.5 || ^4.0.0-rc || ^4.0.0-rc
```

The initial range was enough (though `^4.0.0-rc` is cleaner and satisfies more than the original) but this function still seems to want to append a wider range than it needs to.

**Comment by rarkins** [comment] 2021-02-16 07:43
The reason we need it reproduced in a repo is to understand why the getNewValue function is getting called in the first place. Can you find a public package with similar releases to reproduce with?

**Comment by k2snowman69** [comment] 2021-02-28 08:20
Note to self: Looks like typescript has a package that is of similar naming convention `4.3.0-dev.20210228`, give that a try and see if it reproduces

**Comment by k2snowman69** [comment] 2021-03-21 21:58
I managed to get it to create a PR that created an invalid version number, but not exactly the scenario I mentioned:
https://github.com/k2snowman69/bug-renovate-peer-dep/pull/3/files

**Comment by HonkingGoose** [comment] 2021-04-05 09:40
@rarkins What do you think of the PR and repo in the comment above? Is that enough to consider this `reproduction:provided`? Or do you still want a stand-alone reproduction repo?

**Comment by MaronHatoum** [comment] 2022-08-08 10:52
Hi @k2snowman69
I tried to reproduce the issue using the [reproduction repository](https://github.com/k2snowman69/bug-renovate-peer-dep) you provided but I didn't succeed.

So, I added a new unit test to `\lib\modules\versioning\npm\index.spec.ts` and the test passed successfully.
```
  test.each`
    currentValue                  | rangeStrategy | currentVersion   | newVersion       | expected
    ${'^4.0.0-rc.5 || ^4.0.0-rc'} | ${'widen'}    | ${'4.0.0-rc.5'}  | ${'4.0.0-rc.6'}  | ${'^4.0.0-rc.5 || ^4.0.0-rc'}
  `(
    'test duplicate version when rangeStrategy=widen',
    ({ currentValue, rangeStrategy, currentVersion, newVersion, expected }) => {
      const res = semver.getNewValue({
        currentValue,
        rangeStrategy,
        currentVersion,
        newVersion,
      });
      expect(res).toEqual(expected);
    }
  );
```
I think this issue has been fixed, but to be sure we need a minimal reproduction repository that contains the same issue you reported and if it does not exist we can close this ticket.

**Closed** 2022-08-08 11:06 UTC
Labels: type:bug, priority-3-medium, status:requirements, reproduction:provided

**Comment by k2snowman69** [comment] 2022-08-09 03:01
If I run into it I'll let you know, thanks!
