### ISSUE TITLE
Automerge on hold reason

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#6311] opened 2020-05-23 12:36 UTC
**What would you like Renovate to be able to do?**
If automerge is enabled, I’d like to be given the reason why the pull request isn’t being merged.

**Describe the solution you'd like**
In the body of the pull requests, beside the automerge enabled indicator, the reason renovate is not currently merging the PR should be displayed.

**Describe alternatives you've considered**
Manually merging pull requests which are passing status checks and are fully rebased, due to not being aware of the reason for no automerge taking place.

**Additional context**
Several branch permissions can be configured, any of which could be preventing an automerge, there may be other situations outside of branch permissions which could also correspond to this state.

**Comment by ChipWolf** [comment] 2020-06-01 18:38
On removal of 'branch protection rules' from our master branch, automerges continued, which confirmed this issue for me.

**Comment by rarkins** [comment] 2020-06-01 19:08
We can probably cover a few of these reasons but not all branch protection rules may be easily visible to us at the API level unfortunately. I saw a case today where all status checks returned "success" yet `mergeStateStatus = BLOCKED` in the PR. i.e. GitHub isn't great at responding with "You can't merge because of X reason". We may need to query the branch protection rules themselves and try to reason from them why it doesn't work (e.g. check if there's a list of approved mergers and if we're on it, etc).

**Comment by rarkins** [comment] 2020-06-01 19:09
Needs some exploration of the GitHub API to determine which of the failure conditions we can determine and from which queries.

**Comment by viceice** [comment] 2020-06-01 19:13
Maybe an idea: try automerge PR's as usual, if failed, check protection rules for possible causes. 🤔

**Comment by rarkins** [comment] 2020-06-02 04:59
> Maybe an idea: try automerge PR's as usual, if failed, check protection rules for possible causes. 🤔

Good idea. If it takes any extra queries to determine then we should do it lazily and once per repo, as rules are common per-repo and not per-PR.

**Comment by Jolg42** [comment] 2020-11-03 12:25
I was seeing the same kind of behavior here 

```
DEBUG: getBranchStatus() result(branch="renovate/engines")
{
  "branchStatus": "green",
  "branchName": "renovate/engines"
}
DEBUG: Pull Request #4138 does not need updating(branch="renovate/engines")
DEBUG: Checking #4138 for automerge(branch="renovate/engines")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/engines")
DEBUG: PR is not ready for merge(branch="renovate/engines")
{
  "canMergeReason": "mergeStateStatus = BLOCKED"
}
```

and adding Renovate to allowlist like fixed it.
<img width="1104" alt="" src="https://user-images.githubusercontent.com/20165/64426208-e617a000-d0a5-11e9-9150-75addd84d2de.png">

https://github.com/renovatebot/renovate/issues/846#issuecomment-528826053

It would be really great to have better logging here, the exact problem would be great but a link to docs listing potential problems would be great as well I think 😃

**Comment by rarkins** [comment] 2021-03-14 11:52
Duplicate of #2702

**Closed by rarkins** 2021-03-14 11:52 UTC
Labels: platform:github, priority-3-normal, status:requirements, type:feature
