### ISSUE TITLE
[asdf] Support flutter plugin

### ISSUE THREAD

**Issue by h3y6e** [renovatebot/renovate#20273] opened 2023-02-07 11:19 UTC
### What would you like Renovate to be able to do?

Upgrade the [flutter](https://docs.flutter.dev/development/tools/sdk/releases) version in the `.tool-versions` file.

https://github.com/oae/asdf-flutter

### If you have any ideas on how this should be implemented, please tell us here.

Other plugins were added via #17166, #18612, #19941, #18987.
Additionally, pnpm plugin will be added via #20139.

The datasource should be [`flutter-version`](https://docs.renovatebot.com/modules/datasource/flutter-version/), which is also used in [fvm](https://docs.renovatebot.com/modules/manager/fvm/).
However, the asdf-flutter plugin version has a channel (stable, beta, or dev) suffix.

example:
`.tool-versions`
```
flutter 3.4.0-34.1.pre-beta
                      ^^^^^
```

We need to update this to the current latest version `flutter 3.7.1-stable`, but if we implement it the same way as other plugins, the updated `.tool-versions` will be `flutter 3.7.1`.

To accomplish this, do we need to make changes to the `flutter-version` and create the `versioning` of asdf-flutter instead of semver?

I would appreciate any advice as I do not know how to implement this properly.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment] 2023-02-08 14:51
i think we need a reproduction. your sample version looks a little weird. 🤔

**Comment by viceice** [comment] 2023-02-08 14:58
we can extract the dep with packageName `flutter/<channel>` and check that inside the datasource. if channel is passed, only return versions from channel, otherwise use current behavior to return all versions.

**Comment by h3y6e** [comment] 2023-02-10 04:21
Okay, I'll work on it this weekend.

**Comment by HonkingGoose** [comment] 2023-09-26 07:06
> However, the asdf-flutter plugin version has a channel (stable, beta, or dev) suffix.

It looks like we added _some_ channel support with this PR:

- https://github.com/renovatebot/renovate/pull/22131

But maybe we still need to do something more/else to fix this issue?

**Comment by rarkins** [comment] 2024-09-04 13:03
Closed by #20786

**Closed by rarkins** 2024-09-04 13:03 UTC
Labels: type:feature, priority-4-low, status:in-progress, manager:asdf
