### ISSUE TITLE
Use with pnpm

### ISSUE THREAD

**Issue by safinsingh** [renovatebot/renovate#8471] opened 2021-01-30 08:51 UTC
**I'd like renovate to be able to update my `pnpm-lock.yaml` when making pull requests**

Currently, my continuous integration runs with `pnpm` in `frozen-lockfile` mode, which I'd like to keep. However, this causes all pull requests from `renovate` to fail due to the fact that it does not yet have support for updating `pnpm`'s lockfile, as stated on the [documentation](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance).

**Did you already have any implementation ideas?**

After proposing the new dependency update, `renovate` could run `pnpm [recursive] install --frozen-lockfile=false` to install dependencies and upgrade the current lockfile.

**Comment by rarkins** [comment] 2021-01-30 09:12
In Renovate terminology, "lock file maintenance" is not the same as updating `pnpm` lock files *as part of a dependency upgrade*. Technically you need the latter to work.

`pnpm` lock file support [exists in Renovate](https://github.com/renovatebot/renovate/blob/5d99ff9862bac803dcea4e6ded5f3fec34abccfc/lib/manager/npm/post-update/pnpm.ts), and maybe still partially or mostly works, but it's possible we've fallen behind some of the breaking changes.

Next step would be a [minimal reproduction repo](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) that currently fails, so that we can debug it.

**Comment by rarkins** [comment] 2021-01-30 09:15
Actually, let's close this as a duplicate of #8323 as it already has a reproduction repo too

**Comment by rarkins** [comment] 2021-01-30 09:16
Duplicate of #8823

**Closed by rarkins** 2021-01-30 09:16 UTC
Labels: manager:npm, priority-3-normal, reproduction needed, status:requirements
