### ISSUE TITLE
automerge with semantic prefix commit.

### ISSUE THREAD

**Issue by jeremybaumont** [renovatebot/renovate#7344] opened 2020-09-22 06:58 UTC
**What would you like Renovate to be able to do?**

At the moment, when you enable automerge, it will merge with the commit message "auto merged" but if your CI enforce a semantic prefix in your commit message, you will encounter problems.

**Comment by rarkins** [comment] 2020-09-22 07:02
Duplicate of #7184

**Closed by rarkins** 2020-09-22 07:02 UTC
