### ISSUE TITLE
Add an issue on abort

### ISSUE THREAD

**Issue by sclorng** [renovatebot/renovate#11134] opened 2021-08-06 11:53 UTC
**What would you like Renovate to be able to do?**

When Renovate fails to scan, we should be notified.

Actually, if i'm not wrong, there is a message in the onboarding MR in the What to expect section. But no details. If the MR is approved, then there is no way to know there is a failure (apart watching the logs which project team doesn"t have access to).

I have some projects with docker hub image dependencies and due to docker hub request limit, Renoate fails. I would like the project team to know about the error to have them change the registry.

**Did you already have any implementation ideas?**

Create an issue with errors details ?
If the issue for the same errors is not closed, don't recreate a new one.

**Comment by viceice** [comment] 2021-08-06 12:18
use dependency dashboard?

**Comment by scrocquesel** [comment] 2021-08-06 12:21
> use dependency dashboard?

I'm using renovate docker image `renovate/renovate:25.69.0-slim` in schedule pipeline on a private gitlab.

**Comment by viceice** [comment] 2021-08-06 12:25
https://docs.renovatebot.com/presets-default/#dependencydashboard

So you'll get an overview issue about all updates and it also conatins any errors or warnings

see example:
- https://github.com/renovatebot/renovate/issues/2958
- https://gitlab.com/renovate-bot/renovate-runner/-/issues/2

**Comment by scrocquesel** [comment] 2021-08-06 13:00
Awesome feature. It should have a better exposure in the documentation maybe with a dedicated section in getting started.

Would it be possible to add a label when the issue contains errors and/or warnings ? (not sure about warning if they cannot be fixed by the user)

**Comment by scrocquesel** [comment] 2021-08-06 13:56
Does this should show up in the dashboard issue as an error/warning ?

```
DEBUG: packageFiles with updates (repository=myrepo)
       "config": {
         "dockerfile": [
           {
             "packageFile": "src/main/docker/Dockerfile",
             "deps": [
               {
                 "depName": "ubi8/ubi-minimal",
                 "currentValue": "8.4",
                 "replaceString": "ubi8/ubi-minimal:8.4",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "ubi8/ubi-minimal",
                     "message": "Failed to look up dependency ubi8/ubi-minimal"
                   }
                 ],
                 "versioning": "docker"
               }
             ]
           }
         ],
```

Actually it is not the case.

**Comment by HonkingGoose** [comment] 2021-08-06 15:53
This seems similar to issue:

- https://github.com/renovatebot/renovate/issues/2263

**Comment by viceice** [comment] 2021-08-06 17:16
Duplicate of #2263

**Closed by viceice** 2021-08-06 17:16 UTC
Labels: type:feature, status:requirements, priority-5-triage
