### ISSUE TITLE
Support Nuget ranges

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#7191] opened 2020-09-05 13:27 UTC
**What would you like Renovate to be able to do?**

For now, Nuget manager just parses versions from ranges, stripping out any brackets if such an update would be valid.
It would be better to add support for ranges and their update strategies as well.

**Did you already have any implementation ideas?**

It's very similar to Maven ranges.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

No

**Is this a feature you'd be interested in implementing yourself?**

Yes

**Comment by viceice** [comment] 2020-09-07 05:39
We should also support semver v1 and v2. Currently we only support semver v1 i think.

**Comment by zharinov** [comment] 2020-10-15 04:43
Blocks #6487

**Comment by fgreinacher** [comment] 2020-10-20 19:15
Duplicate of https://github.com/renovatebot/renovate/issues/5016?

**Comment by rarkins** [comment] 2020-10-20 19:20
Duplicate of #5016

**Closed by rarkins** 2020-10-20 19:20 UTC
Labels: feature, manager:nuget
