### ISSUE TITLE
Missing go.sum entry

### ISSUE THREAD

**Issue by nono** [renovatebot/renovate#9136] opened 2021-03-15 08:20 UTC
**What Renovate type, platform and version are you using?**

We are using renovate on GitHub, via the GitHub App.

**Describe the bug**

Our builds fail on some PR made by renovate, with the error:

> missing go.sum entry for module providing package _<the updated package>_

It looks like the go.sum entry was already missing previously, but it fails only with Go 1.16 (before the missing go.sum entry was ignored).

You can find an example of such a PR here: https://github.com/cozy/cozy-stack/pull/2946
and the error here : https://github.com/cozy/cozy-stack/pull/2946/checks?check_run_id=2109623885#step:6:87

The diff shows that renovate have removed 2 lines for v1.8.0, and only added a single line for v1.8.1:

```diff
- github.com/sirupsen/logrus v1.8.0 h1:nfhvjKcUMhBMVqbKHJlk5RPrrfYr/NMo3692g0dwfWU=
- github.com/sirupsen/logrus v1.8.0/go.mod h1:4GuYW9TZmE769R5STWrRakJc4UqQ3+QQ95fyz7ENv1A=
+ github.com/sirupsen/logrus v1.8.1/go.mod h1:yWOB1SBYBC5VeMP7gHvWumXLIWorT60ONWic61uBYv0=
```

**Relevant debug logs**

```
[...]
DEBUG: getBranchPr(renovate/github.com-sirupsen-logrus-1.x)
DEBUG: findPr(renovate/github.com-sirupsen-logrus-1.x, undefined, open)
DEBUG: getBranchPr(renovate/stefanzweifel-git-auto-commit-action-2.x)
[...]
DEBUG: Matches schedule before 6am on Monday(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Branch already exists(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: getBranchPr(renovate/github.com-sirupsen-logrus-1.x)(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: findPr(renovate/github.com-sirupsen-logrus-1.x, undefined, open)(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Skipping stale branch check due to rebaseWhen=auto(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Branch does not need rebasing(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Using reuseExistingBranch: true(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=true(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: gomod.updateDependency: v1.8.1(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: No changes necessary(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: No package files need updating(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: No updated lock files in branch(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: No files to commit(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Checking if we can automerge branch(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: mergeStatus=no automerge(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Ensuring PR(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: getBranchPr(renovate/github.com-sirupsen-logrus-1.x)(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: findPr(renovate/github.com-sirupsen-logrus-1.x, undefined, open)(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Creating PR(branch="renovate/github.com-sirupsen-logrus-1.x")
{
  "prTitle": "Update module github.com/sirupsen/logrus to v1.8.1"
}
DEBUG: Creating PR(branch="renovate/github.com-sirupsen-logrus-1.x")
{
  "title": "Update module github.com/sirupsen/logrus to v1.8.1",
  "head": "cozy:renovate/github.com-sirupsen-logrus-1.x",
  "base": "master",
  "draft": false
}
DEBUG: PR created(branch="renovate/github.com-sirupsen-logrus-1.x")
{
  "pr": 2946,
  "draft": false
}
DEBUG: Adding labels '' to #2946(branch="renovate/github.com-sirupsen-logrus-1.x")
INFO: PR created(branch="renovate/github.com-sirupsen-logrus-1.x")
{
  "pr": 2946,
  "prTitle": "Update module github.com/sirupsen/logrus to v1.8.1"
}
DEBUG: Created Pull Request #2946(branch="renovate/github.com-sirupsen-logrus-1.x")
DEBUG: Checking #2946 for automerge(branch="renovate/github.com-sirupsen-logrus-1.x")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/github.com-sirupsen-logrus-1.x")
[...]
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [X] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Running `go mod tidy` adds the missing entry to go.sum.

**Comment by HonkingGoose** [comment] 2021-03-15 08:45
For the Renovate wizards, here's their current config:

```json
{
  "extends": ["config:base"],
  "schedule": "before 6am on Monday",
  "timezone": "Europe/Paris",
  "postUpdateOptions": ["gomodTidy"]
}
```

Link to their config file: https://github.com/cozy/cozy-stack/blob/master/.renovaterc.json

**Comment by nono** [comment] 2021-03-15 09:17
https://github.com/renovatebot/renovate/issues/6213 looks related

**Comment by nono** [comment] 2021-03-22 08:14
I had the same errors on several pull requests this week too. Cf https://github.com/cozy/cozy-apps-registry/pull/234/checks?check_run_id=2164028827#step:6:56 for example.

**Comment by rarkins** [comment] 2021-03-22 08:16
Absent of a reproduction, let's consider this a duplicate of #6213

**Closed by rarkins** 2021-03-22 08:16 UTC
Labels: manager:gomod, platform:github, priority-2-important, status:requirements, type:bug
