### ISSUE TITLE
do not embed CHANGELOG/release text in PRs

### ISSUE THREAD

**Issue by boneskull** [renovatebot/renovate#2558] opened 2018-09-25 17:58 UTC
*Apologies for ignoring the issue template; it didn't really apply, since I'm not a Renovate user.*

When I write CHANGELOG entries--which I copy & paste into GitHub release notes--I list changes and mention whoever made them, using their GitHub username, e.g., `@boneskull`.

**If this entry text appears, verbatim, in a PR (*any* PR across GitHub), the user mentioned is notified by email per GitHub's default settings.**

I've gotten too many emails recently from Renovate Bot--and I assume other contributors have as well--because I'm mentioned in the CHANGELOG entries, and those entries are embedded in pull requests the bot creates.

Please either:

- *Link* to the CHANGELOG entry or GitHub release
- Embed the CHANGELOG entry in a preformatted text block so it is not interpreted by GitHub's Markdown parser
- Sanitize `@`-usernames by wrapping them in backticks

thanks

**Comment by rarkins** [comment] 2018-09-25 20:50
@boneskull 	sorry you got the spam, it was caused by an embarrassing mistake that was reverted within hours but unfortunately there are always a *lot* of PRs processed per hour by the bot. 

Also even once the bot "fixes" the PR bodies to remove the auto-linked text, GitHub keeps informing you of any updates to that PR forever despite you having no ongoing connection with it.

FYI we insert a "zero width space" HTML char after every @ to "de-link" them. 

If you don't mind the extra work this might entail, I would also like to double check for you that no links remain. Feel free to do it in whatever way is quickest for you, e.g. a screenshot of the repo names, or a pointer to the source repo(s) causing it, etc.

**Comment by rarkins** [comment] 2018-09-25 20:51
Actually I can assume it's probably https://github.com/mochajs/mocha/releases causing most of the noise and will start there.

**Comment by rarkins** [comment] 2018-09-28 13:15
I believe the problem is now resolved, so closing.

**Closed by rarkins** 2018-09-28 13:15 UTC
