### ISSUE TITLE
Replace emoji short codes with unicode representation

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#3799] opened 2019-05-22 20:23 UTC
Emoji shortcodes don't render in all instances, specifically in emails. Additionally, they're mostly to help humans in typing emoji, without having to find the exact Unicode character.

I would like to replace the emoji shortcodes, with the actual Unicode code point. so `:vertical_traffic_light:` becomes `🚦`, `:recycle:` becomes `♻️`.

Thoughts?

**Comment by rarkins** [comment] 2019-05-22 20:49
Sounds ok to me if it renders everywhere

**Comment by rarkins** [comment] 2019-06-22 05:44
@JamieMagee I noticed on GitHub that emoji shortcodes look best in commit messages (because they're text) but unicode would be better for PR titles, because otherwise GitHub doesn't render them. I was considering an option like "Replace emoji with unicode in PR titles" to solve this, but would this be compatible with Azure DevOps too?

**Comment by JamieMagee** [comment] 2019-06-24 18:22
@rarkins I think it would be simplest to just use unicode everywhere. Git is designed with UTF-8 support everywhere. From https://git-scm.com/docs/git-commit

>Commit log messages are typically encoded in UTF-8, but other extended ASCII encodings are also supported.

Additionally most terminals support unicode, so displaying emoji as a developer should be supported.

The main issues I had with using emoji shortcodes is that they weren't supported everywhere. The 2 cases that affected me were in emails, and in Microsoft Teams notifications.

**Comment by nvdbleek** [comment] 2019-07-04 08:10
@rarkins would you be open for a PR that makes replacing emoji shortcodes with their unicode equivalent configurable? In older versions of bitbucket server (together with older version of MysQL) there is a problem with 4 byte Unicode Characters, which results in a `500` error when creating the PR.

**Comment by JamieMagee** [comment] 2019-07-04 08:48
@nvdbleek This seems like a reasonable request.

Out of interest, do you know which versions of Bitbucket Server/MySQL this affects? I can't find any detailed information for Bitbucket Server specifically, but I [found this](https://confluence.atlassian.com/fishkb/migrate-mysql-database-to-utf8mb4-character-encoding-962356253.html) for Fisheye, which suggests MySQL 5.7.7, and [this page](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html) suggesting that `uft8mb4` was supported in MySQL 5.5

**Comment by nvdbleek** [comment] 2019-07-04 08:52
@JamieMagee `uft8mb4` is supported in MySQL 5.5, but you get into trouble because of the max key length of 767 bytes. Bitbucket has keys of 255 characters and 1020 is greater than the maximum of 767... So you can't use `uft8mb4`, or at least I couldn't get it to work ...

**Comment by JamieMagee** [comment] 2019-07-04 09:00
@nvdbleek Thanks for the explanation. I see that the limit was raised to 3072 bytes in MySQL 5.7, which I assume is why Fisheye requires 5.7.7 or higher.

**Comment by rarkins** [comment] 2019-07-04 09:00
@JamieMagee should we revert in the meantime?

**Comment by JamieMagee** [comment] 2019-07-04 09:02
@rarkins Yeah, a revert is the quickest fix. I'm heading on vacation today, so I definitely won't have time to implement the configuration.

**Comment by rarkins** [comment] 2019-07-04 09:05
I’m on vacation too so I think I’ll go with a revert today and then we reimplement with some kind of mapping later.

**Comment by rarkins** [comment] 2019-07-04 09:25
I think it might be named something like “emojiType”, default to value “shortcode” and have a second option “utf8”.

Starting with a revert seems best for now though.

**Comment by nvdbleek** [comment] 2019-07-04 11:39
@rarkins are you going to re-open this issue? Then I can make the PR to rollback and attach it to this issue. And this evening I will start working on the "emojiType " config option (don't have a lot of time this evening, I might finish it this weekend)

**Comment by nvdbleek** [comment] 2019-07-07 18:55
sorry, I have to do more work for my day-job this weekend then I was anticipating... Will try to work on this next week, or otherwise the week after next week when I'm on vacation then I will have for sure more time available...

**Comment by rarkins** [comment] 2019-07-08 13:28
We probably don't need to make this configurable, at least until we're presented with a compelling reason. For now it should be OK to use unicode for all except Bitbucket Server. So the question is - what's the best way to do that?

A nice way to be to use Bitbucket Server's [getPrBody](https://github.com/renovatebot/renovate/blob/af5f13fa8e470fd8047834553695a1950a0552b0/lib/platform/bitbucket-server/index.ts#L917) to massage unicode chars to emojis, including possibly with this library: https://github.com/iamcal/js-emoji

However I think for that to work then we need to ourselves determine and extract the emoji characters, e.g. something like this:

```
let output = '';
prBody.split('').forEach(char => {
  if (isEmoji(char)) {
    output += emoji.replace_unified(char);
  } else {
    output += char;
  }
});
```

**Comment by ViceIce** [comment] 2019-07-11 12:37
Bitbucket server is working fine with unicode here. so i would prefer a config switch.

BBS: 6.4.0
SQL: MS SQL Server 2014 SP3 CU2 (SQL_Latin1_General_CP437_CI_AI)

**Comment by ViceIce** [comment] 2019-07-11 13:54
as the bitbucket-server docu says, there is no unicode support with mysql for all versions:

![image](https://user-images.githubusercontent.com/1798109/61056594-f12ab880-a3f3-11e9-91ac-83343973e38c.png)

https://confluence.atlassian.com/bitbucketserver/connecting-bitbucket-server-to-mysql-776640382.html

**Comment by ViceIce** [comment] 2019-07-11 14:13
@nvdbleek any chance to switch the database to postgres or msssql or anything else with unicode support? This is a really bad blocker because we need a unicode replacement for the \| char in markdown table

**Comment by JamieMagee** [comment] 2019-07-11 20:58
@ViceIce I don't think that's an issue. `utf8` data type supports up to 3 bytes per character, and `|` is a single byte character in utf8 (`0x7C`). The problem is all emoji, like `🚦` are 4 bytes (In this case `0xF0 0x9F 0x9A 0xA6`) and that requires use of `utf8_mb4`, which is apparently not supported by Bitbucket Server.

**Comment by ViceIce** [comment] 2019-07-12 06:23
@JamieMagee They are supported by Bitbucket Server, but not with MySQL.

I'm using emojis without problems on MS SQL Server.
I think the problem is, that Bitbucket supports the ancient MySQL 5.5 which has the index limit.
Also they only support the Connector/J 5.1, which is very old too, but supports [utf8mb4](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html)

So it should be possible to use emojis, if you use Connector/J 5.1.47 with MySQL 5.7 / MariaDB 10.2 or later. (This versions comes with InnoDB 5.7 with expaned index length)

I know that the pipe is a single byte char. I've found another bug with markdown tables.

```md
| head | test | e |
| --- | --- | --- |
| unescaped | `^7.0.0 | ^8.0.0` | test it |
```

| head | test | e |
| --- | --- | --- |
| unescaped | `^7.0.0 | ^8.0.0` | test it |

So we have to escape the pipe. 

* works for github / gitlab
* azure works only with unescaped pipe
* bitbucket server shows the escape symbol
* bitbucket cloud is totally broken

As simple solution @rarkins  and i thougt that we can simply replace the pipe with an unicode char, which looks like a pipe. But all alternatives require 4 bytes.

I will build some docker images to test emojis with newer mysql/mariadb support.

**Comment by rarkins** [comment] 2019-07-12 06:31
Our idea is:
- Massage the markdown to make sure we don't break table columns in each platform
- For platforms that display the escaped pipe (incorrectly), replace the <code>\\|</code> with a unicode pipe lookalike

**Comment by nvdbleek** [comment] 2019-07-12 06:43
@ViceIce I tried changing the collation of an old MySQL DB to mb4 UTF-8 and I can confirm that there is a problem with the max key length of 767 bytes. Bitbucket has keys of 255 characters and 1020 bytes (4x255) is greater than the maximum of 767. This limit is indeed bumped in MySQL 5.7. Atlassian even documents how you can change the collation to a 4-byte UTF-8 Unicode encoding on https://confluence.atlassian.com/kb/how-to-fix-the-collation-and-character-set-of-a-mysql-database-744326173.html

An upgrade to MySQL 5.7 for my database is on our roadmap. But I suspect that I'm not the only person that is running Bitbucket on an older MySQL. So the question is does Renovate wants to support those installations? If the answer is yes, we have to decide how we want to handle this. I like the proposal of @rarkins to massage Unicode chars to emoji  Bitbucket Server's [getPrBody](https://github.com/renovatebot/renovate/blob/af5f13fa8e470fd8047834553695a1950a0552b0/lib/platform/bitbucket-server/index.ts#L917). I don't see any substantial downsides of not using Unicode chars for Prs in Bitbucket (it is not that much extra code and it is also only a couple of bytes extra in the DB).

If we can agree on an approach I'm volunteering to create a GitHub PR.

**Comment by rarkins** [comment] 2019-07-12 07:07
Given that Bitbucket Server (now) recommends against MySQL, and MySQL 5.7 was apparently released in 2013, I definitely have some doubts about how widespread this combination is amongst current or future Renovate users.

The main downsides for supporting unicode massaging are:
- Having to maintain an extra config option for this (assuming we can't autodetect the DB in use)
- Always having to think twice before using unicode anywhere else, e.g. the pipe substitution issue, which is not related to emoji

**Comment by ViceIce** [comment] 2019-07-12 07:28
The escape bug in bitbucket server will be fixed in near future: https://github.com/atlassian/commonmark-java/issues/149
hopefully not so long future 😄

**Comment by ViceIce** [comment] 2019-07-12 07:43
Using initial db with `utf8mb4_bin` not supported, trying to convert later from `utf8_bin`
![image](https://user-images.githubusercontent.com/1798109/61111230-64323e80-a489-11e9-9124-693c4dc58faa.png)

**Comment by ViceIce** [comment] 2019-07-12 07:56
I've tried to create a sample with mysql 5.7: https://github.com/ViceIce/renovate-docker

I can't create a repository 😱 used utf8_bin as db collation

![image](https://user-images.githubusercontent.com/1798109/61112037-406ff800-a48b-11e9-9b73-814353e288f0.png)

**Comment by nvdbleek** [comment] 2019-07-12 08:07
@ViceIce and what if you change it to CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ? The 4 byte encoding version?

**Comment by nvdbleek** [comment] 2019-07-12 08:07
@ViceIce sorry, you first tried utf8mb4_bin, I missed that comment...

**Comment by ViceIce** [comment] 2019-07-12 08:09
@nvdbleek  install not possible, after install i can't convert column collation ecause of a key contraint

the error could be from docker for windows local path mapping, i will try a docker-volume later.

**Comment by ViceIce** [comment] 2019-07-12 08:12
I'll also try [Automated setup for Bitbucket Server](https://confluence.atlassian.com/bitbucketserver/automated-setup-for-bitbucket-server-776640098.html)

**Closed** 2019-09-25 09:40 UTC
Labels: in progress, pri3-normal
