### ISSUE TITLE
Option for self-hosted to prevent the bot looking for an existing renovate config

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#13933] opened 2022-01-31 19:44 UTC
### What would you like Renovate to be able to do?

We have a hybrid situation where one private package (a GitHub release) needs a "self-hosted" Renovate (a GitHub action), and we'd prefer most of our renovation to continue to be performed by the hosted version.

Right now, we supply a special renovate config for this GitHub action; however, no matter what I've tried, during execution Renovate still merges the supplied config with the renovate config in the repo (intended for the managed Renovate's consumption).

### If you have any ideas on how this should be implemented, please tell us here.

I'd like an option to prevent the bot from looking in the repo for config, and use the one supplied to the action as the only source of configuration.

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment] 2022-01-31 19:49
Technically not possible

**Comment by ChipWolf** [comment] 2022-01-31 20:11
> Technically not possible

Everything is technically possible 😆 
What's the limitation of returning null here with an if function & a new config option?
https://github.com/renovatebot/renovate/blob/7e069f4adce758bef94fc31ea4db8984f3169da9/lib/workers/repository/init/merge.ts#L26

**Comment by viceice** [comment] 2022-01-31 20:37
I don't like that idea.

You can always use a `force` option on global config to override everything from repo config.

**Comment by ChipWolf** [comment] 2022-01-31 20:44
> I don't like that idea.
> 
> You can always use a `force` option on global config to override everything from repo config.

This Frankenstein config appears to do the job, but I'm not certain if it's actually overriding anything, the output still shows all of the original config after massaging.
```json5
{
  "extends": [
    ":enableRenovate",
    ":semanticCommits",
    ":separatePatchReleases",
    ":enablePreCommit"
  ],
  "platform": "github",
  "username": "botuser",
  "repositories": ["ourorg/gitops-k8s"],
  "onboarding": false,
  "requireConfig": false,
  "regexManagers": [
    {
      "fileMatch": ["./.*\\.yaml$"],
      "matchStrings": [
        "OLYMPUS_RELEASE: \"?olympus-(?<currentValue>.*).zip\"?\n"
      ],
      "depNameTemplate": "ourorg/olympus-config",
      "datasourceTemplate": "github-releases"
    }
  ],
  "packageRules": [
    {
      "matchPaths": ["**"],
      "dependencyDashboardApproval": true
    },
    {
      "automerge": false,
      "labels": ["olympus"],
      "matchDatasources": ["github-releases"],
      "stabilityDays": 0,
      "dependencyDashboardApproval": false
    }
  ],
  "force": {
    "extends": null,
    "schedule": null,
    "dependencyDashboard": false,
    "prCreation": "immediate",
    "stabilityDays": 0,
    "helm-values": null,
    "kubernetes": null,
  }
}
```

**Comment by ChipWolf** [comment] 2022-01-31 20:56
Yeah, confirmed that config doesn't do much, the dependency dashboard is still created among some other things

**Comment by rarkins** [comment] 2022-02-01 05:44
Duplicate of #6626

See https://github.com/renovatebot/renovate/issues/6626#issuecomment-827870904 for my proposal to add new option to *ignore* repo config

**Closed by rarkins** 2022-02-01 05:45 UTC
Labels: type:feature, status:requirements, priority-5-triage
