### ISSUE TITLE
Dependency dashboard in Confluence or Jira

### ISSUE THREAD

**Issue by fireflo** [renovatebot/renovate#16625] opened 2022-07-17 17:57 UTC
### What would you like Renovate to be able to do?

Hello,
For bitbucket users, would it be possible to have the dependency dashboard implemented in Confluence or Jira ? 
Thank you ! 

### If you have any ideas on how this should be implemented, please tell us here.

A first read-only implementation (no checkboxes) would be easier to implement and can already bring a lot of value.

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment] 2022-07-17 18:07
Duplicate of #3796

**Closed** 2022-07-17 18:07 UTC
Labels: type:feature, status:requirements, priority-5-triage
