### ISSUE TITLE
Merge Request acceptance metrics

### ISSUE THREAD

**Issue by joelfoliveira** [renovatebot/renovate#20271] opened 2023-02-07 10:36 UTC
### What would you like Renovate to be able to do?

We are deploying Renovate Bot in a scenario where there are hundreds of repositories.

In order to understand how teams are using Renovate Bot, it would be useful for Renovate to expose some kind of metrics in order to understand:
- Number of Repositories using Renovate Bot 
- Number of Merge Requests created by Renovate Bot
- Number of Merge Requests created by Renovate Bot merged/closed.

### If you have any ideas on how this should be implemented, please tell us here.

Since Renovate Bot runs on demand and not as a service, collecting the metrics could be challenging. What could be the best way to achieve this?

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by secustor** [comment] 2023-02-07 12:35
Closing as duplicate of https://github.com/renovatebot/renovate/issues/17661

Please add the requested metrics there.

**Closed by secustor** 2023-02-07 12:35 UTC
Labels: type:feature, status:requirements, priority-5-triage

**Comment by HonkingGoose** [comment] 2023-02-09 19:52
Duplicate of #17661
