### ISSUE TITLE
renovate-config manager

### ISSUE THREAD

**Issue by foolioo** [renovatebot/renovate#16679] opened 2022-07-21 08:55 UTC
### What would you like Renovate to be able to do?

Renovate should be able to detect updates to [Sharable Config Preset](https://docs.renovatebot.com/config-presets/#preset-hosting). For instance, look at a Renovate configuration that looks like

```json
{
  "extends": ["gitlab>abc/foo//path/xyz#1.5.4"]
}
```

Renovate should detect that `abc/foo` has a new tag.
There is no builtin [manager](https://docs.renovatebot.com/modules/manager/) for renovate-config where it should be a fundamental manager.

### If you have any ideas on how this should be implemented, please tell us here.

renovate-config manager should use its builtin config library to:
- Parse renovate config (`(^|/).?renovate(?:rc)?(?:\.json5?)?$`)
- Extract the
   - manager (e.g., `github`)
   - repository (e.g., `abc/foo`)
   - version (e.g., `1.5.4`)
- Use the extracted information (manager, repository, and version) from previous step to detect any changes

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment] 2022-07-22 05:27
Sure, PRs welcome

**Comment by mkniewallner** [comment] 2022-10-23 12:18
This looks like a duplicate of #13308.

**Comment by viceice** [comment] 2022-10-23 13:23
Duplicate of #13308

**Closed** 2022-10-23 13:23 UTC
Labels: type:feature, priority-3-medium, new package manager, status:ready, core:config
