### ISSUE TITLE
Issues/PR in Changelogs from GitHub Enterprise Server should point to that Enterprise Server instead of github.com

### ISSUE THREAD

**Issue by Shegox** [renovatebot/renovate#19228] opened 2022-12-02 16:46 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.41.0

### If you're self-hosting Renovate, select which platform you are using.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

3.5.5

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When Renovate adds Changelogs from internal packages hosted on GitHub Enterprise Server (GHES) and they only contain references like `#16`, Renovate leverages the below function to translate them to actual GitHub links. 

https://github.com/renovatebot/renovate/blob/4de1df3a6c054c44eddaf38e9bc2e2071b9c4e8f/lib/util/markdown.ts#L28-L44

Currently these links always point to github.com and not to the hosted GitHub Enterprise Server.

This can be archived with [speciying a custom buildUrl in remarkJS](https://github.com/remarkjs/remark-github#example-buildurl).
 
--- 

Currently following happens: 

A changelog like this 
<img width="373" alt="image" src="https://user-images.githubusercontent.com/16856448/205341763-39934b5c-7c58-4a1f-99ac-775fea9c2e3b.png">

gets transformed to this markdown: 
```md
### Release Notes

<details>
<summary>my-org/my-dependency-repo</summary>

### [`v0.4.3`](https://github.enterprise.com/my-org/my-dependency-repo/blob/HEAD/CHANGELOG.md#&#8203;043---2022-12-02)

-   Automate GitHub Releases ([#&#8203;16](https://github.com/my-org/my-dependency-repo/issues/16))
```

The expected markdown should look like this: 

```md
### Release Notes

<details>
<summary>my-org/my-dependency-repo</summary>

### [`v0.4.3`](https://github.enterprise.com/my-org/my-dependency-repo/blob/HEAD/CHANGELOG.md#&#8203;043---2022-12-02)

-   Automate GitHub Releases ([#&#8203;16](https:///github.enterprise.com/my-org/my-dependency-repo/issues/16))
```

 I will create a PR next week to address this.

### Relevant debug logs

n/a

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by Shegox** [comment] 2022-12-09 08:16
After digging a bit into it, it seems that the `baseUrl` option to change the GitHub base url requires github-remark v11 (Renovate currently uses github-remark v10). github-remark v11 is distributed as ESM only and therefore can't be used. 

Because of that and because I don't see a quick workaround I would put it on hold until ESM support is added in Renovate: 
- https://github.com/renovatebot/renovate/issues/13181
- https://github.com/renovatebot/renovate/issues/9890  

If we really want to add it now, we could ask if the github-remark project backports the feature to v10 and releases that as commonjs module -or- do that ourself and use a fork of it.

**Comment by rarkins** [comment] 2022-12-23 07:07
I'm going to close this as a duplicate of #19503 because I think it's the same problem and that one has a reproduction using gitlab.com

**Comment by rarkins** [comment] 2022-12-23 07:08
Duplicate of #19503

**Closed by rarkins** 2022-12-23 07:08 UTC
Labels: type:bug, priority-3-medium, status:ready, core:changelogs
