### ISSUE TITLE
Configure `configFileNames`

### ISSUE THREAD

**Issue by sbrugman** [renovatebot/renovate#21351] opened 2023-04-05 10:40 UTC
### What would you like Renovate to be able to do?

The configFileNames should be extendable (e.g. through environment variables):
https://github.com/renovatebot/renovate/blob/9ac80ddd037c68c6150ec8598b6388ec00d636f9/lib/config/app-strings.js#L5-L11

The current selection is too limited, and it should not be expected that renovate catches all useful variants. 
Practical example: `.github/renovate.json` is supported, but not `.azure/renovate.json`.

See also:
https://docs.renovatebot.com/configuration-options/

### If you have any ideas on how this should be implemented, please tell us here.

Through environment variables and/or global config.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment] 2023-10-01 07:41
Duplicate of #10682

**Closed by rarkins** 2023-10-01 07:41 UTC
Labels: type:feature, status:requirements, priority-5-triage
