### ISSUE TITLE
Dependency extraction failed for Gradle dependency constraints

### ISSUE THREAD

**Issue by remal** [renovatebot/renovate#6886] opened 2020-07-29 22:37 UTC
**What Renovate type are you using?**

I'm using the hosted app.

**Describe the bug**

I have a separate Gradle subproject with dependency constraints. Renovate App doesn't handle constraints' versions.

As you can see in logs below, all `spring-*-dependencies` and `*-bom` dependencies have `currentValue` equal to `null`.

But dependency constraint versions are set: https://github.com/remal/tracing-spec/blob/08cf62701096028c7c192eb805ed014af97c107a/dependency-versions/build.gradle

**Relevant debug logs**

You can find Renovate App debug logs attached: [renovate.log](https://github.com/renovatebot/renovate/files/4997818/renovate.log)

This commit was the latest at the moment Renovate was executed: https://github.com/remal/tracing-spec/tree/08cf62701096028c7c192eb805ed014af97c107a

**Comment by remal** [comment] 2020-07-29 23:13
https://github.com/renovatebot/renovate/blob/049daa6a8839da019adde803f4c90df5774d76f6/lib/manager/gradle/gradle-updates-report.ts#L113-L129

Looks like that we merge repositories here, but not versions.

I suppose that the problem is that:
1. Renovate App handles non-versioned constraints from root `build.gradle`
1. Only then it handles versioned constraints from the subproject
1. As non-versioned group-module pairs from the root are already handled, we just skip versioned ones from the subproject

Please correct me if I'm wrong with the assumption.

**Comment by MaronHatoum** [comment] 2022-08-07 09:12
I think this issue has been fixed because it is not reproducible.
Logs from Renovate latest release:
```
 {
             "depName": "org.springframework.cloud:spring-cloud-sleuth-dependencies",
             "currentValue": "2.2.3.RELEASE",
             "managerData": {
               "fileReplacePosition": 307,
               "packageFile": "build.gradle"
             },
             "fileReplacePosition": 307,
             "registryUrls": [],
             "depType": "dependencies",
             "depIndex": 1,
             "updates": [
               {
                 "bucket": "non-major",
                 "newVersion": "2.2.7.RELEASE",
                 "newValue": "2.2.7.RELEASE",
                 "releaseTimestamp": "2021-02-11T14:36:05.000Z",
                 "newMajor": 2,
                 "newMinor": 2,
                 "updateType": "patch",
                 "branchName": "renovate/org.springframework.cloud-spring-cloud-sleuth-dependencies-2.x"
               },

```
Logs @remal provided:
```
{
            "name": "spring-cloud-sleuth-dependencies",
            "depGroup": "org.springframework.cloud",
            "depName": "org.springframework.cloud:spring-cloud-sleuth-dependencies",
            "currentValue": null,
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 6,
            "updates": [],
            "warnings": [],
            "skipReason": "unsupported-value"
          },
```
in the old logs the `currentValue` was `null`, and in the new logs `currentValue` contains the relevant version.
Can we close this issue, please?

**Closed** 2022-08-07 09:52 UTC
Labels: type:bug, priority-3-medium, manager:gradle, status:requirements
