### ISSUE TITLE
Could you fix GH mentions to use Markdown links rather than inserting them in raw form?

### ISSUE THREAD

**Issue by isiahmeadows** [renovatebot/renovate#2554] opened 2018-09-22 16:38 UTC
I'm suddenly getting blasted with notifications from this bot over a single commit including an @mention in its description. What I'd like is for it to rewrite cases of `@user` (outside code blocks) to `[\@user](https://github.com/user)`, so it doesn't result in notifying everyone.

**Comment by isiahmeadows** [comment] 2018-09-22 16:45
This would require a little bit of markdown awareness, but I'd be willing to write a simple state machine parser that could trivially do this in one pass pretty quickly. (I literally only need one token of lookahead and a few state counters.)

I'd also be willing to fix #2252 in the process, since fixing it would be very similar.

**Comment by rarkins** [comment] 2018-09-22 16:50
@isiahmeadows thanks for raising this. It's caused by a recent change that I've now reverted. The old way was escaping too much, while the new one seemingly escaped too little. Could you point me to an example of a PR that referenced you?

**Comment by rarkins** [comment] 2018-09-22 16:53
FYI I am using this lib: https://github.com/nitin42/linkify-markdown

The one I'm aware of already that it misses is like this: `@user1/@user2`. The linkify lib skips both of them but GitHub linkifies just user2

**Comment by isiahmeadows** [comment] 2018-09-22 16:53
Here's all the mentions I have had so far:

- https://github.com/jackdbd/threejs-es6-webpack-starter/pull/26
- https://github.com/rehandalal/rehandalaldotcom/pull/13
- https://github.com/chintan9/react-d3/pull/39
- https://github.com/sbardian/winston-reader/pull/13
- https://github.com/geekcojp/config/pull/8

**Comment by rarkins** [comment] 2018-09-22 16:56
Thanks. Seems like linkfy is missing examples like `[@ljharb]` too.

**Comment by isiahmeadows** [comment] 2018-09-22 16:56
@rarkins I'm going to try to come up with a better sledgehammer that's a bit more tolerant. I've written a few parsers before, so this one should be pretty easy to write.

**Comment by rarkins** [comment] 2018-09-22 16:59
@isiahmeadows that would be awesome, thanks. The challenge is how to catch *everything* that GitHub themselves automatically linkify.

**Comment by isiahmeadows** [comment] 2018-09-22 17:06
That's the goal. I'll ping back once I've got a working filter. (It'll be a separate module like linkify.)

**Comment by rarkins** [comment] 2018-09-22 17:43
To summarise:

- We want to avoid any automatic linking to users, issues or Pull Requests from within release notes
- In the "old" approach (which is now the current approach again after I reverted changes), we do this:
  * Use a linkify library to try to find and explicitly link
  * Use our own additional escaping, particularly using zero width spaces
  * Convert to html and then replace any links to github.com to a renovatebot.com/gh/ "redirector"
- In the "new" approach (reverted), we:
  * Still use linkify
  * Removed our own escaping
  * Did not convert to HTML and instead replaced markdown links with our redirector

Both the html as well as the escaping has sometimes been inconvenient to users, so that's why a new way was explored to escape less while still hopefully capturing all of GitHub's implicit links. But it seems we were missing some.

**Comment by rarkins** [comment] 2018-09-23 12:54
Current status: 
- we use linkify but it doesn't catch everything GitHub detects
- we insert a zero width space after `@` and `#` in changelogs to "break" GitHub's linking
- we try to reverse out some of these spaces if we know they are unnecessary

The main thing we're missing is reversing them out of something like:
```
`This is a changelog comment with escaped @&#8203;username`
```

**Comment by isiahmeadows** [comment] 2018-09-24 17:43
The more I look at it, there are two things making this way more difficult than I anticipated: code blocks within list items and indented code blocks. I don't exactly have the time to account for these, so I'll have to rely on whatever you all come up with.

As for links, it's easy: you just parse through the name, expecting balanced braces (excluding those in code blocks) and replacing all mentions and issues outside of inline code, and you skip the href.

But for code blocks, here's the pathological cases:

`````md
<!-- List items - `foo` is not parsed as code -->
1. ```
foo
```

<!-- List items - `foo` is parsed as code -->
1. ```
   foo
   ```

<!-- Indented code blocks - `foo` is not parsed as code -->
    ```
foo
```

<!-- Indented code blocks - `foo` is parsed as the second line of code -->
    ```
    foo
    ```

<!-- Indented code blocks - `foo` is not parsed as code, but the first three backticks are -->
    ```
foo
``` wat
`````

**Comment by rarkins** [comment] 2018-09-25 08:39
@isiahmeadows 	thanks for taking a look at it. I hadn't even thought of all those edge cases. I think for now I'll close this, because as originally suggested - I believe we are fully escaping all usernames correctly again. The remaining "problem" is over-escaping, but that seems hard to solve without doing a full github-flavour markdown parsing, massing, then export. I'll wait until someone feels strongly enough about it to open an issue with a real example.

**Closed by rarkins** 2018-09-25 08:39 UTC
