### ISSUE TITLE
pip_requirements: not resolving MixedCase named packages

### ISSUE THREAD

**Issue by dds** [renovatebot/renovate#6921] opened 2020-08-05 23:31 UTC
**What Renovate type are you using?**

Renovate Self-hosted @ 22.3.1.

**Describe the bug**

When running Renovate on a Python project with a `requirements.txt` file that lists `jinja2==2.10.1` in it, I expected Renovate to find the newer version of `Jinja2` on the PyPI warehouse, but it does not.

This seems to be due to the package names being in lowercase but the package names on the PyPI warehouse are in MixedCase.

**Relevant debug logs**

```
DEBUG: Failed to look up dependency jinja2 (repository=NerdWallet/yak-herder, packageFile=requirements.txt, dependency=jinja2)
```

**To Reproduce**

Please try to run Renovate against this sample Python project: https://github.com/dds/sample/

When I do, Renovate fails to lookup the dependencies `jinja2` and `markupsafe`.

**Additional context**

**Comment by rarkins** [comment] 2020-08-06 04:50
Seems we should do case-insensitive name lookups for pypi sources. In the meantime the workaround is to name packages with case sensitivity in `requirements.txt` as recommended on PyPi:

![image](https://user-images.githubusercontent.com/6311784/89492080-074ea800-d7b1-11ea-9311-630b29683fc8.png)

**Comment by viceice** [comment] 2021-09-23 16:57
Closing this in favor of

Duplicate of #11139

**Closed by viceice** 2021-09-23 16:57 UTC
Labels: priority-3-medium, datasource:pypi, mend:customer-request
