### ISSUE TITLE
The PR body in description seems to be duplicated

### ISSUE THREAD

**Issue by ivankatliarchuk** [renovatebot/renovate#14887] opened 2022-03-31 21:09 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

docker renovate/renovate:32.10-slim

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

renovate/renovate:32.10-slim

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When a pull request is created, the body contains duplicated release notes in the release notes description. 

Example

![duplicated-1](https://user-images.githubusercontent.com/5395690/161149832-c975142e-cb23-4180-b879-5205e25f93ff.png)
![duplicated-2](https://user-images.githubusercontent.com/5395690/161149840-c0827e77-3edd-494b-bd10-40369ae13fda.png)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by ivankatliarchuk** [comment] 2022-03-31 21:12
Repository: https://github.com/ik-workshop/renovate-issue-14887
PR with duplicated release notes description: https://github.com/ik-workshop/renovate-issue-14887/pull/1

**Comment by viceice** [comment] 2022-04-01 00:37
Duplicate of #13037

**Closed by viceice** 2022-04-01 00:37 UTC
Labels: type:bug, status:requirements, priority-5-triage
