### ISSUE TITLE
Setting prConcurrentLimit blocks PRs creation

### ISSUE THREAD

**Issue by remal** [renovatebot/renovate#7239] opened 2020-09-10 08:48 UTC
I'm using hosted Renovate App.

When I set `prConcurrentLimit` to `1` or greater, Renovate doesn't create PRs. When I set `prConcurrentLimit` to `0`, Renovate starts creating PRs.

Here is a part of job logs:
```
DEBUG: 24 flattened updates found: io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift, io.grpc:grpc-bom, io.jaegertracing:jaeger-thrift
DEBUG: Returning 2 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: processRepo()
DEBUG: Processing 2 branches: renovate/io.grpc-grpc-bom-1.x, renovate/io.jaegertracing-jaeger-thrift-1.x
DEBUG: Enforcing prConcurrentLimit (1)
DEBUG: 1 PRs are currently open
DEBUG: PR concurrent limit remaining: 0
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 0
}
```

As you can see, there is `PR concurrent limit remaining: 0` message, which is strange, as at the moment job started, there were no opened PRs in the repository.

**Comment by HonkingGoose** [comment] 2020-10-27 16:44
@rarkins I'm thinking this might be a duplicate of #7197?

**Closed** 2020-10-27 16:45 UTC
Labels: bug
