### ISSUE TITLE
Renovate ignores PHP version constraint

### ISSUE THREAD

**Issue by mbrodala** [renovatebot/renovate#11216] opened 2021-08-11 10:57 UTC
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

25.65.0

### Describe the bug

We have a TYPO3 distribution with `"php": "^7.3"` as PHP version constraint.

Yesterday all TYPO3 packages got an update which is now suggested by Renovate. But Renovate did also update `psr/cache` from version `1.0.1` to version `2.0.0` where the latter requires PHP 8.x or newer:

```diff
            "name": "psr/cache",
-           "version": "1.0.1",
+           "version": "2.0.0",
            "source": {
                "type": "git",
                "url": "https://github.com/php-fig/cache.git",
-               "reference": "d11b50ad223250cf17b86e38383413f5a6764bf8"
+               "reference": "213f9dbc5b9bfbc4f8db86d2838dc968752ce13b"
            },
            "dist": {
                "type": "zip",
-               "url": "https://api.github.com/repos/php-fig/cache/zipball/d11b50ad223250cf17b86e38383413f5a6764bf8",
-               "reference": "d11b50ad223250cf17b86e38383413f5a6764bf8",
+               "url": "https://api.github.com/repos/php-fig/cache/zipball/213f9dbc5b9bfbc4f8db86d2838dc968752ce13b",
+               "reference": "213f9dbc5b9bfbc4f8db86d2838dc968752ce13b",
                "shasum": ""
            },
            "require": {
-               "php": ">=5.3.0"
+               "php": ">=8.0.0"
            },
```

So it looks like Renovate ignores our PHP version constraint and simply uses the latest available PHP version.

This is very likely caused by the `--ignore-platform-reqs` option.

### Relevant debug logs

<details><summary>Logs</summary>

```
{"name":"renovate","hostname":"<hostname>","pid":17,"level":20,"logContext":"QsTH9QFez","repository":"<repository>","branch":"renovate/patch-typo3","command":"docker run --rm --name=renovate_php --label=renovate_child -v \"/<renovate-repository>/renovate/repos/gitlab/<repository>\":\"/<renovate-repository>/renovate/repos/gitlab/<repository>\" -v \"/<renovate-repository>/renovate/cache\":\"/<renovate-repository>/renovate/cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/<renovate-repository>/renovate/repos/gitlab/<repository>\" docker.io/renovate/php:7.4.22 bash -l -c \"install-tool composer 2.1.5 && composer update typo3/cms-backend typo3/cms-belog typo3/cms-beuser typo3/cms-core typo3/cms-extbase typo3/cms-extensionmanager typo3/cms-filelist typo3/cms-fluid typo3/cms-fluid-styled-content typo3/cms-form typo3/cms-frontend typo3/cms-info typo3/cms-install typo3/cms-lowlevel typo3/cms-recordlist typo3/cms-recycler typo3/cms-redirects typo3/cms-reports typo3/cms-rte-ckeditor typo3/cms-scheduler typo3/cms-seo typo3/cms-setup typo3/cms-tstemplate typo3/cms-viewpage --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"","msg":"Executing command","time":"2021-08-11T10:43:40.594Z","v":0}
{"name":"renovate","hostname":"<hostname>","pid":17,"level":20,"logContext":"QsTH9QFez","repository":"<repository>","branch":"renovate/patch-typo3","cmd":"docker run --rm --name=renovate_php --label=renovate_child -v \"/<renovate-repository>/renovate/repos/gitlab/<repository>\":\"/<renovate-repository>/renovate/repos/gitlab/<repository>\" -v \"/<renovate-repository>/renovate/cache\":\"/<renovate-repository>/renovate/cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/<renovate-repository>/renovate/repos/gitlab/<repository>\" docker.io/renovate/php:7.4.22 bash -l -c \"install-tool composer 2.1.5 && composer update typo3/cms-backend typo3/cms-belog typo3/cms-beuser typo3/cms-core typo3/cms-extbase typo3/cms-extensionmanager typo3/cms-filelist typo3/cms-fluid typo3/cms-fluid-styled-content typo3/cms-form typo3/cms-frontend typo3/cms-info typo3/cms-install typo3/cms-lowlevel typo3/cms-recordlist typo3/cms-recycler typo3/cms-redirects typo3/cms-reports typo3/cms-rte-ckeditor typo3/cms-scheduler typo3/cms-seo typo3/cms-setup typo3/cms-tstemplate typo3/cms-viewpage --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"","durationMs":16019,"stdout":"Installing tool composer v2.1.5\nComposer version 2.1.5 2021-07-23 10:35:47\n","stderr":"Loading composer repositories with package information\nDependency \"doctrine/dbal\" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.\nUpdating dependencies\nLock file operations: 2 installs, 39 updates, 0 removals\n  - Upgrading doctrine/annotations (1.13.1 => 1.13.2)\n  - Upgrading enshrined/svg-sanitize (0.14.0 => 0.14.1)\n  - Locking masterminds/html5 (2.7.5)\n  - Upgrading psr/cache (1.0.1 => 2.0.0)\n  - Upgrading symfony/cache (v5.3.3 => v5.3.4)\n  - Upgrading symfony/dependency-injection (v4.4.26 => v4.4.27)\n  - Upgrading symfony/event-dispatcher (v5.3.0 => v5.3.4)\n  - Upgrading symfony/expression-language (v5.3.0 => v5.3.4)\n  - Upgrading symfony/finder (v4.4.25 => v4.4.27)\n  - Upgrading symfony/http-foundation (v5.3.3 => v5.3.6)\n  - Upgrading symfony/mailer (v5.3.3 => v5.3.4)\n  - Upgrading symfony/mime (v5.3.2 => v5.3.4)\n  - Upgrading symfony/property-access (v5.3.0 => v5.3.4)\n  - Upgrading symfony/property-info (v5.3.1 => v5.3.4)\n  - Upgrading symfony/routing (v4.4.25 => v4.4.27)\n  - Upgrading symfony/var-exporter (v5.3.3 => v5.3.4)\n  - Upgrading typo3/cms-backend (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-belog (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-beuser (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-core (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-extbase (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-extensionmanager (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-filelist (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-fluid (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-fluid-styled-content (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-form (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-frontend (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-info (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-install (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-lowlevel (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-recordlist (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-recycler (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-redirects (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-reports (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-rte-ckeditor (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-scheduler (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-seo (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-setup (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-tstemplate (v10.4.18 => v10.4.19)\n  - Upgrading typo3/cms-viewpage (v10.4.18 => v10.4.19)\n  - Locking typo3/html-sanitizer (v2.0.7)\nWriting lock file\nInstalling dependencies from lock file (including require-dev)\nPackage operations: 232 installs, 0 updates, 0 removals\n  - ...","msg":"exec completed","time":"2021-08-11T10:43:56.485Z","v":0}

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by mbrodala** [comment] 2021-08-11 11:10
OK, this is evidently a known issue https://github.com/renovatebot/renovate/issues/2355 (and many more)

**Comment by viceice** [comment] 2021-08-11 11:43
Duplicate of #2355

**Comment by mbrodala** [comment] 2021-08-11 11:44
OK, I now discovered the Renovate [`composerIgnorePlatformReqs` runner option](https://docs.renovatebot.com/self-hosted-configuration/#composerignoreplatformreqs). I've disabled this using a environment variable in our GitLab CI config now:

```yaml
variables:
  # ...
  RENOVATE_COMPOSER_IGNORE_PLATFORM_REQS: 'false'
```

Now Renovate respects the platform requirements when executing Composer.

**Closed by viceice** 2021-08-11 11:44 UTC
Labels: type:bug, status:requirements, priority-5-triage
