### ISSUE TITLE
Ruby PRs don't have release notes

### ISSUE THREAD

**Issue by Tranquility** [renovatebot/renovate#11323] opened 2021-08-18 10:58 UTC
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Describe the bug

The PRs created for ruby don't contain release notes.
This is how it looks:

![image](https://user-images.githubusercontent.com/161065/129886666-4a1fcab8-1c4d-4b1d-a27b-0bd8d389e2b2.png)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment] 2021-08-18 11:20
Duplicate of #3670

**Closed by rarkins** 2021-08-18 11:20 UTC
Labels: type:bug, status:requirements, priority-5-triage
