### ISSUE TITLE
Dependency break detection for ranges

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#322] opened 2017-06-20 04:20 UTC
For those who like to keep semver *ranges* in their `package.json` (as opposed to pinning versions), is there a need to still test new versions for *breaking*? e.g. if dependency `a` is configured for semver `^1.0.0` and a new version `1.3.0` comes out that still satisfies this range, should we:

-   Create a branch to test it?
-   Warn (e.g. via PR or issue?) that the range is currently "broken"?

And in such a case, what's the preferred solution, assuming that it's dependency's `a` fault? e.g. pin to the last known working version such as `1.2.2` ? Or `1.1 || 1.2` etc?

I had thought for a second that using lock files might avoid this problem, but that would work only temporarily. If dependency `b` is subsequently updated then the existing lock file will be invalidated  and `npm` or `yarn` will attempt to install the latest of everything, including `a` version `1.3.0`. Hence the breaking of `a` will prevent upgrading of all other dependencies until `1.3.0` is retracted or fixed.

**Comment by rarkins** [comment] 2017-06-20 04:20
@hbetts @destroyerofbuilds I think this is relevant to you. Another reason that semver ranges make me uneasy..

**Comment by hbetts** [comment] 2017-06-21 02:41
> is there a need to still test new versions for breaking

Perhaps, or perhaps not.

What I do is run `renovate` in it's _normal_ setup to upgrade major versions of my dependencies (since those are the only upgrades given that I use range versions in `package.json`).

I then run a weekly job using the _maintenance_ feature to upgrade the lock file for all my projects. (I don't want to update my `yarn.lock` file any more than once a week, as that ends up being a ton of commits on my repo that don't serve any value to downstream consumers).

For the _maintenance_ case, `renovate` submits a merge request against my project, and my project's CI job kicks off. It either passes or fails.

If it fails, it could be because an upstream project submitted a breaking change as a minor or patch version. In that situation, I typically pull down the renovate branch and begin isolating the failure.

It's a little bit time consuming, but it works.

Now, `renovate` could create branches on my repository, running `yarn upgrade [PACKAGE]`, to test individual packages for compatibility, and then file an issue if the upgrade fails CI.

The downside of doing that is the noise. Someone submits a bad change, realizes it within a short period of time, and submits a fix. In that time, `renovate` may be filing issues against dozens, or even hundreds, of projects.

**Comment by hbetts** [comment] 2017-06-21 02:47
>  pin to the last known working version such as 1.2.2 ? Or 1.1 || 1.2 etc?

So acting on the CI failure by submitting a pull request that pins the direct dependency in `package.json` is a compelling benefit from the feature you're suggesting. That would be a direct benefit to my down stream consumers. It would also save me from dealing with issues filed against my repository that might be caused by the broken upstream dependency.

Just a side note here, my hope would be that `renovate` could re-test the dependency when it releases a new version, and submit a pull request that brings back the version range (though with a minimum version now matching the release that fixed the build).

**Comment by hbetts** [comment] 2017-06-21 02:50
> npm or yarn will attempt to install the latest of everything

That's definitely an ergonomic issue with both `npm` and `yarn`.

Could `renovate` run `yarn upgrade [PACKAGE]` for every direct dependency marked as outdated by `yarn outdated`? For each upgraded dependency, push to a branch and wait for CI to pass or fail. If it fails, skip that dependency as part of the lockfile update, and file a pull request to pin it to a working version?

**Closed** 2018-10-25 20:46 UTC
Labels: #npm, feat, needs-requirements, pri3-normal
