### ISSUE TITLE
Update target branch in existing PRs if baseBranch changes

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#20799] opened 2023-03-08 03:32 UTC
### What would you like Renovate to be able to do?

Update existing pull request target branches when configuration changes such as those below are made to the repository
- use of / changes to Renovate `baseBranches` configuration
- updating the platform branching model (eg: in Bitbucket via [Bitbucket repository branching model](https://support.atlassian.com/bitbucket-cloud/docs/branch-a-repository/#The-branching-model))
- etc

### If you have any ideas on how this should be implemented, please tell us here.

Ensure that when updating PRs, that the destination/target branch name is always provided

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment] 2023-03-08 05:07
This is not a bug, and it's not specific to Bitbucket Cloud

**Comment by setchy** [comment] 2023-03-08 05:47
> This is not a bug, and it's not specific to Bitbucket Cloud. Please rewrite/relabel accordingly

Apologies.  I've reworded the issue and changes this to a feature request for Bitbucket Cloud.  Please let me know if this is what you had in mind.

**Comment by rarkins** [comment] 2023-03-08 06:05
What I would ideally prefer is to support all platforms at once, so that our behavior is consistent and our documentation can be clear.

We'll need to make a decision on whether to allow bitbucket-cloud only initially and have one or more feature requests outstanding for the rest, or if we should do it all-in-one.

Considering you presumably want this to make it into v35 to accommodate your default development branch PR, the first option may not be viable.

**Comment by rarkins** [comment] 2023-03-08 06:06
I've renamed/relabeled this to be generic for now

**Comment by viceice** [comment] 2023-03-08 06:58
what about hiding this behind a config option, so it's not breaking by default?

i like to get v35 done today or tomorrow to get rid of the node v18 warning and open PR's

**Comment by rarkins** [comment] 2023-03-08 07:20
OK, we push this to v36 along with categories?

**Comment by viceice** [comment] 2023-03-08 21:06
> OK, we push this to v36 along with categories?

yes

**Comment by rarkins** [comment] 2023-03-11 06:59
Duplicate of #19900

**Closed by rarkins** 2023-03-11 06:59 UTC
Labels: type:feature, priority-3-medium, worker:pr, status:in-progress
