### ISSUE TITLE
Support gemfury private packages

### ISSUE THREAD

**Issue by fclairamb** [renovatebot/renovate#7677] opened 2020-11-07 23:57 UTC
I'd like renovate to support gemfury private packages. It might be similar to #4487. 

We're currently in the process of moving from dependabot to renovate on all (a few hundred) of our repositories. This is mostly because renovate is much faster (which is important for internal dependencies) and dependabot sometimes completely misses dependencies. It went pretty smoothly with NPM but we're having issues with pypi on gemfury.

Can you help me find a way to do this?

# The config
I have the following config:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "enabledManagers": [
    "pip_requirements"
  ],
  "python": {
    "registryUrls": [
      "https://pypi.fury.io/<org>/",
      "https://pypi.org/simple/"
    ]
  },
  "hostRules": [
    {
      "platform": "pypi",
      "hostName": "pypi.fury.io",
      "password": "",
      "encrypted": {
        "username": "..."
      }
    }
  ]
}
```

# The issues
## Multiple registries issues
[sample run](https://app.renovatebot.com/dashboard#github/habx/worker-github-helper/257373542)
If this is set:
```json
   "registryUrls": [
      "https://pypi.fury.io/<org>/",
      "https://pypi.org/simple/"
    ]
```

I can see in the logs, it will only look on the standard repository when it should look on both:
```json
          {
            "depName": "lib-service-infra",
            "currentValue": "==1.3.0",
            "datasource": "pypi",
            "fromVersion": "1.3.0",
            "depIndex": 5,
            "updates": [],
            "warnings": [
              {
                "depName": "lib-service-infra",
                "message": "Failed to look up dependency lib-service-infra"
              }
            ],
            "fixedVersion": "1.3.0"
          },
```

And if I only add the private registry, it will only look on that one for all packages including public ones.

## Authentication issue
[sample run](https://app.renovatebot.com/dashboard#github/habx/worker-github-helper/257357352)

Even if I make it select only the private registry like that:
```json
   "registryUrls": [
      "https://pypi.fury.io/<org>/"
    ]
```

It still doesn't work because there's an authentication issue:
```
DEBUG: Failed to look up dependency requests (requests)(packageFile="requirements.txt", dependency="requests")
DEBUG: Datasource unauthorized
{
  "datasource": "pypi",
  "lookupName": "lib-service-infra",
  "url": "https://pypi.fury.io/<org>/lib-service-infra"
}
```

Although the same token does work fine with curl:
```
$ curl -u <token>: https://pypi.fury.io/<org>/ -s |grep lib-service-infra
<a href="https://pypi.fury.io/<org>/lib-service-infra">lib-service-infra</a><br/>
```

**Comment by rarkins** [comment] 2020-11-08 09:33
Duplicate of #6845

Would you mind copying your above info over into the other issue?

**Closed by rarkins** 2020-11-08 09:33 UTC
