### ISSUE TITLE
Downgrade instead of upgrade with eslint-plugin-rxjs

### ISSUE THREAD

**Issue by rassie** [renovatebot/renovate#4854] opened 2019-11-22 15:42 UTC
**What Renovate type are you using?**

Self-hosted with self-hosted Gitlab

**Describe the bug**

Renovate proposes an upgrade for [eslint-plugin-rxjs](https://github.com/cartant/eslint-plugin-rxjs) going from `0.0.1-beta.5` to `0.0.1-beta.3clear` while `beta.5` is obviously higher than `beta.3clear`.

**Comment by rarkins** [comment] 2019-11-22 17:07
Strange. We use npm's `semver` package to do these calculations. Checking their semver page:
![image](https://user-images.githubusercontent.com/6311784/69444029-d1b37d00-0d4f-11ea-9b20-4f6d3b228e08.png)

But also debugging on runkit:

![image](https://user-images.githubusercontent.com/6311784/69444801-65397d80-0d51-11ea-9180-ff0c571cd989.png)

I raised a question in the semver package: https://github.com/npm/node-semver/issues/297

**Comment by JamieMagee** [comment] 2020-02-10 20:24
I'm gonna close this issue. It appears that https://semver.npmjs.com now provides the correct comparison—in line with the npm `semver` package

![Screenshot from 2020-02-10 21-17-58](https://user-images.githubusercontent.com/1358764/74186536-1a8e1a00-4c4b-11ea-9e6b-3ce2098f9ecb.png)

The root cause is the final part of the version is alphanumeric, which has a different meaning in semantic versioning. For right or wrong, this is the behaviour of semantic versioning.

@rassie Please leave a comment if you think this issue should be reopened.

**Closed by JamieMagee** 2020-02-10 20:24 UTC
Labels: #npm, blocked, fix, pri2-important

**Comment by rassie** [comment] 2020-02-10 20:35
No, I think this is indeed done. Thank you for your help!
