### ISSUE TITLE
19.208.0 crash for NPM 

### ISSUE THREAD

**Issue by thib3113** [renovatebot/renovate#5964] opened 2020-04-14 10:31 UTC
**What Renovate type are you using?**
19.208.0

Hosted, run by gitlab Ci, with the docker image .
with command :
`docker pull -q renovate/renovate:latest && docker run -e RENOVATE_TOKEN="$RENOVABOT_GITLAB_TOKEN" -e "RENOVATE_PLATFORM=gitlab" -e GITHUB_COM_TOKEN="$RENOVABOT_GITHUB_TOKEN" -v $PWD/renovate.js:/usr/src/app/config.js $(cat repositories.txt)`
each two hours (last time run with 19.207 and works)

**Describe the bug**

A long stacktrace : 
```
 INFO: Repository started (repository=citopia/grc360/API)
       "renovateVersion": "19.208.0"
 INFO: Extraction statistics (repository=citopia/grc360/API)
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 1, "depCount": 1},
           "gitlabci": {"fileCount": 1, "depCount": 1},
           "npm": {"fileCount": 2, "depCount": 148}
         },
         "fileCount": 4,
         "depCount": 150
       }
ERROR: Error updating branch: Cannot read property 'npm' of undefined (repository=citopia/grc360/API, branch=renovate/sendgrid-mail-6.x)
       "err": {
         "message": "Cannot read property 'npm' of undefined",
         "stack": "TypeError: Cannot read property 'npm' of undefined\n    at Object.getAdditionalFiles (/usr/src/app/dist/manager/npm/post-update/index.js:302:24)\n    at Object.processBranch (/usr/src/app/dist/workers/branch/index.js:239:53)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.writeUpdates (/usr/src/app/dist/workers/repository/process/write.js:23:21)\n    at async Object.update (/usr/src/app/dist/workers/repository/process/extract-update.js:26:15)\n    at async Object.renovateRepository (/usr/src/app/dist/workers/repository/index.js:38:25)\n    at async Object.start (/usr/src/app/dist/workers/global/index.js:81:13)\n    at async /usr/src/app/dist/renovate.js:16:24"
       }
```
And repeat same message multiples times ( maybe because I have multiples package.json )

did you need more information ? or the stacktrace is enough ?

**Comment by rarkins** [comment] 2020-04-14 10:53
Can you confirm which version of Renovate does not contain the problem? e.g. 19.207.1?

**Comment by rarkins** [comment] 2020-04-14 10:58
This should be fixed by https://github.com/renovatebot/renovate/commit/c9071a7e5457b26fc6c3e05c37f3ad269675962b

(it's awaiting automated release still though)

**Closed by rarkins** 2020-04-14 10:58 UTC
Labels: needs-reproduction

**Comment by thib3113** [comment] 2020-04-14 11:32
Yes last working version was        "renovateVersion": "19.207.1"

Thanks you for the fix, I will try on the next schedules (or after if automated process not ended)

**Comment by rarkins** [comment] 2020-04-14 11:34
Included in release 19.208.1: https://github.com/renovatebot/renovate/releases/tag/19.208.1

**Comment by rarkins** [comment] 2020-04-14 12:20
@thib3113 FYI we've been unable to reproduce this, so there's the possibility the same or similar problem could be introduced again in future. Would be able to save a full DEBUG log and/or reproduce the problem in a public repo?

**Comment by YuraBeznos** [comment] 2020-04-14 16:25
Reproduction of this is in using `baseBranches` config parameter.
