### ISSUE TITLE
[sbt] When a common variable is used for multiple dependencies, several PR are opened

### ISSUE THREAD

**Issue by gaeljw** [renovatebot/renovate#13929] opened 2022-01-31 17:23 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.38.4

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

13.6.2

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In sbt project, consider the following _build.sbt_ file:

```scala
val kafkaVersion = "3.0.0"

libraryDependencies ++= Seq(
  "org.apache.kafka" % "kafka-clients" % kafkaVersion,
  "io.github.embeddedkafka" %% "embedded-kafka" % kafkaVersion % Test
)
```

When Renovate runs, it opens two distinct PR for each dependency:
- _chore(deps): update dependency io.github.embeddedkafka:embedded-kafka to v3.1.0_
- _chore(deps): update dependency org.apache.kafka:kafka-clients to v3.1.0_

I would expect Renovate to group all dependencies related to same variable in a single PR. I believe that's what happens with Maven for instance?

A drawback of the current mechanism is that if we setup automerge for dependencies with `"matchDepTypes": ["Test"]` (only test scoped dependencies), as the same variable is used for both a test dependency and a non test dependency, both PRs are automerged which is not desired at all.

### Have you created a minimal reproduction repository?

https://github.com/gaeljw/renovate1799/pulls

**Comment by gaeljw** [comment] 2022-01-31 17:25
My memory is failing.. I already opened such a bug some time ago which was fixed but look's like it's not anymore: https://github.com/renovatebot/renovate/issues/6706

**Comment by rarkins** [comment] 2022-02-01 07:57
Let's have a reproduction and make sure we add a test case for any next fix

**Comment by gaeljw** [comment] 2022-02-01 18:29
Sure, here is a reproduction project with minimal `build.sbt` and the 2 PRs created by Renovate: https://github.com/gaeljw/renovate1799/pulls

**Comment by StinkyLord** [comment] 2022-02-14 12:46
@rarkins please assign to me

**Comment by PhilipAbed** [comment] 2022-02-17 08:25
@rarkins please assign to me

**Comment by PhilipAbed** [comment] 2022-02-17 11:47
@gaeljw i checked https://github.com/renovatebot/renovate/issues/6706, it appears we aggregate by `group` name,
and in that task we had :
`libraryDependencies ++= Seq(
  "io.cucumber" %% "cucumber-scala" % cucumberVersion % Test,
  "io.cucumber" % "cucumber-junit" % cucumberVersion % Test,
  "io.cucumber" % "cucumber-picocontainer" % cucumberVersion % Test
)`

all of them have the same group `io.cucumber`

**Comment by PhilipAbed** [comment] 2022-02-17 14:34
@gaeljw 
Currently the code checks the lines and parses the lines according to some regex, 
if we want to aggregate the lines i will have to do big changes to the way we parse the file.
hopefully not breaking anything on the way.

Then we will have an open issue like you said and i'm quoting:
 `A drawback of the current mechanism is that if we setup automerge for dependencies with "matchDepTypes": ["Test"] (only test scoped dependencies), as the same variable is used for both a test dependency and a non test dependency, both PRs are automerged which is not desired at all.`
 
so i'm not sure how to continue with this 100%, this could be problematic in case of two scopes in the same variable.

**Comment by gaeljw** [comment] 2022-02-17 17:19
> Currently the code checks the lines and parses the lines according to some regex,
> if we want to aggregate the lines i will have to do big changes to the way we parse the file.
> hopefully not breaking anything on the way.

Yeah, I was guessing this would not be easy.

I didn't check but maybe there's something we do for Maven build properties (`<properties><xxx>1.0.0</xxx></properties>`) that could be reused for sbt? Or maybe there's the same issue for Maven actually.

> so i'm not sure how to continue with this 100%, this could be problematic in case of two scopes in the same variable.

Regarding the automerge drawback, it's already current behavior. If there was only 1 PR containing change for several dependencies with different scopes, IMHO all the dependencies scopes should match the defined `matchDepTypes`: if at least one dependency has a scope that is not in the `matchDepTypes` list, then automerge should not be possible.

**Comment by PhilipAbed** [comment] 2022-02-20 08:33
@gaeljw no, the current behavior checks every dependency line alone, and extracts every scope from each line and adds it as information on the dependency, but doesn't check for variables.
adding Variables is like adding another hierarchy above it that holds the dependencies

@rarkins please advise, should i implement this change? making PRs for each Variable? what should be the logic?

**Comment by rarkins** [comment] 2022-02-20 08:35
I think it may be best to leave for @zharinov who authored the parser and has done similar things before. However, it's not high priority if there's a simple workaround of creating groups manually through config.

**Comment by gaeljw** [comment] 2022-02-20 11:30
@PhilipAbed I meant current behaviour regarding automerge. Today there are 2 PRs, one for each scope. One will be automerged because the scope match, the other not _but_ as the 1st merge actually updates the shared variable it's the same as if the 2nd PR was merged (2nd PR will actually be auto closed right after).

**Comment by gaeljw** [comment] 2022-02-20 11:30
To be fair, this is clearly not a massive issue for me and I understand it's really not easy to fix.

**Comment by PhilipAbed** [comment] 2022-02-20 11:49
I think its possible but it's that i dont know how to continue since there's no clear requirement of how i should proceed from product point of view, 
what logic should i follow?
Open PR for every Variable or for every scope (like now) 
or what's should i do in case i have the same variable with more than 1 scope?

**Comment by viceice** [comment] 2022-02-20 12:12
I think using one variable in multiple scopes is a config error.

**Comment by gaeljw** [comment] 2022-02-20 12:15
I would group dependencies by variable first if any, then for remaining dependencies group by the "group name".

I expect people that use variable to use it everywhere it makes sense, thus no need to mix the two grouping strategies for a single dependency.

Scope shouldn't matter for the grouping, does it? 🤔

For instance, given the following:
```scala
val sharedVersion = "1.0.0"

libraryDependencies += "groupA" % "artifact1" % sharedVersion
libraryDependencies += "groupB" % "artifact2" % sharedVersion
libraryDependencies += "groupC" % "artifact3" % "x.y.z"
libraryDependencies += "groupC" % "artifact4" % "x.y.z"
libraryDependencies += "groupD" % "artifact5" % "a.b.c"
```

I would expect 3 PRs with:
- artifact1 and artifact2 (because shared variable)
- artifact2 and artifact4 (because group name)
- artifact5 (no grouping)

(I would do the same if groupB is same as groupA because it's unlikely that one would use variable only for a part of the dependencies.)

**Comment by gaeljw** [comment] 2022-02-20 12:17
> I think using one variable in multiple scopes is a config error.

On the contrary, it's fairly common. Having a library that provides a core dependency for runtime and another dependency with helpers for testing purposes.

**Comment by PhilipAbed** [comment] 2022-02-20 15:06
I thought u have 1 variable called LibraryDependencies that has 2 dependenices with scopes
now you are saying that you wan to check if there are any connection to any variable, that is not doable,
i cant differentiate if the version is actually a version or a variable.
to do that i will need to parse every variable i have, put it in a map and check everything against it. 
now lets say i did that, what would u do if u had the same group on 2 dependenices but one of them had a shared version with a 3rd dependency? 
what if they were in 2 different scopes like in the example above?
this task cant be done like this

**Comment by gaeljw** [comment] 2022-02-20 18:30
> I thought u have 1 variable called LibraryDependencies that has 2 dependenices with scopes
Nope, sorry if this was not clear, `libraryDependencies` is a reserved variable of SBT in which we append the dependencies.

> i cant differentiate if the version is actually a version or a variable.
I believe it's already done because Renovate correctly detects variables and suggest upgrades on the variable. But maybe this is not part of the same code/process.

> now lets say i did that, what would u do if u had the same group on 2 dependenices but one of them had a shared version with a 3rd dependency?
First group dependencies by shared variable no matter the group name. Then for all others dependencies not using shared variable, group by the group name.

 > what if they were in 2 different scopes like in the example above?
Again I don't think scope is relevant for grouping. Renovate PRs can already include dependencies with different scopes.

I totally understand if this can't be done. I'll give a look to the code to see if I can grasp an idea of how it works and maybe suggest another approach to solve the issue.

**Comment by PhilipAbed** [comment] 2022-02-21 07:25
Thanks, now the requirement is clear, let me check it out

**Comment by PhilipAbed** [comment] 2022-02-21 09:26
@gaeljw 
please check this test:
https://github.com/StinkyLord/renovate1799/pull/1
is that what you are looking for?

i changed the
`  if (variables[rawVersion]) {
    result.groupName = `${rawVersion} for ${groupId}`;
  }`

to 
```
  if (variables[rawVersion]) {
    result.groupName = `${rawVersion}`;
  }
```

i noticed that it was group +variable needed to do this, 
i tried making it only with variable, regardless of group, but not sure if that breaks anything 
@zharinov @rarkins  does that result.groupName break anything if i change it?

**Comment by gaeljw** [comment] 2022-02-21 11:44
> https://github.com/StinkyLord/renovate1799/pull/1
> is that what you are looking for?

Definitely look's good :+1:

**Comment by PhilipAbed** [comment] 2022-02-21 12:26
ok ill open a PR, this task should be re-assigned to me then, i removed assignment xD

**Comment by PhilipAbed** [comment] 2022-02-21 12:32
i still want an agreement from the maintainers on this, it was agreed by you @gaeljw that we should group by the group id :D 
now it will be grouped by the variable only. regardless of the group id. its either both or this according to what i see in code..
see conversation:
![image](https://user-images.githubusercontent.com/42116482/154955846-ad124052-a912-4f0c-8b4e-a2313b081e1c.png)

**Comment by gaeljw** [comment] 2022-02-21 17:55
Not sure to understand: grouping by the `groupId` still makes sense for dependencies that do not use a variable for the version. 

But as soon as variable is used for a dependency, we shouldn't care about the groupId of this dependency.

I can provide an example repo with both kind to ensure behaviour is correct if you want.

**Comment by PhilipAbed** [comment] 2022-02-22 09:04
@gaeljw yeah, as far as i can see the variable only worked with groupId, now it works alone, 
regardless, if there's no variable, the groupid will be the thing that groups the PRs

**Closed** 2022-02-28 18:01 UTC
Labels: type:bug, priority-3-normal, manager:sbt, status:ready, reproduction:provided
