### ISSUE TITLE
Renovate create the pull request too early when there are a lot of packages sharing the same version

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [renovatebot/renovate#12133] opened 2021-10-12 17:01 UTC
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

In [Gradle Plugins repo](https://github.com/JavierSegoviaCordoba/gradle-plugins), I have like 10-20 projects sharing the same version, but Renovate is not waiting until all projects are available in the remote repositories to create the PR.

As this PR is created too early, it fails because some of the packages are available with the new version, but others are only available with the older version until the next 5-15 minutes. So I have to rerun the GitHub workflow manually or select the PR to be rebased.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by HonkingGoose** [comment] 2021-11-10 17:54
We have another open issue [^issue-1] that's about "waiting until all dependencies in a group have new versions before opening/merging PR". It sounds similar in concept:

> The use case here is that you still want fast updates, but you don't want to open a PR for a group until some required deps have new versions, ensuring they are always updated together.

I also found a issue that wants to "force same versions inside package group", which also sounds related. [^issue-2]

I don't know which issues we want to keep/close.

I'll let @rarkins decide what to do with each issue. 😉 

[^issue-1]: https://github.com/renovatebot/renovate/issues/9739
[^issue-2]: https://github.com/renovatebot/renovate/issues/12310

**Comment by rarkins** [comment] 2021-11-10 20:15
Duplicate of #12310

**Closed by rarkins** 2021-11-10 20:15 UTC
Labels: type:bug, status:requirements, priority-5-triage
