### ISSUE TITLE
Some PRs listed on Dependency Dashboard are not linked to individual PRs when more than 1000 PRs old

### ISSUE THREAD

**Issue by blowery** [renovatebot/renovate#4803] opened 2019-11-12 10:41 UTC
**What Renovate type are you using?**

App, Github

**Describe the bug**

See https://github.com/Automattic/wp-calypso/issues/37419
Some renovate updates there are not linked to the individual PRs. It would be nice if they were all linked.

**Did you see anything helpful in debug logs?**

Nope

**To Reproduce**

See https://github.com/Automattic/wp-calypso/issues/37419

**Additional context**

**Comment by rarkins** [comment] 2019-11-12 14:24
First check: are all the unlinked ones actually opened? Or perhaps are they mistakenly listed as opened when they're not?

**Comment by blowery** [comment] 2019-11-13 11:08
Some are for sure. For instance https://github.com/Automattic/wp-calypso/pull/35623 is listed on the master issue, but not linked. Also https://github.com/Automattic/wp-calypso/pull/34935

**Comment by rarkins** [comment] 2019-12-11 09:40
Screenshot:
![image](https://user-images.githubusercontent.com/6311784/70609785-11f97300-1c0b-11ea-8651-296808ee0dd5.png)

**Comment by rarkins** [comment] 2019-12-11 09:51
Up to date master issue link: https://github.com/Automattic/wp-calypso/issues/37527

Screenshot of master issue open issues (some are unliked):
![image](https://user-images.githubusercontent.com/6311784/70610527-66512280-1c0c-11ea-87e4-9c96e11dd336.png)

Screenshot of actual open issues:
![image](https://user-images.githubusercontent.com/6311784/70610585-81239700-1c0c-11ea-8c4f-e920e5f8701c.png)

**Comment by rarkins** [comment] 2019-12-11 09:54
I don't think it's a coincidence that the unlinked ones are the oldest ones. I'm guessing it's because we don't fetch *every* PR, and this repository has a really high number of PRs.

**Comment by rarkins** [comment] 2019-12-11 11:08
Confirmed, we fetch only 1000 PRs:

```
{"level":20,"msg":"Retrieving PR list","time":"2019-12-11T09:02:58.885Z"}
{"level":20,"msg":"Retrieved 1000 Pull Requests","time":"2019-12-11T09:03:11.304Z"}
```

Unfortunately I can't fix this without first refactoring how we fetch PRs, which is a little bit of technical debt I've been meaning to get to. I'll leave this open for addressing afterwards.

**Comment by blowery** [comment] 2019-12-11 19:22
Thanks for looking into this!

**Comment by HonkingGoose** [comment] 2021-06-13 07:05
@rarkins can you change the title of the issue? We no longer use the term `master issue`, we now use `dependency dashboard`. I've added the `core:dashboard` label.

**Comment by MaronHatoum** [comment] 2022-05-01 10:08
This should be resolved in Renovate release 25.37.1 (issue: https://github.com/renovatebot/renovate/issues/5668)
@rarkins FYI

**Comment by rarkins** [comment] 2022-05-01 12:19
@MaronHatoum are you sure? I thought we limit our fetch to 1000 PRs, so not sure how we would otherwise find them?

**Comment by MaronHatoum** [comment] 2022-05-01 14:41
After checking the code I don't see any limitation and getting PRs from GitHub has been refactored recently,
is there another place where there is a limitation?

**Comment by rarkins** [comment] 2022-05-01 16:13
Our pagination defaults to 10 pages by default and I think it's used for PRs too

**Comment by MaronHatoum** [comment] 2022-05-02 11:24
hi @rarkins 
the code was refactored it calls an unlimited number of pages and gets 20 PR per page.
it is a `while` loop I don't see any restriction to 10 pages at all.

**Comment by MaronHatoum** [comment] 2022-05-02 11:38
https://github.com/renovatebot/renovate/blob/ae9714a3795cda1ab3edb90fe6f2ffca13137ca9/lib/modules/platform/github/pr.ts#L93-L107

This is the refactored code and it is using the new `HTTP`(GOT) request instead of the old `github.ts` request and I don't see any limitation in the new request.

I can see the pagination limitation in the old `github.ts` request but the `github/pr.ts` is not calling it anymore.

**Comment by rarkins** [comment] 2022-05-02 13:15
It should fetch 20 per page only until a date is hit. Otherwise if the cache is empty it uses `opts.paginate=true` which is passed to the HTTP layer and limits to 10 pages.

@zharinov please confirm. Also can you check that we're still fetching 100 per page when the cache is missing?

**Closed** 2023-04-21 06:20 UTC
Labels: type:bug, priority-3-medium, status:ready, core:dashboard
