### ISSUE TITLE
Dependency Dashboard creation sometimes marked as spam in Gitlab and blocks renovate execution

### ISSUE THREAD

**Issue by jpolo** [renovatebot/renovate#8045] opened 2020-12-16 10:08 UTC
**What Renovate type, platform and version are you using?**

Platform : Gitlab
Self hosted using Scheduling + Docker on a Mac mini
(Scheduling hourly)

**Describe the bug**

1. When running the scheduled job, the dependency dashboard is not created because marked as spam.
=> It is not always reproducible, on some repository it passes, sometimes not. Could it be caused by a renovate behavior, identified as spam ?

2. When the dependency dashboard creation fails, the full execution is blocked. If I refer to the documentation, "Enabling the Dependency Dashboard does not itself change any of the "control flow". Then maybe if the creation fails, the error should be handled as a warning and the execution should continue using a fallback  dependencyDashboard=false behavior ?

**Relevant debug logs**
```console
[0KRunning with gitlab-runner 13.0.1 (21cb397c)
[0;m[0K  on docker-developer-macmini wchq7Qdz
[0;msection_start:1608109579:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m
[0;m[0KUsing Docker executor with image renovate/renovate ...
[0;m[0KPulling docker image renovate/renovate ...
[0;m[0KUsing docker image sha256:df9c9934c4bfec2246482c388693f187103e7aaa6343c87e0ac58ab099b1d4eb for renovate/renovate ...
[0;msection_end:1608109590:prepare_executor
[0Ksection_start:1608109590:prepare_script
[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-wchq7qdz-project-14630336-concurrent-0 via b504bda08ad7...
section_end:1608109598:prepare_script
[0Ksection_start:1608109598:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m
[0;m[32;1mFetching changes with git depth set to 5...[0;m
Reinitialized existing Git repository in /builds/koober-sas/plop-plugins/.git/
From https://gitlab.com/koober-sas/plop-plugins
 * [new ref]         refs/pipelines/230586525 -> refs/pipelines/230586525
[32;1mChecking out 62291639 as master...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1608109606:get_sources
[0Ksection_start:1608109606:restore_cache
[0K[0K[36;1mRestoring cache[0;m
[0;msection_end:1608109611:restore_cache
[0Ksection_start:1608109611:download_artifacts
[0K[0K[36;1mDownloading artifacts[0;m
[0;msection_end:1608109616:download_artifacts
[0Ksection_start:1608109616:build_script
[0K[0K[36;1mRunning before_script and script[0;m
[0;m[32;1m$ node /usr/src/app/dist/renovate.js --platform "gitlab" --endpoint "${CI_API_V4_URL}" --git-author "${RENOVATE_GIT_AUTHOR}" --dry-run "${RENOVATE_DRY_RUN}" --log-level "${RENOVATE_LOG_LEVEL}" "${CI_PROJECT_PATH}"[0;m
 WARN: Deprecated! Please use global 'renovate' command.
 INFO: Repository started (repository=koober-sas/plop-plugins)
       "renovateVersion": "24.4.0"
 INFO: Dependency extraction complete (repository=koober-sas/plop-plugins)
       "baseBranch": "master",
       "stats": {
         "managers": {"npm": {"fileCount": 4, "depCount": 46}},
         "total": {"fileCount": 4, "depCount": 46}
       }
 WARN: Could not ensure issue (repository=koober-sas/plop-plugins)
       "err": {
         "name": "HTTPError",
         "timings": {
           "start": 1608109664265,
           "socket": 1608109664268,
           "lookup": 1608109664269,
           "connect": 1608109664273,
           "secureConnect": 1608109664278,
           "upload": 1608109664279,
           "response": 1608109664706,
           "end": 1608109664708,
           "phases": {
             "wait": 3,
             "dns": 1,
             "tcp": 4,
             "tls": 5,
             "request": 1,
             "firstByte": 427,
             "download": 2,
             "total": 443
           }
         },
         "message": "Response code 400 (Bad Request)",
         "stack": "HTTPError: Response code 400 (Bad Request)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
         "options": {
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept-encoding": "gzip, deflate",
             "private-token": "**redacted**",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "1678"
           },
           "url": "https://gitlab.com/api/v4/projects/koober-sas%2Fplop-plugins/issues",
           "username": "",
           "password": "",
           "method": "POST",
           "http2": false
         },
         "response": {
           "statusCode": 400,
           "statusMessage": "Bad Request",
           "body": {
             "message": {
               "base": [
                 "Your issue has been recognized as spam. Please, change the content or solve the reCAPTCHA to proceed."
               ]
             }
           },
           "headers": {
             "date": "Wed, 16 Dec 2020 09:07:44 GMT",
             "content-type": "application/json",
             "content-length": "126",
             "connection": "close",
             "set-cookie": [
               "__cfduid=de7860176f65200d36cb1158d8265089f1608109664; expires=Fri, 15-Jan-21 09:07:44 GMT; path=/; domain=.gitlab.com; HttpOnly; SameSite=Lax; Secure"
             ],
             "cache-control": "no-cache",
             "vary": "Origin",
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "x-gitlab-feature-category": "issue_tracking",
             "x-request-id": "01ESNCWA33Q4Y6355EQVQ1T2WQ",
             "x-runtime": "0.282293",
             "ratelimit-limit": "600",
             "ratelimit-observed": "89",
             "ratelimit-remaining": "512",
             "ratelimit-reset": "1608109724",
             "ratelimit-resettime": "Wed, 16 Dec 2020 09:08:44 GMT",
             "gitlab-lb": "fe-06-lb-gprd",
             "gitlab-sv": "localhost",
             "cf-cache-status": "DYNAMIC",
             "cf-request-id": "070c67400a000032b8b32b2000000001",
             "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
             "server": "cloudflare",
             "cf-ray": "60274179abf832b8-CDG"
           },
           "httpVersion": "1.1"
         }
       }
 INFO: Repository finished (repository=koober-sas/plop-plugins)
       "durationMs": 39478
section_end:1608109665:build_script
[0Ksection_start:1608109665:after_script
[0K[0K[36;1mRunning after_script[0;m
[0;msection_end:1608109668:after_script
[0Ksection_start:1608109668:archive_cache
[0K[0K[36;1mSaving cache[0;m
[0;msection_end:1608109673:archive_cache
[0Ksection_start:1608109673:upload_artifacts_on_success
[0K[0K[36;1mUploading artifacts for successful job[0;m
[0;msection_end:1608109680:upload_artifacts_on_success
[0K[32;1mJob succeeded
[0;m
```

**To Reproduce**

Reproducible in this repository : https://gitlab.com/koober-sas/react-native-markup-view for example

**Additional context**

**Comment by rarkins** [comment] 2020-12-16 10:37
> 1. When running the scheduled job, the dependency dashboard is not created because marked as spam.
>    => It is not always reproducible, on some repository it passes, sometimes not. Could it be caused by a renovate behavior, identified as spam ?

The issue is not spam and you should report it to GitLab as a mistake.

> 2. When the dependency dashboard creation fails, the full execution is blocked. If I refer to the documentation, "Enabling the Dependency Dashboard does not itself change any of the "control flow". Then maybe if the creation fails, the error should be handled as a warning and the execution should continue using a fallback  dependencyDashboard=false behavior ?

Please capture this happening with DEBUG level logs if you think the execution is blocked, because I don't see why that would happen if looking at the code itself: https://github.com/renovatebot/renovate/blob/031823197b02f67d901ed971f969de2eb9283249/lib/workers/repository/dependency-dashboard.ts#L246-L250

**Comment by rarkins** [comment] 2021-01-12 10:19
Closing due to lack of logs

**Closed by rarkins** 2021-01-12 10:19 UTC
Labels: platform:gitlab
