### ISSUE TITLE
Expose some hooks

### ISSUE THREAD

**Issue by Weakky** [renovatebot/renovate#2992] opened 2018-12-21 18:48 UTC
Hey there,

**What would you like Renovate to be able to do?**

We have some code generation tool that needs to be run when `renovate` merges a PR.

**Describe the solution you'd like**

Having access to some hooks would solve our problem !

**Additional context**

Here's the repo if needed for some tests: https://github.com/prisma/nexus-prisma

Thanks 🙌

**Comment by rarkins** [comment] 2018-12-21 18:51
To test out this feature, I would explicitly "white list" commands until I'm sure I have the sandboxing down and nobody's mining cryptocurrency or whatever. What exactly do you need to run once dependencies are updated?

**Comment by Weakky** [comment] 2018-12-21 18:59
A simple script I guess. `nexus-prisma` creates a binary called `nexus-codegen`. All we'd need is to run a script that would do `yarn nexus-codegen` and then push it to the repo

**Comment by rarkins** [comment] 2018-12-21 19:17
How do you do it currently? I don't see any scripts like that already in the repo.

**Comment by rarkins** [comment] 2018-12-22 16:38
I'm going to close this as a duplicate of #838 as it would be the same solution. Will add this use case there.

**Closed by rarkins** 2018-12-22 16:38 UTC
Labels: feat, needs-requirements, pri3-normal
