### ISSUE TITLE
[Gradle] Unable to determine develop version as git describe did not return expected value

### ISSUE THREAD

**Issue by LeJeanbono** [renovatebot/renovate#4754] opened 2019-10-31 12:42 UTC
**What Renovate type are you using?**
hosted App with GitLab

**Describe the bug**

My project `datawarehouse` have 2 modules (`api` and `e2e`) configured in `settings.gradle` : 
`include 'api'
include 'e2e-test'`
I don't know if it's a git configuration problem or a project structure one.

**Did you see anything helpful in debug logs?**
```
WARN: Gradle command docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate failed. Exit code: 1.
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate",
    "stdout": "To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n\n> Configure project :\n\nDeprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.\nUse '--warning-mode all' to show the individual deprecation warnings.\nSee https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings\n",
    "stderr": "Compliance error - Unable to determine develop version as git describe did not return expected value\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring root project 'api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 47s\n",
    "message": "Command failed: docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate\nCompliance error - Unable to determine develop version as git describe did not return expected value\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring root project 'api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 47s\n",
    "stack": "Error: Command failed: docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate\nCompliance error - Unable to determine develop version as git describe did not return expected value\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring root project 'api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 47s\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  }
}
INFO: Aborting Renovate due to Gradle lookup errors
```

**Comment by rarkins** [comment] 2019-12-11 11:17
@LeJeanbono are you able to reproduce this in a public GitHub or GitLab repository?

**Comment by LeJeanbono** [comment] 2020-02-25 11:13
The command passed this morning : 
`DEBUG: Start gradle command
{
  "cmd": "gradle --init-script renovate-plugin.gradle renovate"
}
DEBUG: Using docker to execute
DEBUG: exec completed
{
  "cmd": "docker run --rm -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse/api\" renovate/gradle bash -l -c \"gradle --init-script renovate-plugin.gradle renovate\"",
  "seconds": 59,
  "stdout": "To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n> Task :api:renovate\n\nBUILD SUCCESSFUL in 56s\n1 actionable task: 1 executed\n",
  "stderr": ""
}
DEBUG: To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html. Daemon will be stopped at the end of the build stopping after processing Configuration on demand is an incubating feature. > Task :api:renovate BUILD SUCCESSFUL in 56s 1 actionable task: 1 executed
DEBUG: Gradle report complete
DEBUG: Found gradle package files
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Matched 1 file(s) for manager gradle-wrapper: gradle/wrapper/gradle-wrapper.properties
DEBUG: gradle-wrapper.extractPackageFile()`
Then failed just after...

**Comment by viceice** [comment] 2020-02-25 11:29
@LeJeanbono No warn or error message?

@rarkins  Can the first error be an old git version?

**Comment by rarkins** [comment] 2020-02-25 11:34
Possibly. @LeJeanbono when you say it passed, I assume you also mean it *worked* and extracted the expected dependencies?

Also can you tell us the two job IDs - working and not-working?

**Comment by LeJeanbono** [comment] 2020-02-25 12:08
Ko : https://app.renovatebot.com/dashboard#gitlab/csuite/datawarehouse/145354480
Work : https://app.renovatebot.com/dashboard#gitlab/csuite/datawarehouse/145339348
Ko : https://app.renovatebot.com/dashboard#gitlab/csuite/datawarehouse/145316250
On the working one, I see `"seconds": 59` => Maybe a timeout at 60 ?

**Comment by LeJeanbono** [comment] 2020-02-25 12:09
@viceice You've got the warn in my first message, no errors.
git version 2.17.1

**Comment by viceice** [comment] 2020-02-25 13:03
We have a timeout! @rarkins What is the default timeout for the app?



https://github.com/renovatebot/renovate/blob/ecd981bf6403723868f37d96b380a8fcdde864a2/lib/manager/gradle/index.ts#L178-L181

**Comment by rarkins** [comment] 2020-02-25 13:04
The app doesn't change any of the timeouts. Does that mean it's taking more than 10 minutes to simply extract the dependencies?

**Comment by viceice** [comment] 2020-02-25 13:05
can you look at the logs? here are no time stamps

**Comment by LeJeanbono** [comment] 2020-02-25 13:26
Can you give me the git describe command please?
Is there other tasks during the init script ?

**Comment by rarkins** [comment] 2020-02-25 14:46
Here's timestamped logs of a failure:

```
{"level":20,"msg":"Matched 3 file(s) for manager gradle: api/build.gradle, e2e-test/build.gradle, settings.gradle","time":"2020-02-25T12:58:35.755Z"}
{"level":20,"msg":"Extracting dependencies from all gradle files","time":"2020-02-25T12:58:35.756Z"}
{"level":20,"msg":"Creating renovate-plugin.gradle file with renovate gradle plugin","time":"2020-02-25T12:58:35.756Z"}
{"level":20,"cmd":"gradle --init-script renovate-plugin.gradle renovate","msg":"Start gradle command","time":"2020-02-25T12:58:35.757Z"}
{"level":20,"msg":"Using docker to execute","time":"2020-02-25T12:58:35.757Z"}
{"level":40,"errMessage":"Command failed: docker run --rm -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse/api\" renovate/gradle bash -l -c \"gradle --init-script renovate-plugin.gradle renovate\"\nCompliance error - Unable to determine develop version as git describe did not return expected value\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring project ':api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 1m 5s\n","msg":"Gradle extraction failed","time":"2020-02-25T12:59:44.856Z"}
```

The timestamp indicates that it failed about 69 seconds after the previous log message, so doesn't appear to be timer-related.

Here's the timestamped logs of a (very rare) success:

```
{"level":20,"msg":"Matched 3 file(s) for manager gradle: api/build.gradle, e2e-test/build.gradle, settings.gradle","time":"2020-02-25T09:48:36.856Z"}
{"level":20,"msg":"Extracting dependencies from all gradle files","time":"2020-02-25T09:48:36.856Z"}
{"level":20,"msg":"Creating renovate-plugin.gradle file with renovate gradle plugin","time":"2020-02-25T09:48:36.856Z"}
{"level":20,"cmd":"gradle --init-script renovate-plugin.gradle renovate","msg":"Start gradle command","time":"2020-02-25T09:48:36.857Z"}
{"level":20,"msg":"Using docker to execute","time":"2020-02-25T09:48:36.858Z"}
{"level":20,"cmd":"docker run --rm -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse/api\" renovate/gradle bash -l -c \"gradle --init-script renovate-plugin.gradle renovate\"","seconds":59,"stdout":"To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n> Task :api:renovate\n\nBUILD SUCCESSFUL in 56s\n1 actionable task: 1 executed\n","stderr":"","msg":"exec completed","time":"2020-02-25T09:49:35.717Z"}
{"level":20,"msg":"To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n> Task :api:renovate\n\nBUILD SUCCESSFUL in 56s\n1 actionable task: 1 executed\n","time":"2020-02-25T09:49:35.718Z"}
{"level":20,"msg":"Gradle report complete","time":"2020-02-25T09:49:35.718Z"}
```

I can confirm it found a lot of deps and updates in those three files.

**Comment by viceice** [comment] 2020-02-25 16:07
@LeJeanbono We do not call git directly, we simply call out gradle plugin:
https://github.com/renovatebot/renovate/blob/ecd981bf6403723868f37d96b380a8fcdde864a2/lib/manager/gradle/gradle-updates-report.ts#L35-L68

Can you try to run that manually? or provide a minimal public repo to reproduce the issue.
Maybe one of your gradle plugins are the issue here.

**Comment by rarkins** [comment] 2020-02-25 16:15
I tried Google searching for the log message in the failures and pretty much only find this issue

**Comment by viceice** [comment] 2020-02-25 16:19
Tried that too, nothig found 😅

**Comment by LeJeanbono** [comment] 2020-03-24 08:33
No more problem with Git at this moment, did nothing...
A new one with Gradle :
`WARN: Gradle extraction failed`
`{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse/api\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\nError: Could not find or load main class org.gradle.wrapper.GradleWrapperMain\nCaused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain\n"
}`

I regenerated gradle wrapper (Gradle v6.0.1) but same error
Job : https://app.renovatebot.com/dashboard#gitlab/csuite/datawarehouse/155946182
Any clues @rarkins @viceice .
Thanks ! :)

**Comment by viceice** [comment] 2020-03-24 08:44
🤔  Does graddle wrapper work locally after `git clean -fdx` ?

**Comment by viceice** [comment] 2020-03-24 09:04
Which java version do you use locally? out docker image uses java11 (default jre on ubuntu 18.04)

**Comment by LeJeanbono** [comment] 2020-03-24 09:12
`openjdk 11.0.6 2020-01-14`
`OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)`
`OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)`

`git clean -fdx` => Remove my `.gradle` folder and so the `gradle-wrapper`

**Comment by LeJeanbono** [comment] 2020-03-24 09:13
Got `/.gradle/` in my '.gitignore'

**Comment by viceice** [comment] 2020-03-24 09:15
ok, did you commit `/gradle/wrapper` directory? it's required if you have the `/gradlew` and `/gradlew.bat` files in repo root

**Comment by LeJeanbono** [comment] 2020-03-24 09:18
Yep, I've got `/gradle/wrapper` and `/gradlew` in the repo

**Comment by LeJeanbono** [comment] 2020-03-24 09:23
Properties :
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by viceice** [comment] 2020-03-24 09:26
Oh, I've goot a warning too

```
WARN: Gradle extraction failed (repository=org/repo)
        "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/tmp/renovate/repos/gitlab/org/repo\":\"/tmp/renovate/repos/gitlab/org/repo\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -w \"/tmp/renovate/repos/gitlab/org/repo\" renovate/gradle bash -l -c \"sh gradlew --init-script renovate-plugin.gradle renovate\"\ngradlew: 158: gradlew: Syntax error: \"(\" unexpected\n"
```

@jGleitz Can you help here?

**Comment by viceice** [comment] 2020-03-24 09:32
trying to create a simple repro

**Comment by viceice** [comment] 2020-03-24 09:41
![image](https://user-images.githubusercontent.com/1798109/77410963-08f87000-6dbc-11ea-846b-a10d7ee15170.png)

**Comment by LeJeanbono** [comment] 2020-03-24 10:08
Not the same error, but yes

**Comment by viceice** [comment] 2020-03-24 10:23
Even more strange. locally i get another error

![image](https://user-images.githubusercontent.com/1798109/77414729-c76ac380-6dc1-11ea-8d11-a766b7dc7d30.png)

**Comment by viceice** [comment] 2020-03-24 10:59
![image](https://user-images.githubusercontent.com/1798109/77418176-d1db8c00-6dc6-11ea-8c23-0aabbd839b8b.png)

Last known successful run for my selfhosted bot was around 28.2. 🤔

**Comment by rarkins** [comment] 2020-03-24 12:17
Do you use `renovate/grade` ?

**Comment by viceice** [comment] 2020-03-24 12:45
yes,  using `renovate/renovate:19.179.0-slim` in gitlab pipeline.  Its also failing in renovate app on github

**Comment by rarkins** [comment] 2020-03-24 12:56
Did we upgrade the gradle image around that time?

**Comment by viceice** [comment] 2020-03-24 12:59
![image](https://user-images.githubusercontent.com/1798109/77427970-9e552d80-6dd7-11ea-9a5f-b42fdac84d94.png)

nope, only base digest updates since last year. it worked atleast until 28.2.2020

**Comment by rarkins** [comment] 2020-03-24 13:12
Weird. I was sure I had updated `renovate/gradle` to use gradle v6

**Comment by viceice** [comment] 2020-03-24 13:15
![image](https://user-images.githubusercontent.com/1798109/77429369-d8273380-6dd9-11ea-8b21-5a2bdfe2ba3e.png)
 last changes to gradle, after this only parent digest changes

**Comment by jGleitz** [comment] 2020-03-27 11:55
I had a look at https://github.com/viceice/renovate-test. Here is what I found:

When I first executed renovate on my for of the repo, I also got this error:

```
 WARN: Gradle extraction failed (repository=jGleitz/renovate-test)
       "errMessage": "Command failed: sh gradlew --init-script renovate-plugin.gradle renovate\ngradlew: 158: Syntax error: \"(\" unexpected\n"
```

This is caused by renovate using `sh` instead of `bash`, see https://github.com/renovatebot/renovate/issues/5799

When trying to execute `gradle` locally in this repository, it fails. This is because the Gradle setup is missing repositories and dependencies, see https://developer.android.com/studio/build. This leads to the 
```
> Plugin with id 'com.android.application' not found.
```
that @viceice has found. I have fixed this in my fork, see https://github.com/jGleitz/renovate-test/commit/d6e1507078aec2d8d8b531ceeba7f62d7b52a21b

**Comment by jGleitz** [comment] 2020-03-27 11:59
> Weird. I was sure I had updated `renovate/gradle` to use gradle v6

Please be aware that updating gradle in the Docker image would be a breaking change!

While we should have an eye on versions in the Docker image, this is not relevant here, because the repository uses the Gradle Wrapper. That means that the gradle installation from docker should not be used.

**Comment by viceice** [comment] 2020-03-27 12:18
@jGleitz sorry, missed to add the root `build.gradle` to the test repo. Fixed that

**Comment by rarkins** [comment] 2020-03-27 12:31
> Please be aware that updating gradle in the Docker image would be a breaking change!

I'm not sure we can abide by this. In general, we will continue to support the latest version of each tool in the pre-built image. Anyone who needs different needs to build their own image.

- Should a major update of a third party dependency cause a major version bump to  our published Docker image? Highly undesirable as we want to keep Docker image versions matching the published Renovate version.
- Should a major update of a third party dependency within the pre-built Docker image cause a version bump of Renovate itself? I'd also prefer not for that

But it raises an interesting topic. I guess strictly speaking our deliverable is the published `npm` package and our semver versioning reflects that. If a breaking change is in the Docker image we can try to align it with a major update to Renovate itself, but we can't guarantee it.

**Comment by jGleitz** [comment] 2020-03-27 12:35
I agree that this is a difficult topic. However, I also think that updating gradle without a major version change is not okay. It will break people’s builds.

In the case of gradle, we could avoid this issue by stopping to support repositories that don’t use the gradle wrapper. However, this does not solve the issue for other managers.

**Comment by viceice** [comment] 2020-03-27 12:40
I think we do not break other peoples builds by updating our (internal) tools. But we can break renovate when the new version is not compatible with the old files in the users repository. That case we always try to fix.

For gradle i think most users use the wrapper now?

**Comment by jGleitz** [comment] 2020-03-27 13:07
> But we can break renovate when the new version is not compatible with the old files in the users repository.

Yes, this is what I wanted to say.

> For gradle i think most users use the wrapper now?

That is also my impression.

**Comment by jGleitz** [comment] 2020-03-28 16:57
@LeJeanbono: This issue as developed quite a bit. I, at least, have lost the overview of what has been discussed here. Is there any problem left, now that #5806 is merged?

**Comment by LeJeanbono** [comment] 2020-03-30 11:05
Hi @jGleitz Thanks for your commit, but still same error : 
`WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse/api\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\nError: Could not find or load main class org.gradle.wrapper.GradleWrapperMain\nCaused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain\n"
}`
`DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper`
`DEBUG: Matched 1 file(s) for manager gradle-wrapper: gradle/wrapper/gradle-wrapper.properties`

**Comment by LeJeanbono** [comment] 2020-03-30 14:35
This problem is solved : `/mnt/renovate/gl/csuite/datawarehouse/api\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle` => I have 2 modules `api` and `e2e` and a gradlew in `api` which reference gradle wrapper in `api` not in project root. I deleted it and now It's ok.
**But It come back to the first error of this issue :** 
`WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\nCompliance error - Unable to determine develop version as git describe did not return expected value\`
`FAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring project ':api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 1m 13s\n"
}`

**Comment by LeJeanbono** [comment] 2020-04-27 15:58
@viceice @rarkins @jGleitz 
How can I help you on this ?
Same error on an other project.
Structure file :
- .gradle folder
- gradle wrapper folder
- api module folder
   - build.gradle
- e2e-test module folder
   - build.gradle

Thank you !
Log :
```DEBUG: Start gradle command
{
  "cmd": "./gradlew --init-script renovate-plugin.gradle renovate"
}
DEBUG: Using docker to execute
DEBUG: Fetching Docker image: renovate/gradle
DEBUG: Finished fetching Docker image
DEBUG: Executing command
{
  "command": "docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/passeleveur\":\"/mnt/renovate/gl/csuite/passeleveur\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/passeleveur\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\""
}
WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/passeleveur\":\"/mnt/renovate/gl/csuite/passeleveur\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/passeleveur\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\nCompliance error - Unable to determine develop version as git describe did not return expected value\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring project ':api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 59s\n"
}
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Matched 1 file(s) for manager gradle-wrapper: gradle/wrapper/gradle-wrapper.properties
DEBUG: gradle-wrapper.extractPackageFile()
DEBUG: Gradle Wrapper
{
  "depName": "gradle",
  "currentValue": "5.2.1",
  "datasource": "gradle-version",
  "versioning": "gradle"
}
DEBUG: Found gradle-wrapper package files```

**Comment by rarkins** [comment] 2020-04-27 16:58
Do we have a repo available that reproduces the problem with the latest Renovate code?

**Comment by LeJeanbono** [comment] 2020-05-02 12:49
Here we are @rarkins : https://github.com/LeJeanbono/renovate_gradle
Job Id : LeJeanbono/renovate_gradle: #171835913
```
WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/LeJeanbono/renovate_gradle\":\"/mnt/renovate/gh/LeJeanbono/renovate_gradle\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gh/LeJeanbono/renovate_gradle\" renovate/gradle bash -l -c \"gradle --init-script renovate-plugin.gradle renovate\"\nCompliance error - Unable to determine develop version as git describe did not return expected value\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring project ':api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 55s\n"
}
```

**Comment by LeJeanbono** [comment] 2020-06-17 07:49
@rarkins @viceice @jGleitz 
You've got the public repo to reproduce https://github.com/LeJeanbono/renovate_gradle
Since a long time, renovate work juste one time :
```
DEBUG: Fetching Docker image: renovate/gradle
DEBUG: Finished fetching Docker image
DEBUG: Executing command
{
  "command": "docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\""
}
DEBUG: exec completed
{
  "cmd": "docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"",
  "durationMs": 71503,
  "stdout": "Downloading https://services.gradle.org/distributions/gradle-6.4.1-bin.zip\n.........10%..........20%..........30%..........40%.........50%..........60%..........70%..........80%.........90%..........100%\n\nWelcome to Gradle 6.4.1!\n\nHere are the highlights of this release:\n - Support for building, testing and running Java Modules\n - Precompiled script plugins for Groovy DSL\n - Single dependency lock file per project\n\nFor more details see https://docs.gradle.org/6.4.1/release-notes.html\n\nTo honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.4.1/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n> Task :renovate\n> Task :api:renovate\n> Task :e2e-test:renovate\n\nBUILD SUCCESSFUL in 1m 8s\n3 actionable tasks: 3 executed\n",
  "stderr": ""
}
DEBUG: Downloading https://services.gradle.org/distributions/gradle-6.4.1-bin.zip .........10%..........20%..........30%..........40%.........50%..........60%..........70%..........80%.........90%..........100% Welcome to Gradle 6.4.1! Here are the highlights of this release: - Support for building, testing and running Java Modules - Precompiled script plugins for Groovy DSL - Single dependency lock file per project For more details see https://docs.gradle.org/6.4.1/release-notes.html To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.4.1/userguide/gradle_daemon.html. Daemon will be stopped at the end of the build stopping after processing Configuration on demand is an incubating feature. > Task :renovate > Task :api:renovate > Task :e2e-test:renovate BUILD SUCCESSFUL in 1m 8s 3 actionable tasks: 3 executed
DEBUG: Gradle report complete
DEBUG: Found gradle package files
DEBUG: Found gradle-wrapper package files
```
Then fail the next job : 
```
DEBUG: Fetching Docker image: renovate/gradle
DEBUG: Finished fetching Docker image
DEBUG: Executing command
{
  "command": "docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\""
}
WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gl/csuite/datawarehouse\":\"/mnt/renovate/gl/csuite/datawarehouse\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gl/csuite/datawarehouse\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\nCompliance error - Unable to determine develop version as git describe did not return expected value\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring project ':api'.\n> Unable to determine develop version as git describe did not return expected value\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 1m 6s\n"
}
DEBUG: Found gradle-wrapper package files
```

**Comment by rarkins** [comment] 2020-06-17 08:04
When I run against a fork of this locally I get the error first time (`Compliance error - Unable to determine develop version as git describe did not return expected value`).

Searching these terms on Google still just returns hits related to this issue.

**Comment by LeJeanbono** [comment] 2020-06-17 17:50
When running `git describe` in shell :
```
~/Projets/renovate_gradle (develop)
$ git describe
'annotated-tag'-1-g0f5ce61
```
For what this command is usefull ?
Maybe `--all` option is missing or the quote in the middle is not valid

**Comment by rarkins** [comment] 2020-06-17 18:02
I have no idea where “git describe” is even being called

**Closed** 2021-08-08 12:25 UTC
Labels: type:bug, priority-3-normal, manager:gradle, status:requirements
