### ISSUE TITLE
Multiple Dependency Dashboards per Repo

### ISSUE THREAD

**Issue by mbmx10** [renovatebot/renovate#20151] opened 2023-02-01 13:08 UTC
### What would you like Renovate to be able to do?

We would like to show several dependency dashboards in our gitlab mono repository.

When we run two configured renovatebot jobs, each of them overrides the dashboard of the other. The main reason to separate these jobs is the difference in priorities of updates.

We haven't found an existing solution to this so far.

### If you have any ideas on how this should be implemented, please tell us here.

Perhaps each job might set an identifier for its connected dashboard.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment] 2023-02-01 13:10
Duplicate of #10607

**Closed by rarkins** 2023-02-01 13:10 UTC
Labels: type:feature, status:requirements, priority-5-triage
