### ISSUE TITLE
When using LockFile Maintenance, GitHub PR info is missing version info

### ISSUE THREAD

**Issue by broksonic21** [renovatebot/renovate#7279] opened 2020-09-14 14:30 UTC
We just turned on lock file maintenance (npm) and now the PR messages don't show the right version info - just that the lock file was refreshed. Can we get it to show version change

e.g.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/24306571/93098728-32140200-f675-11ea-8849-3e039c600322.png">

compare to this, when you don't do lock file maintenance.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/24306571/93098805-448e3b80-f675-11ea-9f62-a797f438e056.png">

**Comment by broksonic21** [comment] 2020-09-14 19:20
I think this might happen only if you use group:all

Is there a right way to do group:all for non-lock file, but not have lockfilemaintenance be included in that?

(or else have the PR comment fixed in the case you use both)

**Comment by broksonic21** [comment] 2020-09-14 19:49
Compare this - using group:all and lockFileMaintenance https://github.com/broksonic21/renovate_repo_repro/pulls

to 

this repo, which is the same, but not using group:all, but instead using specific major/minor/patch to group vs a wildcard. So similar to group:all, but not the _exact_ same, so you don't run into this bug nor have them conflicted.

`
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "separateMajorMinor": false,
      "groupSlug": "all",
      "major": {
        "groupName": "all major dependencies",
        "groupSlug": "all"
      },
      "minor": {
        "groupName": "all minor dependencies",
        "groupSlug": "all"
      },
      "patch": {
        "groupName": "all patch dependencies",
        "groupSlug": "all"
      }
    }
  ]
`

https://github.com/broksonic21/renovate_repo_repo2/pulls

That said, our ideal wish is to have the PR comment fixed with the group:all case so just one PR comes out, not two.

**Comment by rarkins** [comment] 2022-01-13 13:12
Duplicate of #5838

**Closed by rarkins** 2022-01-13 13:12 UTC
Labels: type:bug, priority-3-normal, manager:npm, status:ready
