### ISSUE TITLE
Automerge works incorrectly with stability-days and external CI/CD

### ISSUE THREAD

**Issue by XFNeo** [renovatebot/renovate#15545] opened 2022-05-11 13:00 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:32

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab (.com and CE/EE)

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

We have an external CI\CD system on jenkins, a webhook is configured in the repository that launches an assembly job, the first thing the job does is set a pipeline status and after the assembly is completed it turns green or red if the assembly has failed. We also have automerge enabled in the renovate bot.
After turning on the stability-days feature, a new pipeline appeared, which immediately turns green if the specified number of days have passed. We faced the problem that the external CI\CD system often does not have time to set its pipeline status and the MR is merged seeing that there is only one pipeline with green status from the stability-days feature.

How to avoid merging of MR with only one green pipeline status from stability-days?

![image](https://user-images.githubusercontent.com/37923089/167855697-21342fce-86e5-487c-bf72-f32c1112fe7a.png)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment] 2022-05-11 13:02
I'm guessing you have configured prCreation=not-pending?

**Comment by rarkins** [comment] 2022-05-11 13:03
The title needs fixing to more accurately and less alarmingly describe the problem. We don't award points for "how scary can you make your big sound"

**Comment by XFNeo** [comment] 2022-05-11 13:05
We have no prCreation in config only
    "extends": ["config:base", ":prHourlyLimitNone"]

**Comment by XFNeo** [comment] 2022-05-11 13:10
> I'm guessing you have configured prCreation=not-pending?

I will set  prCreation=not-pending.
Should it help?

**Comment by rarkins** [comment] 2022-05-11 13:12
Sorry, no don't set that. I thought you already have. You will need to provide the logs for when the automerge happens, instructions will be below

**Comment by rarkins** [comment] 2022-05-11 13:13
Please also provide your config. If you have a stability days check run then there must be some config you are not sharing above

**Comment by XFNeo** [comment] 2022-05-11 13:23
<details><summary>Config</summary>

```
{
    "labels": ["Dependency Bot"],
    "repositories": [
        ${REPOSITORIES}
    ],
    "extends": ["config:base", ":prHourlyLimitNone"],
    "packageRules": [
      { 
        "matchUpdateTypes": ["minor", "patch", "pin", "digest"], "automerge": true
      },
      {
        "matchPackagePatterns": ["*"],
        "allowedVersions": "!/redhat|composite|groovyless|jboss|atlassian|preview/"
      },
      {
        "matchPackageNames": ["com.company.cloud.junit.cloudcore:cloud-core-extension"],
        "allowedVersions": "!/^3.*/"
      },
      {
        "matchPackageNames": ["org.jboss.arquillian.junit:arquillian-junit-standalone", "io.undertow:undertow-core", "org.reflections:reflections"],
        "enabled": false
      },
      {
        "groupName": "spring",
        "matchPackagePatterns": ["^org.springframework*"]
      },
      {
        "groupName": "quarkus",
        "matchPackagePatterns": ["^io.quarkus"]
      },
      {
        "groupName": "com.company.cloud",
        "matchPackagePatterns": ["com.company.cloud"],
        "stabilityDays": 0,
        "automerge": false
      },
      {
        "groupName": "git.company.com/prod.platform.cloud_core",
        "matchPackagePatterns": ["git.company.com/prod.platform.cloud_core"],
        "stabilityDays": 0,
        "automerge": false
      },
      {
        "matchManagers": ["maven"],
        "registryUrls": [
            "https://artifactorycn.company.com/pd.saas-release.mvn.group"
        ]
      },
      {
        "matchUpdateTypes": ["major"],
        "labels": ["Dependency Bot","UPDATE-MAJOR"]
      }
	],
    "postUpdateOptions":["gomodTidy"],
    "recreateClosed": true,
    "platformAutomerge": true,
    "rebaseWhen": "conflicted"
}
```

</details>

Also we have provide 2 env variable to container
        -e RENOVATE_INTERNAL_CHECKS_FILTER=strict 
        -e RENOVATE_STABILITY_DAYS=14

**Comment by XFNeo** [comment] 2022-05-13 08:52
@rarkins we have no logs for now(
Why do you think prCreation=not-pending does not help?
What is the sequence of actions? Is the pipeline status checked on the branch and the creation of the MR first, or is the stability-days pipeline the first to be set?

**Comment by rarkins** [comment] 2022-05-13 09:15
If you have internalChecksFilter=strict then you won't ever get any pending renovate/stability-days status check, so prCreation=not-pending won't have an effect. Stability days will be set immediately on any branch, if you have configured a non-zero value. So if it's not met then a pending check and if it's met then a passing check. In your config it will always be met.

**Comment by XFNeo** [comment] 2022-05-13 09:39
> If you have internalChecksFilter=strict then you won't ever get any pending renovate/stability-days status check, so prCreation=not-pending won't have an effect. Stability days will be set immediately on any branch, if you have configured a non-zero value. So if it's not met then a pending check and if it's met then a passing check. In your config it will always be met.

Ok, but what about green status of stability-days with prCreation=not-pending ?
Will PR be created immediately after creating branch and green status of stability-days ?

**Comment by rarkins** [comment] 2022-05-13 10:22
No, there won't be any branch or PR while the settings are strict

**Comment by XFNeo** [comment] 2022-05-13 11:07
How to turn off creation of stability-days pipeline  when stability-days period is valid?

**Comment by rarkins** [comment] 2022-05-13 11:54
Not possible

**Comment by XFNeo** [comment] 2022-05-13 11:55
OK, and how to resolve this issue?

**Comment by rarkins** [comment] 2022-05-13 16:21
1. Provide logs of when the situation happens
2. Better yet, provide a minimal reproduction

Or, turn off automerge, stability days, or strict filtering.

**Comment by XFNeo** [comment] 2022-05-16 08:47
> Or, turn off automerge, stability days, or strict filtering.

I don't understand how disable of internalChecksFilter helps with this issue.
We have problem when renovatebot automergs PRs with only one sucessfull stability-days pipeline, because Jenkins did not have time to put its external pipeline.

I have added prCreation=not-pending and looks like renovatebot does not created PRs in current run but in the next run (in a hour) we already have external Jenkins pipeline status on the branch. If this external pipeline has failed status, this PR will not be automerged.

**Comment by XFNeo** [comment] 2022-05-16 13:00
@rarkins
> 1. Provide logs of when the situation happens

Logs
[renovatebot_logs_15545.txt](https://github.com/renovatebot/renovate/files/8700181/renovatebot_logs_15545.txt)

**Comment by XFNeo** [comment] 2022-05-16 18:18
> Branch renovate/com.github.tomakehurst-wiremock-jre8-2.x

**Comment by rarkins** [comment] 2022-05-28 05:41
Here is the relevant logs:

```
DEBUG: Setting current branch to master (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: latest commit (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "branchName": "master",
       "latestCommitDate": "2022-05-13T10:38:35+00:00"
DEBUG: getBranchPr(renovate/com.github.tomakehurst-wiremock-jre8-2.x) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: findPr(renovate/com.github.tomakehurst-wiremock-jre8-2.x, undefined, open) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: branchExists=false (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: dependencyDashboardCheck=undefined (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: recreateClosed is true (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Checking schedule(at any time, null) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: No schedule defined (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Branch needs creating (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Using reuseExistingBranch: false (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Updating com.github.tomakehurst:wiremock-jre8 in security/access-control-thin-client/deployment/pom.xml (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Updated 1 package files (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: No updated lock files in branch (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: 1 file(s) to commit (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Preparing files for committing to branch renovate/com.github.tomakehurst-wiremock-jre8-2.x (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: git commit (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/com.github.tomakehurst-wiremock-jre8-2.x",
         "commit": "2c61fea523a45b1f8ba4b08b0ae772b91c388df8",
         "root": false,
         "summary": {"changes": 1, "insertions": 1, "deletions": 1}
       }
DEBUG: Pushing branch renovate/com.github.tomakehurst-wiremock-jre8-2.x (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: git push (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "result": {
         "pushed": [
           {
             "deleted": false,
             "tag": false,
             "branch": true,
             "new": true,
             "alreadyUpdated": false,
             "local": "refs/heads/renovate/com.github.tomakehurst-wiremock-jre8-2.x",
             "remote": "refs/heads/renovate/com.github.tomakehurst-wiremock-jre8-2.x"
           }
         ],
         "ref": {
           "local": "refs/remotes/origin/renovate/com.github.tomakehurst-wiremock-jre8-2.x"
         },
         "remoteMessages": {
           "all": [
             "To create a merge request for renovate/com.github.tomakehurst-wiremock-jre8-2.x, visit:",
             "https://git.company.com/PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions/-/merge_requests/new?merge_request%5Bsource_branch%5D=renovate%2Fcom.github.tomakehurst-wiremock-jre8-2.x"
           ],
           "pullRequestUrl": "https://git.company.com/PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions/-/merge_requests/new?merge_request%5Bsource_branch%5D=renovate%2Fcom.github.tomakehurst-wiremock-jre8-2.x"
         }
       }
 INFO: Branch created (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "commitSha": "2c61fea523a45b1f8ba4b08b0ae772b91c388df8"
DEBUG: Got res with 0 results (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Updating renovate/stability-days status check state to green (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Ensuring PR (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: There are 0 errors and 0 warnings (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: getBranchPr(renovate/com.github.tomakehurst-wiremock-jre8-2.x) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: findPr(renovate/com.github.tomakehurst-wiremock-jre8-2.x, undefined, open) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: resolveBranchStatus(branchName=renovate/com.github.tomakehurst-wiremock-jre8-2.x, ignoreTests=false) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: getBranchStatus(renovate/com.github.tomakehurst-wiremock-jre8-2.x) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Got res with 1 results (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Branch status green (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Creating PR (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "prTitle": "JIRA-0000 Update dependency com.github.tomakehurst:wiremock-jre8 to v2.33.2"
DEBUG: Creating Merge Request: JIRA-0000 Update dependency com.github.tomakehurst:wiremock-jre8 to v2.33.2 (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
 INFO: PR created (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "pr": 380,
       "prTitle": "JIRA-0000 Update dependency com.github.tomakehurst:wiremock-jre8 to v2.33.2"
DEBUG: addParticipants(pr=380) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Adding assignees 'user1' to #380 (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Added assignees (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "assignees": ["user1"]
DEBUG: Created Merge Request #380 (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: PR is configured for automerge (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: resolveBranchStatus(branchName=renovate/com.github.tomakehurst-wiremock-jre8-2.x, ignoreTests=false) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: getBranchStatus(renovate/com.github.tomakehurst-wiremock-jre8-2.x) (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Got res with 1 results (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Branch status green (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Automerging #380 with strategy auto (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
DEBUG: Gitlab API error (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1652696600909,
           "socket": 1652696600909,
           "lookup": 1652696600913,
           "connect": 1652696600914,
           "secureConnect": 1652696600914,
           "upload": 1652696600914,
           "response": 1652696600983,
           "end": 1652696600984,
           "phases": {
             "wait": 0,
             "dns": 4,
             "tcp": 1,
             "tls": 0,
             "request": 0,
             "firstByte": 69,
             "download": 1,
             "total": 75
           }
         },
         "message": "Response code 405 (Method Not Allowed)",
         "stack": "HTTPError: Response code 405 (Method Not Allowed)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.52.2 (https://github.com/renovatebot/renovate)",
             "private-token": "**redacted**",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "36",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Flibs%2Fcloud-core-quarkus-extensions/merge_requests/380/merge",
           "hostType": "gitlab",
           "username": "",
           "password": "",
           "method": "PUT",
           "http2": false
         },
         "response": {
           "statusCode": 405,
           "statusMessage": "Method Not Allowed",
           "body": {"message": "405 Method Not Allowed"},
           "headers": {
             "server": "nginx",
             "date": "Mon, 16 May 2022 10:23:20 GMT",
             "content-type": "application/json",
             "content-length": "36",
             "connection": "close",
             "cache-control": "no-cache",
             "vary": "Origin",
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "x-gitlab-feature-category": "code_review",
             "x-request-id": "01G3669MAKHY1BSCSKBA3Q23XC",
             "x-runtime": "0.065705"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: merge PR error (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1652696600909,
           "socket": 1652696600909,
           "lookup": 1652696600913,
           "connect": 1652696600914,
           "secureConnect": 1652696600914,
           "upload": 1652696600914,
           "response": 1652696600983,
           "end": 1652696600984,
           "phases": {
             "wait": 0,
             "dns": 4,
             "tcp": 1,
             "tls": 0,
             "request": 0,
             "firstByte": 69,
             "download": 1,
             "total": 75
           }
         },
         "message": "Response code 405 (Method Not Allowed)",
         "stack": "HTTPError: Response code 405 (Method Not Allowed)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.52.2 (https://github.com/renovatebot/renovate)",
             "private-token": "**redacted**",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "36",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://git.company.com/api/v4/projects/PROD.Platform.Cloud_Core%2Flibs%2Fcloud-core-quarkus-extensions/merge_requests/380/merge",
           "hostType": "gitlab",
           "username": "",
           "password": "",
           "method": "PUT",
           "http2": false
         },
         "response": {
           "statusCode": 405,
           "statusMessage": "Method Not Allowed",
           "body": {"message": "405 Method Not Allowed"},
           "headers": {
             "server": "nginx",
             "date": "Mon, 16 May 2022 10:23:20 GMT",
             "content-type": "application/json",
             "content-length": "36",
             "connection": "close",
             "cache-control": "no-cache",
             "vary": "Origin",
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "x-gitlab-feature-category": "code_review",
             "x-request-id": "01G3669MAKHY1BSCSKBA3Q23XC",
             "x-runtime": "0.065705"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: PR merge failed (repository=PROD.Platform.Cloud_Core/libs/cloud-core-quarkus-extensions, branch=renovate/com.github.tomakehurst-wiremock-jre8-2.x)
```

**Comment by rarkins** [comment] 2022-05-28 05:43
Duplicate of #7800

**Closed by rarkins** 2022-05-28 05:43 UTC
Labels: type:bug, reproduction:needed, status:requirements, priority-5-triage, core:automerge
