### ISSUE TITLE
[manager] fluxcd helm operator / helm-controller

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#7415] opened 2020-10-05 15:17 UTC
We should support the `HelmRelease` podinfo.yml files.

https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/introduction/#a-minimal-helmrelease

sample file
```yml
# podinfo.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 3.2.0
```

@rarkins Single registryUrl would work for us, and we're suing regex because we're using [Helm Operator](https://github.com/fluxcd/helm-operator) (and soon [Helm Controller](https://github.com/fluxcd/helm-controller)) to handle Helm releases. Adding native support for those to Dependabot's Helm support would also work for us, but might not address other abstractions.

_Originally posted by @RichiCoder1 in https://github.com/renovatebot/renovate/issues/6130#issuecomment-703695883_

**Comment by RichiCoder1** [comment] 2020-10-05 15:27
This would be great! As an addendum, the Flux project is putting Helm Operator into maintenance mode, so support for its successor would be great/critical: https://toolkit.fluxcd.io/components/helm/api/. That said, the two CRDs (currently) only differ by `apiVersion` and some spec values that Renovate shouldn't need to care about.

**Comment by viceice** [comment] 2020-10-05 15:33
@rdicroce Do you think it would be worth to implement this, as it's deprecated? Maybe we should support the successor first.

sample:
```yml
apiVersion: helm.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
 name: podinfo
spec:
 interval: 5m
 chart:
   spec:
     chart: podinfo
     version: '>=4.0.0 <5.0.0'
     sourceRef:
       kind: HelmRepository
       name: podinfo
     interval: 1m
 install:
   remediation:
     retries: 3
 upgrade:
   remediation:
     remediateLastFailure: false
 values:
   resources:
     requests:
       cpu: 100m
       memory: 64Mi
```

https://toolkit.fluxcd.io/components/helm/controller/

**Comment by rdicroce** [comment] 2020-10-05 15:35
@viceice Did you mean to @rarkins ? Seeing as I'm not part of Renovate's core dev team...

**Comment by viceice** [comment] 2020-10-05 15:37
Ups, sorry.

**Comment by viceice** [comment] 2020-10-05 15:40
@RichiCoder1 I think the complicated part is to find the corresponding chart source.

https://toolkit.fluxcd.io/guides/helmreleases/#define-a-chart-source

as it can be defined in any other yaml file, so we need to do some assumptions like `name` and `namespace` need to match and they must be in same repo.

Is there any convention for file naming? So we can limit the files to check somehow?

**Comment by RichiCoder1** [comment] 2020-10-05 15:44
Bah, I forgot they did that. Current HelmOperator just has all the details in one place.

@viceice Unfortunately I don't there's any current pattern as Toolkit is still pre-release. Probably wouldn't be able to make any assumptions about naming or file placement conventions either.

**Comment by RichiCoder1** [comment] 2020-10-05 15:46
If you provided an option for both a chart source regex and `HelmRelease` regex, that might give people the knobs to tone that down. That's the best I could think of however.

**Comment by viceice** [comment] 2020-10-05 15:54
🤔 can you clarify this a little bit more?

**Comment by RichiCoder1** [comment] 2020-10-05 16:06
Do a two pass approach. Scoop up all the `HelmRepository` resources, and then process the `HelmRelease` resources if that makes sense?

**Comment by viceice** [comment] 2020-10-05 16:11
Could be possible, the nuget manager is using a similar aproach to find `registryUrls` in external config files.

**Comment by Djiit** [comment] 2020-10-05 16:58
FWIW, Helm Operator is not going anywhere for the next couple of months, as Helm Controller is still very alpha.

**Comment by ChipWolf** [comment] 2020-10-05 17:46
Duplicate of #5984, suggest close.

**Closed** 2020-10-05 19:42 UTC
Labels: feature, new package manager
