### ISSUE TITLE
Treat deps with versions <1 as major updates

### ISSUE THREAD

**Issue by barrymcgee** [renovatebot/renovate#6636] opened 2020-06-29 13:23 UTC
**What would you like Renovate to be able to do?**

We want to automate and automerge where possible but find that when using deps with a version less than `v1.x.x`, we can't do that as by their very nature packages with versions less than 1 are considered not yet stable.

**Describe the solution you'd like**
A config option to designate any update to a package version less than one to be considered a major update.

**Comment by rarkins** [comment] 2020-06-29 13:57
Duplicate of #4723 and #4857 

On terminology, we would never treat them as *major* updates (they are not). I think though you are meaning *breaking* updates?

**Closed by rarkins** 2020-06-29 13:57 UTC
