### ISSUE TITLE
Wildcard patterns for baseBranches

### ISSUE THREAD

**Issue by mikaelkolkinn** [renovatebot/renovate#10241] opened 2021-05-31 12:32 UTC
**What would you like Renovate to be able to do?**

Today it seems that the `baseBranches` field in the Renovate configuration requires exact branch names.
It would be nice if we could use simple patterns to cover feature branches, pre-release branches etc.

We use branch patterns in our CI/CD workflow to automatically create pre-release packages for our libraries, by creating branches following a pattern like this `prerelease/*`. Some of these pre-release branches may be long lived and could benefit from automatic updates. With #7019 it became possible to add standardized pre-release names to the baseBranches field, like `prerelease/alpha`, `release/next` and so on. But in our case we want to create dynamic pre-releases that take the branch name:
```
// branch name
prerelease/ef-core-six-experimental

// pre-release version for our package
1.2.0-ef-core-six-experimental.0
```

**Did you already have any implementation ideas?**

Not sure how simple or complex it should be. If there's already some tooling used for similar patterns in other parts of the config, maybe that could be used here (globbing or something similar)? Otherwise just a simple `*` wildcard would be enough for our needs.

With some pointers, I would be interested in contributing myself.

**Comment by rarkins** [comment] 2021-05-31 13:13
Duplicate of #5027

**Closed by rarkins** 2021-05-31 13:13 UTC
Labels: priority-5-triage, status:requirements, type:feature
