### ISSUE TITLE
Support a generic http datasource

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#6223] opened 2020-05-13 15:53 UTC
**What would you like Renovate to be able to do?**
A generic datasource to retrieve the latest of something from an http endpoint would be useful for a variety of applications. One application of this feature I have in mind would be for Jenkins builds.

Using an endpoint such as http://ci.aksw.org/jenkins/job/LinkedGeoData/lastSuccessfulBuild/buildNumber we can retrieve the latest build number for a given Jenkins job.

Perhaps we could use some regex to select a specific piece of text on a given page.

**Describe the solution you'd like**

Something like this:

```json
{
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["^helloworld.yaml$"],
      "matchStrings": [
        "name: BUILD:(?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "generic"
    },
    {
      "fileMatch": ["^otherfile.yaml$"],
      "matchStrings": [
        "name: (?<depName>.*):(?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "generic"
    }
  ],
  "packageRules": [
    {
      "datasources": ["generic"],
      "managers": ["regex"],
      "registryUrls": ["https://ci.openshift.redhat.com/jenkins/job/push_image_inspector_images/"],
      "genericRegex": "build-row\" href=\"\/jenkins\/job\/.*?\/(?<currentValue>.*?)(?s)(?:\\R.*)"
    },
    {
      "datasources": ["generic"],
      "managers": ["regex"],
      "packageNames": [
        "my-package"
      ],
      "registryUrls": ["https://ci.openshift.redhat.com/jenkins/job/push_wildfly_images/lastSuccessfulBuild/buildNumber"]
    }
  ]
}
```

**Comment by rarkins** [comment] 2020-05-13 15:58
It could be nice to do it "properly" and allow (a) multiple values, and (b) maybe even a deep or nested mapping of any JSON response

**Comment by rarkins** [comment] 2020-11-23 08:11
Idea: make this similarly configurable as regex managers:
- template-able registry URL
- auto parse JSON/YAML/TOML/XML
- allow override of parsing type if not able to auto-detect correctly
- use JSONPATH to pinpoint package metadata and release data
- use handlebars objects to map that data back into a compatible release

**Comment by rarkins** [comment] 2023-05-13 18:27
Although this issue came first, I'm going to prefer #15193 to continue with

**Comment by rarkins** [comment] 2023-05-13 18:27
Duplicate of #15193

**Closed by rarkins** 2023-05-13 18:27 UTC
Labels: type:feature, priority-3-medium, status:requirements
