### ISSUE TITLE
Gitlab addAssignees function only adds the first assignee

### ISSUE THREAD

**Issue by mrabuse** [renovatebot/renovate#4463] opened 2019-09-09 20:31 UTC
**What Renovate type are you using?**
Self-hosted Renovate running in Gitlab

**Describe the bug**
The addAssignees function for Gitlab only adds the very first assignee in the array. It also doesn't search for groups of ids, and there is no documentation that Gitlab behaves differently. See the function here in [gitlab/index.ts](https://github.com/renovatebot/renovate/blob/master/lib/platform/gitlab/index.ts#L505-L516)

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://app.renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

**To Reproduce**
Read the code -- I observed this while digging into a different problem. 

**Expected behavior**
All assignees in the list get added to the MR
Add groups as well if that is intended behavior (or document if it is not)

**Screenshots**

**Additional context**

**Comment by rarkins** [comment] 2019-09-09 20:54
Duplicate of #3745 ?

**Closed** 2019-12-11 12:15 UTC
