### ISSUE TITLE
Renovate Bot Downgrading to a lower alpha version

### ISSUE THREAD

**Issue by jordisala1991** [renovatebot/renovate#9873] opened 2021-05-05 14:36 UTC
**What Renovate type, platform and version are you using?**

**Renovate type**

- [x] Hosted app
- [ ] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [x] GitHub (github.com, GitHub Enterprise)
- [ ] GitLab (gitlab.com, self-hosted)
- [ ] Gitea (gitea.com, self-hosted)

**Describe the bug**

https://github.com/Runroom/archetype-drupal/pull/1241
https://github.com/Runroom/archetype-drupal/pull/1240

For some reason renovate bot is trying to downgrade two dependencies.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by jordisala1991** [comment] 2021-05-05 14:38
This might be a duplicate for: https://github.com/renovatebot/renovate/issues/6899

Just saw after opening the issue, shall I close?

**Comment by rarkins** [comment] 2021-05-05 14:44
Duplicate of #6899

**Closed by rarkins** 2021-05-05 14:44 UTC
Labels: priority-5-triage, status:requirements, type:bug
