### ISSUE TITLE
Renovate re-created already merged pull request

### ISSUE THREAD

**Issue by amezin** [renovatebot/renovate#17746] opened 2022-09-12 05:14 UTC
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I have lockfile maintenance enabled for pip-compile.

Today Renovate created a pull request with the same commit that I merged a week ago: https://github.com/ddterm/gnome-shell-extension-ddterm/pull/178/commits/34cac26dfff005debf106f754ceaee425a022dff (previous pull request - https://github.com/ddterm/gnome-shell-extension-ddterm/pull/172 new one - https://github.com/ddterm/gnome-shell-extension-ddterm/pull/178)

It tries to update psutil 5.9.1 -> 5.9.2, but psutil is already ==5.9.2 in the master branch.

### Relevant debug logs

<details><summary>Logs</summary>

Full log at the time when the pull request was created: https://gist.github.com/amezin/3aeb8acb3db93256a5fc42a96194c89c

Not sure which parts are relevant.

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment] 2022-09-12 05:25
The commit was made 6 days ago:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/6311784/189579569-b420a66e-7e5c-4d70-80dd-a914005a0b00.png">

**Comment by rarkins** [comment] 2022-09-12 05:31
When you merged this branch previously, the branch wasn't deleted:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/6311784/189579974-05ae451d-8c38-4488-b12f-a81294072179.png">

Then the branch was picked up again and reused this week. It's not conflicted so it didn't get rebased.

For lock file maintenance to work, you need to configure either automatic branch deletion when PRs are merged, or delete the branch yourself after you merge. This is because Renovate can't reliably delete merged lock file maintenance branches currently.

**Comment by rarkins** [comment] 2022-09-12 05:31
Duplicate of #7636

**Closed by rarkins** 2022-09-12 05:31 UTC
Labels: type:bug, status:requirements, duplicate, priority-5-triage
