### ISSUE TITLE
Poetry "*" dependencies should be resolved correctly

### ISSUE THREAD

**Issue by orf** [renovatebot/renovate#8671] opened 2021-02-12 20:50 UTC
**What would you like Renovate to be able to do?**

A poetry dependency with the `*` constraint, such as:

```toml
boto3 = "*"
```

Should be resolved and updated correctly

**Did you already have any implementation ideas?**

Not quite yet 😅

**Comment by zyv** [comment] 2023-02-04 12:25
@orf @HonkingGoose @rarkins any progress on that? I have completely open dependencies in my `pyproject.toml` and Renovate doesn't seem to be working at all:

https://github.com/moneymeets/sepacetamol

A PR connected to this issue has been merged, but doesn't seem to have an effect. Or do I have to set the strategy explicitly for it to work?

**Comment by zyv** [comment] 2023-02-04 13:18
@rarkins here is the reproducer:

https://github.com/zyv/renovate-poetry-repro-star

I expect Renovate to offer Django 4.1.6, but nothing happens.

**Comment by rarkins** [comment] 2023-02-04 13:30
Please try with `rangeStrategy=update-lockfile` in your config

**Comment by zyv** [comment] 2023-02-04 13:49
@rarkins yes, that seems to work:

https://github.com/zyv/renovate-poetry-repro-star/pull/2

I thought that the default is `auto` and it is supposed to do the right thing (didn't check if that works), but the default seems to be `replace`, which is why it's not working.

So why is this issue open then, is anything else missing? I guess just the documentation has to be updated to tell Poetry users with `*` dependencies to use `update-lockfile` strategy, correct?

**Comment by rarkins** [comment] 2023-02-04 13:55
Yes, it sounds like it can be closed. We play for auto to default to update-lockfile in the next major release, btw - which is a work in progress

**Closed by rarkins** 2023-02-04 13:55 UTC
Labels: priority-3-medium, reproduction:needed, status:in-progress, versioning:poetry

**Comment by zyv** [comment] 2023-02-04 14:58
@rarkins thank you for your help!
