### ISSUE TITLE
Hash updates for GH actions does not work

### ISSUE THREAD

**Issue by laurentsimon** [renovatebot/renovate#16763] opened 2022-07-25 15:20 UTC
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Pinning a GHA by hash `an/action@<hash>` is the recommended way on Github, see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions.

All the examples online, including in the https://github.com/actions/starter-workflows/ repo, uses this. Nobody adds a comment like `# tag=v1.2.3`. Yet, by default, renovatebot treats the lack of tag comment as meaning "@main".

I think this is a bug for multiple reasons:
1. It requires work for developers to migrate.
2. The vast majority of uses case (99.999%)  is intended to use a stable release, not at head
3. Main branch is a development branch, which means code may be unstable. Renovatebot should *not* update users to main branch unless they ask for it *explicitly*. 
4. Services that help users to migrate to using hash, like https://app.stepsecurity.io/ (which is the recommended option by OSSF scorecard), also don't add this tag. 

By default, the lack of tags should mean that users want to get updates for *releases*. That should be the default behavior.
Users who want to pull updates from main should "opt-in" for this rare use case.

### Relevant debug logs

See above.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment] 2022-07-25 16:23
I think this issue is related:

- https://github.com/renovatebot/renovate/issues/7516

**Comment by viceice** [comment] 2022-07-25 17:06
closing this ad it's not a bug.

 there is no knowledge yet to get from digest to a version. renovate has a workaround for GitHub actions to pin from versions to digest.

**Closed** 2022-07-25 17:06 UTC
Labels: type:bug, manager:github-actions, status:requirements, priority-5-triage

**Comment by laurentsimon** [comment] 2022-07-25 17:07
Shall I create a feature request instead?

**Comment by viceice** [comment] 2022-07-25 17:09
please open a discussion and make more clear what do you expect to happen. a reproduction repo would also very helpful

**Comment by rarkins** [comment] 2022-07-25 17:14
Yes, but as we'll discuss it's quite challenging to implement
