### ISSUE TITLE
Preview changes to other files in onboarding branches

### ISSUE THREAD

**Issue by jtdoepke** [renovatebot/renovate#20797] opened 2023-03-07 23:12 UTC
### What would you like Renovate to be able to do?

Renovate ignores changes to files other than the `renovate.json` config file in onboarding branches.

A common pattern for using the regex manager is to pass dependency details to Renovate in a comment e.g.
```json
{
  "regexManagers": [
    {
      "fileMatch": [
        "(^|/|\\.)Dockerfile$",
        "(^|/)Dockerfile[^/]*$"
      ],
      "matchStrings": [
        "# renovate: datasource=(?<datasource>[a-z-]+?) depName=(?<depName>[^\\s]+?)(?: (lookupName|packageName)=(?<packageName>[^\\s]+?))?(?: versioning=(?<versioning>[^\\s]+?))?(?: registryUrl=(?<registryUrl>[^\\s]+?))?\\s(?:ENV|ARG) .+?_VERSION[ =]\"?(?<currentValue>.+?)\"?\\s"
      ]
    }
  ]
}
```

However, if you add those comments in the onboarding branch, the dependencies don't show up in the description of the pull request because Renovate generates that preview based on `baseBranches`.

I can work around this by temporarily adding
```json
{
  "baseBranches": ["renovate/configure"]
}
```
to `renovate.json`, and then removing it before the merge, but it's inconvenient.

### If you have any ideas on how this should be implemented, please tell us here.

If the target branch of the onboarding pull request is in `baseBranches`, then Renovate should preview what the results of merging all files in the pull request would be, not just the `renovate.json` config file.

### Is this a feature you are interested in implementing yourself?

No

**Comment by jtdoepke** [comment] 2023-03-08 16:09
Here is a minimal reproduction: https://github.com/jtdoepke/renovate-20797

**Comment by rarkins** [comment] 2023-03-08 18:34
@RahulGautamSingh this highlights something about our onboarding which I had forgotten. While the config is read from the onboarding branch, Renovate still reads dependencies from the default branch.

I guess the current approach was considered a feature - Renovate can update the onboarding PR based on latest dependencies in the default branch without needing to push to the onboarding branch (which may be modified). It also means that `baseBranches` can work well.

I'm not going to close this, because it's a valid request to be able to do this, but I'm not sure we can without either loss of existing functionality or a major code rewrite.

**Comment by RahulGautamSingh** [comment] 2023-03-08 20:02
Then we should handle this before trying to reduce cloning. Will look into it and let you know how much work is needed.

**Comment by RahulGautamSingh** [comment] 2023-03-09 14:27
We still don't want to rebase/update the onboarding branch right? We on;y want to update the PR body with the new extraction result.

**Comment by RahulGautamSingh** [comment] 2023-03-09 14:57
Maybe we can add an option where the user gets to decide which branch he wants to picks as the baseBranch.
eg. `useOnboardingBranchAsBase` 

If the option is true we handle modified onboarding branches differently else we use existing logic.

**When an onboarding branch is modified**
| Existing logic | New logic |
|-|-|
| No futher branch rebase | No futher branch rebase |
| No extraction is performed | Extraction will be performed |
| No PR body update | PR body will be updated |
| We ensure a comment | We ensure a comment|

What do you say? @rarkins

**Comment by rarkins** [comment] 2023-03-09 16:11
I'm not sure how to get this to work.

If the branch is unmodified (with our onboarding default config) we could either:
- Use dependencies from default branch, but config from the onboarding branch, or
- Refresh the onboarding branch each time the default branch is changed

Both should product the same result (in the PR body). The second one is less efficient because we commit more frequently.

The question from this feature request is what to do when the onboarding branch is modified.

I had one idea, not sure if it floats, but..

The onboarding branch will be merged into the default branch. Meaning whatever modifications which have been made will be merged in.

Maybe we can do this:
- Clone the repo
- git merge (locally) the onboarding branch into the default branch
- proceed accordingly (kind of like we do today) by extracting agains the default branch (which now has the content from onboarding branch)

This will mean that default branch SHA we extract from _won't_ be the same as what's on the server, but it shouldn't matter to the user (they are not exposed to SHAs during onboarding). We might need to think about it for caching though.

Second problem is that if the onboarding branch is conflicted with the default branch then we can't merge. But maybe we document that we can't proceed if the onboarding branch is in conflict - user needs to resolve it.

**Comment by RahulGautamSingh** [comment] 2023-03-10 19:32
Can we use the workaround logic mentioned above by author?
We can introduce a new config option say `useOnboardingAsBase`. To enable this user can add it to the `onboardingBranch` thus modifying the branch. 
In our code when we detect a modified onboarding branch we can also check for this option and if it is true we will add `renovate/configure` in the list of `baseBranches` and return null (ie. no rebase) as our goal is to only update the Pr-body and not the branch itself so we don't lose changes made by user.

**Comment by rarkins** [comment] 2023-03-10 20:41
And where would that new config option live? In the `renovate.json` in the onboarding branch?

It just doesn't seem elegant to me.

**Comment by RahulGautamSingh** [comment] 2023-03-11 06:40
Yes its not elegant. Then maybe we can not use a config option and do this whenever the branch is modified.

**Comment by RahulGautamSingh** [comment] 2023-03-11 08:13
@jtdoepke How were you able to get a onboardingPr generated for your reproduction as the `chartfile.yaml` is not recognised by Renovate? When I try the run finishes with
``` INFO: Repository has no package files - skipping ```

**Comment by RahulGautamSingh** [comment] 2023-03-11 10:31
@rarkins I tried what you mentioned and it will work. Just need to make sure the merge and checkout are clean and don't cause trouble in normal flow.

**Comment by rarkins** [comment] 2023-03-11 10:55
Why not merge every time if it works in both cases?

And yes, let's make sure it's local merge only.

Why/when are we calling `isBranchConflicted`?

**Comment by RahulGautamSingh** [comment] 2023-03-11 10:57
We call isBranchConflicted in ensureOnboardingPr function.

**Comment by rarkins** [comment] 2023-03-11 11:07
I expected that type of logic would be executed before we merge

**Comment by RahulGautamSingh** [comment] 2023-03-11 11:11
We don't perform `merge` for onboardingPrs so that check wouldn't be necessary while processing the branch.

**Comment by rarkins** [comment] 2023-03-11 11:24
I thought we were just discussing merging it?

**Comment by RahulGautamSingh** [comment] 2023-03-11 11:29
My bad, I thoguht you meant why it wasn't there to begin with.
Now that we `merge` before it will be efficient to check it before merging aand store the data to be used for later calls.

**Comment by RahulGautamSingh** [comment] 2023-03-11 11:37
Also, there is no point in merging if the oboardingBranch isn't modified as the changes will be same either way.

**Comment by RahulGautamSingh** [comment] 2023-03-11 11:48
There is one moer issue:
The branchIsConflicted result isn't stored because we don't create cache for onbaording branches.
So the possible solutions are:
 Either create add onboardingbranch to branch cache
 Or use the global object to store the value during the run. (we do this for modified result already)

**Comment by rarkins** [comment] 2023-03-11 12:39
We definitely should add onboarding branch info to the cache

**Comment by RahulGautamSingh** [comment] 2023-03-11 13:29
I can begin work now:
1. Implement onboarding cache 
2. Update [this ](https://github.com/renovatebot/renovate/pull/20733)PR and get it merged. 
3. Work on this one https://github.com/renovatebot/renovate/pull/20702
4. Start work on a draftPr for this issue

**Closed** 2023-05-18 06:16 UTC
Labels: type:feature, priority-3-medium, core:onboarding, status:requirements, reproduction:provided
