### ISSUE TITLE
feat(autodiscover): only consider onboarded repositories

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3334] opened 2019-03-08 14:44 UTC
**What would you like Renovate to be able to do?**
I'm trying to enable `autoDiscover` option, but I'd like Renovate to only consider repositories that contain a config file `renovate.json`. 

I thought at first that `--auto-discover true --require-config true` would work for me, but actually it is not. Indeed, in case of no configuration, Renovate will create the onboarding PR - you have to close it so that it stops that.

**Describe the solution you'd like**
I'd like that Renovate does not create an onboarding PR for every repositories, but let users create the `renovate.json` on their own.

**Describe alternatives you've considered**

**Additional context**
Using on Gitlab.

**Comment by rarkins** [comment] 2019-03-08 15:47
So first of all, make sure you are using a dedicated user account for Renovate, e.g. `@renovate-bot`. I think there's too much chance of confusion and conflict if you run it using a regular user's account.

Then the next thing for me to understand is: what is the reason for adding Renovate as a developer to projects you don't want it to run on? e.g. is it because you added it to a group that has access to everything, or some other reason?

**Comment by rarkins** [comment] 2019-03-09 07:36
Thinking this through more:

- You don't want Renovate to ever initiate onboarding for a repo
- You only want Renovate to run in a repo if there's a config

right?

**Comment by bagage** [comment] 2019-03-09 10:23
Yes that's it @rarkins. For info, my user running Renovate is user `@bot`, which run various tools (including [marge bot](https://github.com/smarkets/marge-bot)). This is due to Gitlab licensing limitation (eg. you pay per user; so we use a single account for all robots). Thus this bot has access to a lot of repositories but not necessarly for renovate.

**Comment by rarkins** [comment] 2019-03-09 11:35
There is also a setting called `onboarding` that can be set to false. I'm wondering what the behaviour is with `--autodiscover=true --onboarding=false --require-config=true`.

**Comment by bagage** [comment] 2019-03-11 14:35
I tried and it still creates the configure renovate PR unfortunately. Is this issue a duplicate of #3338?

**Comment by rarkins** [comment] 2019-03-11 15:36
No, that's a separate issue, and I've updated the description just now to make that clearer. Seems like a bug if onboarding=false and yet it still generates an onboarding PR. Can you double check what happens if you rename/close the old PR and make sure the branch is *deleted*? If the old branch was still there, it may have bypassed the check.

**Comment by bagage** [comment] 2019-03-11 16:05
Oops sorry. I've tried with `--onboarding true`.

But setting `--onboarding false` is worse, because Renovate will create actual MRs (eg update libraries), so it directly creates all MRs.

**Comment by rarkins** [comment] 2019-03-11 16:39
It shouldn't do that if `--require-config` is true! Unless some merged PRs already exist, which is a legacy thing. I'll test on a clean repo and see what I can find.

**Comment by rarkins** [comment] 2019-04-09 15:12
Thanks for the confirmation. I’ve switched this to a “fix” label as I think that combination of settings should produce the configuration you expect

**Comment by mdlavin** [comment] 2019-04-09 16:08
I'd really like to see this work as expected. Do you mind if I take a stab
at debugging it and putting up a fix?

**Comment by rarkins** [comment] 2019-04-09 16:12
Of course, you’d be most welcome to try

**Comment by mdlavin** [comment] 2019-04-10 11:50
I tested with the deployed version today and it works much better, but there is an edge case that was missed.

With the new changes, the onboarding branch / PR is still created. Fix is coming ...

**Comment by bagage** [comment] 2019-04-10 12:11
With master and `node lib/renovate.js --git-fs=ssh --recreate-closed true --onboarding false --require-config true --log-level debug bagage/angutest`, the PR is still created and I am seeing in logs:

>  INFO: Need to create onboarding PR (repository=bagage/angutest)
> ...
>  INFO: Creating onboarding branch (repository=bagage/angutest)

**Comment by mdlavin** [comment] 2019-04-10 12:15
@bagage I agree ... see my comment above. I'm testing a fix now

**Comment by mdlavin** [comment] 2019-04-10 13:11
@bagage the [fix is simple](https://github.com/renovatebot/renovate/pull/3519), and I've confirmed it in a local deployment using auto-discovery with a mix of projects that have config files and some that don't. Do you have the power to merge?

**Closed** 2019-04-10 13:43 UTC
Labels: fix, released
