### ISSUE TITLE
Support for Terraform modules located in GHE repository

### ISSUE THREAD

**Issue by patrickmarabeas** [renovatebot/renovate#5115] opened 2020-01-08 07:14 UTC
Looks like support for Terraform modules is limited to github.com repositories (as per the docs) for Renovate Pro as well.

Log:

```
DEBUG: packageFiles with updates (repository=org/repository)
  "config": {
    "terraform": [
      {
        "packageFile": "module.tf",
        "manager": "terraform",
        "deps": [
          {
            "moduleName": "module",
            "managerData": {},
            "source": "git::https://github.corp.domain/org/module.git?ref=v1.0.0 ",
            "skipReason": "no-version",
            "updates": []
          }
        ]
      }
    ]
  }
```

I can probably work around this by using Git Submodules in the mean time as they are supported by Terraform Enterprise.

**Comment by rarkins** [comment] 2020-01-08 08:26
@patrickmarabeas this would need implementing within the core Renovate code so I have transferred the issue and classified it as a feature request.

**Comment by jakauppila** [comment] 2020-01-25 22:59
This appears to be a duplicate of https://github.com/renovatebot/renovate/issues/3209 ?

**Comment by rarkins** [comment] 2020-01-26 07:18
Possibly. We have two different datasources for Terraform (ref: https://github.com/renovatebot/renovate/tree/master/lib/datasource) so possibly we'd have two different issues to close this.

**Comment by secustor** [comment] 2020-01-26 18:46
@rarkins This is a duplicate, as it is not possible to manually define the location of Terraform providers ( except on the local file system).     

This issue is about Terraform modules.

**Closed** 2020-01-26 18:57 UTC
Labels: #terraform, feat, pri3-normal, ready
