### ISSUE TITLE
Support rebase/retry checkbox for onboarding PRs

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#17152] opened 2022-08-12 08:47 UTC
### What would you like Renovate to be able to do?

Support rebase/retry checkboxes on onboarding PRs. This way we can reduce the frequency at which we check them for updates, because users will have the ability to request it be refreshed on-demand.

### If you have any ideas on how this should be implemented, please tell us here.

Same text as we have for regular PRs. But we also need to make sure our logic is in place to do the refresh/force push.

### Is this a feature you are interested in implementing yourself?

No

**Comment by Gabriel-Ladzaretti** [comment] 2022-09-01 10:45
Currently the general onboarding flow is as follows 
1) `initRepo` phase: `checkOnboardingBranch` where we create the branch and commit the `renovate.json` to, this rebases whenever the user edits the config file or when branch is behind base.
2) `extractDependencies` - preform extraction + lookup
3) `ensureOnboardingPr` - Use data from step 2 to create/ensure the onboarding PR.

So as I understand it, we can determine in step 1) if  `rebase` is requested and do/skip steps 2+3 accordingly. as most of the work is done in these two steps.

**Comment by rarkins** [comment] 2022-09-01 11:24
We can use getBranchPr() once we know a branch exists

**Comment by HonkingGoose** [comment] 2022-12-29 21:07
Duplicate of #11770

**Closed by HonkingGoose** 2022-12-29 21:07 UTC
Labels: type:feature, priority-2-high, core:onboarding, status:ready, impact:small
