### ISSUE TITLE
Deprecation Issue not created

### ISSUE THREAD

**Issue by dword-design** [renovatebot/renovate#6478] opened 2020-06-09 17:51 UTC
**What Renovate type are you using?**

Hosted App with GitHub

**Describe the bug**
I create a Node.js project with a deprecated dependency. After pushing, I expect that an issue with a deprecation warning is created.

**Did you see anything helpful in debug logs?**
In the logs I see that the deprecation is detected, but it doesn't lead to a warning.

**To Reproduce**
I built a minimal example here:
https://github.com/dword-design/test-deprecation
I tried both the base config and explicitly setting suppressNotifications to an empty array, but nothing helped.

**Additional context**

**Comment by rarkins** [comment] 2020-06-10 05:19
Depreciation issues in the app are currently disabled due to a previous bug we encountered. I’ll look int testing and enabling them again

**Comment by dword-design** [comment] 2020-06-10 07:51
@rarkins ah ok. Would be great to have this feature enabled again!

**Comment by dword-design** [comment] 2020-07-11 08:42
@rarkins Does this bug only exist in the app or also in the self-hosted tool?

**Comment by rarkins** [comment] 2020-07-11 08:45
I observed them in the app, and they may have been only in the app, but I can't be sure. It was related to subtle differences in how the GitHub API filtering worked when giving it a "real" user vs app pseudo-user. Renovate wanted to say "give me issues I created" but it behaved differently.

**Comment by rarkins** [comment] 2021-12-19 13:02
Duplicate of #5098

**Closed by rarkins** 2021-12-19 13:02 UTC
Labels: type:bug, priority-3-normal, status:ready
