### ISSUE TITLE
Lerna monorepo / npm token for private packages

### ISSUE THREAD

**Issue by AshHeskes** [renovatebot/renovate#2205] opened 2018-07-02 16:32 UTC
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**

When using the renovate Github app within a [Lerna](https://github.com/lerna/lerna) monorepo. The `npmToken` needs to be added to an `.npmrc` in every "Lerna package" dir. Otherwise private packages will not be updated. Lerna does not reuse the .npmrc config in the root dir when invoking `npm` inside  "Lerna packages".

There was a [ticket](https://github.com/renovatebot/renovate/issues/1713) opened for this issue. However it was closed shortly after with no comments or PRs.

Should this be working or is this still an ongoing issue?

**To Reproduce**

1. Create a test private Npm package.
2. publish the test private Npm package.
3. Create repository with a (Lerna monorepo)[https://github.com/lerna/lerna].
4. Create a new Lerna package in the repository.
5. `lerna add <testNpmPackage> --scope <lernaPackageName>`.
6. Add a `renovate.json` containing a valid `npmToken` for the test Npm package.
7. Version bump and republish the private Npm package.
8. Have renovate run over the Lerna repo.

**Expected behavior**

Renovate should open a PR for the updated private Npm package. However it doesn't because the Lerna package using the private Npm package doesn't have a .npmrc file containing a token to access it.

**Comment by rarkins** [comment] 2018-07-02 16:36
@AshHeskes can you confirm exactly how you're configuring the npmrc credentials? e.g. you define an encrypted `npmToken` in your config, and that's it? Is there any `npmrc` field in your config, or `.npmrc` files within the repository itself?

Also, can you email me any affected repositories you have, so that I can check the logs to see what they say?

**Comment by AshHeskes** [comment] 2018-07-02 16:50
@rarkins We are using the our token within the `renovate.json` like so:

```json
{
  "encrypted": {
    "npmToken": "xxxxxxxxxx"
  }
}
```

It was encrypted following the (renovate private modules guide)[https://renovatebot.com/docs/private-modules/].

i.e. (from your docs)

1. use (generate-npm-token)[https://npmjs.com/package/generate-npm-token] to create a token.
2. use (renovate-encrypt)[https://npmjs.com/package/renovate-encrypt] to encrypt it.

**Comment by rarkins** [comment] 2018-07-02 17:02
OK, please let me know the repository as well so that I can confirm if the problem is like you suspect.

**Comment by AshHeskes** [comment] 2018-07-02 17:03
Sent in an email :)

**Comment by rarkins** [comment] 2018-07-02 17:52
I've checked the logs and see:
- encrypted `npmrc` in config
- failed 404 npm lookups for scoped packages
- no token used for those lookups

So I think that's enough to confirm your suspicion and work on a fix.

**Comment by rarkins** [comment] 2018-07-02 18:23
@AshHeskes I just noticed that there are `.npmrc` files in the repository too. Partially redacted logs:

```
{"msg":"GET repos/a/b/contents/.npmrc?ref=master [retries=5]","time":"2018-06-25T18:27:25.030Z"}
{"msg":"GET repos/a/b/contents/packages/x-components/.npmrc?ref=master [retries=5]","time":"2018-06-25T18:27:25.963Z"}
{"msg":"GET repos/a/b/contents/packages/x/.npmrc?ref=master [retries=5]","time":"2018-06-25T18:27:26.303Z"}
```

If these were added in an attempt to fix the problem, then please remove them so I can see the behaviour without. Otherwise, I need a bit more description from you about these so I can understand their purpose and if we can ignore them.

**Comment by AshHeskes** [comment] 2018-07-03 08:58
@rarkins Yes that was placed in there in an attempt to fix and they have been removed. The repo should be behaving normally now.

**Comment by AshHeskes** [comment] 2018-07-03 09:12
@rarkins Well to be specific we have `.nmprc` files in root and some Lerna packages. But we are using them for different Npm config not for the token. We added a temp token to the root `.npmrc` file in order to see if that could be a fix.

I guess this means your job a little more complex as you would need to append the Npm token config to `.npmrc` files in Lerna packages if one exist otherwise create the `.npmrc`.

Also another thing to consider (although it's not a problem for our use case) would be private packages from repositories other than Npm and @scoped packages. I'm not sure if you already cater for this outside of repos using Lerna. So I just thought I would mention it.

**Comment by rarkins** [comment] 2018-07-03 09:20
Right, so *appending* `.npmrc` files is definitely not supported right now, although I have wondered in the past whether it would be necessary one day. What led me not to do it originally was because `npm` itself does not seem to "append", e.g. if it finds a `.npmrc` file in the current working directly then it doesn't seem to look for `~/.npmrc`. 

Can you tell me what the contents are like in the various `.npmrc` files in root and within packages? Redacted if necessary of course, but it sounds like you don't have tokens in them currently. I want to make 100% sure I understand what's going on.

Can you also tell me how you as developers as well as your CI system use tokens?

**Comment by AshHeskes** [comment] 2018-07-03 11:20
Ah perhaps we've got our wires crossed regarding "append". What I meant was append the token to any local `.npmrc` files I.E. those in the root of the project or in Lerna packages. However I'm not sure if that is needed. It depends on if there's any Npm config that would impact renovate. In our case we only have `save-exact = true` in our `.npmrc` files which has no effect on renovate (as far as I'm aware). So overwriting local `.npmrc` files in our case would be fine.

As developers locally we all just do `npm login` which gives us access to private packages. In CI we have the token as an environment variable and write an `.npmrc` file containing `//registry.npmjs.org/:_authToken=${NPM_TOKEN}`.

**Comment by rarkins** [comment] 2018-07-03 11:21
Thanks, that's helpful. So the `.npmrc` file you write for CI that has `${NPM_TOKEN}` inside is *not* checked into the repo?

**Comment by AshHeskes** [comment] 2018-07-03 11:23
That's right it's written by the CI.

**Comment by rarkins** [comment] 2018-07-03 14:04
Updating for the record:

- The `.npmrc` files in subdirectories - which have no authentication within - were "overwriting" the configured npmrc/npmToken, so no authentication was being used to look up npm updates within those directories

- There already existed a setting `ignoreNpmrcFiles` which fixes this. It was *meant* to be automatically enabled once the configured npmrc/npmToken was found, but there was a mistake in this logic so Renovate was still retrieving the `.npmrc` files. A bugfix was implemented to fix the logic so that `.npmrc` files are ignored automatically 

I think @AshHeskes can hopefully confirm that it's now working and can close this issue.

**Closed** 2018-07-04 08:22 UTC
Labels: fix, needs-requirements

**Comment by AshHeskes** [comment] 2018-07-04 11:32
@rarkins Yes all is working now. Thanks for your help and swift response :)
