### ISSUE TITLE
Recreate merged PRs if updates are available  

### ISSUE THREAD

**Issue by TheKangaroo** [renovatebot/renovate#19938] opened 2023-01-20 10:14 UTC
### What would you like Renovate to be able to do?

This is basically a reopen of [#16820](https://github.com/renovatebot/renovate/issues/16820). This issue was closed with PR https://github.com/renovatebot/renovate/pull/16898 which was reverted one day later https://github.com/renovatebot/renovate/pull/17699 . 

I use 
```
    "docker:pinDigests",
    "default:automergeDigest",
```
to pin and auto merge docker digest in gitlab ci files.
The pin dependency PR works the first time I onboard a repo to renovate, but when I add an image in the gitlab ci file later on, renovate won't create a pin dependencies PR for the new image because of the already merged pin dependency PR.
Relevant debug log:
```
DEBUG: getBranchPr(renovate/pin-dependencies) (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: findPr(renovate/pin-dependencies, undefined, open) (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: branchExists=false (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: dependencyDashboardCheck=undefined (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: recreateClosed is false (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: findPr(renovate/pin-dependencies, chore(deps): pin dependencies, !open) (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: Found closed PR with current title (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: getPr(757) (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: getMR(757) (repository=myrepo, branch=renovate/pin-dependencies)
DEBUG: Closed PR already exists. Skipping branch. (repository=myrepo, branch=renovate/pin-dependencies)
       "prTitle": "chore(deps): pin dependencies"
```

### If you have any ideas on how this should be implemented, please tell us here.

no idea, see https://github.com/renovatebot/renovate/issues/16820

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment] 2023-01-20 11:47
This turned out to be difficult the first time we attempted it, so we've decided to park it for now. A community contribution would be welcome though (please see the previous attempt)

**Comment by viceice** [comment] 2023-01-20 15:22
Duplicate of #16820

i've reopened the original issue

**Comment by viceice** [comment] 2023-01-20 15:23
Duplicate of #16820

**Closed by viceice** 2023-01-20 15:22 UTC
Labels: type:feature, help wanted, priority-3-medium, status:ready
