### ISSUE TITLE
composer versioning should match PHP's version_compare

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#9657] opened 2021-04-20 19:51 UTC
**What Renovate type, platform and version are you using?**

Any

**Describe the bug**

Renovate's version comparing, which is semver 2.0-comparible, does not match that used by Composer, which utilizes PHP's version_compare: https://www.php.net/manual/en/function.version-compare.php

**Relevant debug logs**

None

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

https://github.com/renovatebot/renovate/issues/9097#issuecomment-823460963

**Comment by JorisVanEijden** [comment] 2021-04-30 12:53
Duplicate of #6899 ?

**Closed** 2021-04-30 13:10 UTC
Labels: priority-3-normal, status:ready, type:bug, versioning:composer
