### ISSUE TITLE
Pipenv case-sensitivity issues

### ISSUE THREAD

**Issue by Bruceforce** [renovatebot/renovate#11867] opened 2021-09-23 16:50 UTC
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:27.18.0-slim@sha256:f98bd8eccde499daaeb1b6ae47dabe778c10f2ad83e5e9d7f6c2f3707de5ac30

### Describe the bug

Renovate bot fails to lookup dependencies defined in Pipenv if the case in the Pipfile does not match the case in pypi. This can be fixed by either:
* changing the source.url to `https://pypi.org/pypi/` in the Pipfile or
* Change the case from flask to Flask in the Pipfile

However since the Pipfile in the reproduction repo was created by just issuing the command `pipenv install flask==2.0.0` this issue should be resolved since `https://pypi.org/simple` is the default registry for Pipenv.

Here is a minimal reproduction repo: <https://gitlab.com/1O/pipenv-case-issue>

This bug is most likely related to #11139.  

### Relevant debug logs

<details><summary>Logs</summary>

```
{
    "name": "renovate",
    "hostname": "runner-z3wu8uu--project-29850052-concurrent-0",
    "pid": 11,
    "level": 20,
    "logContext": "k6lMZ4C2G",
    "repository": "1O/pipenv-case-issue",
    "config": {
        "gitlabci-include": [
            {
                "packageFile": ".gitlab-ci.yml",
                "deps": [
                    {
                        "datasource": "gitlab-tags",
                        "depName": "renovate-bot/renovate-runner",
                        "depType": "repository",
                        "skipReason": "unknown-version",
                        "registryUrls": [
                            "https://gitlab.com"
                        ],
                        "depIndex": 0,
                        "updates": []
                    }
                ]
            }
        ],
        "pipenv": [
            {
                "packageFile": "Pipfile",
                "deps": [
                    {
                        "depType": "packages",
                        "depName": "flask",
                        "managerData": {},
                        "currentValue": "==2.0.0",
                        "datasource": "pypi",
                        "depIndex": 0,
                        "updates": [],
                        "warnings": [
                            {
                                "topic": "flask",
                                "message": "Failed to look up dependency flask"
                            }
                        ],
                        "versioning": "pep440"
                    }
                ],
                "registryUrls": [
                    "https://pypi.org/simple"
                ],
                "lockFiles": [
                    "Pipfile.lock"
                ],
                "constraints": {
                    "python": "== 3.8.*"
                }
            }
        ]
    },
    "msg": "packageFiles with updates",
    "time": "2021-09-23T16:31:41.269Z",
    "v": 0
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment] 2021-09-23 16:56
related to #6921

**Comment by viceice** [comment] 2021-09-23 16:58
Looks like

Duplicate of 11139

**Comment by viceice** [comment] 2021-09-23 16:59
Duplicate of #11139

**Comment by viceice** [comment] 2021-09-23 17:00
Can you please post your repro findings to the other issue AS both managers are using our `pypi` datasource, so it's the same issue.

**Closed by viceice** 2021-09-23 17:00 UTC
Labels: type:bug, datasource:pypi, status:requirements, priority-5-triage
