### ISSUE TITLE
Go updates should run go mod tidy to remove old entries

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2594] opened 2018-10-02 20:42 UTC
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Go updates leave duplicate entries in go.sum.
These need to be removed with `go mod tidy`.
https://github.com/sourcegraph/renovate-dependency-test/pull/2/files#diff-f949e2d81c8076ebbf8af38fcbb72c1fR3

Here's information why go modules behave this way: https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using

**Comment by felixfbecker** [comment] 2018-10-03 21:31
Yeah, thinking about it, I agree. I was just worried about a go.sum file that grows by one line for every update. A config sounds the best.

**Comment by prymitive** [comment] 2018-12-23 08:52
@rarkins points are what my understanding of go modules behaviour was after reading the docs, so I 100% that running tidy should be considered an opt-in feature.
A feature I would appreciate but for a different reasons - tidy command will not only remove old versions but also add missing lines, so I wanted to run it in CI to ensure that both files are populated and fail the job if it generates any git diff. But for that to work tidy needs to be run after every renovate job so there are no old entries that could be removed by tidy.

**Comment by rarkins** [comment] 2018-12-29 06:40
@prymitive have you been able to verify that "go mod tidy" produces predictable/repeatable output? I recall there were issues in the go repo previously about "go mod tidy" producing a different output from "go get" so it led me to believe that doing something a "git status" could produce false hits.

BTW you could possibly in the meantime still run "go mod tidy" in CI but then git diff and ignore *removed* lines from the calculation. That way you can still fail your own PRs if there are missing lines but pass Renovate ones that have lines that could be removed.

Also, are you running self-hosted or the app?

**Comment by prymitive** [comment] 2018-12-29 21:41
I didn't look into it that much to be sure about it, but remember that from my testing dependencies will be injected into `go.*` files when they are needed - build deps will be added on build, test deps will be added on the first test run. So I would expect `go get` to only add build dependencies (assuming nothing in go runs tests during `go get`) - whenever `go mod tidy` looks for test deps I don't know, didn't look into it.

I'm using hosted plan. I tried a few different tools for this, there's lots of other really great solutions on marketplace, but renovate feels much more tuned to how I want it to behave.
I'm not too concerned about this right now, especially that modules are still an experiment and they come with some rough edges, so things will change and I didn't have much time to investigate it in depth yet.
My main motivation to look into it was that I want to avoid getting git diff when someone builds my project on "not my laptop", mostly because I've learned my lesson with npm producing different lock files on linux and macOs. This wasn't an issue with dep, since it only maintained vendor dir and go builds wouldn't in any way affect lock file, but now go modules are more like npm - same tool handles both producing and consuming deps.

**Closed** 2019-02-13 18:05 UTC
Labels: #golang, feat, pri4-low, ready

**Comment by rarkins** [comment] 2019-02-13 18:16
This has now been released and hopefully runs as intended. Add `gomodTidy: true` to config to enable it.

The repo needs to have `gitFs` enabled to begin with, otherwise a warning will be issued. For the app, I am watching logs for any such warnings and then switching them to gitFs manually until the day when all repos are cut over.
