### ISSUE TITLE
Renovate doesn't work with new LetsEncrypt ISRG Root X1 intermediate CA

### ISSUE THREAD

**Issue by Ebrithil95** [renovatebot/renovate#11974] opened 2021-09-30 18:15 UTC
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:27.23.0-slim

### Describe the bug

Today the old intermediate DST Root CA X3 from LetsEncrypt expired [Blog Post](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)
My selfhosted GitLab instance uses the new ISRG Root X1 certificate that LetsEncrypt uses now.

But now i get an invalid certificate error when running renovate

### Relevant debug logs

<details><summary>Logs</summary>

```
{
             "message": "fatal: unable to access 'https://git.ebrithil.dev/ta/dotnet-backend.git/': server certificate verification failed. CAfile: none CRLfile: none\n",
             "stack": "Error: fatal: unable to access 'https://git.ebrithil.dev/ta/dotnet-backend.git/': server certificate verification failed. CAfile: none CRLfile: none\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by jokay** [comment] 2021-09-30 18:17
Duplicate of https://github.com/renovatebot/renovate/issues/11973?

**Comment by viceice** [comment] 2021-09-30 18:20
Duplicate of #11973

**Closed by viceice** 2021-09-30 18:21 UTC
Labels: type:bug, status:requirements, priority-5-triage
