### ISSUE TITLE
Gitlab MRs not updated and marked with "MR has been edited" comment on 2nd run

### ISSUE THREAD

**Issue by dominik-bln** [renovatebot/renovate#3619] opened 2019-05-01 09:29 UTC
**What Renovate type are you using?**
Renovate CLI v16.7.4

**Describe the bug**

MRs in Gitlab are correctly opened but the bot adds a comment that the "MR has been edited" the next time it runs even though they only have the single renovate commit and then does not update the MRs anymore.

**Did you see anything helpful in debug logs?**

Only basic info output that the MRs are created on 1st run and this on the 2nd run:

```bash
INFO: Added comment (repository=alpha%2Falpha, dependencies=django-taggit, branch=ren/django-taggit-0.x)
       "issueNo": 2383
 INFO: Added comment (repository=alpha%2Falpha, dependencies=django-watchman, branch=ren/django-watchman-0.x)
       "issueNo": 2384
```

**To Reproduce**

Not completely sure, please let me know if I can somehow help to reproduce this.

Only thing I can say is that this was not present on Renovate v14.x, but as we also update Gitlab frequently it could have been caused by a recent update of Gitlab as well.

**Expected behavior**

Renovate continues to update the MRs when a new update arrives before they are merged.

**Screenshots**

Every single renovate MR has one comment by the bot (disregard the pipeline errors, they are caused by a different issue):

<img width="1326" alt="Screenshot 2019-05-01 at 11 19 24" src="https://user-images.githubusercontent.com/855119/57011756-84c95700-6c03-11e9-9c39-978011537b6a.png">

All of the MRs have just the single bot commit:

<img width="1282" alt="Screenshot 2019-05-01 at 11 09 06" src="https://user-images.githubusercontent.com/855119/57011757-84c95700-6c03-11e9-96f2-acab6c005186.png">

**Additional Context**

Gitlab is self hosted in version 11.10.1

**Comment by rarkins** [comment] 2019-05-01 09:36
Are you using gitFs, or regular API-based committing?

**Comment by dominik-bln** [comment] 2019-05-01 09:50
Regular commits via CLI.

**Comment by Autre31415** [comment] 2019-05-02 17:06
I'm seeing this bug as well after updating renovate, so it must have been introduced within the past month or so.

Gitlab Community Edition 11.10.0

**Comment by toxsick** [comment] 2019-05-02 20:35
Same thing here:

<img width="994" alt=" prime-evaluate · GitLab 2019-05-02 22-32-20" src="https://user-images.githubusercontent.com/951466/57105071-2f3b9a00-6d2a-11e9-98dc-8b049fc14305.png">

Gitlab CE 11.8.0
Renovate 16.10.4

**Comment by rarkins** [comment] 2019-05-02 21:04
Is anyone able to approximate which Renovate release this happened in?

We create this comment if `pr.canRebase === false`: https://github.com/renovatebot/renovate/blob/49c4ad07c7b6230fe44313987a20caf9470030a5/lib/workers/branch/index.js#L126

`canRebase` is set during `getPr()`, and it sets it to true if the last committer matches the bot's email: https://github.com/renovatebot/renovate/blob/49c4ad07c7b6230fe44313987a20caf9470030a5/lib/platform/gitlab/index.js#L700-L706

The bot's email is set during init: https://github.com/renovatebot/renovate/blob/49c4ad07c7b6230fe44313987a20caf9470030a5/lib/platform/gitlab/index.js#L124

I can't figure out where the logic is failing. Commit history for gitlab platform is here: https://github.com/renovatebot/renovate/commits/master/lib/platform/gitlab/index.js

**Comment by toxsick** [comment] 2019-05-02 21:11
For me this seems to have started somewhere between v16.5.4 and v16.5.8 and the 25.04 I think

**Comment by rarkins** [comment] 2019-05-02 21:38
That would point at this commit, but I can't work out why: https://github.com/renovatebot/renovate/commit/788215a

**Comment by rarkins** [comment] 2019-05-02 21:47
I've added extra debugging in `renovate@16.10.5`: https://github.com/renovatebot/renovate/commit/d3dbd93

**Comment by dominik-bln** [comment] 2019-05-03 18:59
```bash
DEBUG: Last committer to branch does not match bot email, so PR cannot be rebased. (repository=leave-manager/lm_frontend, dependencies=jquery, branch=renovate/jquery-3.x)
       "branchCommitEmail": "bot@renovateapp.com",
       "configEmail": "renovate-bot@something.private",
       "iid": 137
```

**Comment by dominik-bln** [comment] 2019-05-03 19:25
I've added `gitAuthor: 'Renovate Bot <renovate-bot@something.private>'` to the config now and am waiting on the next MR to be opened.

**Comment by dominik-bln** [comment] 2019-05-04 07:46
Setting `gitAuthor` with the email of the bot user fixes the problem for us.

**Comment by ViceIce** [comment] 2019-05-04 16:59
renovate v17 drops api based git operations, so this should fixed by #3601

**Comment by ViceIce** [comment] 2019-05-04 17:01
try to use `gitFs=http` or `https` or `ssh` as workaround for now. `gitAuthor` should always be set on self-hosted renovate.

**Comment by rarkins** [comment] 2019-05-04 17:17
@ViceIce thanks for chiming in. I held back on mentioning it myself as I wasn't 100% sure if the same problem would happen in v17 if `gitAuthor` was still unset. i.e. maybe the problem is independent of `gitFs`?

**Comment by ViceIce** [comment] 2019-05-04 17:50
I've never seen this problem on my self-hosted gitlab instance

**Comment by dominik-bln** [comment] 2019-05-05 22:50
I'm happy with closing as this was mainly a configuration issue. Some UX notes from my user perspective:

- at least when I configured it, the docs weren’t clear that `gitAuthor` needs to be set
- I somehow expected the bot to know its email without configuration (I see that this is probably not trivial though)
- logging the user mismatch at `Info` level could help other users to find the misconfiguration
- the docs of `gitAuthor` could use an example, the RFC mentioned is pretty long and not really specific to the problem at hand

Thanks everyone for looking into this.

**Comment by toxsick** [comment] 2019-05-06 08:01
For me it was also solved by passing the email address of the renovate user with `--git-author` from the commandline. Understanding what what happened now I agree with @dominik-bln that the user mismatch should at least appear in Info log level.

Thanks everybody!

**Comment by rarkins** [comment] 2019-06-17 14:03
The latest Renovate detects the email address of the bot account and uses that as gitAuthor, so this problem should now be resolved. Make sure your tokens include user permissions though so that the email address can be read.

**Closed by rarkins** 2019-06-17 14:03 UTC
Labels: #gitlab, fix, help wanted, pri2-important, ready
