### ISSUE TITLE
Gradle: dependency versions via variables are always lower-case's

### ISSUE THREAD

**Issue by snazy** [renovatebot/renovate#17703] opened 2022-09-08 09:31 UTC
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Would be much nicer, if Renovate keeps the variable names as they are, at least for build systems with case-sensitive variable/parameter names like Gradle variables or Maven property names.

The PR titles would be easier to read with the variable name as it is.

Example: [This PR](https://github.com/snazy/nessie/pull/1213) updates the variable `versionSlf4j` (capital `S`), but the PR title updates it to `versionslf4j` (`s`).

Current title:
```
fix(deps): update versionslf4j to v2 (major)
```

Expected title:
```
fix(deps): update versionSlf4j to v2 (major)
```

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment] 2022-09-08 10:01
Duplicate of #12062, which I just reopened.

**Closed by rarkins** 2022-09-08 10:01 UTC
Labels: type:bug, status:requirements, duplicate, priority-5-triage

**Comment by HonkingGoose** [comment] 2022-09-08 10:07
Duplicate of #12062
