### ISSUE TITLE
Bitbucket server: Add support for issues

### ISSUE THREAD

**Issue by Mause** [renovatebot/renovate#16167] opened 2022-06-21 08:15 UTC
### What would you like Renovate to be able to do?

I would like Renovate to be able to open Jira cards for Bitbucket server configuration issues

### If you have any ideas on how this should be implemented, please tell us here.

The documentation for this is quite lacking, but https://docs.atlassian.com/bitbucket-server/rest/5.3.0/bitbucket-jira-rest.html exists.

There is also the rest resource at `https://.../rest/jira-integration/1.0/servers` that returns information about the linked Jira server. It's possible that we could POST to `/rest/jira-integration/1.0/issues` to create the cards

The WADL for the endpoint is also available at `/rest/jira-integration/1.0/application.wadl`

<details>
```xml
```
</details>

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment] 2022-06-21 08:54
Duplicate of #3796

**Closed by viceice** 2022-06-21 08:54 UTC
Labels: type:feature, status:requirements, priority-5-triage

**Comment by Mause** [comment] 2022-06-21 08:55
@viceice can that card please be labelled correctly? It's labelled for bitbucket, when it's actually about bitbucket-server
