### ISSUE TITLE
Transfer Renovate's `togithub.com` redirect domain to GitHub

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#29370] opened 2024-05-31 11:52 UTC
### Describe the proposed change(s).

Renovate's `togithub.com` redirect domain got blocked by GitHub's Umbrella protection system. This block is now reverted, so the redirect works properly again. But maybe having the domain controlled by GitHub officially is better.

`@rarkins` said:

> I would be happy to transfer `togithub.com` to GitHub naturally - the community would benefit by being able to link to GitHub endpoints without triggering backlinks

> I suspect something like `https://to.github.com/` would be better long term, with a 301 permanent redirect from `togithub.com` to `to.github.com`. Alternatively having GitHub unblock `togithub.com` it is suitable :)

`@gr2m` offered to contact somebody from GitHub about transferring the domain to GitHub, and will ping us when they hear something.

Related discussion:

- #27568

**Comment by HonkingGoose** [comment] 2024-05-31 12:07
@gr2n can you post a comment on this issue, so I can assign it to you? Seeing as you're doing the first step of contacting someone internally at GitHub.

I can only assign people that have commented on the issue, or are part of the Renovate team. So that's why I need you to comment. :upside_down_face:

**Comment by rarkins** [comment] 2024-05-31 17:08
It causes "backlink spam". The worst is when release notes include a username. That person could wake up to hundreds or thousands of GitHub notifications. But even merged PRs could get pages of annoying back links from every public repository which gets an upgrade PR referencing it

**Comment by HonkingGoose** [comment] 2024-05-31 18:00
I'll assign both of you to the issue, because we need `@gr2m` for the making-contact-phase, and `@rarkins` later for the transfer.

**Comment by gr2m** [comment] 2024-05-31 20:50
> The worst is when release notes include a username. That person could wake up to hundreds or thousands of GitHub notifications

I don't think that happens if you escape them, which I think you already do? `@gr2m` -> `[@gr2m](https://github.com/gr2m)`. I'm just tried if the same works with links to avoid backlinks, but [that didn't work](https://github.com/gr2m/sandbox/issues/269).

I only know the togithub.com redirect URLs from the package link, like here: https://github.com/semantic-release/semantic-release/pull/3326, where it just links to the repository

![screenshot](https://github.com/renovatebot/renovate/assets/39992/49b852f4-f7e4-4b9c-991f-045f2d11dce9)

This could be linked directly to the repository, right?

From what you are saying is that you replace all `github.com` links with the `togithub.com` domain?

**Comment by rarkins** [comment] 2024-05-31 21:31
We replace all to be careful. Otherwise you can't escape them enough without breaking the links

**Comment by rarkins** [comment] 2024-05-31 21:32
We also don't want the task of playing "catch up" every time there's some new way we discover to accidentally backlink and someone gets spammed for a while. This approach has been successful for years now!

**Comment by gr2m** [comment] 2024-05-31 22:29
The problem is notification and backlink spam, right? Using togithub.com is a solution to that, but maybe there is something else that GitHub can do. I'll think about it and see if I find folks within GitHub to talk about it

**Comment by rarkins** [comment] 2024-06-01 05:48
That's exactly right

**Comment by HonkingGoose** [comment] 2024-06-01 07:30
What if as GitHub app creator you could select a backlink mode?

By default, GitHub would _not_ show backlinks, to prevent bot/app creators from accidentally spamming a repository/users with links. The _new_ default would be a breaking change compared to the _current_ default behavior! 

Currently GitHub _will_ link back for every reference to an Issue or PR.

If you _do_ want the app/bot to backlink to Issues, PRs, you can _opt-in_ with a special toggle. This toggle should have clear text explaining the behavior you'll get, and _ask again_ if you're sure! Like how GitHub asks you to be really sure and confirm again for "potentially dangerous/difficult to revert actions" like transferring repo ownership, making a private repo public and so on.

If GitHub wants to keep the current behavior as default, that's fine also. The main thing is to give app/bot creators a choice. And to give creators peace of mind they're not accidentally spamming users.

**Comment by Valexaa** [comment] 2024-06-05 07:11
This kinda thing about connecting to Github really stress me out

**Comment by HonkingGoose** [comment] 2024-08-23 11:19
`@oliviertassinari` said: [^1]

> Dependabot uses `redirect.github.com` maybe a better option.

I'll let the maintainers decide which is best:

- Give our `togithub.com` domain to GitHub, or
- Drop our custom `togithub.com` domain, and use official `redirect.github.com`

If we decide to use the official redirect domain, we probably should ask for permission from GitHub first? That's because Renovate creates a _lot_ of redirect links, and has a lot of users.

[^1]: https://github.com/renovatebot/renovate/discussions/10796#discussioncomment-10413066

**Comment by rarkins** [comment] 2024-08-23 11:35
We should use redirect.github.com

**Closed** 2024-08-23 12:11 UTC
Labels: priority-3-medium, type:refactor
