### ISSUE TITLE
@types grouping with sibling packages

### ISSUE THREAD

**Issue by pvinis** [renovatebot/renovate#4893] opened 2019-11-27 12:06 UTC
**What Renovate type are you using?**
Regular one on Github.

**Describe the bug**

Packages like `react` and types associated with them like `@types/react` don't get updated in the same PR.

By default, DefinitelyTyped is keeping the first 2 numbers of the versions in sync, so `react@1.2.x` will have `@types/react@1.2.y`.

When renovate tried to upgrade to `react@2.0.x`, it should also go to `@types/react@2.0.y`. 

**Did you see anything helpful in debug logs?**

Not really.

**To Reproduce**

https://github.com/pvinis/bug-renovate-types-sync

Here I have `react` and `@types/react`, `react-native` and `@types/react-native`. All of them are not in their latest version.

I got the PR for pinning, merged it.

After that I got https://github.com/pvinis/bug-renovate-types-sync/pull/3 and https://github.com/pvinis/bug-renovate-types-sync/pull/4 to upgrade the `@types` deps, both are not pointing in versions that in theory are incompatible with the package version of `react` and `react-native`.

Soon I will get PRs for upgrading `react` and `react-native`.

As I see it, there are 2 things here that should go differently.
- `@types/react` should be upgraded in the same PR as `react`. (same for `react-native`)
- `@types/react` should not offer to upgrade to something that's later than the `react` version we have. (that one is not as important)

**Additional context**

**Comment by pvinis** [comment] 2019-11-27 12:10
I just noticed in a private repo that `react-redux` and `@types/react-redux` were grouped.
![Screenshot 2019-11-27 at 13 09 17](https://user-images.githubusercontent.com/100233/69722383-3cc9ce80-1117-11ea-9f4c-a0ab17d1f539.png)

Could it be that `react` and `react-native` are somehow not matched correctly?

**Comment by rarkins** [comment] 2019-11-27 12:13
Synchronising `@types` versions is actually a duplicate of one of the oldest issues we have opened: #519

It's actually a pretty challenging problem, although maybe one day we'll work out an elegant way to solve it.

The second part is why these types aren't being grouped together with their parent package. In this case, it's because the react packages are being specifically grouped: https://github.com/renovatebot/presets/blob/72658888f765b52b8b314a7894a3655dccd85548/packages/renovate-config-monorepo/package.json#L344-L349

We ideally would have an automated way to group these types but right now it's another hard problem!

**Comment by pvinis** [comment] 2019-11-27 12:17
Thanks for the info. I am familiar with the `renovate-config-monorepo` part, but I didn't know this basically "breaks" the normal way.

So there is nothing I/we can do to help for this? Do we just need to wait for the renovate team to work it out?

**Comment by rarkins** [comment] 2019-11-27 13:51
Locally you could define your own package rule like this:

```json
{
  "packageNames": ["@types/react", "@types/reactive-native"],
  "groupName": "react monorepo"
}
```

And this could put the types into the same group as the main packages. But it won't do anything about the "sync" problem with versions.

**Comment by falkenhawk** [comment] 2020-11-26 08:43
> 
> 
> Locally you could define your own package rule like this:
> 
> ```json
> {
>   "packageNames": ["@types/react", "@types/reactive-native"],
>   "groupName": "react monorepo"
> }
> ```
> 
> And this could put the types into the same group as the main packages. But it won't do anything about the "sync" problem with versions.

@rarkins wouldn't it be just enough for now if renovate treats `@types` the same way as in https://github.com/renovatebot/renovate/pull/1368 but that it also works for packages listed in the default monorepo package groups? 🤔 It looks like the monorepo grouping takes precedence and disables the standard `@types` treatment.

**Comment by rarkins** [comment] 2020-11-26 09:06
No, it wouldn't work. 

#1368 makes it so that `@types/foo` goes into a branch like `renovate/foo-1.x` instead of `renovate/types-foo-1.x`. This works if you don't have grouping. 

Meanwhile monorepo grouping is based on source URL and `@types/` packages come from a different source. And the branch name is like `renovate/react-monorepo`.

**Closed** 2021-08-08 12:25 UTC
Labels: type:feature, priority-3-normal, manager:npm, status:requirements
