### ISSUE TITLE
Kubernetes: Renovate hasn't opened a PR in serveral days

### ISSUE THREAD

**Issue by ggilmore** [renovatebot/renovate#3145] opened 2019-01-31 18:19 UTC
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
In both https://github.com/sourcegraph/deploy-sourcegraph-dot-com and https://github.com/sourcegraph/infrastucture, we configured Renovate to update our docker image tags in our Kubernetes manifests. We've just noticed that Renovate hasn't opened a PR in ~ 24 hours (https://github.com/sourcegraph/deploy-sourcegraph-dot-com) / 4 days (https://github.com/sourcegraph/infrastructure).

**Did you see anything helpful in debug logs?**

**https://github.com/sourcegraph/deploy-sourcegraph-dot-com**: 

[(Click here for sourcegraph/deploy-sourcegraph-dot-com's Renovate job dashboard)](https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph-dot-com)

In our renovate.json, we set a up a group for all of our sourcegraph-related docker images:

```js
"packageRules": [
  {
    "packagePatterns": [
      "^sourcegraph/"
    ],
    "groupName": "Sourcegraph Docker images",
    // ...
  }
]
```

Renovate has previously been able to create PRs and automerge them. (See https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph-dot-com/42598925). Our renovate.json config hasn't changed in 17 days, so I don't think anything changed on our end. 

**https://github.com/sourcegraph/infrastructure**: 

[(Click here for sourcegraph/infrastructure's Renovate job dashboard)](https://renovatebot.com/dashboard#github/sourcegraph/infrastructure)

In our renovate.json, we set a up a group for all of our sourcegraph-related docker images within a certain sub-directory:

```js
"packageRules": [
    {
      "paths": [
          "kubernetes/dogfood/server/**", 
          "kubernetes/dogfood/lang/**"
       ],
      "groupName": "Sourcegraph Docker images",
      "semanticCommits": false,
     // ...
    }
]
```

Renovate has previously been able to create PRs and automerge them. Our [job log in the Renovate dashboard](https://renovatebot.com/dashboard#github/sourcegraph/infrastructure) also appears to be completely blank:

![screen shot 2019-01-31 at 10 16 22 am](https://user-images.githubusercontent.com/9022011/52075550-7060ba00-2541-11e9-88d2-cea43ddd867b.png)

Our renovate.json config hasn't changed in 16 days, so I don't think anything changed on our end.

(We previously ran into a similar issue in https://github.com/renovatebot/renovate/issues/2953)

Is there anything that we can do to debug this?

**Comment by rarkins** [comment] 2019-01-31 18:36
Hi @ggilmore thanks for the details. I just queued up some high priority manual jobs for all your repos to force them through. I think something went wonky with the queueing and will determine the root cause of that too. Leaving open until I've done so.

**Comment by rarkins** [comment] 2019-01-31 19:04
I found the queuing bug and fixed it, so now closing. Thanks for the heads-up

**Closed by rarkins** 2019-01-31 19:04 UTC
