### ISSUE TITLE
PR declined in Bitbucket keeps being recreated

### ISSUE THREAD

**Issue by carlosfunk** [renovatebot/renovate#2859] opened 2018-11-21 20:52 UTC
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate created a PR to upgrade to Bootstrap 4, I declined the PR and the during the next run Renovate created a new PR.

**Did you see anything helpful in debug logs?**

```
DEBUG: processBranch with 1 upgrades (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: branchExists(renovate/bootstrap-4.x) (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: getBranchPr(renovate/bootstrap-4.x) (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: findPr(renovate/bootstrap-4.x, null, open) (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: getPrList() (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: branchExists=true (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: Branch has 1 upgrade(s) (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: recreateClosed is false (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: findPr(renovate/bootstrap-4.x, Update dependency bootstrap to v4, MERGED,DECLINED,SUPERSEDED) (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: getPrList() (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: prAlreadyExisted=false (repository=completecc/madc-web-client, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
```

<img width="598" alt="declined" src="https://user-images.githubusercontent.com/907689/48867794-46519400-ee3c-11e8-88c3-6a5ea91f21b4.png">

<img width="524" alt="new" src="https://user-images.githubusercontent.com/907689/48867808-4ce00b80-ee3c-11e8-9573-295b59b66bf2.png">

**Comment by rarkins** [comment] 2018-11-21 21:30
Thanks again @carlosfunk for the bug report. Looks like that findPr function is malfunctioning.

**Comment by rarkins** [comment] 2018-11-21 22:45
Confirmed. Root cause is mostly related to getPrList() though. By default Bitbucket's API returns only open PRs. To get non-open ones looks like we need to query three times for MERGED, SUPERSEDED, DECLINED.

**Comment by iamstarkov** [comment] 2018-11-22 21:35
@rarkins nay, you can include all states into query parameter I think. Like `state=one,two,three`

**Comment by rarkins** [comment] 2018-12-07 12:57
> By default only open pull requests are returned. This can be controlled using the state query parameter. To retrieve pull requests that are in one of multiple states, repeat the state parameter for each individual state.

**Closed** 2018-12-08 05:48 UTC
Labels: #bitbucket, fix, in progress, pri2-important
