### ISSUE TITLE
Meta-Dashboard for all repositories

### ISSUE THREAD

**Issue by lathspell** [renovatebot/renovate#19324] opened 2022-12-09 12:02 UTC
### What would you like Renovate to be able to do?

Create a "meta dashboard" that contains information for all registered repositories.

The current dependency dashboard and merge requests are greate for projects that are actively worked on and where thus people do notice these MRs. But sometimes you have a lot of little projects and some just aren't looked at for month. There the dependency update MRs are piling up.

It would be nice to have one dashboard in the Renovate project itself that gives an overview over all registered projects to quickly see if one stands out with too many open issues: 

    project X
    * fix(deps): update dependency org.flywaydb:flyway-core to v9.10.0
    * major update to SpringBoot 3

   project Y
    *  fix(deps): update 5 minor dependencies
    
   project Z
   * major update to SpringBoot 3
   * minor update to SpringBoot 2.7.9

### If you have any ideas on how this should be implemented, please tell us here.

Collect the links to the generated tasks while iterating over all the repositories. At the end create a dashboard in the renovate project itself with all those links. 

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment] 2022-12-09 13:45
- Duplicate of #7372

**Closed** 2022-12-09 18:37 UTC
Labels: type:feature, status:requirements, priority-5-triage
