### ISSUE TITLE
.npmrc in /home/ubuntu is not picked up

### ISSUE THREAD

**Issue by cambiph** [renovatebot/renovate#4707] opened 2019-10-22 13:03 UTC
**What Renovate type are you using?**

Latest Docker image with Github.

**Describe the bug**

I have mounted my .npmrc file in the Docker container under /home/ubuntu/.npmrc but it isn't picked up. This is causing an error when searching for packages which are only published in our private NPM repo.

**Did you see anything helpful in debug logs?**

```
build	22-Oct-2019 14:44:13	 WARN: npm registry failure (repository=**redacted***)
build	22-Oct-2019 14:44:13	       "err": {
build	22-Oct-2019 14:44:13	         "name": "RequestError",
build	22-Oct-2019 14:44:13	         "code": "ECONNRESET",
build	22-Oct-2019 14:44:13	         "host": "registry.npmjs.org",
build	22-Oct-2019 14:44:13	         "hostname": "registry.npmjs.org",
build	22-Oct-2019 14:44:13	         "method": "GET",
build	22-Oct-2019 14:44:13	         "path": "/***redacted***",
build	22-Oct-2019 14:44:13	         "protocol": "https:",
build	22-Oct-2019 14:44:13	         "url": "https://registry.npmjs.org/***redacted***",
build	22-Oct-2019 14:44:13	         "gotOptions": {
build	22-Oct-2019 14:44:13	           "path": "/***redacted***",
build	22-Oct-2019 14:44:13	           "protocol": "https:",
build	22-Oct-2019 14:44:13	           "slashes": true,
build	22-Oct-2019 14:44:13	           "auth": null,
build	22-Oct-2019 14:44:13	           "host": "registry.npmjs.org",
build	22-Oct-2019 14:44:13	           "port": null,
build	22-Oct-2019 14:44:13	           "hostname": "registry.npmjs.org",
build	22-Oct-2019 14:44:13	           "hash": null,
build	22-Oct-2019 14:44:13	           "search": null,
build	22-Oct-2019 14:44:13	           "query": null,
build	22-Oct-2019 14:44:13	           "pathname": "/***redacted***",
build	22-Oct-2019 14:44:13	           "href": "https://registry.npmjs.org/***redacted***",
build	22-Oct-2019 14:44:13	           "headers": {
build	22-Oct-2019 14:44:13	             "user-agent": "https://github.com/renovatebot/renovate",
build	22-Oct-2019 14:44:13	             "cache-control": "no-cache",
build	22-Oct-2019 14:44:13	             "accept": "application/json",
build	22-Oct-2019 14:44:13	             "accept-encoding": "gzip, deflate"
build	22-Oct-2019 14:44:13	           },
build	22-Oct-2019 14:44:13	           "hooks": {
build	22-Oct-2019 14:44:13	             "beforeError": [],
build	22-Oct-2019 14:44:13	             "init": [],
build	22-Oct-2019 14:44:13	             "beforeRequest": [],
build	22-Oct-2019 14:44:13	             "beforeRedirect": [],
build	22-Oct-2019 14:44:13	             "beforeRetry": [],
build	22-Oct-2019 14:44:13	             "afterResponse": []
build	22-Oct-2019 14:44:13	           },
build	22-Oct-2019 14:44:13	           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
build	22-Oct-2019 14:44:13	           "decompress": true,
build	22-Oct-2019 14:44:13	           "throwHttpErrors": true,
build	22-Oct-2019 14:44:13	           "followRedirect": true,
build	22-Oct-2019 14:44:13	           "stream": false,
build	22-Oct-2019 14:44:13	           "form": false,
build	22-Oct-2019 14:44:13	           "json": true,
build	22-Oct-2019 14:44:13	           "cache": false,
build	22-Oct-2019 14:44:13	           "useElectronNet": false,
build	22-Oct-2019 14:44:13	           "method": "GET",
build	22-Oct-2019 14:44:13	           "gotTimeout": {"request": 60000}
build	22-Oct-2019 14:44:13	         },
build	22-Oct-2019 14:44:13	         "message": "Client network socket disconnected before secure TLS connection was established",
build	22-Oct-2019 14:44:13	         "stack": "RequestError: Client network socket disconnected before secure TLS connection was established\n    at ClientRequest.request.once.error (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:203:15)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
build	22-Oct-2019 14:44:13	       },
build	22-Oct-2019 14:44:13	       "regUrl": "https://registry.npmjs.org/",
build	22-Oct-2019 14:44:13	       "depName": "***redacted***"
```
**To Reproduce**
```bash
#!/usr/env/bin bash

cp /Users/philippe/.npmrc .

docker run --volume ${PWD}/renovate.json:/usr/src/app/renovate.json --volume ${PWD}/.npmrc:/home/ubuntu/.npmrc -e RENOVATE_TOKEN=${bamboo.github_secret_access_token} -e RENOVATE_CONFIG_FILE=/usr/src/app/renovate.json -e HTTP_PROXY=***redacted*** -e HTTPS_PROXY=***redacted***renovate/renovate
```

**Comment by rarkins** [comment] 2019-10-22 13:34
Please try configuring it in the "npmrc" field in your config.js in the meantime. Replace newlines with "\n" before pasting in.

**Comment by cambiph** [comment] 2019-10-22 13:47
> Please try configuring it in the "npmrc" field in your config.js in the meantime. Replace newlines with "\n" before pasting in.

This will expose my authentication key.
I talked to you previously about encrypting the key on a private instance but it's quite the hassle.

**Comment by rarkins** [comment] 2019-10-22 13:54
how about exporting it to RENOVATE_NPMRC in env?

**Comment by cambiph** [comment] 2019-10-22 14:02
> how about exporting it to RENOVATE_NPMRC in env?

Does that still work, I could not find the variable in the codebase?

**Comment by rarkins** [comment] 2019-10-22 16:39
for any config option (e.g. `npmrc`), we attempt to ready from env `RENOVATE_` followed by the option in upper case

**Comment by cambiph** [comment] 2019-10-23 09:47
> for any config option (e.g. `npmrc`), we attempt to ready from env `RENOVATE_` followed by the option in upper case

Does not seem to work. I added the RENOVATE_NPMRC variable and it gets picked up correctly:
```
build	23-Oct-2019 11:40:22	DEBUG: File config
build	23-Oct-2019 11:40:22	       "config": {
build	23-Oct-2019 11:40:22	         "autodiscover": true,
build	23-Oct-2019 11:40:22	         "autodiscoverFilter": "*******",
build	23-Oct-2019 11:40:22	         "assignees": ["******"],
build	23-Oct-2019 11:40:22	         "enabled": true,
build	23-Oct-2019 11:40:22	         "enabledManagers": ["npm"],
build	23-Oct-2019 11:40:22	         "ignoreDeps": ["np"],
build	23-Oct-2019 11:40:22	         "labels": ["dependencies"],
build	23-Oct-2019 11:40:22	         "logLevel": "debug",
build	23-Oct-2019 11:40:22	         "packageRules": [
build	23-Oct-2019 11:40:22	           {
build	23-Oct-2019 11:40:22	             "automerge": true,
build	23-Oct-2019 11:40:22	             "packagePatterns": ["********"],
build	23-Oct-2019 11:40:22	             "updateTypes": ["minor", "patch"]
build	23-Oct-2019 11:40:22	           }
build	23-Oct-2019 11:40:22	         ],
build	23-Oct-2019 11:40:22	         "printConfig": true,
build	23-Oct-2019 11:40:22	         "pruneStaleBranches": true,
build	23-Oct-2019 11:40:22	         "reviewers": ["******"]
build	23-Oct-2019 11:40:22	       }
build	23-Oct-2019 11:40:22	DEBUG: CLI config
build	23-Oct-2019 11:40:22	       "config": {}
build	23-Oct-2019 11:40:22	DEBUG: Env config
build	23-Oct-2019 11:40:22	       "config": {"hostRules": [], "token": "***********", "npmrc": "***********"}
build	23-Oct-2019 11:40:22	DEBUG: Combined config
build	23-Oct-2019 11:40:22	       "config": {
build	23-Oct-2019 11:40:22	         "autodiscover": true,
build	23-Oct-2019 11:40:22	         "autodiscoverFilter": "*******",
build	23-Oct-2019 11:40:22	         "assignees": ["********"],
build	23-Oct-2019 11:40:22	         "enabled": true,
build	23-Oct-2019 11:40:22	         "enabledManagers": ["npm"],
build	23-Oct-2019 11:40:22	         "ignoreDeps": ["np"],
build	23-Oct-2019 11:40:22	         "labels": ["dependencies"],
build	23-Oct-2019 11:40:22	         "logLevel": "debug",
build	23-Oct-2019 11:40:22	         "packageRules": [
build	23-Oct-2019 11:40:22	           {
build	23-Oct-2019 11:40:22	             "automerge": true,
build	23-Oct-2019 11:40:22	             "packagePatterns": ["*******"],
build	23-Oct-2019 11:40:22	             "updateTypes": ["minor", "patch"]
build	23-Oct-2019 11:40:22	           }
build	23-Oct-2019 11:40:22	         ],
build	23-Oct-2019 11:40:22	         "printConfig": true,
build	23-Oct-2019 11:40:22	         "pruneStaleBranches": true,
build	23-Oct-2019 11:40:22	         "reviewers": ["********"],
build	23-Oct-2019 11:40:22	         "hostRules": [],
build	23-Oct-2019 11:40:22	         "token": "***********",
build	23-Oct-2019 11:40:22	         "npmrc": "***********"
build	23-Oct-2019 11:40:22	       }
```

But it still looks up dependencies on the public NPMJS repo:

```
build	23-Oct-2019 11:40:32	 WARN: npm registry failure (repository=********)
build	23-Oct-2019 11:40:32	       "err": {
build	23-Oct-2019 11:40:32	         "name": "RequestError",
build	23-Oct-2019 11:40:32	         "code": "ECONNRESET",
build	23-Oct-2019 11:40:32	         "host": "registry.npmjs.org",
build	23-Oct-2019 11:40:32	         "hostname": "registry.npmjs.org",
build	23-Oct-2019 11:40:32	         "method": "GET",
build	23-Oct-2019 11:40:32	         "path": "/******",
build	23-Oct-2019 11:40:32	         "protocol": "https:",
build	23-Oct-2019 11:40:32	         "url": "https://registry.npmjs.org/******",
build	23-Oct-2019 11:40:32	         "gotOptions": {
build	23-Oct-2019 11:40:32	           "path": "/*******",
build	23-Oct-2019 11:40:32	           "protocol": "https:",
build	23-Oct-2019 11:40:32	           "slashes": true,
build	23-Oct-2019 11:40:32	           "auth": null,
build	23-Oct-2019 11:40:32	           "host": "registry.npmjs.org",
build	23-Oct-2019 11:40:32	           "port": null,
build	23-Oct-2019 11:40:32	           "hostname": "registry.npmjs.org",
build	23-Oct-2019 11:40:32	           "hash": null,
build	23-Oct-2019 11:40:32	           "search": null,
build	23-Oct-2019 11:40:32	           "query": null,
build	23-Oct-2019 11:40:32	           "pathname": "/*******",
build	23-Oct-2019 11:40:32	           "href": "https://registry.npmjs.org/*******",
build	23-Oct-2019 11:40:32	           "headers": {
build	23-Oct-2019 11:40:32	             "user-agent": "https://github.com/renovatebot/renovate",
build	23-Oct-2019 11:40:32	             "cache-control": "no-cache",
build	23-Oct-2019 11:40:32	             "accept": "application/json",
build	23-Oct-2019 11:40:32	             "accept-encoding": "gzip, deflate"
build	23-Oct-2019 11:40:32	           },
build	23-Oct-2019 11:40:32	           "hooks": {
build	23-Oct-2019 11:40:32	             "beforeError": [],
build	23-Oct-2019 11:40:32	             "init": [],
build	23-Oct-2019 11:40:32	             "beforeRequest": [],
build	23-Oct-2019 11:40:32	             "beforeRedirect": [],
build	23-Oct-2019 11:40:32	             "beforeRetry": [],
build	23-Oct-2019 11:40:32	             "afterResponse": []
build	23-Oct-2019 11:40:32	           },
build	23-Oct-2019 11:40:32	           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
build	23-Oct-2019 11:40:32	           "decompress": true,
build	23-Oct-2019 11:40:32	           "throwHttpErrors": true,
build	23-Oct-2019 11:40:32	           "followRedirect": true,
build	23-Oct-2019 11:40:32	           "stream": false,
build	23-Oct-2019 11:40:32	           "form": false,
build	23-Oct-2019 11:40:32	           "json": true,
build	23-Oct-2019 11:40:32	           "cache": false,
build	23-Oct-2019 11:40:32	           "useElectronNet": false,
build	23-Oct-2019 11:40:32	           "method": "GET",
build	23-Oct-2019 11:40:32	           "gotTimeout": {"request": 60000}
build	23-Oct-2019 11:40:32	         },
build	23-Oct-2019 11:40:32	         "message": "Client network socket disconnected before secure TLS connection was established",
build	23-Oct-2019 11:40:32	         "stack": "RequestError: Client network socket disconnected before secure TLS connection was established\n    at ClientRequest.request.once.error (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:203:15)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
build	23-Oct-2019 11:40:32	       },
build	23-Oct-2019 11:40:32	       "regUrl": "https://registry.npmjs.org",
```

**Comment by rarkins** [comment] 2019-10-23 09:53
I just verified that npmrc settings are picked up from env. e.g. `RENOVATE_NPMRC="registry=https://npm.fury.io/AUTH_TOKEN/me/" yarn start renovate-tests/npm2` fails because it attempts to look up the custom registry instead of npmjs. Do you have a .npmrc file within the repo perhaps?

**Comment by cambiph** [comment] 2019-10-25 11:45
I have now the following config:

Bamboo run script:
```
#!/usr/env/bin bash
set -e
cp ${bamboo.npmrc_path} .
NPMRC=$(cat .npmrc)
RESULT=$(echo $NPMRC | cut -c84-)
docker run --volume ${PWD}/renovate.json:/usr/src/app/renovate.json --volume ${PWD}/.npmrc:/usr/src/app/.npmrc -e RENOVATE_TOKEN=${bamboo.github_secret_access_token} -e RENOVATE_NPMRC=${RESULT} -e RENOVATE_CONFIG_FILE=/usr/src/app/renovate.json -e HTTP_PROXY=**** -e HTTPS_PROXY=**** renovate/renovate
```

`RENOVATE_NPMRC` translates to `//xxx:8081/artifactory/api/npm/:_authToken=xxx`

And still, the log is showing:
```
build	25-Oct-2019 13:30:57	         "name": "RequestError",
build	25-Oct-2019 13:30:57	         "code": "ECONNRESET",
build	25-Oct-2019 13:30:57	         "host": "registry.npmjs.org",
build	25-Oct-2019 13:30:57	         "hostname": "registry.npmjs.org",
build	25-Oct-2019 13:30:57	         "method": "GET",
build	25-Oct-2019 13:30:57	         "path": "/http-server",
build	25-Oct-2019 13:30:57	         "protocol": "https:",
build	25-Oct-2019 13:30:57	         "url": "https://registry.npmjs.org/http-server",
```

So that proves, the `RENOVATE_NPMRC` is not picked up correctly.

**Comment by rarkins** [comment] 2019-10-25 11:59
You’re only proving that it doesn’t work for you. What we need is a way to reproduce it so that someone else can fix it. 

We need a simple reproduction case because as I showed earlier, the env variable is being picked up with a simple config, therefore there’s something else about your setup causing it to be ignored, such as an `.npmrc` file within your repo or something like that.

**Comment by rarkins** [comment] 2019-12-11 11:19
Closing as unable to reproduce

**Closed by rarkins** 2019-12-11 11:19 UTC
