### ISSUE TITLE
PR Release Notes: Add the dependency release date for each dependency

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#12554] opened 2021-11-08 12:26 UTC
### What would you like Renovate to be able to do?

It would be handy to know the release date for each of the dependencies within the PR Release Notes section.  This would help repository maintainers understand how old/new the specific dependency release is

### If you have any ideas on how this should be implemented, please tell us here.

-

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment] 2021-11-08 12:32
Duplicate of #5822

**Closed by HonkingGoose** 2021-11-08 12:32 UTC
Labels: type:feature, status:requirements, priority-5-triage, core:changelogs

**Comment by HonkingGoose** [comment] 2021-11-08 12:38
Do you know about GitHub Dependency Review? There's a button you can click in the `Files changed` tab when you're looking at a dependency file that's changed.

https://github.blog/changelog/2021-10-05-dependency-review-is-generally-available/
