### ISSUE TITLE
All repos failing with Undefined Preset Configuration?

### ISSUE THREAD

**Issue by broksonic21** [renovatebot/renovate#8373] opened 2021-01-21 13:14 UTC
**What Renovate type, platform and version are you using?**

Hosted, GitHub

**Describe the bug**

We had been working fine all morning, but all of a sudden every repo failed with a new issue for fixing renovate configuration. Note: the same runs had worked just a few minutes before with no changes.

There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Error type: undefined. Note: this is a nested preset so please contact the preset author if you are unable to fix it yourself.

**Relevant debug logs**

`DEBUG: Preset fetch error
{
  "preset": "workarounds:ignoreSbtLatestIntegration",
  "err": {
    "message": "Cannot convert undefined or null to object",
    "stack": "TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:178:31)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:222:37)\n    at async resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:252:38)\n    at async Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:252:38)\n    at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:194:52)\n    at async Object.getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:231:14)\n    at async Object.initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:60:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:359:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:587:5"
  }
}
INFO: Throwing preset error
{
  "validationError": "undefined. Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself."
}`

**Have you created a minimal reproduction repository?**

https://github.com/broksonic21/renovate_repo_repo2/issues/2
and
https://github.com/broksonic21/renovate_repo_repro/issues/4

- [X] I have provided a minimal reproduction repository

**Additional context**

**Comment by adnathanail** [comment] 2021-01-21 13:15
I've got the same issue

**Comment by broksonic21** [comment] 2021-01-21 13:16
Likely same as https://github.com/renovatebot/renovate/issues/8371

**Comment by viceice** [comment] 2021-01-21 13:16
Duplicate of #8371

**Closed by viceice** 2021-01-21 13:16 UTC

**Comment by rarkins** [comment] 2021-01-21 13:17
Sorry, bad commit now rolled back in the app. The warning issue in repos will be automatically closed on the next run.
