### ISSUE TITLE
Renovate starts opening issues in all repos: Action Required: Fix Renovate Configuration

### ISSUE THREAD

**Issue by simoneb** [renovatebot/renovate#8374] opened 2021-01-21 13:26 UTC
The body of the issue is:

```
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Error type: undefined. Note: this is a nested preset so please contact the preset author if you are unable to fix it yourself.
```

**Comment by rarkins** [comment] 2021-01-21 13:31
Please see #8371

**Comment by viceice** [comment] 2021-01-21 13:31
Duplicate of #8371

**Closed by rarkins** 2021-01-21 13:31 UTC
