### ISSUE TITLE
Bazel container_pull wrong digest proposed

### ISSUE THREAD

**Issue by ns-ggeorgiev** [renovatebot/renovate#15134] opened 2022-04-15 21:33 UTC
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

when having in bazel WORSPACE something like the following

```
container_pull(
    name = "python_base",
    digest = "sha256:894d72ff1431d3109860997dd7efbda12d0a13b74ce20b5109cee1960cc4c5ca",
    registry = "index.docker.io",
    repository = "python",
    tag = "3.8-alpine3.14",
)
```
the renovate creates PR to suggest change of the digest

```
This PR contains the following updates:

Package | Type | Update | Change
python_base | container_pull | digest | 894d72f -> d45c2b4
```

which actually breaks the build.

The reason seems to be that `python:3.8-alpine3.14` is a manifest of manifests, where internally lists a number of images for different platforms. Bazel expects digest based on the aggregated manifest - which seems ok, because it internally has the digest of the rest of the images. On the other side renovate suggest a digest based on a particular instance of the image that is downloaded after the os and platform are resolved.

```
$ docker manifest inspect python:3.8-alpine3.14
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:5302002805d786ca9d158e2414febebfb9b289ba7534559554a6c6c4fe4fb86b",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:bb88d443d7d595ec9407160540fc39e838c3ab31cf7da295f3bb65ad6abc7d16",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v6"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:2cfb58ce0c9bb9e2cf2a1c35230afb5780d2141d80ef1ff0b14c362edc6c45f5",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:d45c2b41a867764c5e93b734cff6609e816a3726055ebaf300544a6ce58944d7",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:b5be8822abafb615b8d0b6fcdb35e5de9b200e79cfe2da1f3d908ce66a1755a0",
         "platform": {
            "architecture": "386",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:79aa5afa47ee7ec21a5c5ddcdd3c9d50ae1a824f071f51646d3f5dd6da2269a6",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:df2f0ba79ad7f612ea3b099fe26fabcb17e3b829ef4139ef9267fb5193c3f09a",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

I can workaround the problem with using specific sha in the `container_pull`, but that will defeat the purpose, because then the renovate would not be able to detect and suggest available update. 

NOTE: I can provide reproducible repo, if the team is willing to work on resolving the issue.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment] 2022-04-16 02:33
Duplicate of #9786

**Closed by viceice** 2022-04-16 02:33 UTC
Labels: type:bug, status:requirements, priority-5-triage
