### ISSUE TITLE
Run `go mod tidy` in subdirectories

### ISSUE THREAD

**Issue by gnuletik** [renovatebot/renovate#19270] opened 2022-12-05 18:32 UTC
### What would you like Renovate to be able to do?

When repo has the following architecture:
`go.mod`
```go.mod
module root

go 1.19

require (
  google.golang.org/x/text v0.4.0
)
```

`cmd/example/go.mod`
```go.mod
go 1.19

replace root -> ../../

require (
  root v0.0.0-00010101000000-000000000000
)

require (
  golang.org/x/text v0.4.0 // indirect
)
```

`go.sum` files are omitted here.

Reproduction repo here: https://github.com/gnuletik/renovate-repro-19270
Failing renovate PR: https://github.com/gnuletik/renovate-repro-19270/pull/1

In a scenario where:
- `golang.org/x/text` should be updated from `v0.4.0` to `v0.5.0`
- with a `renovate.json` with `"postUpdateOptions": ["gomodTidy"]`

Renovate creates a PR which updates `go.mod` and `go.sum` files at the repository root.
However, this breaks the `cmd/example` package which also needs to be updated to `v0.5.0` (in the indirect dependencies part).

Note: This issue only occurs for indirect dependencies upgrade.

### If you have any ideas on how this should be implemented, please tell us here.

 Could `go mod tidy` be executed in every sub-packages in the repo?

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment] 2022-12-06 06:51
I think that running `go mod tidy` in every sub package is not ideal because it could end up updating unrelated `go.sum` files. Instead, the solution should ideally understand which sub-packages are dependent and instead update only those ones (e.g. by linking `root` to `root` in the above example).

**Comment by viceice** [comment] 2022-12-06 08:51
> I think that running `go mod tidy` in every sub package is not ideal because it could end up updating unrelated `go.sum` files. Instead, the solution should ideally understand which sub-packages are dependent and instead update only those ones (e.g. by linking `root` to `root` in the above example).

We can probably use a similar approach like in nuget manager.

**Comment by gnuletik** [comment] 2022-12-06 11:41
Thanks for the fast feedback!

Here is a reproduction repository with a failing PR created by renovate: https://github.com/gnuletik/renovate-repro-19270/pull/1

**Comment by rarkins** [comment] 2022-12-06 12:47
Reproduction forked to https://github.com/renovate-reproductions/19270

**Comment by rarkins** [comment] 2022-12-06 13:10
Ideal solution: build a dependency graph between the `go.mod` files/directories and then run in dependent ones only.

Pragmatic alternative solution: a new option `goModTidyAll` which runs `go mod tidy` in every package in a repo whenever any dependency is updated

**Comment by rarkins** [comment] 2022-12-07 14:12
I thought we maybe had an open issue already about updating indirect dependencies, but I can't find it.

However I found #12999, and it looks like we could combine/close this issue as a duplicate?

**Comment by rarkins** [comment] 2022-12-08 10:36
Duplicate of #12999

**Closed by rarkins** 2022-12-08 10:36 UTC
Labels: type:feature, priority-3-medium, manager:gomod, status:ready, reproduction:provided
