### ISSUE TITLE
add/allow label for dependencyDashboard 

### ISSUE THREAD

**Issue by haghabozorgi** [renovatebot/renovate#7848] opened 2020-11-30 17:23 UTC
**What would you like Renovate to be able to do?**

Renovate currently allows adding labels to PRs. It would be nice if  labels could be added to the dependencyDashboard issue that gets create as well.

**Did you already have any implementation ideas?**

Perhaps the current labels implementation would be sufficient for a first iteration. If labels set at top-level config, dependencyDashboard logic uses those labels for its issue creation call.

**Comment by HonkingGoose** [comment] 2020-12-01 18:53
I think this feature request might be a duplicate of #4911.

**Comment by viceice** [comment] 2020-12-01 19:06
Yes, sounds like a duplicate.

I think there is another issue for an `addLabel` like option, which might be in progress by a contributor. 🤔

**Comment by HonkingGoose** [comment] 2020-12-01 19:42
> I think there is another issue for an `addLabel` like option, which might be in progress by a contributor. 🤔

I haven't been able to find that issue yet...

@viceice can you close this with your "Duplicate of" thing? I don't have the rights to mark things as a duplicate.

**Comment by viceice** [comment] 2020-12-01 19:46
Ok, not a duplicate but related to #6503 😏

**Comment by rarkins** [comment] 2020-12-02 05:28
Duplicate of #4911

**Closed by rarkins** 2020-12-02 05:28 UTC
Labels: priority-4-low, type:feature
