### ISSUE TITLE
Yarn 2 - private packages cause "Artifact update problem"

### ISSUE THREAD

**Issue by AaronBuxbaum** [renovatebot/renovate#9537] opened 2021-04-13 20:28 UTC
**What Renovate type, platform and version are you using?**

GitHub app

**Describe the bug**

In a Yarn 2 repository, Renovate fails when trying to update the yarn.lock file in a repository with private NPM packages, regardless of if valid authentication is provided or not. Renovate makes a comment with "Artifact update problem", but with no obviously useful debugging information.

**Relevant debug logs**
N/A

**Have you created a minimal reproduction repository?**
https://github.com/AaronBuxbaum/renovate-repro

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Comment by rarkins** [comment] 2021-04-14 06:49
Are you committing the secret/credential to the repo? And if not, have you attempted to configure the credentials into Renovate so far?

I think:
- Credentials in repos should be discouraged.. and certainly not added because of Renovate
- Users should configure credentials using hostRules (this will get you past the lookup failure log you see)
- Renovate should pass configured hostRules credentials to Yarn 2+ using either env var (preferred) or writing them to a file, like we do with .npmrc today

**Comment by AaronBuxbaum** [comment] 2021-04-14 15:40
> Are you committing the secret/credential to the repo? And if not, have you attempted to configure the credentials into Renovate so far?
> 
> I think:
> 
> * Credentials in repos should be discouraged.. and certainly not added because of Renovate
> * Users should configure credentials using hostRules (this will get you past the lookup failure log you see)
> * Renovate should pass configured hostRules credentials to Yarn 2+ using either env var (preferred) or writing them to a file, like we do with .npmrc today

It's very likely I'm just not following the proper approach, but... see my minimal repo: https://github.com/AaronBuxbaum/renovate-repro/pull/3

Renovate seems to fail to update the yarn lock, and the authentication works, so that's not the issue. Not really sure what the issue is

**Comment by AaronBuxbaum** [comment] 2021-04-26 13:45
@rarkins Any movement on this? This is a huge annoyance since it means effectively every Renovate PR needs to be re-yarned manually

**Comment by rarkins** [comment] 2021-04-26 14:37
This needs to be resolved by adding authentication to `.yarnrc.yml` instead of `.npmrc` if Yarn 2+ is detected. The current logic for `.npmrc` is here: https://github.com/renovatebot/renovate/blob/ce51f05cef7d8a3275bca67e9397f17991daace2/lib/manager/npm/post-update/index.ts#L440-L470

**Comment by rarkins** [comment] 2021-05-19 07:44
Here's what I had in mind:

- The repo must already have a `.yarnrc.yml` with an entry for each server which requires authentication
- Renovate will find all hostType=npm hostRules, then for each it will look for a matching host in the existing `.yarnrc.yml` and add the token to it
- Renovate will write the existing `.yarnrc.yml` to disk before calling `yarn`

**Comment by rarkins** [comment] 2021-05-19 11:20
Let's treat this as a duplicate of #9985 even though it's newer, because it has more followers and more details.

**Comment by rarkins** [comment] 2021-05-19 11:20
Duplicate of #9985

**Closed by rarkins** 2021-05-19 11:20 UTC
Labels: manager:npm, priority-2-important, status:ready, type:bug
