### ISSUE TITLE
Renovatebot is re-opening update PRs that were previously ignored

### ISSUE THREAD

**Issue by busunkim96** [renovatebot/renovate#7352] opened 2020-09-22 18:17 UTC
**What Renovate type, platform and version are you using?**

Hosted on GitHub

**Describe the bug**
Renovate bot is repeatedly opening PRs for dependency updates that were already ignored. See [this repository](https://github.com/googleapis/python-bigtable/pulls?q=is%3Apr+is%3Aclosed+ubuntu+).
![image](https://user-images.githubusercontent.com/8822365/93920412-64a0a900-fccc-11ea-9ede-e28f7ba847ba.png)

**Relevant debug logs**

**To Reproduce**
Close the open update PR, wait a few minutes, and a new PR with the same update is opened.

**Additional context**

**Comment by rarkins** [comment] 2020-09-22 18:57
I think this might be specific to Forking Renovate. Taking a look

**Comment by rarkins** [comment] 2020-09-22 19:30
I think it should be fixed now. Reproduced and fixed here: https://github.com/rarkins/python-bigtable/pull/4#issuecomment-696932720

Root cause: Forking Renovate mixed up who it was again, it was looking for PRs created by `forking-renovate[bot]` but needed to look for `renovate-bot`

**Comment by JustinBeckwith** [comment] 2020-09-22 19:55
Thank you so much @rarkins, we really appreciate how quickly you jump on these bugs 🐞

**Comment by kurtisvg** [comment] 2020-09-22 21:05
Hi @rarkins,

We've noticed an issue with Dependency Dashboard Issues as well. For example, this repo has [3 open dependency dashboards](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues?q=is%3Aissue+is%3Aopen+Dependency+Dashboard) (the latest being opened 42 minutes ago). 

Is this the same issue? Should we expect Renovate to close the extra issues once resolved?

**Comment by rarkins** [comment] 2020-09-23 03:47
@kurtisvg oh no! Sorry, I missed that one. Should be fixed in the next few minutes.

**Comment by kurtisvg** [comment] 2020-09-24 15:54
Thanks @rarkins!

**Closed** 2020-09-24 16:24 UTC
