### ISSUE TITLE
Automerge isn't merging a PR

### ISSUE THREAD

**Issue by darlenya** [renovatebot/renovate#11425] opened 2021-08-25 13:17 UTC
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.7.0

### Describe the bug

A PR is not closed by automerge:

Command to reproduce the behaviour:
`npx renovate darlenya/renovate-demo-issue --token X9U6q4AMxmc-XK8-rZsV`

Here ist the config I used:

```
{
  "autodiscover": false,
  "baseBranches": ["main"],
  "endpoint": "https://gitlab.com/api/v4/",
  "labels": ["renovate", "dependencies", "automation"],
  "hostRules": [],
  "packageRules": [
    {
      "semanticCommitType": "fix",
      "labels": ["renovate", "dependencies", "automation", "depCi", "npm"],
      "prPriority": 0,
      "matchDepTypes": ["dependencies"]
    },
    {
      "semanticCommitType": "chore",
      "labels": ["renovate", "dependencies", "automation", "devChore", "npm"],
      "prPriority": -5,
      "matchDepTypes": ["devDependencies"]
    }
  ],
  "platform": "gitlab",
  "rangeStrategy": "pin",
  "recreateClosed": true,
  "rollbackPrs": true,
  "semanticCommitType": "fix",
  "semanticCommits": "enabled",
  "unicodeEmoji": true,
  "automerge": true,
  "gitLabAutomerge": true
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: getBranchStatus(renovate/main-eslint-7.x) (repository=darlenya/renovate-demo-issue, branch=renovate/main-eslint-7.x)
DEBUG: Got res with 0 results (repository=darlenya/renovate-demo-issue, branch=renovate/main-eslint-7.x)
DEBUG: getBranchStatus() result (repository=darlenya/renovate-demo-issue, branch=renovate/main-eslint-7.x)
       "branchStatus": "yellow",
       "branchName": "renovate/main-eslint-7.x"
DEBUG: Merge Request #3 does not need updating (repository=darlenya/renovate-demo-issue, branch=renovate/main-eslint-7.x)
DEBUG: PR is configured for automerge (repository=darlenya/renovate-demo-issue, branch=renovate/main-eslint-7.x)
DEBUG: PR is not ready for merge (repository=darlenya/renovate-demo-issue, branch=renovate/main-eslint-7.x)
       "canMergeReason": undefined
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by darlenya** [comment] 2021-08-25 13:27
In the edit mode it is formatted. When I do 'insert code' it is shown as before. Now I removed this and the spaces are removed.

**Comment by rarkins** [comment] 2021-08-25 13:34
@darlenya you need to surround code blocks in trip backticks ```, so I have done that now

**Comment by darlenya** [comment] 2021-08-25 13:34
Ok, thanks

**Comment by rarkins** [comment] 2021-08-25 13:35
I think your title is wrong. Don't you mean "automerge isn't merging" instead of "closing"?

**Comment by rarkins** [comment] 2021-08-25 13:36
Also "I have linked to a minimal reproduction repository in the bug description" seems incorrect because https://gitlab.com/darlenya/renovate-demo-issue either doesn't exist or is private

**Closed** 2021-08-25 13:38 UTC
Labels: type:bug, status:requirements, priority-5-triage
