### ISSUE TITLE
Support GoMock in golang artifact downloading

### ISSUE THREAD

**Issue by Charles546** [renovatebot/renovate#14179] opened 2022-02-11 20:35 UTC
### What would you like Renovate to be able to do?

We use GoMock to generate mock objects in our CI/CD pipelines. See the [Makefile](https://github.com/honeydipper/honeydipper/blob/8effa3d16e059187a1cbd7d76874c1e344a23da5/Makefile#L28-L45) for details. The mocking files are not stored in GitHub, but instead, are generated whenever they are needed. Renovate uses `go get` to download the modules and update `go.sum`. However, `go get` fails due to missing of the mocking files. An example is this [PR](https://github.com/honeydipper/honeydipper/pull/457). It would be nice if renovate could give an opportunity for the files to be generated through a make command etc., before running the `go get` command.

### If you have any ideas on how this should be implemented, please tell us here.

None at tht moment

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment] 2022-11-25 14:45
Duplicate of #18845

**Comment by rarkins** [comment] 2022-11-25 14:45
Duplicate of https://github.com/renovatebot/renovate/issues/8804

**Closed by rarkins** 2022-11-25 14:45 UTC
Labels: type:feature, status:requirements, priority-5-triage
