### ISSUE TITLE
JS-based build.gradle parser

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3898] opened 2019-06-06 07:07 UTC
Example files:
- https://github.com/Jasig/uPortal/blob/master/build.gradle
- https://github.com/Jasig/NotificationPortlet/blob/master/build.gradle
- https://github.com/bagage/gradle-template/blob/master/build.gradle
- https://github.com/bagage/gradle-template/blob/master/module1/build.gradle
- https://github.com/apereo/cas/blob/master/build.gradle

**Comment by viceice** [comment] 2020-06-07 13:55
Isn't this a duplicate of #3608

**Closed** 2020-06-07 14:32 UTC
Labels: #gradle, duplicate, feat, ready
