### ISSUE TITLE
dependency update loop

### ISSUE THREAD

**Issue by pi0** [renovatebot/renovate#3648] opened 2019-05-09 06:52 UTC
**What Renovate type are you using?**
Renovate GitHub App

**Description**
Renovate repetitively opens a PR to update a semver/patch dependency and auto closes in a few minutes. This bug started happening from a few weeks ago in some repos. 

**Did you see anything helpful in debug logs?**

https://renovatebot.com/dashboard#github/nuxt/http

Started with nuxt/http#32, i merged nuxt/http#41

**To Reproduce**

https://github.com/nuxt/http

**Expected behavior**
A pull-request created only once

**Screenshots**
![image](https://user-images.githubusercontent.com/5158436/57433070-bc13b580-724c-11e9-885c-6d4421facf5e.png)

**Additional context**
[n/a]

**Comment by rarkins** [comment] 2019-05-09 07:56
Based on the screenshot, this is not Renovate's "autoclose" feature, because the PR has not been renamed. It looks instead that GitHub is closing the PR, either because:
(a) the branch was deleted, or
(b) the branch was updated to contain "no work"

**Comment by pi0** [comment] 2019-05-09 08:18
@rarkins Thanks for the fast answer. Actually, I didn't delete branch and CI is passing (if you mean by "not work").  What do you suggest to check for next step?

**Comment by rarkins** [comment] 2019-05-09 08:45
@pi0 By "no work" I mean like when GitHub does a "compare changes" of a branch to master and reports that there are no differences. If you push to a PR's branch on GitHub and GitHub determines there are no changes, it closes the PR automatically. So maybe if Renovate is pushing a commit like that then it explains why GitHub is doing the closing

**Comment by rarkins** [comment] 2019-05-09 08:46
e.g.

![image](https://user-images.githubusercontent.com/6311784/57440130-bb2c5500-7247-11e9-8762-30b8ab6992f1.png)

No commits, no changes. I'll dig into the logs

**Comment by rarkins** [comment] 2019-05-09 09:15
I think the root cause is due to the combination of `"core-js": "2"` and rangeStrategy="bump". In short we don't know how to "bump" the value "2". Do you expect it to stay the same, i.e. do nothing? Or do you expect it to be bumped to "2.6.5"?

**Comment by rarkins** [comment] 2019-05-09 09:41
I've fixed the core-js bumping problem, which I'm pretty sure must be the root cause.

**Closed** 2019-05-09 09:41 UTC
Labels: fix, pri2-important, ready
