### ISSUE TITLE
Parameter for never updating to unstable versions

### ISSUE THREAD

**Issue by ph1l1pF** [renovatebot/renovate#20143] opened 2023-02-01 09:45 UTC
### What would you like Renovate to be able to do?

It would be great if there was an option to tell renovate to never update to unstable versions of packages.

There is already the parameter `ignoreUnstable`. In the documentation it says:

"By default, Renovate won't update any package versions to unstable versions (e.g. 4.0.0-rc3) unless the current version has the same major.minor.patch and was already unstable (e.g. it was already on 4.0.0-rc2)"

In our project we sometimes use unstable versions of our self made packages to test new features. In that case, renovate opens pull requests that try to update those unstable refs to another (newer) unstable version. For us, that does not make sense, since these different unstable versions contain completely different features and we don't want to have automatic updates to such unstable versions.

It would be great if we could prevent such PRs.

### If you have any ideas on how this should be implemented, please tell us here.

A paramete like `alwaysIgnoreUnstable` would be nice, which prevents updates to unstable versions even if an unstable version is referenced before.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment] 2023-02-01 11:19
I would combine this into a replacement option called `updateUnstableWhen` with values such as `never` (what you want), `same-patch` (equivalent to ignoreUnstable=true today), `always` (equivalent to `ignoreUnstable=false today) as well as some new options such as `same-minor` and `same-major`, e.g. for people on unstable non-LTS Node major versions.

**Comment by rarkins** [comment] 2023-02-01 11:19
What you can do today is set a package rule with enabled=false to disable updating those packages. Matching either with matchPackageNames, matchPackagePatterns, or possibly matchCurrentValue.

**Comment by ph1l1pF** [comment] 2023-02-01 18:45
> I would combine this into a replacement option called `updateUnstableWhen` with values such as `never` (what you want), `same-patch` (equivalent to ignoreUnstable=true today), `always` (equivalent to `ignoreUnstable=false` today) as well as some new options such as `same-minor` and `same-major`, e.g. for people on unstable non-LTS Node major versions.

That would be a good solution

**Comment by JavierSegoviaCordoba** [comment] 2023-03-12 15:45
Interested in this one. How Renovate decides how to prioritize a feature? Emotes on the OP? Number of comments?

**Comment by rarkins** [comment] 2023-03-26 05:58
Let's combine this into #11185

**Comment by rarkins** [comment] 2023-03-26 05:58
Duplicate of #11185

**Closed by rarkins** 2023-03-26 05:58 UTC
Labels: type:feature, status:requirements, priority-5-triage
