### ISSUE TITLE
Support rangeStrategy=update-lockfile for poetry.lock

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7358] opened 2020-09-23 19:22 UTC
**What would you like Renovate to be able to do?**

Perform lockfile-only updates for Poetry

**Did you already have any implementation ideas?**

No. We'd need to work out if there's a Poetry command that lets us update a locked dependency version without updating all other dependencies unnecessarily.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Pinning package versions, but that's undesirable for libraries

**Is this a feature you'd be interested in implementing yourself?**

Probably not

**Comment by shughes-uk** [comment] 2020-09-23 19:48
Hiya, this should reproduce it https://github.com/shughes-uk/renovate-repro

**Comment by rarkins** [comment] 2020-09-23 20:18
Note for future: `nomnomdata-cli` is set to `^0.1.5` and has version `0.1.5` installed however currently `0.1.7` is available. Unless a perfect `poetry` command exists for surgically updating that version, it looks like we could maybe massage the value in `pyproject.toml`: https://github.com/shughes-uk/renovate-repro/blob/d97faafb04321a80f5064550ec917dc6d187ca22/pyproject.toml#L9 to a fixed version e.g. `0.1.7` before then massaging it back before committing, because the lock file does not contain the original range.

**Comment by viceice** [comment] 2020-09-23 20:30
🤔 interesting idea, can work. Did you elaborate  existing poetry commands?

**Comment by rarkins** [comment] 2020-09-24 05:17
Haven't looked yet. I prefer to use a manager's commands whenever possible though

**Comment by shughes-uk** [comment] 2020-09-28 20:14
`poetry add package@latest` is probably what you would want to do that, it does trigger a lock file update though.

**Comment by rarkins** [comment] 2020-09-28 20:48
That doesn't sound like the right command because what we want is to keep the range in pyproject.toml the same and won't it get changed by that command?

**Comment by shughes-uk** [comment] 2020-09-28 21:00
its not the perfect command but it would help you do this


> maybe massage the value in pyproject.toml: https://github.com/shughes-uk/renovate-repro/blob/d97faafb04321a80f5064550ec917dc6d187ca22/pyproject.toml#L9 to a fixed version e.g. 0.1.7 before then massaging it back before committing

**Comment by viceice** [comment] 2020-09-29 04:11
Checked the poetry issue above and saw, currently there is no command to do a minimal lockfile Update.

The suggested workaround there is to add and remove a dummy package. ☹️

**Comment by rarkins** [comment] 2020-09-29 06:31
Maybe we should create our own dummy package for this purpose if it's the best way.

**Comment by rarkins** [comment] 2020-10-02 09:24
Seems there will soon be a new `poetry lock --no-update` option: https://github.com/python-poetry/poetry/pull/3034/files

**Comment by cailloumajor** [comment] 2020-12-13 14:22
🚀 https://github.com/python-poetry/poetry/pull/3034 is merged and released since https://github.com/python-poetry/poetry/releases/tag/1.1.1

**Comment by shughes-uk** [comment] 2020-12-31 01:22
This is on the roadmap for poetry and seems to be exactly what I want 
https://github.com/python-poetry/poetry/issues/461#event-3971869007

**Comment by rarkins** [comment] 2022-01-13 13:09
Forked to https://github.com/renovate-reproductions/7358

I think we still need to work out which exact command(s) should be run

**Comment by shughes-uk** [comment] 2022-01-25 00:37
[poetry update](https://python-poetry.org/docs/cli/#update) seems to be the command if you want to just update specific packages

**Comment by koffie** [comment] 2022-07-20 14:44
Is this still an open issue? To quote from https://docs.renovatebot.com/configuration-options/#rangestrategy

> `update-lockfile` = Update the lock file when in-range updates are available, otherwise `replace` for updates out of range. Works for `bundler`, `composer`, `npm`, `yarn`, `terraform` and `poetry` so far

So the documentation explicitly says this is supported!

**Closed** 2022-10-30 05:54 UTC
Labels: type:feature, priority-3-medium, manager:poetry, status:requirements
