### ISSUE TITLE
Sharing config presets don't work with JSON5

### ISSUE THREAD

**Issue by stephenwade** [renovatebot/renovate#8158] opened 2020-12-29 16:23 UTC
**What would you like Renovate to be able to do?**

I used a JSON5 file in one repository and I'd like to share it with another repository, but the code that loads config files from other repositories only checks for `.json` files and not `.json5` files.

https://docs.renovatebot.com/config-presets/#github-hosted-presets

**Did you already have any implementation ideas?**

I think this could be solved in two ways:
- Change the code that fetches config files to attempt `.json5` files
- Since JSON5 is a superset of JSON, just parse all files with `JSON5.parse` instead of `JSON.parse`

I'd be interested in trying to implement whichever solution is decided on.

**Comment by rarkins** [comment] 2020-12-30 11:20
Duplicate of #7674

**Closed by rarkins** 2020-12-30 11:20 UTC
Labels: priority-3-normal, type:feature
