### ISSUE TITLE
renovate-config-validator fails on local repo presets

### ISSUE THREAD

**Issue by vitoyucepi** [renovatebot/renovate#17011] opened 2022-08-06 01:22 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.150

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

gitlab.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Caused by #16468.

Since release `32.146` renovate started to fail if used in gitlab-ci to validate renovate config of the current repository, and it has `local>` in `extends` section.

[Reproduction repository](https://gitlab.com/vitoyucepi/renovate-issue-17011)

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Could not resolve preset during config validation
       "err": {
         "message": "Missing platform config for local preset.",
         "stack": "Error: Missing platform config for local preset.\n    at Object.getPreset (/usr/src/app/node_modules/renovate/lib/config/presets/local/index.ts:28:11)\n    at getPreset (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:[22](https://gitlab.com/vitoyucepi/renovate-issue-17011/-/jobs/2822293648#L22)5:54)\n    at validateConfig (/usr/src/app/node_modules/renovate/lib/config/validation.ts:276:36)\n    at validate (/usr/src/app/node_modules/renovate/lib/config-validator.ts:36:35)\n    at /usr/src/app/node_modules/renovate/lib/config-validator.ts:64:17"
       },
       "preset": "local>vitoyucepi/renovate-issue-17011//test-renovate"
ERROR: renovate.json contains errors
       "errors": [
         {
           "topic": "Configuration Warning",
           "message": "Invalid Preset local>vitoyucepi/renovate-issue-17011//test-renovate"
         }
       ]
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by vitoyucepi** [comment] 2022-08-06 01:31
I think that `extends` interface should be a bit more complicated.
```json
{
  "extends": [
    {
      "host": "https://gitlab.something.com",
      "type": "gitlab",
      "repository": "something/something",
      "path": "config.json",
      "branch": "custom"
    }
  ]
}
```

**Comment by viceice** [comment] 2022-08-06 05:15
Duplicate of #17007

**Closed** 2022-08-06 05:15 UTC
Labels: type:bug, status:requirements, priority-5-triage

**Comment by viceice** [comment] 2022-08-06 05:19
- #17012

**Comment by vitoyucepi** [comment] 2022-08-06 13:39
I disagree that this issue is a duplicate of #17007, because that issue is about private repos. My issue is about `local` keyword resolution. 

The solution will fix both though.
