### ISSUE TITLE
Dynamic authentication against OCI repositories

### ISSUE THREAD

**Issue by RiceBowlJr** [renovatebot/renovate#16912] opened 2022-08-02 13:52 UTC
### What would you like Renovate to be able to do?

I want to be able to authenticate to an OCI repository to get update on Helm charts.
I am specifically speaking of using temporary credentials with AWS ECR (or I guess other public cloud providers).

For example to [get a Helm chart on AWS ECR OCI registry](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html#using-helm-charts-eks), I first need to make a request to AWS ECR with my IAM user/role to get credentials that allows me to finally authenticate against the repository:

```
aws ecr get-login-password \
     --region us-west-2 | helm registry login \
     --username AWS \
     --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
```

At the moment, [Renovate support for OCI only allow static credentials](https://docs.renovatebot.com/modules/manager/helmv3/#oci-registries). 

### If you have any ideas on how this should be implemented, please tell us here.

An idea I have is to keep things as generic as possible, so allow to enter a script to generate those credentials.

Otherwise a specific configuration for example with access keys for AWS that behind the scenes generates the credentials and authenticate against ECR.

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment] 2022-08-02 14:11
I think this is out of scope for renovate, you can use self-hosted renovate and call the command before running renovate and pass the generated credentials as host rules.

**Comment by rarkins** [comment] 2022-08-03 05:19
How long are such credentials valid for?

**Comment by RiceBowlJr** [comment] 2022-08-03 08:01
> How long are such credentials valid for?

Those credentials are valid 12 hours: https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html#registry-auth-token

**Comment by rarkins** [comment] 2022-08-04 07:10
Exactly how do you run Renovate, and how long do your runs last for?

**Comment by RiceBowlJr** [comment] 2022-08-09 08:04
> Exactly how do you run Renovate, and how long do your runs last for?

We don't run Renovate as self hosted. For now we run as SaaS but since we cannot get the authentication, I was not able to get the updates from our Chart registry.
I followed this documentation: https://docs.renovatebot.com/modules/manager/helmv3/#oci-registries

**Comment by rarkins** [comment] 2022-08-11 05:43
So in the case of SaaS, let's refer to that as "repo config". If you need to use repo config to authenticate, you would need to provide (encrypted) credentials via hostRules. What would those credentials be? e.g. IAM access key ID and secret access key?

**Comment by RiceBowlJr** [comment] 2022-08-23 15:16
> So in the case of SaaS, let's refer to that as "repo config". If you need to use repo config to authenticate, you would need to provide (encrypted) credentials via hostRules. What would those credentials be? e.g. IAM access key ID and secret access key?

Sorry for the delay. Well actually IAM access key ID ans secret access key are not enough to authenticate against AWS ECR registries. With those credentials you can request a token to `docker login/helm login` against ECR, such as describe in [this documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html#using-helm-charts-eks).

```
aws ecr get-login-password \
     --region us-west-2 | helm registry login \
     --username AWS \
     --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
```

**Comment by viceice** [comment] 2022-08-24 09:15
This is already supported:

https://github.com/renovatebot/renovate/blob/d19b708b195b43961d0744de0c4dc91750203d3c/lib/modules/datasource/docker/index.ts#L232-L260
https://github.com/renovatebot/renovate/blob/d19b708b195b43961d0744de0c4dc91750203d3c/lib/modules/datasource/docker/index.ts#L103-L113


so you only need a proper hostrule and pass `accessKeyId` as username and `secretAccessKey` as password. Renovate will detect region from image name

**Comment by viceice** [comment] 2022-08-24 09:20
Duplicate of #3968

**Closed by viceice** 2022-08-24 09:20 UTC
Labels: type:feature, datasource:docker, status:requirements, priority-5-triage
