### ISSUE TITLE
Renovate creates multiple PRs for common versions in gradle version catalog

### ISSUE THREAD

**Issue by F43nd1r** [renovatebot/renovate#12956] opened 2021-12-04 14:27 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovatebot/github-action@v29.32.1

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

When using gradle version catalog version refs for common versions, a single change in the common version will trigger the creation of multiple PRs, one for each dependency.
The changes and the CI to check them will be the same.

Reproducer: https://github.com/F43nd1r/renovate-bot-multiple-prs-bug-reproducer

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by olegkrivtsov** [comment] 2021-12-28 04:42
I'd like to help with this one.

**Comment by rarkins** [comment] 2021-12-28 06:27
I think we probably need @zharinov to take this one

**Comment by marosseleng** [comment] 2022-02-10 10:25
Hi folks, is there a plan/implementation on how to mitigate this issue? It can become quite a PR-spam with compose nowadays. I have 6 PRs changing the version of jetpack-compose to 1.1.0 (which I use as a version.ref) and 4 more PRs changing kotlin version to 1.6.

**Comment by rarkins** [comment] 2022-02-10 11:37
This is an open source project so everything is out in the open - there is no need to ask for a status report and it's generally unwelcome.

Have you tried adding a package rule to group them yourself?

I also just noticed that the reproduction provided earlier does not qualify as minimal, so this issue is not ready to start. You could help it along with a minimal reproduction (see linked guide above).

**Comment by marosseleng** [comment] 2022-02-10 11:52
Yes, I understand that. I was just looking for an already open issue that describes my problem, saw this one being here quite recently with `status:ready`, didn't see any update since the end of the year, asked about the status.

As per contributing instructions:
>If you've found a bug or have a feature request then please create an issue in this repository (but search first in case a similar issue already exists).

If there was a linked PR or another issue or a solution/suggestion response, I wouldn't have asked.

Anyhow, thanks for a suggestion, will try that out.

**Comment by rarkins** [comment] 2022-02-10 12:07
In future please just thumbs-up any issues you find, unless you've got something to add which would help other users with the same problem.

**Comment by irgaly** [comment] 2022-02-11 07:47
Here is reproducer I made. Let's start discussion with this.

https://github.com/irgaly/reproducer-renovate-12956-version-catalog

**Comment by rarkins** [comment] 2022-02-11 07:50
Thanks. Reproduction forked to https://github.com/renovate-reproductions/12956

**Comment by Churro** [comment] 2022-06-12 16:01
FYI, this was resolved by https://github.com/renovatebot/renovate/pull/15190.

Test repository: https://github.com/Churro/reproducer-renovate-12956-version-catalog/pull/1

**Comment by yschimke** [comment] 2022-06-20 14:16
I'm getting what sounds like similar issues in the last week or so

https://github.com/android/wear-os-samples/pull/422
https://github.com/android/wear-os-samples/pull/423
https://github.com/android/wear-os-samples/pull/421
https://github.com/android/wear-os-samples/pull/404

Is it related, or I should open up another one.

We are grouping Kotlin dependencies like so
https://github.com/android/wear-os-samples/blob/main/renovate.json

**Closed** 2022-10-16 12:12 UTC
Labels: type:bug, priority-3-medium, manager:gradle, status:ready, reproduction:provided
