### ISSUE TITLE
Terraform should update terraform.lock.hcl

### ISSUE THREAD

**Issue by bodinsamuel** [renovatebot/renovate#10752] opened 2021-07-07 10:22 UTC
**What would you like Renovate to be able to do?**

Terraform currently update version of `required_providers` nicely, but do not update the `.terraform.lock.hcl`

**Did you already have any implementation ideas?**

After changing the version, renovate should do 
`terraform providers lock -platform=darwin_arm64 -platform=darwin_amd64`

See documentation: https://www.terraform.io/docs/language/dependency-lock.html#new-provider-package-checksums

**Comment by bodinsamuel** [comment] 2021-07-07 10:29
Now I see this merged PR #10469 
but I can confirm an update happened on my repo 3days ago and did not upgrade the lockfile

**Comment by HonkingGoose** [comment] 2021-07-07 10:52
@bodinsamuel Can you explain if you still have a problem now? Or is the problem fixed with PR #10469?

**Comment by bodinsamuel** [comment] 2021-07-07 11:51
I had the issue 3days ago, so I guess the problem still exists.
Because the PR was merged 20days ago I suppose it's either not the same fix or not a complete fix.

**Comment by viceice** [comment] 2021-07-07 12:20
@bodinsamuel Please provide the debug logs from https://app.renovatebot.com/dashboard.

best is to use the retry checkbox and post the logs after run, so we should see the problem.

**Comment by evanfreed** [comment] 2021-07-07 21:25
@bodinsamuel are you running this self hosted and setting `RENOVATE_X_TERRAFORM_LOCK_FILE`?

I too had a similar issue and I am not running self hosted, so I wondered if this is related.  I get lots of these in my logs:

```
DEBUG: terraform.updateArtifacts: skipping updates. Experimental feature not activated
``` 

As mentioned here it looks like this var must be set: https://github.com/renovatebot/renovate/blob/3be44469bb98600a8f839887f9cb3c5c6bf975f3/lib/manager/terraform/lockfile/index.ts#L59-L65

I'm not sure if there's a way to set this in a "hosted" environment.  Perhaps someone can point me to some docs if there's an easy way.

**Comment by bodinsamuel** [comment] 2021-07-07 21:35
:ah: I did not paid attention that it was behind a Feature Flag.
I'm using the hosted environment, so this explains that 👌🏻

**Comment by viceice** [comment] 2021-07-08 04:11
So closing this. it's working as intended.

**Closed by viceice** 2021-07-08 04:11 UTC
Labels: manager:terraform, priority-5-triage, reproduction:needed, status:requirements, type:feature

**Comment by FlxPeters** [comment] 2021-07-17 10:33
I have an issue with this, but I'm not sure if it's a bug or miss configuration, so i put it here first before making an new issue.

Given i have may Terraform files in a sub directory, the new version of a provider is picked up, but the `.terraform.lock.hcl` is  placed on the root folder of the project. This is the state before running renovate: 

```
├── renovate.json
├── ...
└── terraform
    ├── main.tf
    └── versions.tf
    └── .terraform.lock.hcl
```

The diff of the commit generated by renovate:

```
Update Terraform vsphere to v2

diff --git a/.terraform.lock.hcl b/.terraform.lock.hcl
new file mode 100644
index 0000000..b7514c2
--- /dev/null
+++ b/.terraform.lock.hcl
@@ -0,0 +1,52 @@
+# This file is maintained automatically by "terraform init".
+# Manual edits may be lost in future updates.

+provider "registry.terraform.io/hashicorp/vsphere" {
+  version     = "2.0.2"
+  constraints = "~> 2.0.0"
+  hashes = [
+...
+  ]
+}

diff --git a/terraform/versions.tf b/terraform/versions.tf
index be2dacc..00694d2 100644
--- a/terraform/versions.tf
+++ b/terraform/versions.tf
@@ -2,7 +2,7 @@ terraform {
   required_providers {
     vsphere = {
       source  = "hashicorp/vsphere"
-      version = "~> 1.24.1"
+      version = "~> 2.0.0"
     }
```

As you can see a new  `.terraform.lock.hcl` is created in the root folder, but the existing one in  `terraform/.terraform.lock.hcl` ist unchanged. This is the new state: 
```
├── renovate.json
├──  .terraform.lock.hcl (this is new)
├── ...
└── terraform
    ├── main.tf
    └── versions.tf
    └── .terraform.lock.hcl (unchanged)
```

Is this an intended behavior or a bug?

**Comment by viceice** [comment] 2021-07-17 12:00
It's intend for now. Only repo root ist supported by lockfile currently. Feel free to open a feature request to support terraform lockfile in any directory

**Comment by viceice** [comment] 2021-07-17 12:02
Also checkout following PR https://github.com/renovatebot/renovate/pull/10619

**Comment by FlxPeters** [comment] 2021-07-17 13:12
Thanks for your feedback. Any plans on adding this as a feature? 
Having Terraform states in different sub directories is a quite common use case, so it would be great to have this. 
Unfortunately my Typescript skills are not good enough to implement it on my own.
