### ISSUE TITLE
dependencyDashboard not working on Azure DevOps

### ISSUE THREAD

**Issue by gjvoosten** [renovatebot/renovate#10439] opened 2021-06-15 09:26 UTC
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [x] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.41.3

**Describe the bug**

I've set:
```
  "dependencyDashboard": true,
```
in our `renovate.json`, yet there is no issue created. The [documentation](https://docs.renovatebot.com/configuration-options/#dependencydashboard) doesn't mention any specifics for Azure DevOps, so I assumed it should work.

**Relevant debug logs**

I see warnings in the log like the ones below, and I did find [this comment](https://github.com/renovatebot/renovate/issues/1149#issuecomment-703843021), but I'm not sure it relates to this problem.

<details><summary>Click me to see logs</summary>

```
…
21 WARN: findIssue() is not implemented (repository=X/Y)
…
384 WARN: ensureIssue() is not implemented (repository=X/Y)
385 INFO: Repository finished (repository=X/Y)
386       "durationMs": 137087
387 Finishing: Bash
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

If there's any additional info you need let me know.

**Comment by viceice** [comment] 2021-06-15 09:48
Duplicate of #9592

**Closed by viceice** 2021-06-15 09:48 UTC
Labels: platform:azure, priority-5-triage, status:requirements, type:feature

**Comment by viceice** [comment] 2021-06-15 09:50
Dependency dashboard only works for platforms where issues can be created. This is currently not supported / implemented for azure devops.

**Comment by gjvoosten** [comment] 2021-06-15 10:16
> Dependency dashboard only works for platforms where issues can be created. This is currently not supported / implemented for azure devops.

So… will the documentation get updated to clearly state this?

[Side note: is it just me or is the description in issue #9592 not very clear to the average user of Renovate?]

**Comment by viceice** [comment] 2021-06-15 10:23
@gjvoosten Added a small description to #9592, not sure where to write it to the docs.

@HonkingGoose Do you have an idea, where we can add the information, that some platforms do not support issues (and therefor dependency dashboard)?

**Comment by HonkingGoose** [comment] 2021-06-15 14:43
I think the real fix is to create a proper "feature comparison" page/overview somewhere in our docs, where we show all big features and list which platforms have those features. See my new issue #10446.
