### ISSUE TITLE
gitlabci-include failure with pinDigest=true

### ISSUE THREAD

**Issue by SebastianGoeb** [renovatebot/renovate#17277] opened 2022-08-19 10:05 UTC
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.159.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

 13.12.15

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I am trying to update gitlab-ci include dependencies with the `gitlabci-include` manager, where multiple dependencies come from the same repo but from different files:
```
include:
  # shared things
  - project: 'ridi/pipelines'
    ref: 3.6.2-rc0
    file: '/shared/proxy.yml'
  - project: 'ridi/pipelines'
    ref: 3.6.2-rc0
    file: '/shared/setup-scripts.yml'
  - project: 'ridi/pipelines'
... 8 more such dependencies from the same repo, making 10 in total
```

I have set up the tags `3.6.2-rc0` and `3.6.2-rc1` in the target repo, hoping that renovate will bump `rc0` to `rc1`. However, I get the following warnings:
```
DEBUG: Found match at index 66 ....
       "depName": "ridi/pipelines"
TRACE: Replacing 3.6.2-rc0 with 3.6.2-rc1 at index 66 ...
DEBUG: Value mismatch ...
       "manager": "gitlabci-include",
       "expectedValue": "3.6.2-rc1",
       "foundValue": "3.6.2-rc0"
```

With some further js-hacking, I've figured out that renovate is able to update the contents, and able to write the file to disk:
```
>>> content to write .gitlab-ci.yml
include:
  # shared things
  - project: 'ridi/pipelines'
    ref: 3.6.2-rc1
    file: '/shared/proxy.yml'
  - project: 'ridi/pipelines'
    ref: 3.6.2-rc0
    file: '/shared/setup-scripts.yml'
  - pro
>>> content written .gitlab-ci.yml
>>> content on disk .gitlab-ci.yml
include:
  # shared things
  - project: 'ridi/pipelines'
    ref: 3.6.2-rc1
    file: '/shared/proxy.yml'
  - project: 'ridi/pipelines'
    ref: 3.6.2-rc0
    file: '/shared/setup-scripts.yml'
  - pro
```

However, when renovate re-reads the file in `auto-replace.ts confirmIfDepUpdated`, it uses `depIndex 10` for all dependencies, when it should obviously use `0, 1, 2, ... 10`.

The `newExtract.deps` list has them unnumbered, and is also missing the filename alltogether, but it does see the `rc1`:
```
>>> newExtract depIndex 10
>>> newExtract deps
[
  {
    "datasource": "gitlab-tags",
    "depName": "ridi/pipelines",
    "depType": "repository",
    "currentValue": "3.6.2-rc1",
    "registryUrls": [
      "..."
    ]
  },
  {
    "datasource": "gitlab-tags",
    "depName": "ridi/pipelines",
    "depType": "repository",
    "currentValue": "3.6.2-rc0",
    "registryUrls": [
      "..."
    ]
  },
...
```

At some point they are detected correctly, and are also numbered depIndex 1-10:
```
TRACE:  packageFiles ...
       "config": {
         ...

         "baseDeps": [
           {
             "datasource": "gitlab-tags",
             "depName": "ridi/pipelines",
             "depType": "repository",
             "currentValue": "3.6.2-rc0",
             "registryUrls": ["..."],
             "depIndex": 0,
             "updates": [
               {
                 "bucket": "non-major",
                 "newVersion": "3.6.2-rc1",
                 "newValue": "3.6.2-rc1",
                 "releaseTimestamp": "2022-08-15T11:55:30.000Z",
                 "newMajor": 3,
                 "newMinor": 6,
                 "updateType": "patch",
                 "newDigest": "81821dee7b24de69c19b632cafa37ba89055efda",
                 "branchName": "renovate-patch"
               },
               {
                 "isPinDigest": true,
                 "updateType": "pinDigest",
                 "newValue": "3.6.2-rc0",
                 "newDigest": "81821dee7b24de69c19b632cafa37ba89055efda",
                 "branchName": "renovate-pin-dependencies"
               }
             ],
             "warnings": [],
             "versioning": "semver",
             "sourceUrl": "...",
             "currentVersion": "3.6.2-rc0",
             "isSingleVersion": true,
             "fixedVersion": "3.6.2-rc0"
           },
           {
             "datasource": "gitlab-tags",
             "depName": "ridi/pipelines",
             "depType": "repository",
             "currentValue": "3.6.2-rc0",
             "registryUrls": ["..."],
             "depIndex": 1,
             "updates": [
               {
                 "bucket": "non-major",
                 "newVersion": "3.6.2-rc1",
                 "newValue": "3.6.2-rc1",
                 "releaseTimestamp": "2022-08-15T11:55:30.000Z",
                 "newMajor": 3,
                 "newMinor": 6,
                 "updateType": "patch",
                 "newDigest": "81821dee7b24de69c19b632cafa37ba89055efda",
                 "branchName": "renovate-patch"
               },
               {
                 "isPinDigest": true,
                 "updateType": "pinDigest",
                 "newValue": "3.6.2-rc0",
                 "newDigest": "81821dee7b24de69c19b632cafa37ba89055efda",
                 "branchName": "renovate-pin-dependencies"
               }
             ],
             "warnings": [],
             "versioning": "semver",
             "sourceUrl": "...",
             "currentVersion": "3.6.2-rc0",
             "isSingleVersion": true,
             "fixedVersion": "3.6.2-rc0"
           },
```

What I can't figure out is why all 10 dependency updates use depIndex 10, even though they are numbered correctly at some point. Renovate simply extracts the wrong dependency from `newExtract.deps[10]` when it should extract `newExtract.deps[0]`, which then fails with `Value mismatch` even though the actual update worked fine.

I have a feeling it might have something to do with `newExtract.deps` not including the fileNames or the depIndex. If there was an `Array.find()` somewhere, matching the depName, that could explain the behaviour but so far I've come up blank. I'm sure you guys can find the issue much faster.

### Relevant debug logs

Debug logs in description above

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment] 2022-08-19 11:37
could not reproduce
- renovate-reproductions/17277-auto-replace-bug#1

**Comment by SebastianGoeb** [comment] 2022-08-19 13:48
`pinDigests` breaks it:
https://github.com/SebastianGoeb/17277-auto-replace-bug/commit/bb92e15eb2a2a580dd3da7ebd26f674f8dce1522

Now Renovate Bot also gives me the warning:
```
DEBUG: Found match at index 800(packageFile=".gitlab-ci.yml", branch="renovate/pin-dependencies")
{
  "depName": "renovate-bot/renovate-runner"
}
DEBUG: Found match at index 888(packageFile=".gitlab-ci.yml", branch="renovate/pin-dependencies")
{
  "depName": "renovate-bot/renovate-runner"
}
WARN: Error updating branch: update failure(branch="renovate/pin-dependencies")
```

Sorry I misunderstood the whole numbering thing. The working Renovate Bot log showed me what I was supposed to expect. So to summarize (for me mostly):
- dependencies are updated in reverse order to avoid the char offset of the next dependency being broken by the string replacement of the preceding dependency update
- each dependency to update is found be traversing the file in forward order.
  - so for the last dependency we expect 9 `Value mismatch`, then `Contents updated`
  - for the second-to-last dependency we expect 8 `Value mismatch`, then `Contents updated`
  - etc.
- with `pinDigest: true` the first dependency does go through 9 `Value mismatch`, then finds the correct spot in the file.
- however, it fails the final if-conditions (confirmIfDepUpdated still returns false), causing not `Contents updated`, but `throw new Error(WORKER_FILE_UPDATE_FAILED);` and eventually`WARN Error updating branch`.

None of these are matched, so it falls through to `return false` even though the spot in the file was actually found.
```
  if (!newDigest) {
    return true;
  }
  if (newUpgrade.currentDigest === newDigest) {
    return true;
  }
  if (!currentDigest && !pinDigests) {
    return true;
  }
  // istanbul ignore next
  return false;
  ```
  
I checked the contents of these variables back in my original repo because I can mess with the JS there:
  ```
  // using pinDigests: false
  {
  "newUpgrade": {
    "datasource": "gitlab-tags",
    "depName": "ridi/pipelines",
    "depType": "repository",
    "currentValue": "3.6.2-rc1",
    "registryUrls": [
      "..."
    ]
  },
  "pinDigests": false
}

// using pinDigests: true
{
  "newDigest": "81821dee7b24de69c19b632cafa37ba89055efda",
  "newUpgrade": {
    "datasource": "gitlab-tags",
    "depName": "ridi/pipelines",
    "depType": "repository",
    "currentValue": "3.6.2-rc1",
    "registryUrls": [
      "..."
    ]
  },
  "pinDigests": true
}
```
The newDigest is in fact the correct `-rc1` commit. Because it finds the newDigest, it refuses to `return true` in the first `if`. However, because there is no `newUpgrade.currentDigest`, it does want to `return true` in the last `if` either.

Which `if` would you expect it to exit from? Which `if` do other managers exit from, when they apply a `pinDigest` operation for the first time, when there wasn't a digest before? That's something that we have seen work for at least Dockerfiles before.

**Comment by rarkins** [comment] 2022-08-20 06:17
Maybe resolved by adding a default pinDigests=false config to gitlab-ci-include? Example: https://github.com/renovatebot/renovate/blob/844887a0cc6389e8bcb4b8ce6754f59c55312b79/lib/modules/manager/helm-values/index.ts#L7

**Comment by SebastianGoeb** [comment] 2022-08-20 06:22
We do set pinDigests=true in our config.js (globally). If gitlabci-include came with a default pinDigest=false, would the global config.js entry override it? Or not?

Also, pinDigests should in theory be possible. Git obviously uses hashes. If I had a moving `1` tag, wouldn't I expect renovate to update the corresponding hash?

**Comment by rarkins** [comment] 2022-08-20 06:26
BTW I assume you are aware that you can work around this problem already by making your `pinDigests` config specific to whichever manager/datasource you actually need?

**Comment by SebastianGoeb** [comment] 2022-08-20 06:32
Yes, that will definitely be the next thing to do on Monday, to disable pinDigests for gitlabci-include. I just think it's a useful feature in general, and I would like to use it wherever possible (globally true and all capable managers do it, others ignore it).

**Comment by viceice** [comment] 2023-04-12 12:53
Duplicate of #14177

**Closed by viceice** 2023-04-12 12:53 UTC
Labels: type:bug, priority-3-medium, manager:gitlabci, status:requirements, reproduction:provided
