### ISSUE TITLE
kustomize git-raw-refs - no auth on private repo?

### ISSUE THREAD

**Issue by krohrsb** [renovatebot/renovate#6566] opened 2020-06-22 15:19 UTC
**What Renovate type are you using?**

Github Enterprise, Selfhosted Whitesource Renovate (OSS Renovate version 21.6.6)

**Describe the bug**

When renovating kustomize configurations that contain bases that point to our github enterprise instance (which requires some form of auth) we get some fatal errors.

**Did you see anything helpful in debug logs?**

```
   err: { [-]
     message: fatal: unable to update url base from redirection:
  asked for: https://github.company.com/my-org/company-kustomize//company-service-hpa-base/info/refs?service=git-upload-pack
   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fmy-org%2Fcompany-kustomize%2Fcompany-service-hpa-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack

     stack: Error: fatal: unable to update url base from redirection:
  asked for: https://github.company.com/my-org/company-kustomize//company-service-hpa-base/info/refs?service=git-upload-pack
   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fmy-org%2Fcompany-kustomize%2Fcompany-service-hpa-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack

    at toError (/usr/src/app/node_modules/simple-git/promise.js:90:14)
    at /usr/src/app/node_modules/simple-git/promise.js:61:36
    at Git.<anonymous> (/usr/src/app/node_modules/simple-git/src/git.js:725:18)
    at Function.Git.fail (/usr/src/app/node_modules/simple-git/src/git.js:1475:18)
    at fail (/usr/src/app/node_modules/simple-git/src/git.js:1433:20)
    at /usr/src/app/node_modules/simple-git/src/git.js:1442:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
   }
   hostname: renovate-pro-deployment-worker-2-885977cf7-66kjk
   level: 50
   logContext: QlD-3n6om
   msg: Git-Raw-Refs lookup error in https://github.company.com/my-org/company-kustomize//company-service-hpa-base
   name: renovate
   pid: 9
   repository: the-org/rbac-authorization-deployment
   time: 2020-06-22T14:55:32.181Z
   v: 0
```

**To Reproduce**

Define a kustomization.yaml with a base that points to a private repository.

**Additional context**

As seen in the error it appears to be 302 redirecting to the login page, which i presume is due to the fact that the original request was done without auth.

**Comment by rarkins** [comment] 2020-06-22 18:36
Please provide more details of the `kustomization.yaml`, sanitized as necessary. The debug log from when it's extracted would also help.

**Comment by krohrsb** [comment] 2020-06-23 15:50
Logs:

```
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Checking for greenkeeper config","time":"2020-06-20T14:52:26.687Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"No greenkeeper config migration","time":"2020-06-20T14:52:26.688Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","config":{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["@appfabric"]},"msg":"onboarding config","time":"2020-06-20T14:52:26.689Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Onboarding branch is up to date","time":"2020-06-20T14:52:26.689Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Setting baseBranch to renovate/configure","time":"2020-06-20T14:52:26.689Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","branchName":"renovate/configure","latestCommitDate":"2020-06-19 12:05:25 +0000","msg":"latest commit","time":"2020-06-20T14:52:26.729Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Found renovate.json config file","time":"2020-06-20T14:52:26.747Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","configFile":"renovate.json","config":{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["@appfabric"]},"msg":"Repository config","time":"2020-06-20T14:52:26.747Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"migrateAndValidate()","time":"2020-06-20T14:52:26.747Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"No config migration necessary","time":"2020-06-20T14:52:26.747Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","config":{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["@appfabric"]},"msg":"massaged config","time":"2020-06-20T14:52:26.747Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","config":{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["@appfabric"]},"msg":"migrated config","time":"2020-06-20T14:52:26.748Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","ignorePaths":["**/node_modules/**","**/bower_components/**","**/vendor/**","**/examples/**","**/__tests__/**","**/test/**","**/tests/**","**/__fixtures__/**"],"msg":"Found repo ignorePaths","time":"2020-06-20T14:52:26.875Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"checkBaseBranch()","time":"2020-06-20T14:52:26.875Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"config.repoIsOnboarded=false","time":"2020-06-20T14:52:26.875Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Setting baseBranch to master","time":"2020-06-20T14:52:26.875Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","branchName":"master","latestCommitDate":"2020-05-04 23:40:08 +0000","msg":"latest commit","time":"2020-06-20T14:52:26.910Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Setting branchPrefix: renovate/","time":"2020-06-20T14:52:26.911Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Using file match: (^|/)pubspec\\.ya?ml$ for manager pub","time":"2020-06-20T14:52:28.223Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Using file match: (^|/)\\.ruby-version$ for manager ruby-version","time":"2020-06-20T14:52:28.244Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Using file match: \\.sbt$ for manager sbt","time":"2020-06-20T14:52:28.265Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Using file match: project/[^/]*.scala$ for manager sbt","time":"2020-06-20T14:52:28.265Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Using file match: (^|/)Package\\.swift for manager swift","time":"2020-06-20T14:52:28.284Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Using file match: \\.tf$ for manager terraform","time":"2020-06-20T14:52:28.308Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Using file match: ^.travis.yml$ for manager travis","time":"2020-06-20T14:52:28.328Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Matched 3 file(s) for manager kustomize: app-base/kustomization.yaml, environments/e2e-usw2/kustomization.yaml, environments/qal-usw2/kustomization.yaml","time":"2020-06-20T14:52:28.328Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Found kustomize package files","time":"2020-06-20T14:52:28.332Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Found 3 package file(s)","time":"2020-06-20T14:52:28.332Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":30,"logContext":"QlD-3n6om","repository":"test/test-service","baseBranch":"master","stats":{"managers":{"kustomize":{"fileCount":3,"depCount":4}},"total":{"fileCount":3,"depCount":4}},"msg":"Dependency extraction complete","time":"2020-06-20T14:52:28.332Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Dependency docker.company.com/test/test-service has unsupported value master-3e8b491","time":"2020-06-20T14:52:28.343Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Dependency docker.company.com/test/test-service has unsupported value master-3e8b491","time":"2020-06-20T14:52:28.345Z","v":0}
fatal: unable to update url base from redirection:
  asked for: https://github.company.com/patterns/company-kustomize//company-service-base/info/refs?service=git-upload-pack
   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fpatterns%2Fcompany-kustomize%2Fcompany-service-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":50,"logContext":"QlD-3n6om","repository":"test/test-service","err":{"message":"fatal: unable to update url base from redirection:\n  asked for: https://github.company.com/patterns/company-kustomize//company-service-base/info/refs?service=git-upload-pack\n   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fpatterns%2Fcompany-kustomize%2Fcompany-service-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack\n","stack":"Error: fatal: unable to update url base from redirection:\n  asked for: https://github.company.com/patterns/company-kustomize//company-service-base/info/refs?service=git-upload-pack\n   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fpatterns%2Fcompany-kustomize%2Fcompany-service-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack\n\n    at toError (/usr/src/app/node_modules/simple-git/promise.js:90:14)\n    at /usr/src/app/node_modules/simple-git/promise.js:61:36\n    at Git.<anonymous> (/usr/src/app/node_modules/simple-git/src/git.js:725:18)\n    at Function.Git.fail (/usr/src/app/node_modules/simple-git/src/git.js:1475:18)\n    at fail (/usr/src/app/node_modules/simple-git/src/git.js:1433:20)\n    at /usr/src/app/node_modules/simple-git/src/git.js:1442:16\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"},"msg":"Git-Raw-Refs lookup error in https://github.company.com/patterns/company-kustomize//company-service-base","time":"2020-06-20T14:52:28.644Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","dependency":"https://github.company.com/patterns/company-kustomize//company-service-base","packageFile":"app-base/kustomization.yaml","msg":"Failed to look up dependency https://github.company.com/patterns/company-kustomize//company-service-base","time":"2020-06-20T14:52:28.644Z","v":0}
fatal: unable to update url base from redirection:
  asked for: https://github.company.com/patterns/company-kustomize//company-service-appd-base/info/refs?service=git-upload-pack
   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fpatterns%2Fcompany-kustomize%2Fcompany-service-appd-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":50,"logContext":"QlD-3n6om","repository":"test/test-service","err":{"message":"fatal: unable to update url base from redirection:\n  asked for: https://github.company.com/patterns/company-kustomize//company-service-appd-base/info/refs?service=git-upload-pack\n   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fpatterns%2Fcompany-kustomize%2Fcompany-service-appd-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack\n","stack":"Error: fatal: unable to update url base from redirection:\n  asked for: https://github.company.com/patterns/company-kustomize//company-service-appd-base/info/refs?service=git-upload-pack\n   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fpatterns%2Fcompany-kustomize%2Fcompany-service-appd-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack\n\n    at toError (/usr/src/app/node_modules/simple-git/promise.js:90:14)\n    at /usr/src/app/node_modules/simple-git/promise.js:61:36\n    at Git.<anonymous> (/usr/src/app/node_modules/simple-git/src/git.js:725:18)\n    at Function.Git.fail (/usr/src/app/node_modules/simple-git/src/git.js:1475:18)\n    at fail (/usr/src/app/node_modules/simple-git/src/git.js:1433:20)\n    at /usr/src/app/node_modules/simple-git/src/git.js:1442:16\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"},"msg":"Git-Raw-Refs lookup error in https://github.company.com/patterns/company-kustomize//company-service-appd-base","time":"2020-06-20T14:52:28.646Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","dependency":"https://github.company.com/patterns/company-kustomize//company-service-appd-base","packageFile":"app-base/kustomization.yaml","msg":"Failed to look up dependency https://github.company.com/patterns/company-kustomize//company-service-appd-base","time":"2020-06-20T14:52:28.646Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","baseBranch":"master","msg":"Package releases lookups complete","time":"2020-06-20T14:52:28.646Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","config":{"kustomize":[{"packageFile":"app-base/kustomization.yaml","manager":"kustomize","deps":[{"datasource":"git-tags","depName":"https://github.company.com/patterns/company-kustomize//company-service-appd-base","lookupName":"https://github.company.com/patterns/company-kustomize//company-service-appd-base","currentValue":"v3.0.0","depIndex":0,"updates":[],"warnings":[{"depName":"https://github.company.com/patterns/company-kustomize//company-service-appd-base","message":"Failed to look up dependency https://github.company.com/patterns/company-kustomize//company-service-appd-base"}]},{"datasource":"git-tags","depName":"https://github.company.com/patterns/company-kustomize//company-service-base","lookupName":"https://github.company.com/patterns/company-kustomize//company-service-base","currentValue":"v3.0.0","depIndex":1,"updates":[],"warnings":[{"depName":"https://github.company.com/patterns/company-kustomize//company-service-base","message":"Failed to look up dependency https://github.company.com/patterns/company-kustomize//company-service-base"}]}]},{"packageFile":"environments/e2e-usw2/kustomization.yaml","manager":"kustomize","deps":[{"datasource":"docker","depName":"docker.company.com/test/test-service","lookupName":"docker.company.com/test/test-service","currentValue":"master-3e8b491","depIndex":0,"updates":[],"warnings":[],"skipReason":"unsupported-value"}]},{"packageFile":"environments/qal-usw2/kustomization.yaml","manager":"kustomize","deps":[{"datasource":"docker","depName":"docker.company.com/test/test-service","lookupName":"docker.company.com/test/test-service","currentValue":"master-3e8b491","depIndex":0,"updates":[],"warnings":[],"skipReason":"unsupported-value"}]}]},"msg":"packageFiles with updates","time":"2020-06-20T14:52:28.647Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"branchifyUpgrades","time":"2020-06-20T14:52:28.647Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"0 flattened updates found: ","time":"2020-06-20T14:52:28.649Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Returning 0 branch(es)","time":"2020-06-20T14:52:28.649Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"config.repoIsOnboarded=false","time":"2020-06-20T14:52:28.649Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"ensureOnboardingPr()","time":"2020-06-20T14:52:28.649Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"getBranchPr(renovate/configure)","time":"2020-06-20T14:52:28.649Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"findPr(renovate/configure, undefined, open)","time":"2020-06-20T14:52:28.649Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Found PR #1","time":"2020-06-20T14:52:28.649Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Skipping unsupported graphql PullRequests.mergeStateStatus query on GHE","time":"2020-06-20T14:52:28.650Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","prNo":1,"msg":"PR not found in open or closed PRs list - trying to fetch it directly","time":"2020-06-20T14:52:28.650Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","prNo":1,"msg":"1 commit matches configured gitAuthor so can rebase","time":"2020-06-20T14:52:28.650Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Filling in onboarding PR template","time":"2020-06-20T14:52:28.650Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"getConfigDesc()","time":"2020-06-20T14:52:28.650Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"getDescriptionArray()","time":"2020-06-20T14:52:28.650Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"getScheduleDesc()","time":"2020-06-20T14:52:28.650Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"No schedule","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","length":15,"msg":"Found description array","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","warnings":["Failed to look up dependency https://github.company.com/patterns/company-kustomize//company-service-appd-base","Failed to look up dependency https://github.company.com/patterns/company-kustomize//company-service-base"],"warningFiles":["app-base/kustomization.yaml"],"msg":"Found package lookup warnings in onboarding","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"getPrList()","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Found open onboarding PR","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Pull Request #1 does not need updating","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"processRepo()","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Removing any stale branches","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"config.repoIsOnboarded=false","time":"2020-06-20T14:52:28.651Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","branchList":["renovate/configure"],"renovateBranches":["renovate/configure"],"msg":"Branch lists","time":"2020-06-20T14:52:28.665Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"remainingBranches=","time":"2020-06-20T14:52:28.665Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"No branches to clean up","time":"2020-06-20T14:52:28.666Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"ensureIssueClosing(Action Required: Fix Renovate Configuration)","time":"2020-06-20T14:52:28.666Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Retrieving issueList","time":"2020-06-20T14:52:28.666Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","msg":"Retrieved 0 issues","time":"2020-06-20T14:52:28.828Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":20,"logContext":"QlD-3n6om","repository":"test/test-service","splits":{"init":3758,"extract":972,"lookup":317,"update":2},"total":5230,"msg":"Repository timing splits (milliseconds)","time":"2020-06-20T14:52:28.832Z","v":0}
{"name":"renovate","hostname":"renovate-deploy","pid":9,"level":30,"logContext":"QlD-3n6om","repository":"test/test-service","durationMs":5230,"msg":"Repository finished","time":"2020-06-20T14:52:28.832Z","v":0}
```

`kustomization.yaml` from `test-service`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: test-service-

bases:
- https://github.company.com/patterns/company-kustomize//company-service-appd-base?ref=v3.0.0
- https://github.company.com/patterns/company-kustomize//company-service-base?ref=v3.0.0

patchesStrategicMerge:
- Service-patch.yaml
```

Where repo & file `patterns/company-kustomize/company-service-appd-base/kustomization.yaml` exists with some standard resources.

**Comment by krohrsb** [comment] 2020-06-26 23:21
An example error (i got while running renovate cli against it):

```
 "err": {
         "message": "fatal: unable to update url base from redirection:\n  asked for: https://**redacted**@github.company.com/my-org/company-kustomize//company-service-base/info/refs?service=git-upload-pack\n   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fmy-org%2Fcompany-kustomize%2Fcompany-service-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack\n",
         "stack": "Error: fatal: unable to update url base from redirection:\n  asked for: https://**redacted**@github.company.com/my-org/company-kustomize//company-service-base/info/refs?service=git-upload-pack\n   redirect: https://github.company.com/login?return_to=https%3A%2F%2Fgithub.company.com%2Fmy-org%2Fcompany-kustomize%2Fcompany-service-base%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack\n\n    at toError (/Users/my-user/.config/yarn/global/node_modules/simple-git/promise.js:90:14)\n    at /Users/my-user/.config/yarn/global/node_modules/simple-git/promise.js:61:36\n    at Git.<anonymous> (/Users/my-user/.config/yarn/global/node_modules/simple-git/src/git.js:725:18)\n    at Function.Git.fail (/Users/my-user/.config/yarn/global/node_modules/simple-git/src/git.js:1475:18)\n    at fail (/Users/my-user/.config/yarn/global/node_modules/simple-git/src/git.js:1433:20)\n    at /Users/my-user/.config/yarn/global/node_modules/simple-git/src/git.js:1442:16\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
```

Just unsure why that type of request with auth doesn't work, yet. Likely some nuance with Github Enterprise.

**Comment by viceice** [comment] 2020-12-03 09:01
Duplicate of #5471

**Closed by viceice** 2020-12-03 09:01 UTC
Labels: manager:kustomize, priority-3-normal
