### ISSUE TITLE
devcontainer fails to build

### ISSUE THREAD

**Issue by morremeyer** [renovatebot/renovate#13148] opened 2021-12-16 13:41 UTC
### How are you running Renovate?

Self-hosted

### Describe the bug

This issue might be related to #12156.

When building the dev container for development in VS Code according to [docs/development/local-development.md](https://github.com/renovatebot/renovate/blob/main/docs/development/local-development.md#vs-code-remote-development), it fails to build.

Reproduction:

1. Open the renovatebot/renovate repository in VSCode
2. Start the development container according to https://github.com/renovatebot/renovate/blob/main/docs/development/local-development.md#vs-code-remote-development

### Relevant debug logs

<details><summary>Logs</summary>

```
[223 ms] Setting up container for folder or workspace: /Users/mmeyer/repos/github.com/morremeyer/renovate
[225 ms] Start: Check Docker is running
[225 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[423 ms] Server API version: 1.41
[447 ms] Start: Run: git rev-parse --show-cdup
[468 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/mmeyer/repos/github.com/morremeyer/renovate --filter label=vsch.quality=stable
[673 ms] Start: Run: docker build -f /Users/mmeyer/repos/github.com/morremeyer/renovate/.devcontainer/Dockerfile -t vsc-renovate-a0b9e5d27517c1f12a0053bb5fb44a09 /Users/mmeyer/repos/github.com/morremeyer/renovate/.devcontainer
[+] Building 6.3s (5/5) FINISHED                                                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                                                 0.0s
 => => transferring dockerfile: 207B                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/containerbase/node:14.18.2@sha256:39288a62b456a381b12cf63aa207ec0b356a05410e95ee1b3fbbc2e1933b1ebc                                                        2.5s
 => CACHED [1/2] FROM docker.io/containerbase/node:14.18.2@sha256:39288a62b456a381b12cf63aa207ec0b356a05410e95ee1b3fbbc2e1933b1ebc                                                                   0.0s
 => ERROR [2/2] RUN install-tool yarn 1.22.17                                                                                                                                                        3.7s
------                                                                                                                                                                                                    
 > [2/2] RUN install-tool yarn 1.22.17:                                                                                                                                                                   
#5 0.232 Installing tool yarn v1.22.17                                                                                                                                                                    
#5 2.714                                                                                                                                                                                                  
#5 2.714 > yarn@1.22.17 preinstall /home/user/.npm-global/lib/node_modules/yarn                                                                                                                           
#5 2.714 > :; (node ./preinstall.js > /dev/null 2>&1 || true)                                                                                                                                             
#5 2.714 
#5 2.951 /home/user/.npm-global/bin/yarn -> /home/user/.npm-global/lib/node_modules/yarn/bin/yarn.js
#5 2.951 /home/user/.npm-global/bin/yarnpkg -> /home/user/.npm-global/lib/node_modules/yarn/bin/yarn.js
#5 2.956 + yarn@1.22.17
#5 2.956 added 1 package in 2.268s
#5 3.226 1.22.17
#5 3.412 npm WARN using --force I sure hope you know what you are doing.
#5 3.662 rm: cannot remove '/root/.cache': Permission denied
------
```
</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment] 2021-12-16 14:17
This should fixy the issue
- https://github.com/containerbase/node/pull/5

**Comment by fgreinacher** [comment] 2022-03-14 10:18
Duplicate of #12156

**Closed** 2022-03-14 10:22 UTC
Labels: type:bug, priority-3-normal, status:in-progress
