### ISSUE TITLE
Renovate fails to upgrade packages due to "external-host-error"

### ISSUE THREAD

**Issue by joemckenney** [renovatebot/renovate#18059] opened 2022-09-30 15:34 UTC
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Without having changed our renovate configuration in > 9 months but having moved from yarn to pnpm it seems that renovate no longer updates are dependencies correctly.   Looking at the logs, renovate is consistently failing with an `external-host-error`.  I've pasted what appears to be the relevant section of the logs below.  I tried uninstalling and installing renovate with no affect.

### Relevant debug logs

<details><summary>Logs</summary>

```

WARN: Host error
{
  "hostType": "npm",
  "packageName": "@prisma/client",
  "err": {
    "name": "TimeoutError",
    "code": "ETIMEDOUT",
    "timings": {
      "start": 1664544758137,
      "socket": 1664544758153,
      "lookup": 1664544758164,
      "connect": 1664544758164,
      "secureConnect": 1664544758475,
      "upload": 1664544758476,
      "response": 1664544758644,
      "error": 1664544819906,
      "abort": 1664544819946,
      "phases": {
        "wait": 16,
        "dns": 11,
        "tcp": 0,
        "tls": 311,
        "request": 1,
        "firstByte": 168,
        "total": 61809
      }
    },
    "event": "request",
    "message": "Timeout awaiting 'request' for 60000ms",
    "stack": "RequestError: Timeout awaiting 'request' for 60000ms\n    at ClientRequest.<anonymous> (/home/ubuntu/renovateapp/node_modules/got/dist/source/core/index.js:970:65)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.emit (node:domain:489:12)\n    at ClientRequest.origin.emit (/home/ubuntu/renovateapp/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/home/ubuntu/renovateapp/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (node:internal/timers:561:11)\n    at processTimers (node:internal/timers:502:7)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://registry.npmjs.org/@prisma%2Fclient",
      "hostType": "npm",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    },
    "response": {
      "statusCode": 200,
      "statusMessage": "OK",
      "headers": {
        "date": "Fri, 30 Sep 2022 13:32:38 GMT",
        "content-type": "application/json",
        "transfer-encoding": "chunked",
        "connection": "close",
        "cf-ray": "752d53648b93c39f-SEA",
        "access-control-allow-origin": "*",
        "age": "264",
        "cache-control": "public, max-age=300",
        "etag": "W/\"5d5d7ec9c2755a3e1df0522c94dac538\"",
        "last-modified": "Thu, 29 Sep 2022 17:37:14 GMT",
        "vary": "accept-encoding, accept",
        "cf-cache-status": "HIT",
        "x-amz-replication-status": "PENDING",
        "server": "cloudflare",
        "content-encoding": "gzip"
      },
      "httpVersion": "1.1"
    }
  }
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment] 2022-10-02 04:51
Duplicate of #17677

**Closed by rarkins** 2022-10-02 04:51 UTC
Labels: type:bug, status:requirements, priority-5-triage

**Comment by joemckenney** [comment] 2022-10-03 15:33
Regarding the conversation and guidance in https://github.com/renovatebot/renovate/issues/17677, we aren't setting a timeout explicitly in our configuration.  Should we but bumping the default timeout higher?  We are seeing 0 successful runs at this point. 

  
![2022-10-03-083258_2264x1605_scrot](https://user-images.githubusercontent.com/2209122/193617445-5dd1aecb-d724-4096-bfa4-50b1677ac4ac.png)

**Comment by esetnik** [comment] 2022-10-07 19:22
I'm still seeing 100% of builds failing with `external-host-error`.
