### ISSUE TITLE
warning cdnjs Custom registries are not allowed

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#27576] opened 2024-02-27 07:39 UTC
### Discussed in https://github.com/renovatebot/renovate/discussions/27553

<div type='discussions-op-text'>

<sup>Originally posted by **nabeelsaabna** February 26, 2024</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

None

### Describe the problem

getting the error `Custom registries are not allowed for this datasource and will be ignored` without setting any custom registries

minimal reproduction repository:
https://github.com/nabeelsaabnaTests/pmdp-test-cdnjs

### Relevant debug logs

<details><summary>Logs</summary>

```

DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "html": [
      {
        "deps": [
          {
            "currentDigest": "sha512-zJYu9ICC+mWF3+dJ4QC34N9RA0OVS1XtPbnf6oXlvGrLGNB8egsEzu/5wgG90I61hOOKvcywoLzwNmPqGAdATA==",
            "currentValue": "1.2.1",
            "currentVersion": "1.2.1",
            "datasource": "cdnjs",
            "depName": "axios",
            "fixedVersion": "1.2.1",
            "isSingleVersion": true,
            "packageName": "axios/axios.min.js",
            "registryUrl": "https://api.cdnjs.com/",
            "replaceString": "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.1/axios.min.js\" integrity=\"sha512-zJYu9ICC+mWF3+dJ4QC34N9RA0OVS1XtPbnf6oXlvGrLGNB8egsEzu/5wgG90I61hOOKvcywoLzwNmPqGAdATA==\" crossorigin=\"anonymous\">",
            "sourceUrl": "https://github.com/mzabriskie/axios",
            "versioning": "semver",
            "warnings": [],
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.6.7",
                "newValue": "1.6.7",
                "newMajor": 1,
                "newMinor": 6,
                "updateType": "minor",
                "newDigest": "sha512-NQfB/bDaB8kaSXF8E77JjhHG5PM6XVRxvHzkZiwl3ddWCEPBa23T76MuWSwAJdMGJnmQqM0VeY9kFszsrBEFrQ==",
                "branchName": "renovate/axios-1.x"
              }
            ]
          },
          {
            "currentDigest": "sha256-FtWfRI+thWlNz2sB3SJbwKx5PgMyKIVgwHCTwa3biXc=",
            "currentValue": "2.5.17",
            "currentVersion": "2.5.17",
            "datasource": "cdnjs",
            "depName": "vue",
            "fixedVersion": "2.5.17",
            "homepage": "http://vuejs.org",
            "isSingleVersion": true,
            "packageName": "vue/vue.min.js",
            "registryUrl": "https://api.cdnjs.com/",
            "replaceString": "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js\" integrity=\"sha256-FtWfRI+thWlNz2sB3SJbwKx5PgMyKIVgwHCTwa3biXc=\" crossorigin=\"anonymous\">",
            "sourceUrl": "https://github.com/vuejs/vue",
            "versioning": "semver",
            "warnings": [
              {
                "message": "Could not determine new digest for update (cdnjs package vue/vue.min.js)",
                "topic": "vue/vue.min.js"
              }
            ],
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "2.7.16",
                "newValue": "2.7.16",
                "newMajor": 2,
                "newMinor": 7,
                "updateType": "minor",
                "newDigest": "sha512-Wx8niGbPNCD87mSuF0sBRytwW2+2ZFr7HwVDF8krCb3egstCc4oQfig+/cfg2OHd82KcUlOYxlSDAqdHqK5TCw==",
                "branchName": "renovate/vue-monorepo"
              },
              {
                "updateType": "digest",
                "newValue": "2.5.17",
                "newDigest": "sha512-E0wcoW3BSv/ZvprR5qZnsQ//TAHOSaq5AvRWfuSvwqravuBXOeeSycmecbN4otneNObeipZ2UkKLhXn6p3jLvw==",
                "branchName": "renovate/vue-monorepo"
              }
            ]
          }
        ],
        "packageFile": "test.html"
      }
    ]
  }
}


DEBUG: Fetching changelog: https://github.com/mzabriskie/axios (1.2.1 -> 1.6.7) (branch="renovate/axios-1.x")
WARN: Package lookup failures (branch="renovate/axios-1.x")
{
  "warnings": [
    "Could not determine new digest for update (cdnjs package vue/vue.min.js)"
  ]
  "files": [
    "test.html"
  ]
}


DEBUG: Fetching changelog: https://github.com/vuejs/vue (2.5.17 -> 2.7.16) (branch="renovate/vue-monorepo")
WARN: Package lookup failures (branch="renovate/vue-monorepo")
{
  "warnings": [
    "Could not determine new digest for update (cdnjs package vue/vue.min.js)"
  ]
  "files": [
    "test.html"
  ]
}

DEBUG: repository problems
{
  "repoProblems": [
    "WARN: Custom registries are not allowed for this datasource and will be ignored",
    "WARN: Package lookup failures"
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

**Comment by rarkins** [comment] 2024-02-27 07:42
@RahulGautamSingh I see two problems here, but probably the same bug:
- warning about default URLs
- bad join resulting in lookups for `https://api.cdnjs.comlibraries` which is an invalid host

**Comment by RahulGautamSingh** [comment] 2024-02-29 11:11
1. The custom registry warning is triggered because of code attached below. Before the `config` gets passed to `getDigest` function the `regsitryUrls` field i populated hence we get the warning.

https://github.com/renovatebot/renovate/blob/f74ece18d38e3862fc49e1aed1b0f430388d23d3/lib/workers/repository/process/lookup/index.ts#L492-L494

2. Not sure about the bad join you mentiioned, I couldn't reproduce it.

Now getting back to point 1. I am not sure of the best approach the fix it within the datasoruce logic itself. So, as a workaround we can add an if-check here:
https://github.com/renovatebot/renovate/blob/f74ece18d38e3862fc49e1aed1b0f430388d23d3/lib/workers/repository/process/lookup/index.ts#L500-L502

The `if-check` will remove the registryUrls field the config being passed to the getDigest function if the datasource is `cdnjs`. Since, `customRegistrySupport` is disabled for cdnjs it shouldn't case any problems.

**Comment by RahulGautamSingh** [comment] 2024-02-29 13:36
This seems to be aside-effect of this PR: https://github.com/renovatebot/renovate/pull/24175

https://github.com/renovatebot/renovate/blob/f74ece18d38e3862fc49e1aed1b0f430388d23d3/lib/workers/repository/process/lookup/index.ts#L492-L494 to the lookup function.

It was useful when `git-tags` supported `hunt` strategy but it doen't anymore. So, its resdiual code which needs to be removed.

**Comment by viceice** [comment] 2024-03-02 07:24
I think we should simply skip the check inside grtDigest, as we know we set the url in worker code to be a valid registry url.

**Comment by RahulGautamSingh** [comment] 2024-03-03 14:05
The warning is inside the `resolveRegistryUrls` function, and we can't remove it from there as it is reused in the getReleases function as well.

Even if the regsitryUrl is set in workers, the datasources with `customRegistrySupport=false` won't be using it, since they fallback to default ones.

**Comment by RahulGautamSingh** [comment] 2024-03-05 17:33
Fixed by @rarkins in https://github.com/renovatebot/renovate/pull/27724

**Closed by RahulGautamSingh** 2024-03-05 17:33 UTC
Labels: type:bug, priority-2-high, datasource:cdnjs
