### ISSUE TITLE
Gradle Kotlin support

### ISSUE THREAD

**Issue by jcornaz** [renovatebot/renovate#3054] opened 2019-01-09 09:21 UTC
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
As far as I understand, gradle should be supported since #2610. However, activating renovate for a gradle project doesn't create the onboarding PR.

**Did you see anything helpful in debug logs?**
Yes. Gradle is disabled.

See abstract of the log:
```
[...]
INFO: Repo is not onboarded
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, null, open)
DEBUG: Onboarding PR does not exist
[...]
DEBUG: gradle is disabled
[...]
DEBUG: Found 0 package file(s)
INFO: Repository has no package files - skipping
[...]
```

**To Reproduce**
1. Fork: https://github.com/jcornaz/islands-on-map
2. Activate renovate for the forked repository

**Expected behavior**
I'd expect renovate to detect that I'm using gradle, and create an onboarding PR accordingly.

**Comment by rarkins** [comment] 2019-01-09 11:37
Grade support is not considered battle hardened yet, so it's still disabled by default and hence opt-in.

If a repo has other package files, it means you need to add `"gradle": { "enabled": true }` to the config there, but otherwise onboarding will be skipped and you need to add a `renovate.json` file manually including the same.

In your case, I added a manual server side setting to enable Gradle however it's not detecting any gradle dependencies. Which files in your repo did you expect to be found and parsed?

**Comment by jcornaz** [comment] 2019-01-09 13:46
> Grade support is not considered battle hardened yet, so it's still disabled by default and hence opt-in.

Ok, thanks for the information. Is it documented somewhere?

>In your case, I added a manual server side setting to enable Gradle however it's not detecting any gradle dependencies.

Thanks.

My build file is the root `build.gradle.kts` (as usual) and dependency versions are defined in `buildSrc/src/main/kotlin/Version.kt`

**Comment by rarkins** [comment] 2019-01-09 14:06
Thanks for the further info. I think I need to add a "beta" status to the definitions file for Gradle so that it's reflected in the documentation.

We had not considered `build.gradle.kts` originally, so would need an enhancement to allow for it. FYI @corecanarias is working on a rewrite of gradle support currently so we'll probably add it as part of that or immediately after.

If you happen to know any "gotchas" of the kotlin build.gradle vs regular, please let us know.

**Comment by jcornaz** [comment] 2019-01-09 14:20
>If you happen to know any "gotchas" of the kotlin build.gradle vs regular, please let us know.

Kotlin script, is often valid groovy script but not the opposite. It is likely that you can use the same code, if you target Kotlin DSL.

For instance this plugin declaration is valid in both DSL (Kotlin and Groovy)
```
plugins {
    id("com.github.ben-manes.versions") version "0.20.0"
    id("se.patrikerdes.use-latest-versions") version "0.2.7"
}
```

The other point to keep in mind is that, although not specific to the Kotlin DSL, storing version numbers in java or Kotlin files in `buildSrc` is quite popular among Kotlin DSL users (because it gives us good auto-completion and type-safety in build scripts)

**Comment by corecanarias** [comment] 2019-01-09 16:20
To provide support for kotlin dsl we will need some additional changes. There may be some cases where it should work out of the box, but not at the same extent than the groovy dsl.

About externalizing the versions. We will need o make some compromises. I'm not aware of a broad well establish, standard way of solving this problem. Seems like most people tend to implement it the way that works for them. There are some plugins to externalize versions, but doesn't seem to be broadly used, really: https://github.com/fkorotkov/gradle-libraries-plugin.
We supported one of the use cases where you define the versions in your settings file https://remonsinnema.com/2016/05/09/how-to-manage-dependencies-in-a-gradle-multi-project-build/

Also using renovate to manage your dependencies will change the way you manage them, so your needs might change. That doesn't help with projects already defined in a way that is not supported, but we could find ways to decide whether we should implement a new method or just migrate the project.

If you could provide some examples of common projects using kotlin dsl and external dependencies we could start taking a look see how can we support them.

**Comment by jcornaz** [comment] 2019-01-09 20:15
>If you could provide some examples of common projects using kotlin dsl and external dependencies we could start taking a look see how can we support them.

[dokka](https://github.com/Kotlin/dokka) and [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines) externalize dependencies in `gradle.properties` for instance.

You may also want to have a look at:
* https://handstandsam.com/2018/02/11/kotlin-buildsrc-for-better-gradle-dependency-management/
* https://proandroiddev.com/gradle-dependency-management-with-kotlin-94eed4df9a28

**Comment by rarkins** [comment] 2019-01-09 20:50
@corecanarias it seems like there are two options available:

1. We hunt/follow links to externalised settings files. Or maybe just search a few well-known patterns,
2. Users extend `fileMatch` for any we miss. These would probably not be `build.gradle` files but more like `gradle.settings` files

I agree with you though on the point that if you're using a tool like Renovate, it may make sense to restructure how/where you define dependency versions anyway.

**Comment by corecanarias** [comment] 2019-01-10 14:58
I could try to test those two repositories dokka and kotlinx.coroutines because I think we should be able to support them out of the box. 
We implemented externalized dependencies in gradle.properties, because it's the most common method that I know. 
Other methods would become a bit more tricker

**Comment by ihostage** [comment] 2019-04-03 12:44
Hi! Have you got any update for this issue?
I try to enable Renovate for our [repository](https://github.com/taymyr/lagom-metrics/pull/10).
But in the [log](https://renovatebot.com/dashboard#github/taymyr/lagom-metrics/57216035) of bot I see next message:
```
WARN: No root build.gradle found - skipping
```
Maybe I can help you with anything?

**Comment by ihostage** [comment] 2019-04-03 12:50
We store version of dependency in `build.gradle.kts`. Can you add support of this base case how the first step of resolve this issue?

**Comment by BigMichi1** [comment] 2019-04-23 17:33
just a note for other projects that are using build.gradle.kts
- https://github.com/mvysny/bookstore-vok
- https://github.com/mvysny/vaadin-on-kotlin

**Comment by ihostage** [comment] 2019-08-31 22:02
Hi, folks 👋 
I have a very strange problem on our repository with Gradle Kotlin DSL.
1. We configured Renovate https://github.com/taymyr/lagom-elasticsearch-client/pull/50 and Renovate promised to` create 12 pull requests
> With your current configuration, Renovate will create 12 Pull Requests:

But it created only 6 (https://github.com/taymyr/lagom-elasticsearch-client/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate) and these PR only for update a plugins.

2. Renovate has a next logs (https://app.renovatebot.com/dashboard#github/taymyr/lagom-elasticsearch-client/91879483)
```
INFO: Processing 7 branches: renovate/com.fasterxml.jackson.datatype-jackson-datatype-jsr310-2.x, renovate/com.fasterxml.jackson.module-jackson-module-kotlin-2.x, renovate/net.javacrumbs.json-unit-json-unit-assertj-2.x, renovate/org.assertj-assertj-core-3.x, renovate/org.junit.jupiter-junit-jupiter-api-5.x, renovate/org.junit.jupiter-junit-jupiter-engine-5.x, renovate/org.junit.jupiter-junit-jupiter-params-5.x
INFO: Branch needs creating(branch="renovate/com.fasterxml.jackson.datatype-jackson-datatype-jsr310-2.x")
INFO: Branch needs creating(branch="renovate/com.fasterxml.jackson.module-jackson-module-kotlin-2.x")
INFO: Branch needs creating(branch="renovate/net.javacrumbs.json-unit-json-unit-assertj-2.x")
INFO: Branch needs creating(branch="renovate/org.assertj-assertj-core-3.x")
INFO: Branch needs creating(branch="renovate/org.junit.jupiter-junit-jupiter-api-5.x")
INFO: Branch needs creating(branch="renovate/org.junit.jupiter-junit-jupiter-engine-5.x")
INFO: Branch needs creating(branch="renovate/org.junit.jupiter-junit-jupiter-params-5.x")
INFO: Finished repository
```
But branches not created.
What is a problem? Configuration or it's a bug?

**Comment by rarkins** [comment] 2019-09-01 05:22
I think we might want to close this issue (basic Kotlin is supported now) and open separate issues to address any feature gaps or bug fixes. Referring to @ikesyo

**Comment by ikesyo** [comment] 2019-09-01 06:46
I checked https://github.com/taymyr/lagom-elasticsearch-client, and the problem is the syntax: `testCompile("org.junit.jupiter", "junit-jupiter-api", Versions.junit5)`. Variables like `Versions.junit5` is not supported yet (not included in the initial Gradle Kotlin DSL support).

Detecting and replacing such variables should be a bit difficult or require much work (we should parse and understand Kotlin's `object` syntax and so on).

**Comment by ikesyo** [comment] 2019-09-01 07:05
@rarkins I don't have the access rights to manage issues, so please close this instead of me.

**Comment by ikesyo** [comment] 2019-09-01 07:13
And also non-named arguments call `testCompile(group, artifact, version)` is not supported yet. You should use either `testCompile("group:artifact:version")` or `testCompile(group: group, name: artifact: version: version)`. PRs are welcome.

**Closed** 2019-09-01 07:13 UTC
Labels: #java, feat, needs-requirements

**Comment by rarkins** [comment] 2019-09-01 07:40
@ikesyo did you get our Slack invite?

**Comment by ikesyo** [comment] 2019-09-01 08:00
@rarkins I'm sorry I missed the invitation 🙈 I've just joined that!
