### ISSUE TITLE
Gradle : gradle depCount not extracted

### ISSUE THREAD

**Issue by LeJeanbono** [renovatebot/renovate#7487] opened 2020-10-16 12:00 UTC
**What Renovate type, platform and version are you using?**

hosted App - Platform GitLab

**Describe the bug**

Renovate didn't find gradle dependencies during `Dependency extraction`

**Relevant debug logs**

`gitlab/csuite/datawarehouse/247291996`
Working extraction depCount = 150
```
DEBUG: processRepo()
DEBUG: baseBranches
{
  "baseBranches": [
    "develop"
  ]
}
DEBUG: baseBranch: develop
DEBUG: extract()
DEBUG: Found cached extract
{
  "baseBranch": "develop",
  "baseBranchSha": "a61402fc643411b144d2b7563fc04ec08228290e"
}
INFO: Dependency extraction complete
{
  "baseBranch": "develop",
  "stats": {
    "managers": {
      "gradle": {
        "fileCount": 3,
        "depCount": 150
      },
      "gradle-wrapper": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 4,
      "depCount": 151
    }
  }
}
DEBUG: baseBranch: develop
```

`gitlab/csuite/datawarehouse/247317839`
Next run (stats.managers.gradle not here) : 
```
DEBUG: processRepo()
DEBUG: baseBranches
{
  "baseBranches": [
    "develop"
  ]
}
DEBUG: baseBranch: develop
DEBUG: extract()
DEBUG: Found cached extract
{
  "baseBranch": "develop",
  "baseBranchSha": "c408bfc916877d40a75397b1569d9fe9c02e6880"
}
INFO: Dependency extraction complete
{
  "baseBranch": "develop",
  "stats": {
    "managers": {
      "gradle-wrapper": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}
DEBUG: baseBranch: develop
```

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment] 2020-10-16 12:03
Is it reproducible or was it possibly just one "bad run"? Any logs from the bad run which indicate why it failed?

**Comment by LeJeanbono** [comment] 2020-10-16 12:08
No error log differents.
Actually the bad run `247317839` it's a "normal" run. I mean, I never have dependencies PR since long time. 247291996 run is an exception that's working

**Comment by rarkins** [comment] 2020-10-16 12:33
What's strange is that both of them are finding a cached extract, so Gradle is not actually being run on either of those runs (which explains no log).

Unfortunately, the job which did run Gradle was interrupted by an upgrade event, although I do have INFO/WARN logs in another system so could find this:

```
Compliance error - Unable to determine develop version as git describe did not return expected value
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':api'.
> Unable to determine develop version as git describe did not return expected value
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 38s
```

I'm not a Gradle user so it doesn't tell me too much. I think the reference to `develop version` may be because the branch is named `develop`. When I google the "git describe did not return expected value" error I get 3 results and the first one is your previous issue! https://github.com/renovatebot/renovate/issues/4754

**Comment by rarkins** [comment] 2021-01-12 10:29
Duplicate of #4754

**Closed by rarkins** 2021-01-12 10:29 UTC
Labels: type:bug
