### ISSUE TITLE
update CircleCI orb when available

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3359] opened 2019-03-11 18:09 UTC
**What would you like Renovate to be able to do?**
I want to:

- update `@dmx/` packages when available
- update other NPM packages only once a month (but if they're updated in a PR updating a `@dmx/` package, it's OK)
- update CircleCI orb version when available
- update other docker dependencies (Node.js, MongoDB, Redis...) only once a month

**Describe the solution you'd like**
I would like the following `renovate.json` to do this stuff:
```
{
  "groupName": "all dependencies",
  "packageRules": [
    {
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    },
    {
      "managers": [
        "orb"
      ],
      "schedule": "at any time"
    }
  ],
  "schedule": "before 3am on the first day of the month"
}
```

**Describe alternatives you've considered**
Instead of `packageRules[].managers.orb`, it could be something like:
```
    {
      "filePath": ".circleci/config.yml"
      "fieldPath": "orbs.dmx_base",
      "schedule": "at any time"
    }
```

**Additional context**
CircleCI orbs (https://circleci.com/orbs/) allow using shared code between multiple repos. Above all, it's useful for very long CircleCI config files or when we want to change easily the config for many repos in the same time or in order to ensure easily some security stuff.

When using a shared orb, `.circleci/config.yml` file starts with (it's available only for 2.1+ CircleCI versions):
```
version: 2.1
orbs:
  dmx_base: dmx-io/base@1.10.127
```

It's possible to write ` dmx_base: dmx-io/base@1` which at DMX, we decided to do initially. However later, when we started using renovate, we decided to use strict orb versions to have more control e.g. we can do a bug or breaking backwards compatibility (not intentionally) in a new patch/minor version and we are informed about that when there's a new job triggered. On the other hand, when using renovate to update orb versions, we have a job triggered in renovate PRs and even if another job (like deployment) is triggered only after merging, it's still better to have a failed build in a short time after new orb publishing than after a long time.

**Comment by rarkins** [comment] 2019-03-11 18:13
Duplicate of #3335. This will be solvable by using the `packageRules>datasources` selector once it's implemented in #3344

**Closed by rarkins** 2019-03-11 18:13 UTC

**Comment by piotr-s-brainhub** [comment] 2019-03-11 18:19
Thanks @rarkins 

The good support is one of the reasons we decided to use renovate instead of greenkeeper.

Btw. congratulations - renovate recently overtook greenkeeper by the stars number:
https://star-history.t9t.io/#renovatebot/renovate&greenkeeperio/greenkeeper
<img width="1327" alt="Screen Shot 2019-03-11 at 19 18 07" src="https://user-images.githubusercontent.com/20856232/54147496-9b88d400-4432-11e9-8166-da0a47f49cfd.png">
