### ISSUE TITLE
Support dependency dashboard in Azure DevOps

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/renovate#10725] opened 2021-07-06 06:27 UTC
**What would you like Renovate to be able to do?**

Have a dependency dashboardin Azure DevOps since this seems to not be supported yet:

> WARN: ensureIssue() is not implemented
> ...
> WARN: findIssue() is not implemented

**Did you already have any implementation ideas?**

N/A

**Comment by rarkins** [comment] 2021-07-06 07:05
Would this function ok as a "work item" though?

**Comment by tomkerkhove** [comment] 2021-07-06 07:29
Definately

**Comment by viceice** [comment] 2021-07-06 07:38
Duplicate of #9592

**Closed by viceice** 2021-07-06 07:38 UTC
Labels: platform:azure, priority-3-normal, status:requirements, type:feature

**Comment by tomkerkhove** [comment] 2021-07-06 07:58
Sorry!
