### ISSUE TITLE
Created issue deleted

### ISSUE THREAD

**Issue by frenck** [renovatebot/renovate#7835] opened 2020-11-28 13:05 UTC
**What Renovate type, platform and version are you using?**

Hosted version

**Describe the bug**

Well, I created an issue, which has been deleted. I found that a rather offensive action to take and not really in style for an open-source project.

If I have violated your code of conduct, please let me know. But as far as I am concerned, I was not. But no communication efforts from this project has been made to inform me of the action either.

So now, I'm left with nothing. Or is the idea you guys delete issues you don't want to deal with? That is fine for me as well, but just be honest about that.

**Relevant debug logs**

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment] 2020-11-28 13:28
Hi @frenck, your issue wasn't deleted and instead was transferred to https://github.com/renovatebot/app-support/issues/101 and answered there, as it's not related to any code in this open source project. The code to insert the header is done as config in the hosted app which WhiteSource operates. I subsequently added a rule to skip that specifically for what I think is the org you were referencing.

FWIW you were unnecessarily rude in that issue though and I was surprised to see it come from someone in who bases themselves in open source too. You shouldn't need a CoC to tell you not to act like this:

![image](https://user-images.githubusercontent.com/6311784/100516700-f1148f80-3185-11eb-8d27-960cf500c96b.png)

**Closed by rarkins** 2020-11-28 13:28 UTC

**Comment by frenck** [comment] 2020-11-28 13:33
I wasn't rude in my opinion; straight to the point for sure! Thanks for pointing me in the direction. 

Somehow I haven't received a notification in GitHub of the taken actions, nor was I able to find my issue here using the filters. Hence the creation of this issue and my assumption of it being deleted.

Thanks for your answer nevertheless 👍

**Comment by frenck** [comment] 2020-11-28 13:35
Can you move it back? as it is a bug, see the issue you've moved.

**Comment by rarkins** [comment] 2020-11-28 13:46
It's not a bug. You are using the hosted version for Renovate, which has certain settings on or off by default, including both PR header and footer. Some users also have requested us add custom settings for them too, plus we change settings if we find warnings or errors at runtime that we can fix via config. You're welcome to self host the open source CLI version or GitHub action if you find this undesirable.

**Comment by frenck** [comment] 2020-11-28 14:00
It is, the documentation states it is a `null` by default:


https://docs.renovatebot.com/configuration-options/#prheader

So either the docs are wrong and need to be corrected, or it is a bug.

**Comment by rarkins** [comment] 2020-11-28 14:20
Your opinion is noted, but we won't be changing anything.

**Comment by frenck** [comment] 2020-11-28 14:23
That is fine, but I was past that. The documentation doesn't match reality.

You offered a solution to set the prheader to `null` to resolve my issue, however, according to the documentation this is already the default.

So is the default documented incorrect?

**Comment by viceice** [comment] 2020-11-28 14:42
As @rarkins already mentioned, some settings are explicit overridden by the hosted app. So the docs say the default values of the open source renovate cli, which can be overridden by  anybody who hosts the bot. They can also overridden by config preset's.

**Comment by frenck** [comment] 2020-11-28 14:45
Aah right, so where can I find the defaults and documentation for the hosted app?
As far as I can see, the documentation is universal for all offered options, including the hosted version. Or is there different documentation?

Is there an overview of default differences? Shouldn't be those documented in the same place?

**Comment by viceice** [comment] 2020-11-28 14:51
Currently there is no docu for the changed settings by the hosted app. Maybe we can do that in future.

You also need to know, that the suggested onboarding `config:base` preset overrides a lot default values too.

**Comment by frenck** [comment] 2020-11-28 14:53
From a user perspective, that is really causing unexpected behavior if the documentation is incorrect depending on presets or the way it is run. Especially if it isn't mentioned at all.

Alright, thanks for that explanation and good luck on your journey.
