### ISSUE TITLE
[gitlab] Gitlab.com shared runners can't properly detect if docker dind is started up

### ISSUE THREAD

**Issue by vitoyucepi** [renovatebot/renovate#9052] opened 2021-03-09 17:02 UTC
**What Renovate type, platform and version are you using?**
Renovate runner repository configured according to [official renovate guide](https://gitlab.com/renovate-bot/renovate-runner) at gitlab

**Describe the bug**

Part two of a [question](https://gitlab.com/renovate-bot/renovate-runner/-/issues/16).
Each time renovate job is started gitlab runner tries to check if docker dind service is running.
The original problem was described [here](https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/).

If I use default config it fails with timeout. But else everything is ok.
https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/blob/35cb9c4b8c4b6424f469c7b9998abe0cdd2a50c1/.gitlab-ci.yml
https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/jobs/1039960534

If I create custom config then status of service is ok. But renovate couldn't find docker service.
https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/blob/7f321df4dece573096c3b178202d9741d7926d24/.gitlab-ci.yml
https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/jobs/1084256041

**Relevant debug logs**
Debug log available here
https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/jobs/1084256041

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I'm interested in this issue because docker dind service status checker has about 30 seconds timeout.
For my repos average job run time is
| Job step | Run time (min:sec) |
| --- | --- |
| Resolving secrets | 00:00 |
| **Preparing the "docker+machine" executor** | **01:09** |
| Preparing environment | 00:02 |
| Getting source from Git repository | 00:02 |
| Restoring cache | 00:32 |
| Executing "step_script" stage of the job script | 00:11 |
| Saving cache for successful job | 01:04 |
| Uploading artifacts for successful job | 00:02 |
| Cleaning up file based variables | 00:01 |
| Total | 03:05 |

On step *Preparing the "docker+machine" executor* it tries to wait until service is ready and fails.

**Comment by viceice** [comment] 2021-03-09 17:11
Thisis a gitlab issue, not a renovate one. If you know how, you can try to use renovate with dind and docker certs. I'm not able to fix that currently.

**Comment by rarkins** [comment] 2021-03-09 18:18
Shall we move this to a discussion?

**Comment by vitoyucepi** [comment] 2021-03-09 18:28
Probably I've already found an issue.

It seems the difference is in container entrypoint script.
https://github.com/docker-library/docker/blob/9728dce92752348ac2623bcf96436f1a89e15dd3/docker-entrypoint.sh
This entrypoint sets additional variables.
So currently I'm testing updated gitlab-ci.yml
```yml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  LOG_LEVEL: debug
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"
  
renovate:
  only:
    - pushes
```

**Comment by viceice** [comment] 2021-03-09 21:56
If it's solvable with those env vars only, we should add them to the dind template. You can send a pr if you like 🤗

**Comment by HonkingGoose** [comment] 2021-03-10 08:20
@viceice do you want to assign @vitoyucepi to this issue?

**Comment by vitoyucepi** [comment] 2021-03-10 08:26
mr is ready https://gitlab.com/renovate-bot/renovate-runner/-/merge_requests/181

**Comment by viceice** [comment] 2021-03-10 08:39
merged

**Closed** 2021-03-10 08:39 UTC
Labels: platform:gitlab, priority-4-low, type:bug

**Comment by viceice** [comment] 2021-03-10 08:40
@vitoyucepi Next time if the issue is specific to our gitlab pipeline template file the issue directly on that repo . Thanks for contribution.

**Comment by vitoyucepi** [comment] 2021-03-10 08:55
@viceice thanks. I wasn't sure what is the cause of the problem.

**Comment by viceice** [comment] 2021-03-10 09:03
If you're not sure, open a discussion intead. 😉
